
OUTER_SPRINT kit_description ~魔射手/法师：该角色可同时使用魔射手与法师的能力，但身着护甲时无法施展法术。

魔射手：精灵战团的精锐，魔射手是擅长以魔法辅弼战技的战士。走出森林之外，魔射手凭借超凡的弓术与附魔箭矢的能力，在诸国间声名远扬。队伍之中，他们足以令整支敌军闻风丧胆。

职业优势：
–可将长弓、短弓或十字弓修习至宗师级。
–1级起，所有远程武器命中+1，之后每提升5级再+1。
–获得「强化箭矢」能力。

强化箭矢：魔射手被动为<PRO_HISHER>箭矢注入魔力。其射出的投射物始终视为+1附魔武器，并额外造成1点魔法伤害；每提升5级，附魔等级与魔法伤害各+1，20级时达到最高+5附魔与5点魔法伤害。额外伤害受目标魔法抗性减免。

–3级：每日可使用一次「熵光护盾」。

熵光护盾：魔射手周身浮现出五彩辉光的魔法力场，免疫普通远程武器，并对远程武器的护甲等级获得-2加值，持续时长为每等级1轮。10级时加值提升至-4，17级时提升至-6。

–5级：每日可使用三次「魔爆箭矢」能力。

魔爆箭矢：魔射手以奥术魔法为<PRO_HISHER>下一轮内射出的下一发箭矢附魔，使其命中后爆炸，每5级额外造成1d6点火焰范围伤害。

–9级：每日可使用一次「觅心箭矢」能力。

觅心箭矢：技艺精湛的魔射手可为<PRO_HISHER>箭矢附魔，使其必中目标。<PRO_HISHER>下一轮内的下一次远程攻击必定暴击，且每提升5级额外造成2点伤害。

–13级：每日可使用一次「相位箭矢」能力。

相位箭矢：经验丰富的魔射手可为<PRO_HISHER>下一轮内的下一发箭矢附魔，使其化为虚体投射物穿透护甲，目标的远程抗性降低50%，同时对远程武器的护甲等级每5级降低2点。

–17级：每日可使用一次「死亡箭矢」能力。

死亡箭矢：魔射手大师可为<PRO_HISHER>下一轮内的下一发箭矢附魔，目标若未通过死亡豁免即被即刻斩杀。每提升5级，目标的豁免惩罚增加1点。

职业限制：
–手持近战武器时，零级命中值（THAC0）受-3惩罚。
–仅限精灵或半精灵种族。KIT_DISADV_1
–除长弓、短弓与十字弓外，其他武器的熟练等级不得超过入门级（1点熟练槽）。
–所有武器风格的熟练等级不得超过入门级（1点熟练槽）。
–不得穿戴比精灵锁甲更重的护甲。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「猛力攻击」与「武器娴熟」。
–16级时不会获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 7
	
    mixed         = RESOLVE_STR_REF(~魔射手 / 法师~)
	
    lower         = RESOLVE_STR_REF(~魔射手 / 法师~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~魔射手/法师：该角色可同时使用魔射手与法师的能力，但身着护甲时无法施展法术。~)
  STR_VAR
    kit_name      = ~C0AA2~
	
    unusable      = ~0x00008000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    abclasrq      = ~0 15 0 14 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 0 0 0~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 0 0 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~FM0~
	
    stweap        = ~CLCK13 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    // clab_path     = ~override/C0AA.2da~
	
    // kittable      = ~K_F_H K_F_D K_F_G K_F_E K_F_HE K_F_HL K_F_HO~
	
	base_class = F
	
	clab_base_f = ~C0AA~
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPFM~
	
    // numwslot      = ~4~
	
	// clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl
	
	// traplimt = ~6~
	
    bdstweap      = ~CLCK12 * * * RING06 * * * * BRAC02 BELT04 * BULL02,40 * POTN08,5 POTN17,3 POTN24,1 SLNG02 DAGG05,40 STAF02~
  RET
    kit_id
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABFI01.2DA~ BEGIN
COPY_EXISTING ~CLABFI01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 18 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 21 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 22 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 23 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 24 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 25 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 26 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 27 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 28 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 29 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 30 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 31 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 32 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 33 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 34 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 35 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 36 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 37 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 38 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 39 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 40 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 41 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 42 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 43 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 44 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 45 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 46 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 47 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 48 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 49 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 50 f_MaxLevel = 50 STR_VAR f_Entry = AP_C0AAZX END
  PRETTY_PRINT_2DA
BUT_ONLY
END

COPY_EXISTING ~C0AAZX.SPL~ ~OVERRIDE~
 LPF ALTER_EFFECT INT_VAR match_opcode = 177 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0AA2~) END

COPY_EXISTING ~C0AAINN.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 290 parameter1 = RESOLVE_STR_REF (~魔射手~) END

ACTION_IF FILE_EXISTS_IN_GAME ~C0FIG04.SPL~ THEN BEGIN
COPY_EXISTING ~C0FIG04.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 2 timing = 0 duration = 1 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0AA2~) parameter2 = 109 STR_VAR resource = C0FIG04 END
END