
COPY ~%MOD_FOLDER%/Thief/Adventurer~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Thief/Adventurer/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/C0ADVENT.2DA~
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 3 STR_VAR f_Entry = AP_C0ADV01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0ARC03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0ADV00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 18 STR_VAR f_Entry = AP_C0ADV00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = GA_SPCL121 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~游荡射手：许多游荡者出于务实考量选择使用远程武器，习惯于在安全距离外接战。游荡射手精于此道，远距交锋时不逊于任何战士，无需身犯险境，便能以致命的投射物击倒敌人。

职业优势：
–1级起，所有远程武器的命中与伤害掷骰获得+1加值，之后每提升3级再+1。
–远视：游荡射手的视野范围略高于常人，处于潜行或隐形状态时会进一步提升。
–可将任意远程武器修习至精通级（3点熟练槽）。
–可使用「速射」攻击模式。

速射：射手每轮可额外进行一次攻击，但命中受-4惩罚。

–每日可使用一次「精准射击」能力。4级时增加一次使用次数，之后每提升4级再增加一次。

精准射击：接下来10秒内，所有成功命中的远程攻击除造成正常伤害外，还将根据游荡射手的等级叠加以下效果：
 4级：目标的零级命中值（THAC0）受-1惩罚。
 8级：目标的法术豁免检定受-1惩罚。
 12级：目标的力量属性受-1惩罚。
 16级：伤害掷骰获得+2加值。
 
–12级：精通速射：速射状态下的命中惩罚降低至-2。
–18级：狙击：潜行或隐形状态下，射手的远程攻击必定暴击。

职业限制：
–无法使用背刺能力。KIT_DISADV_1~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「致残打击」。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 4
	
    mixed         = RESOLVE_STR_REF(~游荡射手~)
	
    lower         = RESOLVE_STR_REF(~游荡射手~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~游荡射手：许多游荡者出于务实考量选择使用远程武器，习惯于在安全距离外接战。游荡射手精于此道，远距交锋时不逊于任何战士，无需身犯险境，便能以致命的投射物击倒敌人。~)
  STR_VAR
    kit_name      = ~C0ADVENT~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 1 3 0 1 0 0 3 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 3 0 3 3 3 1 1 1 1~
	
    abclasrq      = ~0 9 0 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0ADV~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0ADVENT.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
	
	sneakatt = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
	
	crippstr = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~LUTH0.2da~ ~override/LUC0ADV.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL916~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0ADV~ ability = ~GA_SPCL900~ num_allowed = 16 END	

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

INCLUDE ~%MOD_FOLDER%/spells/rapidshot.tpa~