COPY ~%MOD_FOLDER%/Sorcerer/Arcane_Trickster/2das~ ~override~
COPY ~%MOD_FOLDER%/Sorcerer/Arcane_Trickster/spells~ ~override~

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 19
	
    mixed         = RESOLVE_STR_REF(~诡术师~)
	
    lower         = RESOLVE_STR_REF(~诡术师~)
	
    help          = RESOLVE_STR_REF(~诡术师：诡术师兼修法术之道与诡计、盗窃乃至恶作剧之术。他们以精深的奥术学识辅益潜行窃盗之技，是冒险者中适应性最强的群体之一。
	
职业优势：
–盗贼技能：扒窃、找寻并解除陷阱、开锁、阴影躲藏、无声行动、侦测幻象。
–扒窃与侦测幻象技能获得+10%加值。
–潜行施法：诡术师处于躲藏或隐形状态时施放的法术，若施法时间大于1，则缩短为1。
–可使用背刺造成额外伤害：
  1-9级：2倍
  10-17级：3倍
  18级及以上：4倍
–每日可使用一次「窃法」。

窃法：诡术师可窃取目标法师或吟游诗人的魔力，移除目标一个已记忆的最高环奥术法术，并回复自身一个已消耗的法术位。

–5级：额外获得一次窃法使用次数。
–5级：可使用「即兴背刺」。

即兴背刺：诡术师的背刺会降低目标的敏捷属性与法术豁免检定，持续1小时；效果强度随诡术师的游荡者等级提升而增强。同一目标身上该效果不可叠加。

  1-8级：敏捷-4，豁免检定-1
  9-12级：敏捷-6，豁免检定-2
  13级及以上：敏捷-8，豁免检定-3
  
–9级：额外获得一次窃法使用次数。
–10级：窃法可移除目标一个不高于5环的法术防护效果。
–13级：额外获得一次窃法使用次数。
–15级：窃法可移除目标一个不高于8环的法术防护效果。
–17级：额外获得一次窃法使用次数。
–20级：窃法可移除目标一个不高于9环的法术防护效果。

职业限制：
–每个法术等级每日可施展的法术数量减少1个。
–必须为非守序阵营。~)
	
    briefdesc     = RESOLVE_STR_REF(~诡术师：诡术师兼修法术之道与诡计、盗窃乃至恶作剧之术。他们以精深的奥术学识辅益潜行窃盗之技，是冒险者中适应性最强的群体之一。~)
	
    suppress_warnings     = 1
	
  STR_VAR
    kit_name      = ~C0_ARCANE_TRICKSTER_SORC~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//   T   S           F   Q S S
	//   W   C           L   U W I
	//       B L S   O   I   W       A   A O N
	//       A O H   H   M   A       I   R C   S       R G
	//   L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//   _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//   S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//   W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//   O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//   R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//   D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1~
	
    abclasrq      = ~0 12 0 12 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//   L L L N N N C C C
	//   G N E G N E G N E
    alignmnt      = ~0 0 0 1 1 1 1 1 1~
	
    dualclas      = ~0 0 0 0 0 0~
	
    luabbr        = ~C0ATRS~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0ATRSO.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = T
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = ~C0ATR~
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    clascolr = ~24 99 169 2 93~
	
	clasiskl = ~10 0 0 0 0 10 0~
	
	// clasthac = ~0~
	
	thiefscl = ~100 100 100 100 100 100 0 0~ // PICK POCKETS, OPEN LOCKS, FIND TRAPS, MOVE SILENTLY, HIDE IN SHADOWS, DETECT ILLUSIONS, SET TRAPS, STEALTH
	
	//								1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 5
	//			0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 
	backstab = ~2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	sneakatt = ~1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 8 8 8 8 8 8 9 9 9 9~
	
	crippstr = ~0 0 0 0 0 0 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5 6 6 6 6 6 7 7 7 7 7 8 8 8 8 8 9 9 9 9 9~
	
	// thiefskl = ~40 20~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~C0ATRNAM.SPL~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 290 parameter1 = RESOLVE_STR_REF (~诡术师~) END

COPY_EXISTING ~C0ATR01.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~法术防护已移除~) END
SAY NAME1 ~窃法~
SAY UNIDENTIFIED_DESC ~窃法
诡术师可窃取目标法师或吟游诗人的魔力，移除目标一个已记忆的最高环奥术法术，并回复自身一个已消耗的法术位。~
COPY_EXISTING ~C0ATR01B.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~法术已窃取~) END

COPY_EXISTING ~C0ATR02.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~即兴背刺~) END

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

OUTER_SET sorcerer_trickster = IDS_OF_SYMBOL (~kit~ ~C0_ARCANE_TRICKSTER_SORC~)
  
COPY ~%MOD_FOLDER%/lua/m_c0src.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%sorcerer_trickster%~~~~~ //"
  END

END

ACTION_IF GAME_IS ~BG2EE EET~ BEGIN

COMPILE ~%MOD_FOLDER%/strongholds/arcane_trickster_sorc.d~

  END