
COPY_EXISTING ~C0AA.2DA~ ~OVERRIDE/C0AARN.2DA~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/C0AARN.2DA~
	REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%] ~ ~**** ~ // TOUGHNESS
	REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%][%0-9%] ~ ~**** ~ // TOUGHNESS
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN0 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_C0AAIN3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0AAIN3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0AAIN4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAINN END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = GA_C0AASP1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0AASP2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0AASP2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0AASP2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = GA_C0AASP3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = GA_C0AASP4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 STR_VAR f_Entry = GA_C0AASP5 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT aa_ranger ~魔射手：精灵战团的精锐，魔射手是擅长以魔法辅弼战技的战士。走出森林之外，魔射手凭借超凡的弓术与附魔箭矢的能力，在诸国间声名远扬。队伍之中，他们足以令整支敌军闻风丧胆。由于精灵族秘传其技，人类魔射手十分罕见，但也并非闻所未闻。

职业优势：
–1级起，所有远程武器命中+1，之后每提升5级再+1。
–可将长弓、短弓与十字弓修习至宗师级（5点熟练槽）。
–可记忆少量法师法术：
 1环：魔法飞弹、护盾、镜像术
 2环：模糊术、麦夫酸箭、衰弱射线
 3环：火焰箭、防护普通远程武器、麦夫流星雨
–获得「附魔箭」能力。

附魔箭：魔射手被动为<PRO_HISHER>箭矢注入魔力。其射出的投射物始终视为+1附魔武器，并额外造成1点魔法伤害；每提升5级，附魔等级与魔法伤害各+1，20级时达到最高+5附魔与5点魔法伤害。额外伤害受目标魔法抗性减免。

–3级：每日可使用一次「熵光护盾」。

熵光护盾：魔射手周身浮现出五彩辉光的魔法力场，免疫普通远程武器，并对远程武器的护甲等级获得-2加值，持续时长为每等级1轮。10级时加值提升至-4，17级时提升至-6。

–5级：每日可使用三次「灌法箭」能力。

灌法箭：魔射手以奥术魔法为<PRO_HISHER>下一轮内射出的下一发箭矢附魔，使其命中后爆炸，每5级额外造成1d6点火焰范围伤害。
RAPID_SHOT
–9级：每日可使用一次「追踪箭」能力。

追踪箭：技艺精湛的魔射手可为<PRO_HISHER>箭矢附魔，使其必中目标。<PRO_HISHER>下一轮内的下一次远程攻击必定暴击，且每提升5级额外造成2点伤害。

IMPROVED_SHOT
–13级：每日可使用一次「相位箭」能力。

相位箭：经验丰富的魔射手可为<PRO_HISHER>下一轮内的下一发箭矢附魔，使其化为虚体投射物穿透护甲，额外造成4d6点魔法伤害，同时目标的远程抗性降低50%，对远程武器的护甲等级每5级降低2点，持续1轮。

–17级：每日可使用一次「死亡箭」能力。

死亡箭：魔射手大师可为<PRO_HISHER>下一轮内的下一发箭矢附魔，目标若未通过死亡豁免即被即刻斩杀。生命值超过60的目标可进行死亡豁免以抵消效果。每提升5级，目标的豁免惩罚增加1点。

职业限制：
–生命骰：d8
–手持近战武器时，零级命中值（THAC0）受-3惩罚。
–仅限人类、精灵或半精灵种族。SET_TRAPS
–除长弓、短弓与十字弓外，其他武器的熟练等级不得超过入门级（1点熟练槽）。
–所有武器风格的熟练等级不得超过入门级（1点熟练槽）。
–不得穿戴比精灵锁甲更重的护甲。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE aa_ranger ~%aa_ranger%~ BEGIN
  REPLACE_TEXTUALLY EXACT_MATCH ~RAPID_SHOT~ ~
–6级：可使用「速射」攻击模式。

速射：射手每轮可额外进行一次攻击，但命中受-4惩罚。
~
  REPLACE_TEXTUALLY EXACT_MATCH ~IMPROVED_SHOT~ ~
–12级：精通速射：速射状态下的命中惩罚降低至-2。~
END

END ELSE BEGIN

OUTER_PATCH_SAVE aa_ranger ~%aa_ranger%~ BEGIN
  REPLACE_TEXTUALLY ~RAPID_SHOT~ ~~
  REPLACE_TEXTUALLY ~IMPROVED_SHOT~ ~~
END

END

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

OUTER_PATCH_SAVE aa_ranger ~%aa_ranger%~ BEGIN
  REPLACE_TEXTUALLY ~SET_TRAPS~ ~
–无法设置陷阱。~
END

END ELSE BEGIN

OUTER_PATCH_SAVE aa_ranger ~%aa_ranger%~ BEGIN
  REPLACE_TEXTUALLY ~SET_TRAPS~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 12
	
    mixed         = RESOLVE_STR_REF(~魔射手~)
	
    lower         = RESOLVE_STR_REF(~魔射手~)
	
    help          = RESOLVE_STR_REF(~%aa_ranger%~)
	
    briefdesc     = RESOLVE_STR_REF(~魔射手：精灵战团的精锐，魔射手是擅长以魔法辅弼战技的战士。走出森林之外，魔射手凭借超凡的弓术与附魔箭矢的能力，在诸国间声名远扬。队伍之中，他们足以令整支敌军闻风丧胆。由于精灵族秘传其技，人类魔射手十分罕见，但也并非闻所未闻。~)
  STR_VAR
    kit_name      = ~C0AA_RANGER~
	
    unusable      = ~0x00008000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    abclasrq      = ~13 15 0 14 14 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 0 0 0 0 0~
	
    // luabbr        = ~FI0~
	
    stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0AARN.2da~
	
    kittable      = ~K_R_H K_R_E K_R_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPARCH~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// traplimt = ~6~
	
    bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "C0AA_RANGER") BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count 0
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~SPWI112.SPL~ ~OVERRIDE/C0AA101.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI114.SPL~ ~OVERRIDE/C0AA102.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI120.SPL~ ~OVERRIDE/C0AA103.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI201.SPL~ ~OVERRIDE/C0AA201.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI211.SPL~ ~OVERRIDE/C0AA202.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI221.SPL~ ~OVERRIDE/C0AA203.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI303.SPL~ ~OVERRIDE/C0AA301.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI311.SPL~ ~OVERRIDE/C0AA302.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI325.SPL~ ~OVERRIDE/C0AA303.SPL~
WRITE_SHORT 0X1C 2

COPY_EXISTING ~C0AARNS.SPL~ ~OVERRIDE~
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA101 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA102 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA103 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA201 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA202 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA203 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA301 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA302 END
 LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 2 timing = 1 STR_VAR resource = C0AA303 END


ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~M_C0RAN1.lua~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~C0AARN.2DA~ BEGIN
COPY_EXISTING ~C0AARN.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 18 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  PRETTY_PRINT_2DA
BUT_ONLY

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "C0AA_RANGER") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "C0AA_RANGER") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 20
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 20
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END
END
END
