COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells~ ~override~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/C0AA.2DA~
	REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	// REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	// REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	// REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN0 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_C0AAIN3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAIN3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0AAIN3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0AAIN4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AAINN END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = GA_C0AASP1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0AASP2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0AASP2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0AASP2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = GA_C0AASP3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = GA_C0AASP4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 STR_VAR f_Entry = GA_C0AASP5 END

 	PRETTY_PRINT_2DA

COPY ~%MOD_FOLDER%/2DAs/HPARCH.2da~ ~OVERRIDE~

OUTER_SPRINT kit_description ~魔射手：精灵战团的精锐，魔射手是擅长以魔法辅弼战技的战士。走出森林之外，魔射手凭借超凡的弓术与附魔箭矢的能力，在诸国间声名远扬。队伍之中，他们足以令整支敌军闻风丧胆。由于精灵族秘传其技，人类魔射手十分罕见，但也并非闻所未闻。

职业优势：
–1级起，所有远程武器命中+1，之后每提升5级再+1。
–获得「附魔箭」能力。

附魔箭：魔射手被动为<PRO_HISHER>箭矢注入魔力。其射出的投射物始终视为+1附魔武器，并额外造成1点魔法伤害；每提升5级，附魔等级与魔法伤害各+1，20级时达到最高+5附魔与5点魔法伤害。额外伤害受目标魔法抗性减免。

–3级：每日可使用一次「熵光护盾」。

熵光护盾：魔射手周身浮现出五彩辉光的魔法力场，免疫普通远程武器，并对远程武器的护甲等级获得-2加值，持续时长为每等级1轮。10级时加值提升至-4，17级时提升至-6。

–5级：每日可使用三次「灌法箭」能力。

灌法箭：魔射手以奥术魔法为<PRO_HISHER>下一轮内射出的下一发箭矢附魔，使其命中后爆炸，每5级额外造成1d6点火焰范围伤害。

–9级：每日可使用一次「追踪箭」能力。

追踪箭：技艺精湛的魔射手可为<PRO_HISHER>箭矢附魔，使其必中目标。<PRO_HISHER>下一轮内的下一次远程攻击必定暴击，且每提升5级额外造成2点伤害。

–13级：每日可使用一次「相位箭」能力。

相位箭：经验丰富的魔射手可为<PRO_HISHER>下一轮内的下一发箭矢附魔，使其化为虚体投射物穿透护甲，额外造成4d6点魔法伤害，同时目标的远程抗性降低50%，对远程武器的护甲等级每5级降低2点，持续1轮。

–17级：每日可使用一次「死亡箭」能力。

死亡箭：魔射手大师可为<PRO_HISHER>下一轮内的下一发箭矢附魔，目标若未通过死亡豁免即被即刻斩杀。生命值超过60的目标可进行死亡豁免以抵消效果。每提升5级，目标的豁免惩罚增加1点。

职业限制：
–生命骰：d8
–手持近战武器时，零级命中值（THAC0）受-3惩罚。
–仅限人类、精灵或半精灵种族。KIT_DISADV_1
–除长弓、短弓与十字弓外，其他武器的熟练等级不得超过入门级（1点熟练槽）。
–所有武器风格的熟练等级不得超过入门级（1点熟练槽）。
–不得穿戴比精灵锁甲更重的护甲。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「猛力攻击」与「武器娴熟」。
–16级时不会获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~魔射手~)
	
    lower         = RESOLVE_STR_REF(~魔射手~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)

    briefdesc     = RESOLVE_STR_REF(~魔射手：精灵战团的精锐，魔射手是擅长以魔法辅弼战技的战士。走出森林之外，魔射手凭借超凡的弓术与附魔箭矢的能力，在诸国间声名远扬。队伍之中，他们足以令整支敌军闻风丧胆。由于精灵族秘传其技，人类魔射手十分罕见，但也并非闻所未闻。~)
  STR_VAR
    kit_name      = ~C0AA~
	
    unusable      = ~0x00008000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    abclasrq      = ~0 15 0 14 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~FI0~
	
    stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0AA.2da~
	
    kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPARCH~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// traplimt = ~6~
	
    bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aain1.spl~ ~override~
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aain2.spl~ ~override~

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~附魔箭~) STR_VAR bam_file = c0aain3i RET c0aain3i = icon END

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aain3.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0aain3i END

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1a.eff~ ~override/c0aaen2a.eff~
WRITE_SHORT 0x1c 2 
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1b.eff~ ~override/c0aaen2b.eff~
WRITE_SHORT 0x1c 2
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1c.eff~ ~override/c0aaen2c.eff~
WRITE_SHORT 0x1c 2
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1d.eff~ ~override/c0aaen2d.eff~
WRITE_SHORT 0x1c 2
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1a.eff~ ~override/c0aaen3a.eff~
WRITE_SHORT 0x1c 3 
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1b.eff~ ~override/c0aaen3b.eff~
WRITE_SHORT 0x1c 3
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1c.eff~ ~override/c0aaen3c.eff~
WRITE_SHORT 0x1c 3
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1d.eff~ ~override/c0aaen3d.eff~
WRITE_SHORT 0x1c 3
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1a.eff~ ~override/c0aaen4a.eff~
WRITE_SHORT 0x1c 4 
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1b.eff~ ~override/c0aaen4b.eff~
WRITE_SHORT 0x1c 4
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1c.eff~ ~override/c0aaen4c.eff~
WRITE_SHORT 0x1c 4
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1d.eff~ ~override/c0aaen4d.eff~
WRITE_SHORT 0x1c 4
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1a.eff~ ~override/c0aaen5a.eff~
WRITE_SHORT 0x1c 5 
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1b.eff~ ~override/c0aaen5b.eff~
WRITE_SHORT 0x1c 5
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1c.eff~ ~override/c0aaen5c.eff~
WRITE_SHORT 0x1c 5
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aaen1d.eff~ ~override/c0aaen5d.eff~
WRITE_SHORT 0x1c 5

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aain4.spl~ ~override~
SAY NAME1 ~附魔箭~
SAY UNIDENTIFIED_DESC ~附魔箭
魔射手被动为<PRO_HISHER>箭矢注入魔力。其射出的投射物始终视为+1附魔武器，并额外造成1点魔法伤害；每提升5级，附魔等级与魔法伤害各+1，20级时达到最高+5附魔与5点魔法伤害。额外伤害受目标魔法抗性减免。

本能力可随时开启或关闭附魔箭效果。~

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aain4a.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~附魔箭已停用~) END

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp1.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
      match_parameter1 = 26335
 parameter1 = RESOLVE_STR_REF (~免疫普通远程武器~)
  END
SAY NAME1 ~熵光护盾~
 SAY NAME2 ~熵光护盾~
 SAY UNIDENTIFIED_DESC ~熵光护盾
魔射手周身浮现出五彩辉光的魔法力场，免疫普通远程武器，并对远程武器的护甲等级获得-2加值，持续时长为每等级1轮。10级时加值提升至-4，17级时提升至-6。~
 
ADD_PROJECTILE ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp2.PRO~
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp2.spl~ ~override~
SAY NAME1 ~灌法箭~
 SAY NAME2 ~灌法箭~
 SAY UNIDENTIFIED_DESC ~灌法箭
魔射手以奥术魔法为<PRO_HISHER>下一发箭矢附魔，使其命中后爆炸，每5级额外造成1d6点火焰范围伤害。~
 
COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp2a.spl~ ~override~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%c0aasp2%~
END

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp3.spl~ ~override~
SAY NAME1 ~追踪箭~
 SAY NAME2 ~追踪箭~
 SAY UNIDENTIFIED_DESC ~追踪箭
技艺精湛的魔射手可为<PRO_HISHER>下一发箭矢附魔，使其必中目标。<PRO_HISHER>下一次远程攻击必定暴击，且每提升5级额外造成2点伤害。
生成一枚必中箭矢，获得+20命中加值与额外穿刺伤害。~

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp4.spl~ ~override~
SAY NAME1 ~相位箭~
 SAY NAME2 ~相位箭~
 SAY UNIDENTIFIED_DESC ~相位箭
经验丰富的魔射手可为<PRO_HISHER>下一发箭矢附魔，使其化为虚体投射物穿透护甲，目标的远程抗性降低50%，同时对远程武器的护甲等级每5级降低2点。~

COPY ~%MOD_FOLDER%/Fighter/ArcaneArcher/spells/c0aasp5.spl~ ~override~
SAY NAME1 ~死亡箭~
 SAY NAME2 ~死亡箭~
 SAY UNIDENTIFIED_DESC ~死亡箭
魔射手大师可为<PRO_HISHER>下一发箭矢附魔，目标若未通过死亡豁免即被即刻斩杀。每提升5级，目标的豁免惩罚增加1点。~


COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
      READ_BYTE    0x1E row1
      READ_BYTE    0x1F row2
      READ_BYTE    0x20 row3
      READ_BYTE    0x21 row4
      READ_BYTE    0x2d kit3
    PATCH_IF ((row3 BAND 0b01100000) = 0b00000000) BEGIN // if it is usable by thieves and rangers
      READ_SHORT    0x1C type //reads the byte containing item type
	  READ_SHORT    0x22 appearance //reads the byte containing item appearance
      PATCH_IF (type = 2) AND (appearance = 16691) BEGIN // if it is chain mail
       WRITE_BYTE    0x2d (kit3 BAND 0b01111111)
      END
    END
  END
BUT_ONLY_IF_IT_CHANGES

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ BEGIN

COPY_EXISTING ~C0AA.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  // LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // POWER ATTACK
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
  // LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = AP_C0FIG04 END // SPECIALIZATION
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0FIG03 END // IMPROVED INITIATIVE
  PRETTY_PRINT_2DA

	END