COPY ~%MOD_FOLDER%/Ranger/Archer/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Ranger/Archer/spells~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/bmp~ ~OVERRIDE~

COPY_EXISTING ~CLABRN01.2DA~ ~OVERRIDE/CLABRN02.2DA~
	REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%] ~ ~**** ~ // TOUGHNESS
	REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%][%0-9%] ~ ~**** ~ // TOUGHNESS
	REPLACE_TEXTUALLY ~GA_SPCL311~ ~**** ~ // CHARM ANIMAL
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPCL121 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0ARC03 END
  	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0ARC00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 3 STR_VAR f_Entry = AP_C0ARC01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = GA_SPCL121 END

 	PRETTY_PRINT_2DA

COPY ~%MOD_FOLDER%/2DAs/HPARCH.2da~ ~OVERRIDE~

APPEND ~splprot.2da~ ~C0_KIT_CHECK_NOT 152 -1 5~ UNLESS ~C0_KIT_CHECK_NOT~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_KIT_CHECK_NOT~ BEGIN
	    SET C0_KIT_CHECK_NOT = %row%
	  END
	END

OUTER_SET opcode_342_eeex = 0
ACTION_IF MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~ AND FILE_EXISTS ~EEex_scripts/EEex_Opcode_Patch.lua~ THEN BEGIN
  
  PRINT ~EEex_Opcode_Patch exists.~

COPY_EXISTING ~EEex_scripts/EEex_Opcode_Patch.lua~ ~EEex_scripts~
PATCH_IF ~~ STRING_MATCHES_REGEXP ~Opcode #342~ BEGIN
  SET opcode_342_eeex = 1
  END

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN
  PRINT ~Opcode #342 has been patched.~
    END

END

ACTION_IF NOT (opcode_342_eeex = 1) THEN BEGIN

ACTION_DEFINE_ASSOCIATIVE_ARRAY archer_anims_6xxx BEGIN
    ~6100~ => ~ARCHER_MALE_HUMAN_1~
    ~6100a~ => ~ARCHER_MALE_HUMAN_2~
    ~6101~ => ~ARCHER_MALE_ELF_1~
    ~6101a~ => ~ARCHER_MALE_ELF_2~
    ~6102~ => ~ARCHER_MALE_DWARF_1~
    ~6102a~ => ~ARCHER_MALE_DWARF_2~
    ~6103~ => ~ARCHER_MALE_HALFLING_1~
    ~6103a~ => ~ARCHER_MALE_HALFLING_2~
    ~6104~ => ~ARCHER_MALE_GNOME_1~
    ~6104a~ => ~ARCHER_MALE_GNOME_2~
    ~6105~ => ~ARCHER_MALE_HALFORC_1~
    ~6105a~ => ~ARCHER_MALE_HALFORC_2~
    ~6110~ => ~ARCHER_FEMALE_HUMAN_1~
    ~6110a~ => ~ARCHER_FEMALE_HUMAN_2~
    ~6111~ => ~ARCHER_FEMALE_ELF_1~
    ~6111a~ => ~ARCHER_FEMALE_ELF_2~
    ~6112~ => ~ARCHER_FEMALE_DWARF_1~
    ~6112a~ => ~ARCHER_FEMALE_DWARF_2~
    ~6113~ => ~ARCHER_FEMALE_HALFLING_1~
    ~6113a~ => ~ARCHER_FEMALE_HALFLING_2~
    ~6114~ => ~ARCHER_FEMALE_GNOME_1~
    ~6114a~ => ~ARCHER_FEMALE_GNOME_2~
    ~6115~ => ~ARCHER_FEMALE_HALFORC_1~
    ~6115a~ => ~ARCHER_FEMALE_HALFORC_2~
  END
  ACTION_PHP_EACH archer_anims_6xxx AS animation => symbol BEGIN
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x6000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/Ranger/archer/animations/%animation%.ini~ ~override/%hexNumber%.ini~
    OUTER_SET EVAL ~slot_%folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x%hexNumber% %symbol%~

	END

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
      READ_SHORT    0x1C type //reads the byte containing item type
	  READ_SHORT    0x22 appearance //reads the byte containing item appearance
      PATCH_IF (type = 15) OR (type = 27) BEGIN // if it is leather armor
// human
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 1
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP01
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 1
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP02
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 1
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP03
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 1
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP04
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP01
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP02
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP03
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP04
		END
    
// tiefling
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 153
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 153
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 153
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 153
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP08
		END
    
// aasimar
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 185
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 185
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 185
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 185
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP08
		END
    
// halfelf
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 3
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 3
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 3
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 3
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP08
		END
    
// elf
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 2
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 2
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 2
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 2
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP08
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP08
		END

// halforc
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 7
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP09
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 7
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP10
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 7
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP11
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 7
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP12
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP09
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP10
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP11
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP12
		END

// dwarf
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 4
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP13
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 4
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP14
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 4
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP15
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 4
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP16
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP13
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP14
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP15
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP16
		END

// halfling
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 5
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP17
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 5
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP18
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 5
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP19
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 5
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP20
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP17
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP18
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP19
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP20
		END

// gnome
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 6
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP21
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 6
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP22
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 6
				parameter2 = 4
				timing = 2
        dicenumber = 19
        dicesize = 7
			STR_VAR
				resource = C0ARCP23
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 6
				parameter2 = 4
				timing = 2
        dicenumber = 0
        dicesize = 20
			STR_VAR
				resource = C0ARCP24
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP21
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 117
				timing = 2
			STR_VAR
				resource = C0ARCP22
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP23
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = 1
				parameter2 = 107
				timing = 2
			STR_VAR
				resource = C0ARCP24
		END

		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP01
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP02
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP03 
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP04
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP08
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP09
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP10
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP11
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP12
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP13
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP14
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP15
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP16
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP17
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP18
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP19
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP20
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP21
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP22
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP23
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 318
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = C0_KIT_CHECK_NOT
				timing = 2
			STR_VAR
				resource = C0ARCP24
		END
    
      END
    END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_HUMAN_1~)
WRITE_BYTE 0x90 1
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP02.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_HUMAN_2~)
WRITE_ASCII 0x94 C0ARCP02
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP03.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_HUMAN_1~)
WRITE_ASCII 0x94 C0ARCP03
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP04.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_HUMAN_2~)
WRITE_ASCII 0x94 C0ARCP04

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP05.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_ELF_1~)
WRITE_ASCII 0x94 C0ARCP05
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP06.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_ELF_2~)
WRITE_ASCII 0x94 C0ARCP06
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP07.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_ELF_1~)
WRITE_ASCII 0x94 C0ARCP07
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP08.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_ELF_2~)
WRITE_ASCII 0x94 C0ARCP08

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP09.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_HALFORC_1~)
WRITE_ASCII 0x94 C0ARCP09
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP10.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_HALFORC_2~)
WRITE_ASCII 0x94 C0ARCP10
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP11.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_HALFORC_1~)
WRITE_ASCII 0x94 C0ARCP11
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP12.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_HALFORC_2~)
WRITE_ASCII 0x94 C0ARCP12

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP13.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_DWARF_1~)
WRITE_ASCII 0x94 C0ARCP13
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP14.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_DWARF_2~)
WRITE_ASCII 0x94 C0ARCP14
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP15.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_DWARF_1~)
WRITE_ASCII 0x94 C0ARCP15
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP16.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_DWARF_2~)
WRITE_ASCII 0x94 C0ARCP16

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP17.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_HALFLING_1~)
WRITE_ASCII 0x94 C0ARCP17
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP18.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_HALFLING_2~)
WRITE_ASCII 0x94 C0ARCP18
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP19.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_HALFLING_1~)
WRITE_ASCII 0x94 C0ARCP19
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP20.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_HALFLING_2~)
WRITE_ASCII 0x94 C0ARCP20

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP21.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_GNOME_1~)
WRITE_ASCII 0x94 C0ARCP21
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP22.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_MALE_GNOME_2~)
WRITE_ASCII 0x94 C0ARCP22
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP23.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_GNOME_1~)
WRITE_ASCII 0x94 C0ARCP23
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP24.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~ARCHER_FEMALE_GNOME_2~)
WRITE_ASCII 0x94 C0ARCP24

END ELSE BEGIN

COPY ~%MOD_FOLDER%/Ranger/Archer/eeex~ ~override~

COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP02.EFF~
	WRITE_SHORT 0x1c 1
	WRITE_ASCII 0x30 ~C0MSHO02~
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP03.EFF~
	WRITE_SHORT 0x1c 2
	WRITE_ASCII 0x30 ~C0MSHO03~
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP04.EFF~
	WRITE_SHORT 0x1c 3
	WRITE_ASCII 0x30 ~C0MSHO04~
COPY_EXISTING ~C0ARCP01.EFF~ ~OVERRIDE/C0ARCP05.EFF~
	WRITE_SHORT 0x1c 4
	WRITE_ASCII 0x30 ~C0MSHO05~

COPY_EXISTING ~C0ARCP02.EFF~ ~OVERRIDE/C0ARCP06.EFF~
	WRITE_ASCII 0x30 ~C0MSHO06~
COPY_EXISTING ~C0ARCP03.EFF~ ~OVERRIDE/C0ARCP07.EFF~
	WRITE_ASCII 0x30 ~C0MSHO07~
COPY_EXISTING ~C0ARCP04.EFF~ ~OVERRIDE/C0ARCP08.EFF~
	WRITE_ASCII 0x30 ~C0MSHO08~
COPY_EXISTING ~C0ARCP05.EFF~ ~OVERRIDE/C0ARCP09.EFF~
	WRITE_ASCII 0x30 ~C0MSHO09~
	
COPY_EXISTING ~C0ARCP03.EFF~ ~OVERRIDE/C0ARCP10.EFF~
	WRITE_ASCII 0x30 ~C0MSHO10~
COPY_EXISTING ~C0ARCP04.EFF~ ~OVERRIDE/C0ARCP11.EFF~
	WRITE_ASCII 0x30 ~C0MSHO11~
COPY_EXISTING ~C0ARCP05.EFF~ ~OVERRIDE/C0ARCP12.EFF~
	WRITE_ASCII 0x30 ~C0MSHO12~

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
      READ_SHORT    0x1C type //reads the byte containing item type
	  READ_SHORT    0x22 appearance //reads the byte containing item appearance
      PATCH_IF (type = 15) OR (type = 27) BEGIN // if it is leather armor

		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicesize = 7
			STR_VAR
				resource = C0ARCP01
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 12
				dicesize = 7
			STR_VAR
				resource = C0ARCP02
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 12
				dicesize = 7
			STR_VAR
				resource = C0ARCP03
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 12
				dicesize = 7
			STR_VAR
				resource = C0ARCP04
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 12
				dicesize = 7
			STR_VAR
				resource = C0ARCP05
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicesize = 13
			STR_VAR
				resource = C0ARCP06
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 19
				dicesize = 13
			STR_VAR
				resource = C0ARCP07
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 19
				dicesize = 13
			STR_VAR
				resource = C0ARCP08
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicenumber = 19
				dicesize = 13
			STR_VAR
				resource = C0ARCP09
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicesize = 20
			STR_VAR
				resource = C0ARCP10
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicesize = 20
			STR_VAR
				resource = C0ARCP11
		END
    
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~FERALAN~)
				parameter2 = 9
				timing = 2
				dicesize = 20
			STR_VAR
				resource = C0ARCP12
		END
    
      END
    END
BUT_ONLY_IF_IT_CHANGES
	END


ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN
LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~FERALAN~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~射手：射手是远程武器技艺的极致化身——顶尖的神射手，无论难度多高都能精准命中。无论是作为游骑兵独自倾泻箭雨，还是潜伏于暗影中等待最佳时机的狙击手，射手精通各类射术。为了练就这般技艺，射手牺牲了部分近战武器与护甲的熟练度。

职业优势：
–远程武器命中掷骰+1，每提升3级再额外+1。
–可将长弓、短弓与十字弓修习至宗师级（5点熟练槽）。
–远视：射手的视野范围略高于常人，处于潜行或隐形状态时会进一步提升。
–可使用「速射」攻击模式。

速射：射手每轮可额外进行一次攻击，但命中受-4惩罚。
–4级：每日可使用一次「精准射击」能力，每提升4级额外获得一次使用次数。

精准射击：射手瞄准敌人的肢体与要害射出致残一击。接下来10秒内所有成功的远程攻击，除造成正常伤害外，还将根据射手等级叠加以下非累积效果，每提升一级效果持续1轮：
 4级：目标的敏捷属性减半
 8级：目标的移动速度降至25%
 12级：目标每轮损失一次攻击
 16级：每次命中额外造成2点无视护甲远程伤害。
 
–7级：多重射击：射手每轮使用弓或十字弓的第一次攻击会射出两发投射物而非一发，每发箭矢单独进行命中判定。
–12级：精通速射：速射状态下的命中惩罚降低至-2。
–13级：多重射击现在适用于每轮的前两次攻击。
–16级：狙击：潜行或隐形状态下，射手的远程攻击必定暴击。
–20级：多重射击现在适用于每轮的前三次攻击。

职业限制：
–生命骰：d8，不获得强健加值
–手持近战武器时，零级命中值（THAC0）受-3惩罚。
–近战武器仅能达到熟练级（1点熟练槽）。
–无法获得双武器风格熟练。
–无法设置陷阱。
–无法使用「魅惑动物」能力。~
END
ACTION_IF NOT MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN
LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~FERALAN~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~射手：射手是远程武器技艺的极致化身——顶尖的神射手，无论难度多高都能精准命中。无论是作为游骑兵独自倾泻箭雨，还是潜伏于暗影中等待最佳时机的狙击手，射手精通各类射术。为了练就这般技艺，射手牺牲了部分近战武器与护甲的熟练度。

职业优势：
–远程武器命中掷骰+1，每提升3级再额外+1。
–可将长弓、短弓与十字弓修习至宗师级（5点熟练槽）。
–远视：射手的视野范围略高于常人，处于潜行或隐形状态时会进一步提升。
–可使用「速射」攻击模式。

速射：射手每轮可额外进行一次攻击，但命中受-4惩罚。
–4级：每日可使用一次「精准射击」能力，每提升4级额外获得一次使用次数。

精准射击：射手瞄准敌人的肢体与要害射出致残一击。接下来10秒内所有成功的远程攻击，除造成正常伤害外，还将根据射手等级叠加以下非累积效果，每提升一级效果持续1轮：
 4级：目标的敏捷属性减半
 8级：目标的移动速度降至25%
 12级：目标每轮损失一次攻击
 16级：每次命中额外造成2点无视护甲远程伤害。
 
–7级：多重射击：射手每轮使用弓或十字弓的第一次攻击会射出两发投射物而非一发，每发箭矢单独进行命中判定。
–12级：精通速射：速射状态下的命中惩罚降低至-2。
–13级：多重射击现在适用于每轮的前两次攻击。
–16级：狙击：潜行或隐形状态下，射手的远程攻击必定暴击。
–20级：多重射击现在适用于每轮的前三次攻击。

职业限制：
–生命骰：d8
–手持近战武器时，零级命中值（THAC0）受-3惩罚。
–近战武器仅能达到熟练级（1点熟练槽）。
–无法获得双武器风格熟练。
–无法使用「魅惑动物」能力。~
END
	
// ARCHER - HIT DIE
COPY_EXISTING ~hpclass.2da~ OVERRIDE
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FERALAN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~HPARCH~
	  END
	END
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ARCHER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 0 cols ~FERALAN~
		SET_2DA_ENTRY (%patch_row%) 1 cols ~HPARCH~
	  END
	END
  
// ARCHER - HLA
  COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FERALAN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~C0RA1~
	  END
	END

COPY_EXISTING ~LURA0.2da~ ~override/LUC0RA1.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL907~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0ARCH1~ ability = ~GA_C0ARCH01~ num_allowed = 20 END
	
// ARCHER - PROFICIENCIES
ACTION_CLEAR_ARRAY weapprof_cols_archer
        
COPY_EXISTING ~weapprof.2da~  ~override~
  COUNT_2DA_COLS col_count
  SET col_check = col_count - 1
  FOR (column = 0; column < col_check; ++column) BEGIN
    READ_2DA_ENTRY 0 column col_check name
    PATCH_IF (("FERALAN" STRING_COMPARE_CASE "%name%" = 0)) BEGIN
      SET column += 1 // row with names has an empty entry for the first column
      DEFINE_ASSOCIATIVE_ARRAY weapprof_cols_archer BEGIN ~%column%~ => ~%column%~ END
    END
  END
  PATCH_PHP_EACH weapprof_cols_archer AS column => foo BEGIN
    FOR (row = 8; row < 32; ++row) BEGIN
      READ_2DA_ENTRY row column col_count stars
      PATCH_IF (stars < 5) BEGIN
        SET_2DA_ENTRY 31 column col_count 0
      END
    END
  END
  PRETTY_PRINT_2DA
  BUT_ONLY
  
DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

COPY_EXISTING SPCL121.SPL OVERRIDE
SAY NAME1 ~精准射击~
SAY UNIDENTIFIED_DESC ~精准射击
射手瞄准敌人的肢体与要害射出致残一击。接下来10秒内所有成功的远程攻击，除造成正常伤害外，还将根据射手等级叠加以下非累积效果，效果持续1轮：
 4级：目标的敏捷属性减半
 8级：目标的移动速度降至25%
 12级：目标每轮损失一次攻击
 16级：每次命中额外造成2点无视护甲远程伤害。~

INCLUDE ~%MOD_FOLDER%/spells/rapidshot.tpa~

COPY_EXISTING C0ARCH01.SPL OVERRIDE
SAY NAME1 ~强效精准射击~
SAY UNIDENTIFIED_DESC ~强效精准射击
接下来10秒内所有成功的远程攻击，附带普通精准射击的全部效果。此外，每次攻击还将造成最大伤害，并将目标眩晕3秒。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~M_C0RAN1.lua~ THEN BEGIN

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "FERALAN") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "FERALAN") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 20
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 20
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END
END
