COPY ~%MOD_FOLDER%/Thief/Assassin/2da~ ~override~
COPY ~%MOD_FOLDER%/Thief/Assassin/bams~ ~override~
COPY ~%MOD_FOLDER%/Thief/Assassin/spells~ ~override~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/CLABTH02.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0ASIN2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AS#I1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AS#I3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_Increment = 10 STR_VAR f_Entry = AP_C0AS#I3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 6 STR_VAR f_Entry = GA_C0AS#P1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0ASIN1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0A_A01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_Increment = 1 STR_VAR f_Entry = AP_C0AS#I2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = AP_C0AS#I4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = AP_C0AS#I5 END

 	PRETTY_PRINT_2DA

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~背刺：麻痹~) STR_VAR bam_file = c0asic01 RET c0asic01 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~背刺：断筋~) STR_VAR bam_file = c0asic02 RET c0asic02 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~背刺：流血~) STR_VAR bam_file = c0asic03 RET c0asic03 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~背刺：割喉~) STR_VAR bam_file = c0asic04 RET c0asic04 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~背刺：致命~) STR_VAR bam_file = c0asic05 RET c0asic05 = icon END

  COPY_EXISTING ~alignmnt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ASSASIN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 0
		SET_2DA_ENTRY (%patch_row%) 2 cols 1
		SET_2DA_ENTRY (%patch_row%) 3 cols 1
		SET_2DA_ENTRY (%patch_row%) 4 cols 0
		SET_2DA_ENTRY (%patch_row%) 5 cols 1
		SET_2DA_ENTRY (%patch_row%) 6 cols 1
		SET_2DA_ENTRY (%patch_row%) 7 cols 0
		SET_2DA_ENTRY (%patch_row%) 8 cols 1
		SET_2DA_ENTRY (%patch_row%) 9 cols 1
	  END
	END

  COPY_EXISTING ~abclasrq.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ASSASIN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols 15
	  END
	END

  COPY_EXISTING ~abclsmod.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ASSASIN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 6 cols %-2%
	  END
	END

  COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ASSASIN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~c0as~
	  END
	END
	
COPY_EXISTING ~LUTH0.2da~ ~override/LUC0AS.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL910~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL911~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL912~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0ASSAS1~ ability = ~GA_C0ASHLA1~ num_allowed = 16 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0ASSAS2~ ability = ~AP_C0ASHLA2~ num_allowed = 1 prerequisite = ~GA_C0ASHLA1~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0ASSAS3~ ability = ~GA_C0ASHLA3~ num_allowed = 1 prerequisite = ~AP_C0ASHLA2~ END	

COPY_EXISTING ~clasiskl.2da~ ~override~
SET_2DA_ENTRY 6 36 1 ~10~
SET_2DA_ENTRY 7 36 1 ~10~
	
COPY_EXISTING ~thiefscl.2da~ ~override~
SET_2DA_ENTRY 9 36 1 ~0~
	
  COPY_EXISTING ~thiefskl.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ASSASIN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 2 cols 10
	  END
	END
	
LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~ASSASIN~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~刺客：刺客之道是一门令人闻风丧胆的行当，这绝非虚言。作为刺杀艺术的大师，刺客最令人忌惮之处，在于既能以一记蓄谋已久的突袭夺命，也能仅凭淬毒之刃的一道浅伤取人性命。世上无人能像刺客这般以千般手法猎杀目标，而一旦刺客锁定了猎物，其命运往往便已注定。刺杀之道讲究迅捷与狡诈，但刺客最重要的技艺却是耐心——耐心分析目标，观察破绽，寻得最有效的方式确保一击必杀，而后遁形无踪。

选择踏上刺杀之路的人，缘由各有不同。多者是投机之徒，为一己之利出卖技艺。也有治安维持者，以铲除「败类」的方式，妄图让世界变得更好，或至少更太平。更有甚者，单纯只为猎杀的快感而行事。世人常说，没有两名刺客的动机与手法是相同的。

由于其行当的阴暗性质，加之行事偏好隐秘，刺客为正派人士所恐惧与唾弃。刺客不求声名与认可，因这些事物只会有碍其行事，因此他们极少出任领袖之位，也极少成群结队。顶尖的刺客，几乎籍籍无名。

职业优势：
–初始背刺倍率为3倍。刺客的背刺倍率在17级时达到上限7倍。
–1级起，躲藏暗影与无声移动获得+10%加值，之后每提升1级再额外+5%。
–1级起，死亡豁免获得+1加值，之后每提升10级再+1。
–可随意使用「分析」能力。

分析：使用该能力时，使用者会仔细观察目标，辨识其优劣，显示目标的生命骰、零级命中值、豁免检定、魔法抗性、伤害抗性，以及对毒素与背刺的易伤程度。本能力可无限制使用。

–1级起，每日可使用一次「武器淬毒」能力，之后每提升6级额外获得一次使用次数。

武器淬毒：刺客可为<PRO_HISHER>武器涂抹起效缓慢但药性猛烈的剧毒，持续8小时。该毒素会立即造成伤害并降低目标的体质，之后每回合持续生效，至少持续4回合。4回合过后，目标必须进行一次死亡豁免，否则将再中毒4回合。因此只要目标未能成功豁免，毒素就有可能无限期持续。目标不会因毒素造成的体质流失而死亡。
  1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
  6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
  11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
  16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
  21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。
  
–获得「蓄势待发」与「强化背刺」被动效果。

蓄势待发：刺客每处于隐形状态一回合，<PRO_HESHE>的命中与伤害便获得+1加值，1级时上限为+2。该加值在5级及之后每5级再+1。此外，若刺客保持隐形状态满10回合，<PRO_HISHER>的下一次攻击将必定暴击。脱离潜行状态后，所有堆叠的加值将立即清空。

强化背刺：刺客是潜行攻击的大师，潜行时可从任意方向发动背刺，并以背刺重创<PRO_HISHER>目标，附带以下效果之一。豁免惩罚每提升6级减少1点。
  麻痹：目标需进行+2难度的死亡豁免，否则麻痹2回合。
  断筋：目标需进行死亡豁免，否则移动速度与敏捷减半，持续8回合。
  流血：目标需进行+2难度的死亡豁免，否则每回合受到1d4+1点穿刺伤害，持续2回合，之后每6级增加1回合。
  割喉：目标需进行死亡豁免，否则沉默20回合。
  致命（17级及以上）：目标需进行+4难度的死亡豁免，否则即刻被斩杀。若目标免疫死亡效果，则改为造成最大生命值20%的伤害。

–5级起，获得「隐刃」被动效果。

隐刃：刺客击杀目标时，<PRO_HESHE>将短暂进入隐形状态，并以双倍移动速度移动1回合。该效果每5回合最多触发一次，之后每提升5级冷却时间减少1回合（30级时无冷却）。

–10级起，获得「暗影披风」被动效果。

暗影披风：刺客对潜行的掌控炉火纯青，躲藏或隐形时，无论魔法还是凡俗手段都完全无法探测与锁定。即便是通常能看破隐形的生物，也无法察觉刺客的存在。

职业限制：
–魅力属性受-2惩罚。
–初始声望受-2惩罚。
–无法设置陷阱。
–只能为非善良阵营。
–每次升级只能获得10点的技能点数。~

// change backstab

ACTION_FOR_EACH file IN backstab crippstr sneakatt BEGIN

  ACTION_IF FILE_EXISTS_IN_GAME ~%file%.2da~ THEN BEGIN

    COPY_EXISTING ~%file%.2da~ ~override~
      COUNT_2DA_COLS col_num
      COUNT_2DA_ROWS (col_num - 1) row_num
      READ_2DA_ENTRY 0 (col_num - 2) (col_num - 1) level    // read last enry of top line as level
      READ_2DA_ENTRY 0 0 (col_num - 1) val                  // weidu seems to freak out with a top line w/ one less entry
      SET_2DA_ENTRY  0 0 (col_num - 1) ~CD_DELETE_ME %val%~ // temp
      FOR (index = level ; index < 50 ; ++index) BEGIN
        SET new = index + 1
        FOR (index2 = 1 ; index2 < row_num ; ++index2) BEGIN // extend all other rows with previous column's value
          READ_2DA_ENTRY index2 (col_num - 1) (col_num) val
          SET_2DA_ENTRY  index2 (col_num - 1) (col_num) ~%val% %val%~
        END
        SET_2DA_ENTRY 0 (col_num - 1) (col_num) ~%index% %new%~ // extend level row
        SET col_num += 1
      END
      REPLACE_TEXTUALLY ~CD_DELETE_ME~ ~~
      PRETTY_PRINT_2DA
      BUT_ONLY

  END

END

// backstab

COPY_EXISTING ~BACKSTAB.2da~ ~override~
  REPLACE_EVALUATE ~ASSASIN \([- %TAB%0-9]+\)~ BEGIN
    SPRINT data ~%MATCH1%~
  END ~ASSASIN 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7~

COPY_EXISTING ~sneakatt.2da~ ~override~
  REPLACE_EVALUATE ~ASSASIN \([- %TAB%0-9]+\)~ BEGIN
    SPRINT data ~%MATCH1%~
  END ~ASSASIN 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23 24 24 25 25~

COPY_EXISTING ~crippstr.2da~ ~override~
  REPLACE_EVALUATE ~ASSASIN \([- %TAB%0-9]+\)~ BEGIN
    SPRINT data ~%MATCH1%~
  END ~ASSASIN 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9 10 10 11 11 12 12 13 13 14 14 15 15 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23 24 24 25 25~

ACTION_IF FILE_EXISTS_IN_GAME ~clabth02.2da~ THEN BEGIN
COPY ~%MOD_FOLDER%/Thief/Assassin/2da/clabth02.2da~ ~override~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/Thief/Assassin/scripts/reputation.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/Thief/Assassin/scripts/reputation.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/Thief/Assassin/scripts/reputation.baf~
END

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0ashla1.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~易伤~ /* Vulnerable */)
  END
SAY NAME1 ~破绽暴露~ /* Expose Weakness */
SAY NAME2 ~破绽暴露~ /* Expose Weakness */
SAY UNIDENTIFIED_DESC ~破绽暴露
在刺客眼中，没有无懈可击的敌人。使用本能力后，刺客可标记目标为易伤状态，使其护甲等级降低10点，物理抗性（若有）归零，持续3回合。此外，若目标免疫背刺，将永久失去该免疫。本能力可多次习得，但刺客同一时间只能标记一个目标。~ /* Expose Weakness
To an assassin, no enemy is without a weak point. Using this ability, the assassin may mark a target as vulnerable, reducing their Armor Class by 10 points and setting their physical resistance (if any) to zero for three rounds. Additionally, if the target is immune to backstabs, they lose their immunity permanently. This ability can be taken multiple times, but an assassin can only mark a single target at any given time. */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0ashla2.spl~ ~override~
SAY NAME1 ~刺客之刃~ /* Assassin's Blade */
SAY NAME2 ~刺客之刃~ /* Assassin's Blade */
SAY UNIDENTIFIED_DESC ~刺客之刃
大师级刺客的利刃，必须磨砺至最为锋利的刃口。该天生能力使刺客的近战武器暴击几率永久提升10%，<PRO_HISHER>的背刺倍率+1。

前置需求：破绽暴露~ /* Assassin's Blade
A master assassin's blade must be honed to the sharpest edge. This innate ability permanently increases the assassin's critical hit chance with melee weapons by 10% and <PRO_HISHER> backstab modifier by 1.

Requires: Expose Weakness */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0ashla3.spl~ ~override~
SAY NAME1 ~夺命攻击~ /* Death Attack */
SAY NAME2 ~夺命攻击~ /* Death Attack */
SAY UNIDENTIFIED_DESC ~夺命攻击
高阶刺客对敌人要害部位了如指掌，<PRO_HIMHER>每日可发动一次致命打击。使用本能力后，刺客5回合内的下一次攻击将必定暴击，目标若未通过-4难度的死亡豁免则即刻死亡。

前置需求：刺客之刃~ /* Death Attack
A high-level assassin's intimate knowledge of vital spots on opponents allows <PRO_HIMHER> to, once per day, strike a lethal blow against a target. With this ability, the assassin's next attack within five rounds becomes a guaranteed critical hit and kills the target instantly on a failed save vs. death at -4.

Requires: Assassin's Blade */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asin1.spl~ ~override~
SAY NAME1 ~强化背刺~ /* Enhanced Backstab */
SAY NAME2 ~强化背刺~ /* Enhanced Backstab */
SAY UNIDENTIFIED_DESC ~强化背刺
刺客能以背刺重创<PRO_HISHER>目标，附带以下效果之一。豁免惩罚每提升6级减少1点。

麻痹：目标需进行+2难度的死亡豁免，否则麻痹2回合。
断筋：目标需进行死亡豁免，否则移动速度与敏捷减半，持续8回合。
流血：目标需进行+2难度的死亡豁免，否则每回合受到1d4+1点穿刺伤害，持续2回合，之后每6级增加1回合。
割喉：目标需进行死亡豁免，否则沉默20回合。
致命（17级及以上）：目标需进行+4难度的死亡豁免，否则即刻被斩杀。若目标免疫死亡效果，则改为造成最大生命值20%的伤害。~ /* Enhanced Backstab
The assassin is capable of crippling <PRO_HISHER> victim with <PRO_HISHER> backstabs, inflicting one of the following effects. Save modifiers decrease by one for every six levels of the assassin.

Paralysis: Target must save vs. death at +2 or become paralyzed for 2 rounds.
Hamstring: Target must save vs. death or have their movement rate and Dexterity halved for 8 rounds.
Bleeding: Target must save vs. death at +2 or suffer 1d4+1 piercing damage every round for 2 rounds + 1 round/6 levels.
Cutthroat: Target must save vs. death or be silenced for 20 rounds.
Lethality (Level 17+): Target must save vs. death at +4 or be slain instantly. */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0as#01.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~分析：暴击加成~)
  END

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0as#i4.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~获得被动能力：隐刃~)
  END

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0as#i5.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~获得被动能力：暗影披风~)
  END
  
INCLUDE ~%MOD_FOLDER%/effects/poison_weapon.tpa~

ACTION_IF FILE_EXISTS_IN_GAME ~C0TR#30A.spl~ THEN BEGIN
COPY_EXISTING ~C0TR#30A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER STR_VAR icon = C0ASIN8B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = c0as#p1 END
SAY NAME1 ~模仿：武器淬毒~
END

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asin2.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = c0asic01
      END
SAY NAME1 ~背刺：麻痹~ /* Backstab: Paralysis */
SAY NAME2 ~背刺：麻痹~ /* Backstab: Paralysis */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asin3.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = c0asic02
      END
SAY NAME1 ~背刺：断筋~ /* Backstab: Hamstring */
SAY NAME2 ~背刺：断筋~ /* Backstab: Hamstring */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asin4.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = c0asic03
      END
SAY NAME1 ~背刺：流血~ /* Backstab: Bleeding */
SAY NAME2 ~背刺：流血~ /* Backstab: Bleeding */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asin5.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = c0asic04
      END
SAY NAME1 ~背刺：割喉~ /* Backstab: Cutthroat */
SAY NAME2 ~背刺：割喉~ /* Backstab: Cutthroat */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asin6.spl~ ~override~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = c0asic05
      END
SAY NAME1 ~背刺：致命~ /* Backstab: Lethality */
SAY NAME2 ~背刺：致命~ /* Backstab: Lethality */

COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0assp2.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~断筋~ /* Hamstrung */)
  END
COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0assp3.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~流血~ /* Bleeding */)
  END
COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0assp4.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~沉默~ /* Silenced */)
  END
  
COPY ~%MOD_FOLDER%/Thief/Assassin/spells/c0asinv2.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 139 // display string
	  parameter1 = RESOLVE_STR_REF (~隐刃就绪~ /* Hidden Blade Ready */)
  END