
COPY ~%MOD_FOLDER%/Druid/Avenger/2DAs~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Druid/Avenger/SPELLS~ ~OVERRIDE~

COPY_EXISTING ~CLABDR01.2DA~ ~OVERRIDE/CLABDR04.2DA~
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0SS-S END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0D4_0 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0D4_1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0D4_2 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0D4_3 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0D4_4 END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0D4_5A END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = GA_SPCL632 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = GA_SPCL633 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = GA_SPCL634 END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = AP_C0D4_6A END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = AP_C0D4_1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = AP_C0D4_2 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = AP_C0D4_3 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = AP_C0D4_4 END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0D4_7A END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0D4_1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0D4_2 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0D4_3 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0D4_4 END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19 STR_VAR f_Entry = GA_SPCL632 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19 STR_VAR f_Entry = GA_SPCL633 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19 STR_VAR f_Entry = GA_SPCL634 END

  PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~复仇者：德鲁伊教团内的特殊分支成员，这类德鲁伊献身于讨伐亵渎自然的恶徒。复仇者拥有普通德鲁伊没有的力量——这些额外能力得自繁复的仪式，整个过程会极大损耗身体。

职业优势：
–智慧属性+1。KIT_ADV_1
–自然复苏：复仇者处于树肤术、石肤术或铁皮术效果下时，每回合回复最大生命值的12%。
–3级：可从三项自然誓约中选择一项，每项提供永久加成与代价。每项誓约只能选择一次。

自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷。
   
自然之秘誓约：复仇者可使用部分奥术法术，且施法速度+1。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量。
   
自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质。
–7级：除正常变形能力外，还可变形为剑蛛、幼翼龙、火蜥蜴。
–8级：自然复苏的每回合回复量提升至最大生命值的18%。
–9级：可再选择一项自然誓约。
–14级：自然复苏的每回合回复量提升至最大生命值的24%。
–15级：可再选择一项自然誓约。
–19级：额外获得一次变形术使用次数。

职业限制：
–不得穿戴比皮甲更重的护甲。
–选择任何自然誓约后，复仇者永久失去从多数来源获得直接治疗的能力，但伤害转化治疗、再生、自然复苏等效果除外。~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_ADV_1~ ~
–伪装：复仇者在户外时，阴影躲藏与无声行动获得25%加值。
–可使用阴影躲藏。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_ADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~BEAST_FRIEND~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~
	
COPY_EXISTING ~abclsmod.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BEAST_FRIEND~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 5 cols %-2%
	  END
	END

// STONESKINS
APPEND ~splprot.2da~ ~C0_STONESKIN_GT 88 -1 3~ UNLESS ~C0_STONESKIN_GT~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_STONESKIN_GT~ BEGIN
	    SET C0_STONESKIN_GT = %row%
	  END
	END
	
// Resistances

ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY_SPECIFIC	BEGIN
	~CRUSH~		=>	22
	~ACID~		=>	17
	~COLD~		=>	15
	~ELEC~		=>	16
	~FIRE~		=>	14
	~PIERC~		=>	23
	~POISN~		=>	74
	~MAGIC~		=>	73
	~MSSL~		=>	24
	~SLASH~		=>	21
	~MFIRE~		=>	19
	~MCOLD~		=>	20
	~MRES~		=>	18
END
ACTION_PHP_EACH	DMG_ARRAY_SPECIFIC AS one => two	BEGIN
APPEND ~splprot.2da~ ~C0_%one%_EQUALS %two% -1 1~ UNLESS ~C0_%one%_EQUALS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_%one%_EQUALS~ BEGIN
	    SET "C0_%one%_EQUALS" = %row%
	  END
	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	DMG_ARRAY_GT	BEGIN
	~CRUSH~		=>	22
	~ACID~		=>	17
	~COLD~		=>	15
	~ELEC~		=>	16
	~FIRE~		=>	14
	~PIERC~		=>	23
	~POISN~		=>	74
	~MAGIC~		=>	73
	~MSSL~		=>	24
	~SLASH~		=>	21
	~MFIRE~		=>	19
	~MCOLD~		=>	20
	~MRES~		=>	18
END
ACTION_PHP_EACH	DMG_ARRAY_GT AS one => two	BEGIN
APPEND ~splprot.2da~ ~C0_%one%_GT %two% -1 3~ UNLESS ~C0_%one%_GT~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_%one%_GT~ BEGIN
	    SET "C0_%one%_GT" = %row%
	  END
	END
END

COPY_EXISTING ~splprot.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW rows cols
    FOR (row = 1; row < rows; ++row) BEGIN
      READ_2DA_ENTRY_FORMER rows row 0 ~stat~
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_CRUSH_EQUALS~ BEGIN 
        SET C0_CRUSH_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_ACID_EQUALS~ BEGIN 
        SET C0_ACID_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_COLD_EQUALS~ BEGIN 
        SET C0_COLD_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_ELEC_EQUALS~ BEGIN 
        SET C0_ELEC_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_FIRE_EQUALS~ BEGIN 
        SET C0_FIRE_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PIERC_EQUALS~ BEGIN 
        SET C0_PIERC_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_POISN_EQUALS~ BEGIN 
        SET C0_POISN_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MAGIC_EQUALS~ BEGIN 
        SET C0_MAGIC_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MSSL_EQUALS~ BEGIN 
        SET C0_MSSL_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_SLASH_EQUALS~ BEGIN 
        SET C0_SLASH_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MFIRE_EQUALS~ BEGIN 
        SET C0_MFIRE_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MCOLD_EQUALS~ BEGIN 
        SET C0_MCOLD_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MRES_EQUALS~ BEGIN 
        SET C0_MRES_EQUALS = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_CRUSH_GT~ BEGIN 
        SET C0_CRUSH_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_ACID_GT~ BEGIN 
        SET C0_ACID_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_COLD_GT~ BEGIN 
        SET C0_COLD_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_ELEC_GT~ BEGIN 
        SET C0_ELEC_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_FIRE_GT~ BEGIN 
        SET C0_FIRE_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_PIERC_GT~ BEGIN 
        SET C0_PIERC_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_POISN_GT~ BEGIN 
        SET C0_POISN_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MAGIC_GT~ BEGIN 
        SET C0_MAGIC_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MSSL_GT~ BEGIN 
        SET C0_MSSL_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_SLASH_GT~ BEGIN 
        SET C0_SLASH_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MFIRE_GT~ BEGIN 
        SET C0_MFIRE_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MCOLD_GT~ BEGIN 
        SET C0_MCOLD_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      // 
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_MRES_GT~ BEGIN 
        SET C0_MRES_GT = %row%
      PRETTY_PRINT_2DA
      // 
      END 
      
      
    END
// STONESKINS
APPEND ~splprot.2da~ ~C0_CRUSH_GT 88 -1 3~ UNLESS ~C0_STONESKIN_GT~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_STONESKIN_GT~ BEGIN
	    SET C0_STONESKIN_GT = %row%
	  END
	END
	
COPY_EXISTING ~abclasrq.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BEAST_FRIEND~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 5
		SET_2DA_ENTRY (%patch_row%) 2 cols 5
		SET_2DA_ENTRY (%patch_row%) 3 cols 5
    PRETTY_PRINT_2DA
	  END
	END

COPY_EXISTING ~abclsmod.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BEAST_FRIEND~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 0
		SET_2DA_ENTRY (%patch_row%) 3 cols 0
		SET_2DA_ENTRY (%patch_row%) 5 cols 1
    PRETTY_PRINT_2DA
	  END
	END

// CHROMATIC ORB
COPY_EXISTING ~SPWI118.SPL~ ~OVERRIDE/C0D4_11.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2
// SPOOK
COPY_EXISTING ~SPWI125.SPL~ ~OVERRIDE/C0D4_12.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2
// HORROR
COPY_EXISTING ~SPWI205.SPL~ ~OVERRIDE/C0D4_21.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2
// INVISIBILITY
COPY_EXISTING ~SPWI206.SPL~ ~OVERRIDE/C0D4_22.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2
// SLOW
COPY_EXISTING ~SPWI312.SPL~ ~OVERRIDE/C0D4_31.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2
// VAMPIRIC TOUCH
COPY_EXISTING ~SPWI314.SPL~ ~OVERRIDE/C0D4_32.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2
// IMPROVED INVISIBILITY
COPY_EXISTING ~SPWI405.SPL~ ~OVERRIDE/C0D4_41.SPL~
WRITE_SHORT 0X34 4
WRITE_SHORT 0X1C 2
// POLYMORPH SELF
COPY_EXISTING ~SPWI416.SPL~ ~OVERRIDE/C0D4_42.SPL~
WRITE_SHORT 0X34 4
WRITE_SHORT 0X1C 2
// CHAOS
COPY_EXISTING ~SPWI508.SPL~ ~OVERRIDE/C0D4_51.SPL~
WRITE_SHORT 0X34 5
WRITE_SHORT 0X1C 2
// LOWER RESISTANCE
COPY_EXISTING ~SPWI514.SPL~ ~OVERRIDE/C0D4_52.SPL~
WRITE_SHORT 0X34 5
WRITE_SHORT 0X1C 2
// FLESH TO STONE
COPY_EXISTING ~SPWI604.SPL~ ~OVERRIDE/C0D4_61.SPL~
WRITE_SHORT 0X34 6
WRITE_SHORT 0X1C 2
// WYVERN CALL
COPY_EXISTING ~SPWI619.SPL~ ~OVERRIDE/C0D4_62.SPL~
WRITE_SHORT 0X34 6
WRITE_SHORT 0X1C 2
// SPHERE OF CHAOS
COPY_EXISTING ~SPWI711.SPL~ ~OVERRIDE/C0D4_71.SPL~
WRITE_SHORT 0X34 7
WRITE_SHORT 0X1C 2
// MASS INVISIBILITY
COPY_EXISTING ~SPWI721.SPL~ ~OVERRIDE/C0D4_72.SPL~
WRITE_SHORT 0X34 7
WRITE_SHORT 0X1C 2

COPY_EXISTING ~C0D4_0A.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter2 = 0 parameter2 = C0_STONESKIN_GT END

ACTION_FOR_EACH healing_spell IN dw#fpplo SPIN101 SPIN200 SPIN958 SPPR103 SPPR217 SPPR315 SPPR317 SPPR401 SPPR502 SPPR514 BHAAL1A DEVAHEAL SENSPIHE SPIN679 SPIN699 SPIN711 SPPR607 SPCL211 SPCL815 SPIN200 C0APOT01 C0ARUNE8 C0TRBS1 C0TRBS3 C0TRBS4 C0TRBS5 FINP101 POTN08 POTN55 POTN52 BRAC20 BEGIN
COPY_EXISTING ~C0D4_8.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 324 target = 2 timing = 9 STR_VAR resource = EVAL ~%healing_spell%~ END
END

COPY_EXISTING ~C0D4_A61.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~自然之丰收：生命值与抗性已吸取~) END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_CRUSH_GT STR_VAR resource = C0D4_5_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ACID_GT  STR_VAR resource = C0D4_5_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_COLD_GT  STR_VAR resource = C0D4_5_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ELEC_GT  STR_VAR resource = C0D4_5_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_FIRE_GT  STR_VAR resource = C0D4_5_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_PIERC_GT STR_VAR resource = C0D4_5_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MAGIC_GT STR_VAR resource = C0D4_5_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MSSL_GT  STR_VAR resource = C0D4_5_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_SLASH_GT STR_VAR resource = C0D4_5_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MFIRE_GT STR_VAR resource = C0D4_5_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MCOLD_GT STR_VAR resource = C0D4_5_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MRES_GT  STR_VAR resource = C0D4_5_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_CRUSH_EQUALS STR_VAR resource = C0D4_4_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ACID_EQUALS  STR_VAR resource = C0D4_4_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_COLD_EQUALS  STR_VAR resource = C0D4_4_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ELEC_EQUALS  STR_VAR resource = C0D4_4_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_FIRE_EQUALS  STR_VAR resource = C0D4_4_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_PIERC_EQUALS STR_VAR resource = C0D4_4_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MAGIC_EQUALS STR_VAR resource = C0D4_4_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MSSL_EQUALS  STR_VAR resource = C0D4_4_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_SLASH_EQUALS STR_VAR resource = C0D4_4_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MFIRE_EQUALS STR_VAR resource = C0D4_4_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MCOLD_EQUALS STR_VAR resource = C0D4_4_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MRES_EQUALS  STR_VAR resource = C0D4_4_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_CRUSH_EQUALS STR_VAR resource = C0D4_3_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_ACID_EQUALS  STR_VAR resource = C0D4_3_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_COLD_EQUALS  STR_VAR resource = C0D4_3_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_ELEC_EQUALS  STR_VAR resource = C0D4_3_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_FIRE_EQUALS  STR_VAR resource = C0D4_3_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_PIERC_EQUALS STR_VAR resource = C0D4_3_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MAGIC_EQUALS STR_VAR resource = C0D4_3_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MSSL_EQUALS  STR_VAR resource = C0D4_3_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_SLASH_EQUALS STR_VAR resource = C0D4_3_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MFIRE_EQUALS STR_VAR resource = C0D4_3_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MCOLD_EQUALS STR_VAR resource = C0D4_3_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MRES_EQUALS  STR_VAR resource = C0D4_3_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_CRUSH_EQUALS STR_VAR resource = C0D4_2_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_ACID_EQUALS  STR_VAR resource = C0D4_2_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_COLD_EQUALS  STR_VAR resource = C0D4_2_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_ELEC_EQUALS  STR_VAR resource = C0D4_2_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_FIRE_EQUALS  STR_VAR resource = C0D4_2_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_PIERC_EQUALS STR_VAR resource = C0D4_2_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MAGIC_EQUALS STR_VAR resource = C0D4_2_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MSSL_EQUALS  STR_VAR resource = C0D4_2_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_SLASH_EQUALS STR_VAR resource = C0D4_2_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MFIRE_EQUALS STR_VAR resource = C0D4_2_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MCOLD_EQUALS STR_VAR resource = C0D4_2_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MRES_EQUALS  STR_VAR resource = C0D4_2_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_CRUSH_EQUALS STR_VAR resource = C0D4_1_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_ACID_EQUALS  STR_VAR resource = C0D4_1_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_COLD_EQUALS  STR_VAR resource = C0D4_1_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_ELEC_EQUALS  STR_VAR resource = C0D4_1_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_FIRE_EQUALS  STR_VAR resource = C0D4_1_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_PIERC_EQUALS STR_VAR resource = C0D4_1_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MAGIC_EQUALS STR_VAR resource = C0D4_1_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MSSL_EQUALS  STR_VAR resource = C0D4_1_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_SLASH_EQUALS STR_VAR resource = C0D4_1_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MFIRE_EQUALS STR_VAR resource = C0D4_1_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MCOLD_EQUALS STR_VAR resource = C0D4_1_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MRES_EQUALS  STR_VAR resource = C0D4_1_M END
COPY_EXISTING ~C0D4_A62.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~自然之丰收：生命值与抗性已吸取~) END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_CRUSH_GT savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ACID_GT  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_COLD_GT  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ELEC_GT  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_FIRE_GT  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_PIERC_GT savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MAGIC_GT savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MSSL_GT  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_SLASH_GT savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MFIRE_GT savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MCOLD_GT savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MRES_GT  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_5_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_4_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_3_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_2_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 3) savetype = 1 STR_VAR resource = C0D4_1_M END
COPY_EXISTING ~C0D4_A63.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~自然之丰收：生命值与抗性已吸取~) END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_CRUSH_GT savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ACID_GT  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_COLD_GT  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ELEC_GT  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_FIRE_GT  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_PIERC_GT savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MAGIC_GT savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MSSL_GT  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_SLASH_GT savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MFIRE_GT savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MCOLD_GT savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MRES_GT  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_5_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 4 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_4_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 3 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_3_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 2 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_2_M END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_CRUSH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_A END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_ACID_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_B END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_COLD_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_C END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_ELEC_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_D END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_FIRE_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_E END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_PIERC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_F END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MAGIC_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_H END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MSSL_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_I END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_SLASH_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_J END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MFIRE_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_K END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MCOLD_EQUALS savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_L END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 2 timing = 1 parameter1 = 1 parameter2 = C0_MRES_EQUALS  savebonus = (0 - 1) savetype = 1 STR_VAR resource = C0D4_1_M END

COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_B.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 27 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_C.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 28 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_D.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 29 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_E.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 30 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_F.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 88 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_H.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 31 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_I.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 89 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_J.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 86 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_K.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 84 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_L.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 85 END
COPY_EXISTING ~C0D4_5_A.SPL~ ~OVERRIDE/C0D4_5_M.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 166 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_B.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 27 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_C.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 28 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_D.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 29 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_E.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 30 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_F.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 88 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_H.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 31 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_I.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 89 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_J.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 86 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_K.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 84 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_L.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 85 END
COPY_EXISTING ~C0D4_4_A.SPL~ ~OVERRIDE/C0D4_4_M.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 166 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_B.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 27 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_C.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 28 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_D.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 29 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_E.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 30 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_F.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 88 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_H.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 31 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_I.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 89 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_J.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 86 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_K.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 84 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_L.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 85 END
COPY_EXISTING ~C0D4_3_A.SPL~ ~OVERRIDE/C0D4_3_M.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 166 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_B.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 27 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_C.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 28 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_D.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 29 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_E.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 30 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_F.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 88 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_H.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 31 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_I.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 89 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_J.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 86 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_K.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 84 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_L.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 85 END
COPY_EXISTING ~C0D4_2_A.SPL~ ~OVERRIDE/C0D4_2_M.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 166 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_B.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 27 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_C.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 28 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_D.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 29 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_E.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 30 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_F.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 88 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_H.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 31 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_I.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 89 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_J.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 86 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_K.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 84 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_L.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 85 END
COPY_EXISTING ~C0D4_1_A.SPL~ ~OVERRIDE/C0D4_1_M.SPL~
LPF ALTER_EFFECT INT_VAR opcode = 166 END

COPY_EXISTING ~C0D4_5.SPL~ ~OVERRIDE~
SAY NAME1 ~自然誓约 I~
SAY UNIDENTIFIED_DESC ~自然誓约
复仇者可从三项自然誓约中选择一项，每项均提供永久加成与相应代价。每项誓约仅可选择一次。

自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷属性。
   
自然之秘誓约：复仇者可使用部分奥术法术，且施法速度获得+1加值。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量属性。
   
自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质属性。~

COPY_EXISTING ~C0D4_6.SPL~ ~OVERRIDE~
SAY NAME1 ~自然誓约 II~
SAY UNIDENTIFIED_DESC ~自然誓约
复仇者可从三项自然誓约中选择一项，每项均提供永久加成与相应代价。每项誓约仅可选择一次。

自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷属性。
   
自然之秘誓约：复仇者可使用部分奥术法术，且施法速度获得+1加值。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量属性。
   
自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质属性。~

COPY_EXISTING ~C0D4_7.SPL~ ~OVERRIDE~
SAY NAME1 ~自然誓约 III~
SAY UNIDENTIFIED_DESC ~自然誓约
复仇者可从三项自然誓约中选择一项，每项均提供永久加成与相应代价。每项誓约仅可选择一次。

自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷属性。
   
自然之秘誓约：复仇者可使用部分奥术法术，且施法速度获得+1加值。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量属性。
   
自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质属性。~

COPY_EXISTING ~C0D4_A4A.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之怒誓约~
SAY UNIDENTIFIED_DESC ~自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷属性。~

COPY_EXISTING ~C0D4_A4B.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之怒誓约~
SAY UNIDENTIFIED_DESC ~自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷属性。~

COPY_EXISTING ~C0D4_A4C.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之怒誓约~
SAY UNIDENTIFIED_DESC ~自然之怒誓约：复仇者的攻击对不死生物、异界生物、畸变体等非自然生物额外造成1点无视护甲穿刺伤害。
   9级时伤害加成提升至2点，15级时提升至3点。
   选择此誓约后，复仇者失去4点敏捷属性。~

COPY_EXISTING ~C0D4_A5A.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之秘誓约~
SAY UNIDENTIFIED_DESC ~自然之秘誓约：复仇者可使用部分奥术法术，且施法速度获得+1加值。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量属性。~

COPY_EXISTING ~C0D4_A5B.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之秘誓约~
SAY UNIDENTIFIED_DESC ~自然之秘誓约：复仇者可使用部分奥术法术，且施法速度获得+1加值。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量属性。~

COPY_EXISTING ~C0D4_A5C.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之秘誓约~
SAY UNIDENTIFIED_DESC ~自然之秘誓约：复仇者可使用部分奥术法术，且施法速度获得+1加值。
   1级：七彩飞弹、惊吓术
   2级：隐形术、恐惧术
   3级：迟缓术、吸血之触
   4级：高等隐形术、变形术（自身）
   5级：混沌术、降低抗力
   6级：石化术、翼龙召唤
   7级：群体隐形术、混沌法球
   9级时施法速度加成提升至+2，15级时提升至+3。
   选择此誓约后，复仇者失去4点力量属性。~

COPY_EXISTING ~C0D4_A6A.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之丰收誓约~
SAY UNIDENTIFIED_DESC ~自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质属性。~

COPY_EXISTING ~C0D4_A6B.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之丰收誓约~
SAY UNIDENTIFIED_DESC ~自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质属性。~

COPY_EXISTING ~C0D4_A6C.SPL~ ~OVERRIDE~
SAY NAME1 ~自然之丰收誓约~
SAY UNIDENTIFIED_DESC ~自然之丰收誓约：复仇者获得2倍背刺倍率。此外，复仇者的背刺会纠缠目标最多3回合。每回合结束时，目标损失当前生命值的5%，其抗性（包括魔法抗性）会转移给复仇者，持续1回合。目标在纠缠的第1回合无法进行豁免检定，后续两回合可分别以-3和-1难度的法术豁免挣脱并抵抗吸取效果。
   9级时复仇者的背刺倍率提升至3倍，15级时提升至4倍。
   选择此誓约后，复仇者失去4点体质属性。~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~C0D4_0.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 272 target = 1 parameter1 = 1 parameter2 = 3 timing = 9 STR_VAR resource = C0D4_E2 END

COPY ~%MOD_FOLDER%/Druid/Avenger/Spells/camouflage~ ~OVERRIDE~

APPEND ~splprot.2da~ ~C0_OUTDOORS_CHECK%TAB%0x106%TAB%1%TAB%8~ UNLESS ~C0_OUTDOORS_CHECK~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_OUTDOORS_CHECK~ BEGIN
	    SET C0_OUTDOORS_CHECK = %row%
	  END
	END
	
APPEND ~splprot.2da~ ~C0_NOT_OUTDOORS_CHECK%TAB%0x106%TAB%1%TAB%9~ UNLESS ~C0_NOT_OUTDOORS_CHECK~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_NOT_OUTDOORS_CHECK~ BEGIN
	    SET C0_NOT_OUTDOORS_CHECK = %row%
	  END
	END
	
COPY_EXISTING ~C0D4_E2a.spl~ ~override~
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0_OUTDOORS_CHECK STR_VAR match_resource = C0D4_E2b END
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0_NOT_OUTDOORS_CHECK STR_VAR match_resource = C0D4_E2c END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABDR04.2DA~ BEGIN
COPY_EXISTING ~CLABDR04.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0D4_E1 END // STEALTH
  PRETTY_PRINT_2DA
BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////


COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "BEAST_FRIEND" = 0) BEGIN
      READ_2DA_ENTRY 4 col col_count val
      SET_2DA_ENTRY  4 col col_count 100
      READ_2DA_ENTRY 5 col col_count val
      SET_2DA_ENTRY  5 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF 	("%kit%" STRING_EQUAL_CASE "BEAST_FRIEND") BEGIN
      READ_2DA_ENTRY 4 col col_count val
      SET_2DA_ENTRY  4 col col_count 15
      READ_2DA_ENTRY 5 col col_count val
      SET_2DA_ENTRY  5 col col_count 15
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END

OUTER_SET avenger_ids = IDS_OF_SYMBOL (~kit~ ~BEASTFRIEND~)
  
COPY ~%MOD_FOLDER%/lua/m_c0dru1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%avenger_ids%~~~~~ //"
  END

END
