COPY ~%MOD_FOLDER%/Fighter/Barbarian/bams~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Barbarian/SPELLS~ ~OVERRIDE~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/CLABFI05.2DA~
	// REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	// REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	// REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	// REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL151 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 4 STR_VAR f_Entry = GA_SPCL152 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = AP_SPCL143 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 4 STR_VAR f_Entry = AP_SPCL151 END

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BAR#00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BAR#01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = AP_C0BAR#03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 STR_VAR f_Entry = AP_C0BAR#01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0BAR#01 END

 	PRETTY_PRINT_2DA

INCLUDE ~%MOD_FOLDER%/effects/toughness.tpa~

APPEND ~STATE.IDS~ // STUN, PANIC, BERSERK, CHARM, FEEBLEMIND, CONFUSED
  ~0x8010202f C0_BARB_STATUS~
  UNLESS ~C0_BARB_STATUS~
  
OUTER_SPRINT kit_description ~野蛮人：野蛮人是出色的战士。尽管不像战士那般训练有素、技艺精湛，但野蛮人能主动陷入狂暴状态，成为更强悍、更凶猛的对手。

职业特性：

–不得穿戴比锁子甲更重的护甲。
–任何武器类别的熟练等级不得超过专精级（2点熟练槽）。
–任意战斗风格都可达到专精级（2点熟练槽），双武器风格可分配3点熟练槽。
–移动速度比其他角色快2点。
–免疫背刺。
–钢铁意志：体质每超过9点4点，野蛮人所有豁免检定+1。
–获得「坚韧」被动能力。

坚韧：野蛮人获得5%物理伤害抗性。当野蛮人生命值低于最大生命值50%时，该加成翻倍。

–每日可使用一次「狂暴」能力。1级时获得1次使用次数，之后每提升4级额外获得1次。

狂暴：狂暴状态持续5回合，提供+4力量与体质加成，以及+2法术豁免加值。但野蛮人会受到-2护甲等级惩罚。此外，激活狂暴会恢复野蛮人所有被吸取的等级，并在持续期间免疫后续的等级吸取效果。狂暴结束后，野蛮人会进入疲劳状态，力量、敏捷、护甲等级与移动速度受-2惩罚，持续5回合。在此期间野蛮人无法使用狂暴。
KIT_SKILL_1
–8级：获得「不屈意志」被动能力。

不屈意志：当野蛮人陷入以下任意负面状态：狂暴、魅惑、定身、恐惧、眩晕、睡眠、弱智、困惑时，每回合有20%（每提升1级+2%）的几率挣脱负面效果。

–10级：狂暴的力量与体质加成提升至+6。
–11级：坚韧的基础物理抗性提升至10%。生命值低于最大生命值50%时，野蛮人每3秒回复1点生命值。KIT_SKILL_2
–18级：野蛮人狂暴结束后不再承受疲劳惩罚。
–20级：坚韧的基础物理抗性提升至15%。再生速率提升至每秒1点生命值。
–22级：不死狂怒：野蛮人在狂暴结束后的1回合内不会死亡。
–24级：狂暴的力量与体质加成提升至+8。法术豁免加值提升至+4。
–生命骰：d12~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_SKILL_1~ ~
–5级：可使用「猛力攻击」攻击模式。

猛力攻击：野蛮人牺牲精准度换取更重、更具杀伤力的打击，近战零级命中值降低3点，近战伤害增加3点。野蛮人力量需达到17或以上才能激活此能力。

–6级：可使用「速射」攻击模式。

速射：野蛮人每轮可额外进行一次远程攻击，但命中受-4惩罚。
~
  REPLACE_TEXTUALLY ~KIT_SKILL_2~ ~
–12级：精通速射：速射状态下的命中惩罚降低至-2。
–14级：可使用「精通猛力攻击」，将原能力的加成与惩罚提升至6点。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_SKILL_1~ ~~
  REPLACE_TEXTUALLY ~KIT_SKILL_2~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~BARBARIAN~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~

COPY ~%MOD_FOLDER%/Fighter/Barbarian/spells/c0bar#03.eff~ ~override~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~STATE~ ~C0_BARB_STATUS~)
COPY ~%MOD_FOLDER%/Fighter/Barbarian/spells/c0bar#06.spl~ ~override~
SAY NAME1 ~猛击：激活~
SAY NAME2 ~猛击：激活~
SAY UNIDENTIFIED_DESC ~猛击

野蛮人可选择牺牲精准度换取更强的威力，零级命中值降低4点，但每次命中额外造成4点伤害（仅近战）。20级起，零级命中值与伤害修正提升至8点。~

COPY ~%MOD_FOLDER%/Fighter/Barbarian/spells/c0bar#07.spl~ ~override~
SAY NAME1 ~猛击：关闭~
SAY NAME2 ~猛击：关闭~
SAY UNIDENTIFIED_DESC ~使用本能力可随时关闭猛击。~

COPY ~%MOD_FOLDER%/Fighter/Barbarian/SPELLS/SPCL152.SPL~ ~OVERRIDE~
SAY NAME1 ~野蛮人狂暴~
SAY UNIDENTIFIED_DESC ~野蛮人狂暴
狂暴状态持续5回合，提供+4力量与体质加成，以及+2法术豁免加值。但野蛮人会受到-2护甲等级惩罚。此外，激活狂暴会恢复野蛮人所有被吸取的等级，并在持续期间免疫后续的等级吸取效果。狂暴结束后，野蛮人会进入疲劳状态，力量、敏捷、护甲等级与移动速度受-2惩罚，持续5回合。在此期间野蛮人无法使用狂暴。10级起，力量与体质加成提升至+6；24级起，加成提升至+8。~

COPY ~%MOD_FOLDER%/Fighter/Barbarian/SPELLS/SPCL152a.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT INT_VAR match_opcode = 206 parameter1 = RESOLVE_STR_REF (~需等待当前狂暴效果结束。~) STR_VAR match_resource = spcl152 END
  
COPY ~%MOD_FOLDER%/Fighter/Barbarian/SPELLS/C0BAR#05.SPL~ ~OVERRIDE~
SAY NAME1 ~不屈意志~
