COPY ~%MOD_FOLDER%/Ranger/Beastmaster/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABRN01.2DA~ ~OVERRIDE/CLABRN04.2DA~
	// REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%] ~ ~**** ~ // TOUGHNESS
	// REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%][%0-9%] ~ ~**** ~ // TOUGHNESS
	// REPLACE_TEXTUALLY ~GA_SPCL311~ ~**** ~ // CHARM ANIMAL
	// REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	// REPLACE_TEXTUALLY ~C0RNG00A ~ ~**** ~ // CAMOUFLAGE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BMA00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPCL342 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 2 STR_VAR f_Entry = GA_C0BMA01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 STR_VAR f_Entry = GA_C0BMA02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = GA_C0BMA02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_C0BMA02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = GA_SPRA304 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_SPRA305 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_SPRA306 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = GA_C0BMA03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = GA_C0BMA03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 STR_VAR f_Entry = GA_C0BMA03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = GA_C0BMA03 END

 	PRETTY_PRINT_2DA

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~BEASTMASTER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~万兽王：这类游侠天性浪迹天涯，难以适应文明之地。因此，<PRO_HESHE>与所有自然生灵都有着天生的亲和——从寻常走兽到常人眼中的凶兽，皆是<PRO_HISHER>的挚友与战友。万兽王还能与它们进行有限的心灵感应。

职业优势：
–兽类之友：万兽王对抗动物与魔兽类生物时，护甲等级与豁免检定获得+2加值。此外，视野范围内的友方动物与魔兽类生物，会获得非叠加的+2护甲等级、豁免检定、零级命中值与伤害加成。
–可使用「寻找魔宠」能力，召唤一只伪龙（守序或中立善良）或仙龙（混乱善良）作为伙伴。
–可使用强化版「魅惑动物」。

强化魅惑动物：这一进阶版魅惑动物与原版效果相近，但目标动物需进行-6难度的法术豁免。本能力也可影响安克赫格、双足飞龙、土巨怪等魔兽类生物。在常规2回合效果结束后，动物仍会对万兽王保持友善，并会协助攻击所见敌人，但不受操控。

–6级：每日可使用一次「动物狂怒」能力，9级与12级各额外获得一次使用次数。

动物狂怒：本法术为目标生物注入野性狂怒。目标生物力量变为19，获得+20生命值、+20%移动速度，所有豁免检定+2。效果持续期间目标无法施法；视野内出现敌人时，<PRO_HESHE>会立即手持武器近战攻击。法术生效期间，每回合有5%几率目标陷入狂暴，不分敌我胡乱攻击。

–8级：可将「一级召唤动物」作为1环神术施放。
–9级：兽类之友强化：友方加成提升至+4。
–10级：可将「二级召唤动物」作为2环神术施放。
–12级：可将「三级召唤动物」作为3环神术施放。
–14级：可将「翼龙召唤」作为天生能力，每日使用两次；17级与20级各额外获得一次使用次数。
–15级：兽类守护：友方加成提升至+6。

职业限制：
–仅可使用以下武器类型：斧、匕首、棍棒、长矛、法杖、十字弓、长弓、短弓、飞镖、投石索。
–仅可使用非金属护甲。
–魅力属性受-2惩罚。~
/*
CALL OF THE WILD: The beast master calls upon the creatures of the wild, summoning 1d4 creatures to assist them in battle. The types of creature that can be summoned are dependent on the beast master’s level and the area in which the ability is used.

  5th level+: Dogs, bears, wolves, rats, spiders
  9th level+: Ettercaps, dire bears, dire wolves, giant spiders, ankhegs, myconids, baby wyverns
  13th level+: Wyverns, umber hulks, sword spiders, spore colonies
  18th level+: Basilisks, greater wyverns
*/

// Item restrictions

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x20 ranger //reads the byte containing the fighter usability flag
    PATCH_IF ((ranger BAND 0b00100000) = 0b00000000) BEGIN // if it is usable by fighters
      READ_BYTE    0x2B beastmaster //reads the byte containing monks usability flag
      READ_SHORT    0x1C type //reads the byte containing item type
      PATCH_IF (type = 25) OR (type = 16) OR (type = 29) BEGIN // if it is a crossbow
        WRITE_BYTE    0x2B (beastmaster BAND 0b11111101)  // makes usable by clerics
      END
    END
  END
BUT_ONLY

ACTION_FOR_EACH nonmetalarmors IN ~plat06~ ~plat13~ ~plat18~ ~plat20~ ~ohdarmor~ ~king~ ~swanarm~ ~umhulk~ BEGIN
ACTION_IF FILE_EXISTS_IN_GAME ~%nonmetalarmors%.itm~ THEN BEGIN
COPY_EXISTING ~%nonmetalarmors%.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x20 ranger //reads the byte containing the fighter usability flag
    PATCH_IF ((ranger BAND 0b00100000) = 0b00000000) BEGIN // if it is usable by fighters
      READ_BYTE    0x2B beastmaster //reads the byte containing monks usability flag
        WRITE_BYTE    0x2B (beastmaster BAND 0b11111101)  // makes usable by clerics
      END
    END
BUT_ONLY_IF_IT_CHANGES
  END
  END

// Proficiencies

ACTION_CLEAR_ARRAY weapprof_cols_beastmaster
        
COPY_EXISTING ~weapprof.2da~  ~override~
  COUNT_2DA_COLS col_count
  SET col_check = col_count - 1
  FOR (column = 0; column < col_check; ++column) BEGIN
    READ_2DA_ENTRY 0 column col_check name
    PATCH_IF (("BEASTMASTER" STRING_COMPARE_CASE "%name%" = 0)) BEGIN
      SET column += 1 // row with names has an empty entry for the first column
      DEFINE_ASSOCIATIVE_ARRAY weapprof_cols_beastmaster BEGIN ~%column%~ => ~%column%~ END
    END
  END
  PATCH_PHP_EACH weapprof_cols_beastmaster AS column => foo BEGIN
    FOR (row = 8; row < 32; ++row) BEGIN
      READ_2DA_ENTRY row column col_count stars
      PATCH_IF (stars < 5) BEGIN
        SET_2DA_ENTRY 11 column col_count 2
        SET_2DA_ENTRY 15 column col_count 2
        SET_2DA_ENTRY 18 column col_count 2
      END
    END
  END
  PRETTY_PRINT_2DA
  BUT_ONLY
  

  COPY_EXISTING ~abclsmod.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BEASTMASTER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 6 cols %-2%
	  END
	END

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "BEASTMASTER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "BEASTMASTER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count (val+20)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

COPY_EXISTING ~C0BMA00A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

COPY_EXISTING C0BMA01.SPL OVERRIDE
SAY NAME1 ~强化魅惑动物~
SAY UNIDENTIFIED_DESC ~强化魅惑动物
这一进阶版魅惑动物与原版效果相近，但目标动物需进行-6难度的法术豁免。本能力也可影响安克赫格、双足飞龙、土巨怪等魔兽类生物。在常规2回合效果结束后，动物仍会对万兽王保持友善，并会协助攻击所见敌人，但不受操控。~

ACTION_IF FILE_EXISTS_IN_GAME ~SPPR522.SPL~ BEGIN
COPY_EXISTING ~SPPR522.spl~ ~override/C0BMA02.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI619.SPL~ BEGIN
COPY_EXISTING ~SPWI619.spl~ ~override/C0BMA03.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPPR522.SPL~ BEGIN
COPY ~%MOD_FOLDER%/Ranger/Beastmaster/spells/sppr522~ ~override~
COPY_EXISTING ~SPPR522.spl~ ~override~
SAY NAME1 ~动物狂怒~
SAY UNIDENTIFIED_DESC ~动物狂怒
（附魔系）

等级：5
领域：战斗
范围：触碰
持续时间：15回合
施法时间：8
影响区域：1个生物
豁免检定：无

本法术为目标生物注入野性狂怒。目标生物力量变为19，获得+20生命值、+20%移动速度，所有豁免检定+2。效果持续期间目标无法施法；视野内出现敌人时，<PRO_HESHE>会立即手持武器近战攻击。法术生效期间，每回合有5%几率目标陷入狂暴，不分敌我胡乱攻击。~
END

COPY ~%MOD_FOLDER%/Ranger/Beastmaster/spells/sppr522/sppr522.spl~ ~override/C0BMA02.spl~
LPF ALTER_EFFECT STR_VAR match_resource = SPPR522 resource = C0BMA02 END
LPF ALTER_EFFECT STR_VAR match_resource = SPPR522B resource = C0BMA02A END
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END

COPY ~%MOD_FOLDER%/Ranger/Beastmaster/spells/sppr522/SPPR522B.spl~ ~override/C0BMA02a.spl~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Berserking~) END

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~M_C0RAN1.lua~ THEN BEGIN

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "BEASTMASTER") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "BEASTMASTER") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 20
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 20
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END
END