COPY ~%MOD_FOLDER%/Fighter/Berserker/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/BAMS~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS~ ~OVERRIDE~

// CURRENT HP CHECK
APPEND ~splprot.2da~ ~C0CURHP 0 -1 0~ UNLESS ~C0CURHP 0 -1 0~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0CURHP~ BEGIN
	    SET C0CURHP = %row%
	  END
	END

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/CLABFI02.2DA~
  // REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
  REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
  REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
  REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
  REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
  // REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BER#07 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BER#1X END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BER#2X END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BER#3X END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BER#I1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 STR_VAR f_Entry = GA_C0BER#05 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 4 STR_VAR f_Entry = GA_C0BER#00 END

  PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~狂战士：这类战士深谙自身的兽性本能，战斗中能进入一种极致亢奋的精神状态，让自己比常人更持久、更凶猛、更狂野地战斗。狂战士的天性大多类同野蛮人，但并非一概如此——有时这是受训战士主动做出的选择。无论如何，当战场上的对手目睹狂战士性格中狂野、非人的一面时，都会心神不宁。该职业在矮人之中十分常见，他们称其为「战狂者」。

职业优势：
－免疫恐惧、士气崩溃与非自愿狂暴效果。
－获得「死斗」被动效果。

死斗：狂战士嗜享厮杀的快感，近乎施虐受虐的程度；当大多数战士都会动摇或撤退的生死关头，他们反而越战越勇。这份力量虽强，却是双刃剑——战斗中受伤越重，攻势就越发致命，但防御也随之下降，更容易受到更多伤害。
  生命值>75%：近战零级命中值与伤害+2，护甲等级-2
  生命值>50%：近战零级命中值与伤害+4，护甲等级-4
  生命值>25%：近战零级命中值与伤害+8，护甲等级-6
  
－每日可使用一次「狂怒」能力。1级时获得1次使用次数，之后每提升4级额外获得1次。

狂怒：狂战士仅凭纯粹的意志力引爆自身的狂乱。接下来2回合内，<PRO_HESHE>获得+15点最大生命值，每秒损失1点生命值，且每损失5%生命值，斩击、穿刺与钝击伤害便额外+5%（生命值仅剩1点时伤害+100%）。若狂怒剩余持续时间不足1回合，狂战士的近战攻击会将狂怒持续时间重置为1回合，总持续时间最长可达10回合。狂怒造成的生命值损失不会将狂战士的生命值降至1点以下。狂怒状态下，狂战士无法施法。

－4级起，可随意使用「鲁莽狂暴」能力。

鲁莽狂暴：狂战士故意伤及自身，立刻将<PRO_HISHER>生命值降至最大生命值的70%、45%或20%。若狂战士当前生命值已低于所选数值，本技能无效。

－7级起，死斗状态下狂战士的移动速度获得+2/+4/+8加成。

－10级起，狂战士的恍惚状态让<PRO_HIMHER>更易摆脱负面效果，死斗状态下所有豁免检定获得+2/+4/+8加成。

－14级起，死斗状态下狂战士每回合额外攻击次数获得+0.5/+1/+2加成。

－20级起，死斗状态下，狂战士造成与受到的伤害掷骰获得+1/+3/+5幸运加值。

职业限制：
－使用狂怒后会气喘吁吁5回合，期间护甲等级、命中掷骰与伤害掷骰受-2惩罚。此外，气喘吁吁状态下，狂战士无法使用狂怒，也无法获得死斗的增益。
－无法精通远程武器。KIT_DISADV_1
－仅限非守序阵营。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
－无法使用「武器娴熟」与「速射」。
－16级时不会获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~BERSERKER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~死斗~) STR_VAR bam_file = c0ber#ic RET c0ber#ic = icon END

COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#07.SPL~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#0X.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~气喘吁吁~) END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#00.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 206 parameter1 = RESOLVE_STR_REF (~狂战士正处于狂怒状态。~) STR_VAR match_resource = SPCL321 END
SAY NAME1 ~狂怒~
SAY UNIDENTIFIED_DESC ~狂怒
狂战士仅凭纯粹的意志力引爆自身的狂乱。接下来2回合内，<PRO_HESHE>获得+15点最大生命值，每秒损失1点生命值，且每损失5%生命值，斩击、穿刺与钝击伤害便额外+5%（生命值仅剩1点时伤害+100%）。若狂怒剩余持续时间不足1回合，狂战士的近战攻击会将狂怒持续时间重置为1回合，总持续时间最长可达10回合。狂怒造成的生命值损失不会将狂战士的生命值降至1点以下。狂怒状态下，狂战士无法施法。~

COPY ~%MOD_FOLDER%/SPELLS/C0KTNAME.EFF~ ~OVERRIDE/C0BER#00.EFF~
WRITE_LONG 0x1c RESOLVE_STR_REF (~战狂者~)
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#1x.SPL~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#2x.SPL~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#3x.SPL~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#01.EFF~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#01.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ber#ic END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#02.EFF~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#02.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ber#ic END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#03.EFF~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#03.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ber#ic END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#04.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 318 parameter2 = C0CURHP END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#05.SPL~ ~OVERRIDE~
SAY NAME1 ~鲁莽狂暴~
SAY UNIDENTIFIED_DESC ~鲁莽狂暴
狂战士故意伤及自身，立刻将<PRO_HISHER>生命值降至最大生命值的70%、45%或20%。若狂战士当前生命值已低于所选数值，本技能无效。~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#5A.SPL~ ~OVERRIDE~
SAY NAME1 ~鲁莽狂暴—70%~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~最大生命值降至70%~) END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#5B.SPL~ ~OVERRIDE~
SAY NAME1 ~鲁莽狂暴—45%~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~最大生命值降至45%~) END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#5C.SPL~ ~OVERRIDE~
SAY NAME1 ~鲁莽狂暴—20%~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~最大生命值降至20%~) END

COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#62.EFF~
WRITE_ASCII 0x30 ~C0BER#62~
WRITE_BYTE 0x48 90
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#63.EFF~
WRITE_BYTE 0x48 86
WRITE_ASCII 0x30 ~C0BER#63~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#64.EFF~
WRITE_BYTE 0x48 80
WRITE_ASCII 0x30 ~C0BER#64~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#65.EFF~
WRITE_BYTE 0x48 76
WRITE_ASCII 0x30 ~C0BER#65~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#66.EFF~
WRITE_BYTE 0x48 70
WRITE_ASCII 0x30 ~C0BER#66~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#67.EFF~
WRITE_BYTE 0x48 66
WRITE_ASCII 0x30 ~C0BER#67~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#68.EFF~
WRITE_BYTE 0x48 60
WRITE_ASCII 0x30 ~C0BER#68~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#69.EFF~
WRITE_BYTE 0x48 56
WRITE_ASCII 0x30 ~C0BER#69~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#60.EFF~
WRITE_BYTE 0x48 50
WRITE_ASCII 0x30 ~C0BER#60~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6a.EFF~
WRITE_BYTE 0x48 46
WRITE_ASCII 0x30 ~C0BER#6A~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6b.EFF~
WRITE_BYTE 0x48 40
WRITE_ASCII 0x30 ~C0BER#6B~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6c.EFF~
WRITE_BYTE 0x48 36
WRITE_ASCII 0x30 ~C0BER#6C~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6d.EFF~
WRITE_BYTE 0x48 30
WRITE_ASCII 0x30 ~C0BER#6D~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6e.EFF~
WRITE_BYTE 0x48 26
WRITE_ASCII 0x30 ~C0BER#6E~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6f.EFF~
WRITE_BYTE 0x48 20
WRITE_ASCII 0x30 ~C0BER#6F~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6g.EFF~
WRITE_BYTE 0x48 16
WRITE_ASCII 0x30 ~C0BER#6G~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6h.EFF~
WRITE_BYTE 0x48 10
WRITE_ASCII 0x30 ~C0BER#6H~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6i.EFF~
WRITE_BYTE 0x48 6
WRITE_ASCII 0x30 ~C0BER#6I~
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.EFF~ ~OVERRIDE/C0BER#6j.EFF~
WRITE_BYTE 0x20 19
WRITE_BYTE 0x48 2
WRITE_ASCII 0x30 ~C0BER#6J~

COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#62.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#62 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#63.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#63 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#64.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#64 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#65.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#65 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#66.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#66 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#67.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#67 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#68.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#68 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#69.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#69 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#60.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#60 END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6A.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6A END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6B END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6C END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6D END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6E END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6F END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6G END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6H END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6I END
COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#61.SPL~ ~OVERRIDE/C0BER#6J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = C0BER#6J END

  COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BERSERKER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~C0BER~
	  END
	END
	
  
COPY_EXISTING ~LUFI0.2da~ ~override/LUC0BER.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL907~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0BERS1~ ability = ~AP_C0BER#H1~ num_allowed = 1 END	

COPY ~%MOD_FOLDER%/Fighter/Berserker/SPELLS/C0BER#H1.SPL~ ~OVERRIDE~
SAY NAME1 ~狂怒延绵~
SAY UNIDENTIFIED_DESC ~狂怒延绵
狂战士对狂野战斗风格的精通，让他们能更久地维持狂暴状态，永久将狂怒的最大总持续时间延长至20回合。~