COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/2da~ ~override~
COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/spells~ ~override~

COPY_EXISTING ~CLABRN01.2DA~ ~OVERRIDE/C0TBM.2DA~
	// REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%] ~ ~**** ~ // TOUGHNESS
	// REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%][%0-9%] ~ ~**** ~ // TOUGHNESS
	// REPLACE_TEXTUALLY ~GA_SPCL311~ ~**** ~ // CHARM ANIMAL
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	// REPLACE_TEXTUALLY ~C0RNG00A ~ ~**** ~ // CAMOUFLAGE
	// REPLACE_TEXTUALLY ~C0CL922 ~ ~**** ~ // TRACKING

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0TBMA END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPIN117 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = GA_SPIN117 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = AP_C0TBMB END

 	PRETTY_PRINT_2DA

// Minsc

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 12
	
	visible = 0
	
    mixed         = RESOLVE_STR_REF(~拉西曼狂战士~)
	
    lower         = RESOLVE_STR_REF(~拉西曼狂战士~)
	
    help          = RESOLVE_STR_REF(~拉西曼狂战士：遥远的拉西曼之地有着悠久的狂战士传统。拉西曼的狂战士以当地生物命名分属各个战团，比如冰龙狂战士战团。名如其人，拉西曼狂战士不仅以狂暴之力闻名，更以战技精湛、荣誉感强烈，以及对故土与统治者巫女议会的赤胆忠心著称。新晋狂战士要经历名为「达杰玛」的成年传统：离开故土远行游历，去见识与理解世界。他们往往与一位立誓以命相护的巫女议会成员同行。拉西曼狂战士与塞伊红袍法师是死敌，双方已交战数百年。

职业优势：
–生命骰：d12
–任意近战武器均可修习至宗师级。
–每日可使用一次「狂战士之怒」能力。每提升4级额外获得一次使用次数。

狂战士之怒：拉西曼狂战士进入狂暴状态，持续1回合。狂暴期间，力量获得+2加值，每回合额外攻击一次，免疫魅惑、困惑、恐惧、弱智、定身、等级吸取、迷宫、眩晕与睡眠。但狂暴期间护甲等级受4点惩罚。拉西曼狂战士还会获得15点临时生命值，狂暴结束后扣除，可能导致其陷入昏迷。此外，狂暴结束前，狂战士除移动与攻击外无法进行任何行动，比如施法、使用物品、潜行或交谈。12级时力量加值提升至+4，20级时提升至+6。

效果结束后，拉西曼狂战士会陷入疲劳状态，零级命中值、护甲等级与伤害降低4点，且5回合内无法再次进入狂暴。

–5级：可使用「强力攻击」攻击模式。

强力攻击：狂战士牺牲精准度换取更重、更具杀伤力的打击，近战零级命中值降低3点，近战伤害提升3点。狂战士力量需达到17或以上才能激活此能力。

–8级：获得「不屈意志」。

不屈意志：拉西曼狂战士拥有惊人的意志力。狂战士的法术豁免永久获得+3加值，狂暴期间翻倍。狂暴期间，拉西曼狂战士还免疫灵能效果。

–12级：获得「狂怒不止」。

狂怒不止：拉西曼狂战士狂暴时如同不可阻挡的战争机器，是真正令人畏惧的存在。狂暴期间，狂战士免疫所有阻碍移动的效果与监禁效果。

–14级：可使用「精通强力攻击」，将原能力的加成与惩罚提升至6点。
–16级：获得「不倦狂怒」。

不倦狂怒：拉西曼狂战士不会再陷入疲劳，狂暴结束后也不会受到伤害。

–18级：获得「不死狂乱」。

不死狂乱：拉西曼狂战士的狂怒之强，足以让其暂时抵挡死亡。18级起，拉西曼狂战士进入狂暴后的前2回合内，不会以任何方式死亡。

职业限制：
–仅限非守序阵营。
–每个法术等级的牧师法术少施展1个。
–无法设置陷阱。
–无法精通远程武器。~)
	
    briefdesc     = RESOLVE_STR_REF(~拉西曼狂战士：遥远的拉西曼之地有着悠久的狂战士传统。拉西曼的狂战士以当地生物命名分属各个战团，比如冰龙狂战士战团。名如其人，拉西曼狂战士不仅以狂暴之力闻名，更以战技精湛、荣誉感强烈，以及对故土与统治者巫女议会的赤胆忠心著称。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0TBM~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 2 2 2 3~
	
    abclasrq      = ~13 13 14 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0TBM.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

// Spells

ACTION_IF NOT FILE_EXISTS_IN_GAME ~C0FIG01.SPL~ BEGIN
COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/spells/fighter~ ~override~
DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~强力攻击~) STR_VAR bam_file = C0FIG01I RET C0FIG01I = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~精通强力攻击~) STR_VAR bam_file = C0FIG01J RET C0FIG01J = icon END

COPY ~ArtisansKitpack/Fighter/2da/c0fig01a.2da~ ~OVERRIDE~
COPY ~ArtisansKitpack/Fighter/2da/c0fig01b.2da~ ~OVERRIDE~

COPY_EXISTING ~C0FIG01X.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~强力攻击——力量不足~) END
COPY_EXISTING ~C0FIG01.SPL~ OVERRIDE
SAY NAME1 ~强力攻击~
SAY UNIDENTIFIED_DESC ~强力攻击
狂战士牺牲精准度换取更重、更具杀伤力的打击，近战零级命中值降低3点，近战伤害提升3点。狂战士力量需达到17或以上才能激活此能力。~
	
COPY_EXISTING ~C0FIG01a.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~强力攻击已激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 272 special = C0FIG01I END

COPY_EXISTING ~C0FIG01b.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~精通强力攻击已激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 272 special = C0FIG01J END

COPY_EXISTING ~C0FIG01c.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~强力攻击已关闭~) END
END

COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/spells/spin117.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139 // display string
      match_parameter1 = 30788
 parameter1 = RESOLVE_STR_REF (~别绝望！我会悍然冲锋，为你助威！~)
END
SAY NAME1 ~狂战士之怒~
SAY NAME2 ~狂战士之怒~
SAY UNIDENTIFIED_DESC ~狂战士之怒
拉西曼狂战士进入狂暴状态，持续2回合。狂暴期间，力量获得+2加值，免疫魅惑、困惑、恐惧、弱智、定身、等级吸取、迷宫、眩晕与睡眠。拉西曼狂战士还会获得15点临时生命值，狂暴结束后扣除，可能导致其陷入昏迷。但狂暴期间护甲等级受4点惩罚。此外，狂暴结束前，狂战士除移动与攻击外无法进行任何行动，比如施法、使用物品、潜行或交谈。12级时力量加值提升至+4，20级时提升至+6。

效果结束后，拉西曼狂战士会陷入疲劳状态，零级命中值、护甲等级与伤害降低4点，且1回合内无法再次进入狂暴。

8级：拉西曼狂战士拥有惊人的意志力。狂战士的法术豁免永久获得+3加值，狂暴期间翻倍。狂暴期间，拉西曼狂战士还免疫灵能效果。

12级：拉西曼狂战士狂暴时如同不可阻挡的战争机器，是真正令人畏惧的存在。狂暴期间，狂战士免疫所有阻碍移动的效果与监禁效果。

16级：拉西曼狂战士不会再陷入疲劳，狂暴结束后也不会受到伤害。

18级：拉西曼狂战士的狂怒之强，足以让其暂时抵挡死亡。18级起，拉西曼狂战士进入狂暴后的前5回合内，不会以任何方式死亡。~

COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/spells/c0tbm3.spl~ ~override~
SAY NAME1 ~疲劳~
SAY NAME2 ~疲劳~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 206
      match_parameter1 = 0
 parameter1 = RESOLVE_STR_REF (~狂战士太过疲惫，无法进入狂暴状态。~)
END

COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/spells/c0tbm4.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 206
      match_parameter1 = 0
 parameter1 = RESOLVE_STR_REF (~狂战士正处于狂暴状态。~)
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc.cre~ THEN BEGIN
    COPY_EXISTING ~minsc.cre~ ~override~
	WRITE_SHORT 0x24 12
	WRITE_SHORT 0x26 12
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc2.cre~ THEN BEGIN
    COPY_EXISTING ~minsc2.cre~ ~override~
	WRITE_SHORT 0x24 24
	WRITE_SHORT 0x26 24
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc4.cre~ THEN BEGIN
    COPY_EXISTING ~minsc4.cre~ ~override~
	WRITE_SHORT 0x24 48
	WRITE_SHORT 0x26 48
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc6.cre~ THEN BEGIN
    COPY_EXISTING ~minsc6.cre~ ~override~
	WRITE_SHORT 0x24 72
	WRITE_SHORT 0x26 72
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF GAME_IS ~BGEE~ AND FILE_EXISTS_IN_GAME ~minsc7.cre~ THEN BEGIN
    COPY_EXISTING ~minsc7.cre~ ~override~
	WRITE_SHORT 0x24 72
	WRITE_SHORT 0x26 72
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	ADD_CRE_ITEM ~chan05~ #0 #0 #0 ~IDENTIFIED~ ~ARMOR~
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF GAME_IS ~eet~ AND FILE_EXISTS_IN_GAME ~minsc7_.cre~ THEN BEGIN
    COPY_EXISTING ~minsc7_.cre~ ~override~
	WRITE_SHORT 0x24 72
	WRITE_SHORT 0x26 72
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	ADD_CRE_ITEM ~chan05~ #0 #0 #0 ~IDENTIFIED~ ~ARMOR~
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF GAME_IS ~bg2ee eet~ AND FILE_EXISTS_IN_GAME ~minsc7.cre~ THEN BEGIN
    COPY_EXISTING ~minsc7.cre~ ~override~
	WRITE_SHORT 0x24 84
	WRITE_SHORT 0x26 84
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc8.cre~ THEN BEGIN
    COPY_EXISTING ~minsc8.cre~ ~override~
	WRITE_SHORT 0x24 96
	WRITE_SHORT 0x26 96
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc9.cre~ THEN BEGIN
    COPY_EXISTING ~minsc9.cre~ ~override~
	WRITE_SHORT 0x24 108
	WRITE_SHORT 0x26 108
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc10.cre~ THEN BEGIN
    COPY_EXISTING ~minsc10.cre~ ~override~
	WRITE_SHORT 0x24 111
	WRITE_SHORT 0x26 111
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc12.cre~ THEN BEGIN
    COPY_EXISTING ~minsc12.cre~ ~override~
	WRITE_SHORT 0x24 117
	WRITE_SHORT 0x26 117
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~minsc14.cre~ THEN BEGIN
    COPY_EXISTING ~minsc14.cre~ ~override~
	WRITE_SHORT 0x24 123
	WRITE_SHORT 0x26 123
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
	ADD_CRE_ITEM ~chan05~ #0 #0 #0 ~IDENTIFIED~ ~ARMOR~
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~ohb1mnsc.cre~ THEN BEGIN
    COPY_EXISTING ~ohb1mnsc.cre~ ~override~
	WRITE_SHORT 0x24 123
	WRITE_SHORT 0x26 123
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
	REMOVE_KNOWN_SPELLS
	ADD_CRE_ITEM ~chan05~ #0 #0 #0 ~IDENTIFIED~ ~ARMOR~
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~ttminsc.cre~ THEN BEGIN
    COPY_EXISTING ~ttminsc.cre~ ~override~
	WRITE_SHORT 0x24 72
	WRITE_SHORT 0x26 72
	WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0TBM~))
		SET_BG2_PROFICIENCY 104 1
		SET_BG2_PROFICIENCY 93 3
		BUT_ONLY
END

ACTION_IF GAME_IS ~bgee eet~ THEN BEGIN

// CREATURES

COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/creatures/c0mbear.cre~ ~override~
SAY NAME1 ~巨红熊~
SAY NAME2 ~巨红熊~

// DIALOGUES

COMPILE ~ArtisansKitpack/Ranger/BerserkerMinsc/dialogue/minscj.d~
COMPILE ~ArtisansKitpack/Ranger/BerserkerMinsc/dialogue/taerom.d~
END

// SCRIPTS

ACTION_IF GAME_IS ~bgee~
THEN BEGIN
EXTEND_TOP ~minsc.bcs~ ~ArtisansKitpack/Ranger/BerserkerMinsc/scripts/minsc.baf~
END

ACTION_IF GAME_IS ~eet~
THEN BEGIN
EXTEND_TOP ~minsc_.bcs~ ~ArtisansKitpack/Ranger/BerserkerMinsc/scripts/minsc.baf~
END

ACTION_IF GAME_IS ~bgee~
THEN BEGIN
EXTEND_BOTTOM ~ar5101.bcs~ ~ArtisansKitpack/Ranger/BerserkerMinsc/scripts/ar5101.baf~
END

ACTION_IF GAME_IS ~eet~
THEN BEGIN
EXTEND_BOTTOM ~bg5101.bcs~ ~ArtisansKitpack/Ranger/BerserkerMinsc/scripts/ar5101.baf~
END

// ITEMS

COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/items/c0min01.bam~ ~override~ 
COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/items/c0min02.bam~ ~override~ 
COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/items/c0mskin.itm~ ~override~ 
SAY NAME1 ~红熊皮~
SAY NAME2 ~红熊皮~
SAY DESC ~这张厚皮取自一头巨熊，带着不寻常的淡红色调。可制成一套实用的护甲。

属性：

重量：10~

COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/items/c0mleat1.eff~ ~override~ 
COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/items/c0mleat1.spl~ ~override~ 
COPY ~ArtisansKitpack/Ranger/BerserkerMinsc/items/c0mleat.itm~ ~override~ 
SAY NAME1 ~兽皮护甲~
SAY NAME2 ~红熊皮甲~
SAY DESC ~这套厚实护甲由巨熊之皮制成。熊皮的红色在鞣制与打造成甲的过程中略有褪去，但坚韧程度不输巨兽本身。护甲的款式效仿拉西曼之地狂战士的装束。

属性：

装备效果：
–开锁：-10%
–寻找陷阱：-10%
–扒窃：-10%
–静音移动：-20%
–近战伤害抗性：+5%（狂暴期间+10%）
–远程伤害抗性：+20%（狂暴期间+40%）
–每3回合回复1点生命值
–狂暴期间，穿戴者移动速度为正常的两倍

护甲等级：4（对抗穿刺与远程攻击时为6）
需求：
 力量6

重量：40~

ACTION_IF FILE_EXISTS_IN_GAME ~shop03.sto~ THEN BEGIN
COPY_EXISTING ~shop03.sto~ ~override~
ADD_STORE_ITEM ~c0mleat~ LAST #0 #0 #0 ~IDENTIFIED~ #1
END

ACTION_IF FILE_EXISTS_IN_GAME ~M_C0RAN1.lua~ THEN BEGIN

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "C0TBM" = 0) BEGIN
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "C0TBM" = 0) BEGIN
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 10
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0TBM.2DA~ BEGIN
COPY_EXISTING ~C0TBM.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 18 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TBMS END // FIND TRAP/ILLUSION POINTS
  PRETTY_PRINT_2DA
BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//MINSC
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "C0TBM" BEGIN
          READ_2DA_ENTRY index 4 col_count minsc_desc
          SPRINT old_minsc ~职业限制：~
          SPRINT new_minsc ~职业限制：
–寻找陷阱的技能等级仅为正常的一半。
–识破幻象技能不会随等级提升。~
          GET_STRREF %minsc_desc% minsc_text
          INNER_PATCH_SAVE minsc_text ~%minsc_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_minsc%~ ~%new_minsc%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%minsc_desc%~ ~%minsc_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
  END
