COPY ~%MOD_FOLDER%/Paladin/Blackguard/2da~ ~override~
COPY ~%MOD_FOLDER%/Paladin/Blackguard/bams~ ~override~
COPY ~%MOD_FOLDER%/Paladin/Blackguard/spells~ ~override~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/CLABPA06.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE
	REPLACE_TEXTUALLY ~GA_SPCL213 ~ ~**** ~ // PROTECTION FROM EVIL
	REPLACE_TEXTUALLY ~GA_SPCL212 ~ ~**** ~ // DETECT EVIL
	REPLACE_TEXTUALLY ~GA_SPCL211 ~ ~**** ~ // LAY ON HANDS
	REPLACE_TEXTUALLY ~GA_C0PAL02 ~ ~**** ~ // SMITE EVIL
	REPLACE_TEXTUALLY ~SPCL111 ~ ~**** ~ // CURE DISEASE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPCL102 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = GA_SPCL102 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_SPCL102 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BG#04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0AS#P1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL104 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL105 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BG#02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0BG#S END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_C0AS#P1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0BG#00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_C0BG#03 END

 	PRETTY_PRINT_2DA

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~绝望暗气~) STR_VAR bam_file = c0bgic01 RET c0bgic01 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~邪祟清算~) STR_VAR bam_file = c0bgic02 RET c0bgic02 = icon END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~BLACKGUARD~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~黑暗卫士：黑暗卫士是邪恶的化身，与凡间的魔物无异。作为典型的黑骑士，这类恶徒声名狼藉且完全咎由自取。他们与魔鬼恶魔为伍，侍奉黑暗神祇，为众生所憎惧。因其彻头彻尾的邪恶本质，世人常称其为“反圣武士”。

职业优势：
–免疫等级吸取与恐惧。
–可如同同级圣武士般超度不死生物。
–可记忆少量法师法术：
  1环：目盲术、拉洛克的轻微吸取
  2环：恐惧术、隐形术
  3环：吸血之触、定身不死生物
  4环：高等隐形术、瘟疫术
  
–每日可使用一次「吸取生命」能力。8级与12级各额外获得一次使用次数。

吸取生命：黑暗卫士汲取接触范围内不幸目标的生命力，吸取1点零级命中值与伤害（每5级额外吸取1点，20级时最高5点），以及每等级1点生命值，并将其加至<PRO_HISHER>的最大值。被吸取的属性持续3回合，每等级额外持续1回合。不死生物与构装体等非活物免疫此效果。

–每日可使用一次「淬毒武器」能力。1级获得1次，5级获得1次，之后每5级额外获得一次。

淬毒武器：黑暗卫士可为<PRO_HISHER>武器涂抹起效缓慢但药性猛毒的剧毒，持续8小时。该毒素会立即造成伤害并降低目标体质，之后每回合持续生效，至少持续4回合。4回合过后，目标必须进行一次死亡豁免，否则将再中毒4回合。因此只要目标未能成功豁免，毒素就有可能无限期持续。目标不会因毒素造成的体质流失而死亡。

1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。

–3级：获得「绝望暗气」被动能力。

绝望暗气：黑暗卫士会散发秽暗不洁的气息，根据黑暗卫士的等级，对<PRO_HIMHER>15尺范围内的所有敌人造成负面效果。不死生物与构装体等非活物不受影响。
  3级：所有敌人的豁免检定与士气-1。
  11级：所有敌人的豁免检定与士气-1，所有造成的伤害-5%。
  19级：所有敌人的豁免检定与士气-2，所有造成的伤害-10%。
  
–11级：可使用背刺，倍率为2倍。
–12级：每日可使用一次「邪祟清算」能力。

邪祟清算：黑暗卫士汲取其邪性宿主的力量，获得+4零级命中值、所有来源造成的伤害+30%，以及+20点生命值，持续3回合。邪祟清算生效期间击杀生物，可为黑暗卫士回复20点生命值并重置持续时间。但若初始持续时间内未击杀任何生物，黑暗卫士将受到40点魔法伤害，且零级命中值-4、所有造成的伤害-50%，持续6回合作为惩罚。

–16级：背刺倍率提升至3倍。

职业限制：
–声望受-2惩罚。
–仅限邪恶阵营。
–无法施展多数治疗与防护领域的法术。
–不获得勇气光环。
–无法施展侦测邪恶。
–无法使用破邪斩。
–无法将防护邪恶作为天生能力施展。
–无法使用圣疗术。~

// backstab
APPEND ~backstab.2da~ ~BLACKGUARD 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3~
APPEND ~sneakatt.2da~ ~BLACKGUARD 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 6~
APPEND ~crippstr.2da~ ~BLACKGUARD 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~

// REPUTATION
ACTION_IF FILE_EXISTS_IN_GAME ~CLABPA06.2da~ THEN BEGIN
COPY ~%MOD_FOLDER%/Paladin/Blackguard/2da/CLABPA06.2da~ ~override~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/Paladin/Blackguard/scripts/reputation.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/Paladin/Blackguard/scripts/reputation.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/Paladin/Blackguard/scripts/reputation.baf~
END

COPY_EXISTING ~C0BG#00.spl~ ~override~
      LPF ADD_SPELL_EFFECT
      INT_VAR
	    opcode = 142
	    target = 2
		timing = 9
        parameter2 = c0bgic01
      END

COPY_EXISTING ~SPCL102.spl~ ~override~
SAY NAME1 ~吸取生命~
SAY UNIDENTIFIED_DESC ~吸取生命
黑暗卫士汲取接触范围内不幸目标的生命力，吸取1点零级命中值与伤害（每5级额外吸取1点，20级时最高5点），以及每等级1点生命值，并将其加至<PRO_HISHER>的最大值。被吸取的属性持续3回合，每等级额外持续1回合。不死生物与构装体等非活物免疫此效果。~

ACTION_IF FILE_EXISTS ~C0TR#20A.spl~ THEN BEGIN
COPY_EXISTING ~C0TR#20A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER STR_VAR icon = C0BG#02 END
SAY NAME1 ~模仿：吸取生命~
END

INCLUDE ~%MOD_FOLDER%/effects/poison_weapon.tpa~

ACTION_IF FILE_EXISTS ~C0TR#30A.spl~ THEN BEGIN
COPY_EXISTING ~C0TR#30A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER STR_VAR icon = C0ASIN8B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = c0as#p1 END
SAY NAME1 ~模仿：淬毒武器~
END

COPY_EXISTING ~C0BG#00.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~获得被动能力：绝望暗气~)
END

COPY_EXISTING ~C0BG#03.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 142 // display string
      parameter2 = c0bgic02
  END
SAY NAME1 ~邪祟清算~
SAY UNIDENTIFIED_DESC ~邪祟清算
黑暗卫士汲取其邪性宿主的力量，获得+4零级命中值、所有来源造成的伤害+30%，以及+20点生命值，持续3回合。邪祟清算生效期间击杀生物，可为黑暗卫士回复20点生命值并重置持续时间。但若初始持续时间内未击杀任何生物，黑暗卫士将受到40点魔法伤害，且零级命中值-4、所有造成的伤害-50%，持续6回合作为惩罚。~

COPY_EXISTING ~C0BG#03a.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 142 // display string
      parameter2 = c0bgic02
  END
  
COPY_EXISTING ~C0BG#03c.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
      match_opcode = 142 // display string
      parameter2 = c0bgic02
  END
  
COPY_EXISTING ~C0BG#03b.spl~ ~override~
SAY NAME1 ~惩罚~

//BLINDNESS
COPY_EXISTING ~SPWI106.SPL~ ~OVERRIDE/C0BG106.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2
//LARLOCH'S MINOR DRAIN
COPY_EXISTING ~SPWI119.SPL~ ~OVERRIDE/C0BG119.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2
//HORROR
COPY_EXISTING ~SPWI205.SPL~ ~OVERRIDE/C0BG205.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2
//INVISIBILITY
COPY_EXISTING ~SPWI206.SPL~ ~OVERRIDE/C0BG206.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2
//VAMPIRIC TOUCH
COPY_EXISTING ~SPWI314.SPL~ ~OVERRIDE/C0BG314.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2
//HOLD UNDEAD
COPY_EXISTING ~SPWI324.SPL~ ~OVERRIDE/C0BG324.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2
//IMPROVED INVISIBILITY
COPY_EXISTING ~SPWI405.SPL~ ~OVERRIDE/C0BG405.SPL~
WRITE_SHORT 0X34 4
WRITE_SHORT 0X1C 2
//CONTAGION
COPY_EXISTING ~SPWI409.SPL~ ~OVERRIDE/C0BG409.SPL~
WRITE_SHORT 0X34 4
WRITE_SHORT 0X1C 2

 ACTION_FOR_EACH dorn IN dorn dorn2 dorn4 dorn6 dorn7 dorn8 dorn9 dorn10 dorn12 dorn14 BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%dorn%.cre~ THEN BEGIN
    COPY_EXISTING ~%dorn%.cre~ ~override~
		REMOVE_KNOWN_SPELL ~SPCL102~ ~SPCL423~ ~SPCL103~
		REMOVE_MEMORIZED_SPELL ~SPCL102~ ~SPCL423~ ~SPCL103~
		BUT_ONLY
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~C0PAL00.SPL~ THEN BEGIN

COPY_EXISTING ~C0PAL00.SPL~ ~OVERRIDE/C0BG#04.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 272 STR_VAR resource = C0BG#04A END
LPF DELETE_EFFECT INT_VAR match_opcode = 142 END

COPY_EXISTING ~C0PAL01.EFF~ ~OVERRIDE/C0BG#04A.EFF~
WRITE_ASCII 0x30 ~C0BG#04B~

COPY_EXISTING ~C0PAL01.SPL~ ~OVERRIDE/C0BG#04B.SPL~
LPF DELETE_EFFECT STR_VAR match_resource = C0PAL04A END
LPF DELETE_EFFECT STR_VAR match_resource = C0PAL04B END
LPF DELETE_EFFECT STR_VAR match_resource = C0PAL04C END

END

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY ~%MOD_FOLDER%/lua/m_c0blk1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself

ACTION_IF FILE_EXISTS_IN_GAME ~CLABPA06.2DA~ BEGIN
COPY_EXISTING ~CLABPA06.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = AP_C0BLK01 END // STEALTH
  PRETTY_PRINT_2DA
BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////

APPEND_COL ~thiefscl.2da~ ~DELETE_TEXT DELETE_TEXT BLACKGUARD 0 0 0 100 100 0 0 0~ UNLESS ~BLACKGUARD~

COPY_EXISTING ~thiefscl.2da~ ~override~
REPLACE_TEXTUALLY ~DELETE_TEXT~ ~~
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF 	("%kit%" STRING_EQUAL_CASE "BLACKGUARD") BEGIN
      READ_2DA_ENTRY 4 col col_count val
      SET_2DA_ENTRY  4 col col_count 15
      READ_2DA_ENTRY 5 col col_count val
      SET_2DA_ENTRY  5 col col_count 15
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    BGCLATXT  
    clastext  
    sodcltxt 
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//blackguard
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "BLACKGUARD" BEGIN
          READ_2DA_ENTRY index 4 col_count blackguard_desc
          SPRINT old_blackguard ~–可如同同级圣武士般超度不死生物。~
          SPRINT new_blackguard ~–可如同同级圣武士般超度不死生物。
–可使用躲藏暗影。~
          GET_STRREF %blackguard_desc% blackguard_text
          INNER_PATCH_SAVE blackguard_text ~%blackguard_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_blackguard%~ ~%new_blackguard%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%blackguard_desc%~ ~%blackguard_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
  END
  
ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREE.PRO~ ~C0 Instant Area Enemies~

COPY_EXISTING ~C0BG#01.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREE
END
