
COPY ~%MOD_FOLDER%/Thief/BountyHunter/2DAs~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Thief/BountyHunter/SPELLS~ ~OVERRIDE~

INCLUDE ~%MOD_FOLDER%/spells/tracking.tpa~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/CLABTH03.2DA~
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE
	REPLACE_TEXTUALLY ~AP_C0TH-A2~ ~**** ~ // EPIC PRECISION

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0STK01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BH-0 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0BH-1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_C0BH-1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPCL414 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_SPCL414 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0A_A01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_c0dh#002 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~赏金猎人：这类猎手以猎捕人为业，精于追踪猎物并将其生擒——无论效劳于合法当局，还是地下势力。赏金猎人受过专门的追猎训练，是可怕的对手。他们布设陷阱的技艺远胜普通游荡者。

职业优势：
–对类人生物的命中与伤害+2。
–设置陷阱+15%奖励。
–可随意使用「分析」能力。

分析：使用本能力时，使用者会仔细观察目标，辨识其优劣，显示目标的生命骰、零级命中值、豁免检定、魔法抗性、伤害抗性，以及对毒素与背刺的易伤程度。本能力可无限制使用。

–可使用「追踪」攻击模式。

追踪：游侠对周遭环境与栖息其中的生物了若指掌，可使用追踪能力大致知晓区域内有何种生物，以及它们的方位。游侠50尺范围内的所有敌人都会在战争迷雾中显现。9级与18级时，追踪范围额外增加25尺半径。

–每日可使用一次「淬毒武器（衰弱）」能力，每提升5级额外获得一次使用次数。

淬毒武器：赏金猎人可为<PRO_HISHER>武器涂抹非致命但会削弱体力的毒素，持续8小时。该毒素造成伤害，附带迟缓效果，并立即及之后每回合降低目标的强韧豁免，持续回合数随赏金猎人等级提升。该毒素造成的强韧豁免惩罚持续5回合。
  1级：目标受到2点非致命伤害，每回合损失1点强韧豁免，持续2回合。
  6级：目标受到4点非致命伤害，每回合损失1点强韧豁免，持续3回合。
  11级：目标受到6点非致命伤害，每回合损失1点强韧豁免，持续4回合。
  16级：目标受到8点非致命伤害，每回合损失1点强韧豁免，持续5回合。
  21级：目标受到10点非致命伤害，每回合损失1点强韧豁免，持续6回合。
  
–除普通游荡者的陷阱外，每日可额外使用一次「特制捕网陷阱」能力。1级获得1次，之后每提升5级额外获得一次。

特制捕网陷阱：视野内无敌对生物时，在选定位置布设陷阱。赏金猎人的特制捕网陷阱与普通陷阱不同，会释放一团炼金烟雾，虽不造成伤害，但会对15尺范围内的敌人造成致残效果。赏金猎人及其盟友因预先服用了解毒剂，不受烟雾影响。
  1级：目标的护甲等级与零级命中值受-2惩罚，持续1回合。若强韧豁免失败，目标陷入眩晕（护甲-10且无法行动，但受到攻击后效果解除），持续1回合。
  11级：目标的护甲等级、零级命中值与豁免检定受-2惩罚，持续1回合。所有目标昏迷1回合；若强韧豁免失败，昏迷时间延长1回合。
  16级：目标的护甲等级、零级命中值、伤害与豁免检定受-2惩罚，持续1回合。所有目标眩晕1回合；若强韧豁免失败，眩晕时间延长至5回合。
  21级：目标的护甲等级、零级命中值、伤害与豁免检定受-3惩罚，持续1回合。所有目标眩晕1回合；若强韧豁免失败，眩晕时间延长至5回合，且永久目盲。
  
–12级起，每日可使用一次「猎者捕网陷阱」能力。

猎者捕网陷阱：这是一种强力陷阱，用于致残并标记目标。陷阱造成10d10+20点远程伤害，若目标死亡豁免失败（每8级豁免惩罚-1）则陷入麻痹；否则目标移动速度大幅降低，且会不受控制地流血，4回合内额外造成24点伤害。此外，流血期间目标会被暴露，在友方视野外也保持可见，且无法进入潜行或隐形状态。猎者捕网陷阱的次级效果对不死生物、元素生物与虚体生物无效。

职业限制：KIT_DISADV_1
–背刺成长远弱于普通游荡者：
  1-4级：1倍（无倍率）
  5-8级：2倍
  9-12级：3倍
–每次升级只能获得20点盗贼技能。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「致残打击」。
–无法获得「史诗精准」。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~BOUNTY_HUNTER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~
	
// PROFICIENCIES

COPY_EXISTING ~BACKSTAB.2da~ ~override~
  REPLACE_EVALUATE ~BOUNTY_HUNTER \([- %TAB%0-9]+\)~ BEGIN
    SPRINT data ~%MATCH1%~
  END ~BOUNTY_HUNTER 1 1 1 1 1 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3~

  COPY_EXISTING ~thiefskl.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BOUNTY_HUNTER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 2 cols 20
	  END
	END

COPY_EXISTING ~C0BH-1.SPL~ ~OVERRIDE~
SAY NAME1 ~淬毒武器（衰弱）~
SAY UNIDENTIFIED_DESC ~淬毒武器（衰弱）
赏金猎人可为<PRO_HISHER>武器涂抹非致命但会削弱体力的毒素，持续8小时。该毒素造成伤害，附带迟缓效果，并立即及之后每回合降低目标的强韧豁免，持续回合数随赏金猎人等级提升。该毒素造成的强韧豁免惩罚持续5回合。
  1级：目标受到2点非致命伤害，每回合损失1点强韧豁免，持续2回合。
  6级：目标受到4点非致命伤害，每回合损失1点强韧豁免，持续3回合。
  11级：目标受到6点非致命伤害，每回合损失1点强韧豁免，持续4回合。
  16级：目标受到8点非致命伤害，每回合损失1点强韧豁免，持续5回合。
  21级：目标受到10点非致命伤害，每回合损失1点强韧豁免，持续6回合。~

ADD_PROJECTILE ~%MOD_FOLDER%/Thief\BountyHunter\spells/C0BH-TR.PRO~
ADD_PROJECTILE ~%MOD_FOLDER%/Thief\BountyHunter\spells/C0BH-T2.PRO~
COPY_EXISTING ~C0BH-TR.PRO~ ~OVERRIDE~
WRITE_SHORT 0x21A (IDS_OF_SYMBOL (~projectl~ ~C0BH-T2~)) + 1

COPY_EXISTING ~C0BH-T1.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 1 parameter1 = RESOLVE_STR_REF (~眩晕~) END

COPY_EXISTING ~SPCL414.SPL~ ~OVERRIDE~
LPF ALTER_SPELL_HEADER INT_VAR header = 1 projectile = C0BH-TR END
SAY NAME1 ~特制捕网陷阱~
SAY UNIDENTIFIED_DESC ~特制捕网陷阱
视野内无敌对生物时，在选定位置布设陷阱。赏金猎人的特制捕网陷阱与普通陷阱不同，会释放一团炼金烟雾，虽不造成伤害，但会对15尺范围内的敌人造成致残效果。赏金猎人及其盟友因预先服用了解毒剂，不受烟雾影响。
  1级：目标的护甲等级与零级命中值受-2惩罚，持续1回合。若强韧豁免失败，目标陷入眩晕（护甲-10且无法行动，但受到攻击后效果解除），持续1回合。
  11级：目标的护甲等级、零级命中值与豁免检定受-2惩罚，持续1回合。所有目标昏迷1回合；若强韧豁免失败，昏迷时间延长1回合。
  16级：目标的护甲等级、零级命中值、伤害与豁免检定受-2惩罚，持续1回合。所有目标眩晕1回合；若强韧豁免失败，眩晕时间延长至5回合。
  21级：目标的护甲等级、零级命中值、伤害与豁免检定受-3惩罚，持续1回合。所有目标眩晕1回合；若强韧豁免失败，眩晕时间延长至5回合，且永久目盲。~
COPY_EXISTING ~SPCL415.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 match_parameter1 = 0 parameter1 = RESOLVE_STR_REF (~衰弱~) END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~C0DH#002.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Thief/BountyHunter/SPELLS/manhunter_snare~ ~OVERRIDE~

COPY_EXISTING ~C0DH#002.SPL~ ~OVERRIDE~
SAY NAME1 ~猎者捕网陷阱~
SAY UNIDENTIFIED_DESC ~猎者捕网陷阱
这是一种强力陷阱，用于致残并标记目标。陷阱造成10d10+20点远程伤害，若目标死亡豁免失败（每8级豁免惩罚-1）则陷入麻痹；否则目标移动速度大幅降低，且会不受控制地流血，4回合内额外造成24点伤害。此外，流血期间目标会被暴露，在友方视野外也保持可见，且无法进入潜行或隐形状态。猎者捕网陷阱的次级效果对不死生物、元素生物与虚体生物无效。~

END