COPY ~%MOD_FOLDER%/MonkRevision/Brawler/2das~ ~override~
COPY ~%MOD_FOLDER%/MonkRevision/Brawler/spells~ ~override~

INCLUDE ~%MOD_FOLDER%/effects/toughness.tpa~

INCLUDE ~%MOD_FOLDER%/effects/fortitude.tpa~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~K_MN_HO.2DA~ THEN BEGIN
COPY ~%MOD_FOLDER%/MonkRevision/K_MN_HO~ OVERRIDE
END

COPY_EXISTING ~CLABMO01.2DA~ ~OVERRIDE/C0BRAWL.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL811~ ~**** ~ // STUNNING BLOW
	REPLACE_TEXTUALLY ~AP_C0MN#14~ ~**** ~ // QUIVERING PALM
	REPLACE_TEXTUALLY ~GA_SPCL815~ ~**** ~ // WHOLENESS OF BODY
	REPLACE_TEXTUALLY ~AP_C0MN#00~ ~**** ~ // INNATE BONUSES
	REPLACE_TEXTUALLY ~AP_C0MN#13~ ~**** ~ // INNATE BONUSES
	REPLACE_TEXTUALLY ~AP_C0MN#03~ ~**** ~ // SAVING THROWS
	REPLACE_TEXTUALLY ~AP_SPCL817~ ~**** ~ // SAVE VS. ENCHANTMENT
	REPLACE_TEXTUALLY ~AP_SPCL814~ ~**** ~ // FREE ACTION
	REPLACE_TEXTUALLY ~AP_C0MN#06~ ~**** ~ // AC BONUS
	REPLACE_TEXTUALLY ~AP_SPCL818~ ~**** ~ // DIAMOND BODY
	REPLACE_TEXTUALLY ~AP_SPCL819~ ~**** ~ // DIAMOND SOUL
	REPLACE_TEXTUALLY ~GA_C0MN#05~ ~**** ~ // EMPTY BODY
	REPLACE_TEXTUALLY ~AP_SPCL821~ ~**** ~ // PERFECT SELF
	REPLACE_TEXTUALLY ~AP_SPCL822~ ~**** ~ // AC BONUS

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 4 STR_VAR f_Entry = GA_C0BRW01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BRS00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0BRS03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 STR_VAR f_Entry = AP_C0BRS03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 STR_VAR f_Entry = AP_C0BRS03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = AP_C0BRS02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_C0BRS01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = AP_C0BRS04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0BRS05 END

 	PRETTY_PRINT_2DA

COPY_EXISTING ~LUFI0.2DA~ ~OVERRIDE/LUC0BRWL.2DA~

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 20
	
    mixed         = RESOLVE_STR_REF(~拳斗家~)
	
    lower         = RESOLVE_STR_REF(~拳斗家~)
	
    help          = RESOLVE_STR_REF(~拳斗家：这类战士专精于最朴素的战斗方式——仅凭赤手空拳作战。他们的格斗技艺在粗野而残酷的打斗中干锤百炼，摒弃了武僧的技法与灵修，仅以最微薄的气强化拳脚，其余全凭力量与韧性取胜。他们饱经风霜、布满老茧的身躯，被锤炼得如钢铁般强韧，正是其过往经历的写照。

职业优势：
–无阵营限制。
–每提升4级，徒手攻击的命中与伤害掷骰+1。
–每提升5级，徒手攻击的暴击修正+1。
–刚毅：拳斗家每次受到伤害时，回复1点生命值。
–获得「坚韧」被动能力。

坚韧：拳斗家获得5%物理伤害减免。生命值低于最大生命值50%时，该加成翻倍。

–每日可使用一次「斗式」能力。1级时获得1次使用次数，之后每提升4级额外获得1次。

斗式：接下来2回合内，拳斗家所有成功的攻击都造成最大伤害，但同一时间内护甲等级受4点惩罚。此外，拳斗家每次受到伤害时，额外回复2点生命值。

–11级：坚韧的基础物理抗性提升至10%。生命值低于50%时，拳斗家每3秒回复1点生命值。
–14级：获得「粉碎打击」被动效果。

粉碎打击：拳斗家的暴击会使目标的钝击抗性累计降低25%，持续2回合，并使目标眩晕3秒。

–15级：处于斗式状态时，拳斗家每回合额外获得一次攻击。
–16级：坚韧的基础物理抗性提升至15%。再生速率提升至每秒1点生命值。
–20级：徒手攻击伤害获得+4加值。
–生命骰：d12

职业限制：
–无法使用游荡者技能
–无法使用圣疗术能力
–无法使用震眩拳
–无法使用渗透劲
–远程武器无法获得熟练等级
–不获得魔法抗性
–不免疫疾病、迟缓、加速、魅惑、毒素与非魔法武器~)
	
    briefdesc     = RESOLVE_STR_REF(~拳斗家：这类战士专精于最朴素的战斗方式——仅凭赤手空拳作战。他们的格斗技艺在粗野而残酷的打斗中干锤百炼，摒弃了武僧的技法与灵修，仅以最微薄的气强化拳脚，其余全凭力量与韧性取胜。他们饱经风霜、布满老茧的身躯，被锤炼得如钢铁般强韧，正是其过往经历的写照。~)
  STR_VAR
    kit_name      = ~C0_BRAWLER~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    abclasrq      = ~14 0 16 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~1 1 1 1 1 1 1 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0BRWL~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0BRAWL.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    clswpbon      = ~1 3 2~
	
    hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
    clascolr = ~1 6 43 138 93~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~C0BRW01.SPL~ ~OVERRIDE~
SAY NAME1 ~斗式~
SAY UNIDENTIFIED_DESC ~斗式
接下来2回合内，拳斗家所有成功的攻击都造成最大伤害，但同一时间内护甲等级受4点惩罚。此外，拳斗家每次受到伤害时，额外回复2点生命值。15级起，拳斗家每回合额外获得一次攻击。~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY ~%MOD_FOLDER%/lua/m_c0mon1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself

OUTER_SET brawler_ids = IDS_OF_SYMBOL (~kit~ ~C0_BRAWLER~)
  
COPY ~%MOD_FOLDER%/lua/m_c0mon1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%brawler_ids%~~~~~ //"
  END

END