COPY ~%MOD_FOLDER%/Paladin/Cavalier/2da~ ~override~
COPY ~%MOD_FOLDER%/Paladin/Cavalier/bams~ ~override~
COPY ~%MOD_FOLDER%/Paladin/Cavalier/spells~ ~override~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/CLABPA02.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0CAV03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0CAV01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_Increment = 8 STR_VAR f_Entry = GA_C0CAV03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 STR_VAR f_Entry = AP_C0CAV02 END

 	PRETTY_PRINT_2DA

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~侠义光环~) STR_VAR bam_file = c0cav01i RET c0cav01i = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~英勇鼓舞~) STR_VAR bam_file = c0cav02i RET c0cav02i = icon END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~CAVALIER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~侠义骑士：该职业是最经典的骑士形象——恪守荣誉、勇气与忠诚的侠义战士。侠义骑士专于对抗恶魔、巨龙等「经典」邪恶怪物。

职业优势：
–免疫魅惑、毒素、恐惧与士气崩溃。
–对抗所有邪系与龙类生物时，命中与伤害掷骰+3。
–每日可使用一次「挑战」能力。每提升8级额外获得一次使用次数。

挑战：侠义骑士向目标发起挑战，接下来3回合内，目标与自身的护甲等级均降低10点。侠义骑士对被挑战目标造成额外的无视护甲魔法伤害。此外，被挑战目标在战争迷雾中可见，且持续期间无法隐形。
  1-11级：1d6点伤害
  12-19级：2d6点伤害
  20级及以上：4d6点伤害
  
–3级：获得「侠义光环」。

侠义光环：侠义骑士散发出光环，激励友军全力作战。视野范围内的所有友军免疫恐惧与士气崩溃，并获得战斗加成。
  3级：零级命中值+1。
  11级：零级命中值与伤害+1。
  19级：零级命中值与伤害+2，幸运+1。
  
–9级：获得「英勇鼓舞」。

英勇鼓舞：当侠义骑士的最大生命值降至50%以下时，视野范围内的所有友军（自身除外）额外获得+1命中、伤害与豁免检定加成。

职业限制：
–不获得基于魅力的神恩加值。
–不获得勇气光环。
–无法驱散不死生物。
–无法使用远程武器；若将近战/远程武器作远程使用，命中受-4惩罚。~

COPY_EXISTING ~C0CAV01.spl~ ~override~
      LPF ADD_SPELL_EFFECT
      INT_VAR
	    opcode = 142
	    target = 2
		timing = 9
        parameter2 = c0cav01i
      END

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

COPY_EXISTING ~C0CAV01A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

COPY_EXISTING ~C0CAV02.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~获得被动能力：英勇鼓舞~)
END

COPY_EXISTING ~C0CAV02A.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~英勇鼓舞：所有友军零级命中值、伤害与豁免检定+1~)
END
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 267
	  parameter1 = RESOLVE_STR_REF (~英勇鼓舞：所有友军零级命中值、伤害与豁免检定+1~)
END
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 142
	  parameter2 = c0cav02i
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~C0CAV03.SPL~ BEGIN

COPY ~%MOD_FOLDER%/spells/challenge~ ~override~

COPY_EXISTING ~C0CAV03.spl~ ~override~
SAY NAME1 ~挑战！~
SAY UNIDENTIFIED_DESC ~挑战
使用者向目标发起挑战，接下来3回合内，目标与自身的护甲等级均降低10点。使用者对被挑战目标造成额外的无视护甲魔法伤害。此外，被挑战目标在战争迷雾中可见，且持续期间无法隐形。
  1-11级：1d6点伤害
  12-19级：2d6点伤害
  20级及以上：4d6点伤害~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~已受挑战~)
END

END