COPY ~%MOD_FOLDER%/Ranger/DarkHunter/bams~ ~override~
COPY ~%MOD_FOLDER%/Ranger/DarkHunter/spells~ ~override~

COPY_EXISTING ~CLABRN01.2DA~ ~OVERRIDE/C0DHUNT.2DA~
	// REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%] ~ ~**** ~ // TOUGHNESS
	// REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%][%0-9%] ~ ~**** ~ // TOUGHNESS
	REPLACE_TEXTUALLY ~GA_SPCL311~ ~**** ~ // CHARM ANIMAL
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	// REPLACE_TEXTUALLY ~C0RNG00A ~ ~**** ~ // CAMOUFLAGE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0DH#000 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0AS#P1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 5 STR_VAR f_Entry = GA_SPCL412 END // Set Snare
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 1 STR_VAR f_Entry = AP_C0DH#004 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_C0AS#P1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0DH#S END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_C0DH#002 END

 	PRETTY_PRINT_2DA

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 12
	
    mixed         = RESOLVE_STR_REF(~黑暗猎人~)
	
    lower         = RESOLVE_STR_REF(~黑暗猎人~)
	
    help          = RESOLVE_STR_REF(~黑暗猎人：黑暗猎人将潜行与生存技艺用于渗透、谍报与追猎，必要时正面作战的能力也毫不逊色。在普通林间游侠眼中，他们不过是名义上的游侠；但在公会与权势集团中，作为刺客与情报搜集者的黑暗猎人往往更受欢迎。

与普通游侠不同，黑暗猎人无阵营限制；且他们的力量并非神祇所赐，因此永远不会堕落。

职业优势：
–可使用背刺能力，但伤害倍率低于盗贼：
  1-8级：2倍
  9-16级：3倍
  17级及以上：4倍
–对抗类人生物时，命中与伤害+2。
–每个区域最多可布设6个陷阱。
–可记忆少量法师法术：
  1环：魅惑人类、夜视术、一级召唤怪物、镜像术
  2环：模糊术、隐形术、敲击术、二级召唤怪物
  3环：识破幻象、幽灵护甲、定身术、三级召唤怪物
–每日可使用一次「淬毒武器」能力，每提升5级额外获得一次使用次数。

淬毒武器：黑暗猎人可为<PRO_HISHER>武器涂抹起效缓慢但药性猛毒的剧毒，持续8小时。该毒素造成伤害，并立即及之后每回合降低目标体质，至少持续4回合。4回合过后，目标必须进行一次死亡豁免，否则将再中毒4回合。因此只要目标未能成功豁免，毒素就有可能无限期持续。目标不会因毒素造成的体质流失而死亡。
  1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
  6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
  11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
  16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
  21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。
  
–10级起，每日可使用一次「猎者捕网陷阱」能力。

猎者捕网陷阱：这是一种强力陷阱，用于致残并标记目标。陷阱造成10d10+20点远程伤害，若目标死亡豁免失败（每8级豁免惩罚-1）则陷入麻痹；否则目标移动速度大幅降低，且会不受控制地流血，4回合内额外造成24点伤害。此外，流血期间目标会被暴露，在友方视野外也保持可见，且无法进入潜行或隐形状态。猎者捕网陷阱的次级效果对不死生物、元素生物与虚体生物无效。
职业限制：
–无法施展任何德鲁伊法术。
–无法兼职。
–无法穿戴重于钉皮甲的护甲。
–无法使用「魅惑动物」能力。~)
	
    briefdesc     = RESOLVE_STR_REF(~黑暗猎人：黑暗猎人将潜行与生存技艺用于渗透、谍报与追猎，必要时正面作战的能力也毫不逊色。在普通林间游侠眼中，他们不过是名义上的游侠；但在公会与权势集团中，作为刺客与情报搜集者的黑暗猎人往往更受欢迎。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0DHUNT~
	
    unusable      = ~0x00010000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    // abclasrq      = ~0 15 0 14 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~1 1 1 1 1 1 1 1 1~
	
    dualclas      = ~0 0 0 0 0 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0DHUNT.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
	clascolr = ~182 182 136 184 142~
	
	clasiskl = ~0 0 0 25 25 0 50~
	
	// clasthac = ~0~
	
	thiefscl = ~0 0 0 100 100 0 100 0~
	
	backstab = ~1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	sneakatt = ~1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 6~
	
	crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

APPEND ~fallen.2da~ ~C0DHUNT 0~

//CHARM PERSON
COPY_EXISTING ~SPWI104.SPL~ ~OVERRIDE/C0DH101.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2

//INFRAVISION
COPY_EXISTING ~SPWI111.SPL~ ~OVERRIDE/C0DH102.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2

//REFLECTED IMAGE
COPY_EXISTING ~SPWI120.SPL~ ~OVERRIDE/C0DH103.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2

//MONSTER SUMMONING I
COPY_EXISTING ~SPWI309.SPL~ ~OVERRIDE/C0DH104.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2

//BLUR
COPY_EXISTING ~SPWI201.SPL~ ~OVERRIDE/C0DH201.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2

//INVISIBILITY
COPY_EXISTING ~SPWI206.SPL~ ~OVERRIDE/C0DH202.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2

//KNOCK
COPY_EXISTING ~SPWI207.SPL~ ~OVERRIDE/C0DH203.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2

//MONSTER SUMMONING II
COPY_EXISTING ~SPWI407.SPL~ ~OVERRIDE/C0DH204.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2

//HOLD PERSON
COPY_EXISTING ~SPWI306.SPL~ ~OVERRIDE/C0DH301.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2

//GHOST ARMOR
COPY_EXISTING ~SPWI317.SPL~ ~OVERRIDE/C0DH302.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2

//DETECT ILLUSION
COPY_EXISTING ~SPWI322.SPL~ ~OVERRIDE/C0DH303.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2

//MONSTER SUMMONING III
COPY_EXISTING ~SPWI504.SPL~ ~OVERRIDE/C0DH304.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2

LAF ADD_CLASS_SPELL STR_VAR excludeAllNormalPriestSpellsFromThisKit=~C0DHUNT~ END

LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH101~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH102~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH103~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH104~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH201~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH202~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH203~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH204~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH301~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH302~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH303~ kit_include=~{'C0DHUNT', }~ END
LAF ADD_CLASS_SPELL STR_VAR resref=~C0DH304~ kit_include=~{'C0DHUNT', }~ END

INCLUDE ~%MOD_FOLDER%/effects/poison_weapon.tpa~

COPY_EXISTING ~C0DH#002.SPL~ ~OVERRIDE~
SAY NAME1 ~猎者捕网陷阱~
SAY UNIDENTIFIED_DESC ~猎者捕网陷阱
这是一种强力陷阱，用于致残并标记目标。陷阱造成10d10+20点远程伤害，若目标死亡豁免失败（每8级豁免惩罚-1）则陷入麻痹；否则目标移动速度大幅降低，且会不受控制地流血，4回合内额外造成24点伤害。此外，流血期间目标会被暴露，在友方视野外也保持可见，且无法进入潜行或隐形状态。猎者捕网陷阱的次级效果对不死生物、元素生物与虚体生物无效。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~M_C0RAN1.lua~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~C0DHUNT.2DA~ BEGIN
COPY_EXISTING ~C0DHUNT.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0RNG01 END // Set Traps
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0RNG02 END // Set Traps
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0DH#005 END // Set Traps
  PRETTY_PRINT_2DA
BUT_ONLY

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "C0DHUNT") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      READ_2DA_ENTRY 2 col col_count val
      SET_2DA_ENTRY  2 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "C0DHUNT") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 20
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 20
      READ_2DA_ENTRY 2 col col_count val
      SET_2DA_ENTRY  2 col col_count 20
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

OUTER_SET darkhunter_ids = IDS_OF_SYMBOL (~kit~ ~C0DHUNT~)
  
COPY ~%MOD_FOLDER%/lua/m_c0ran2.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%darkhunter_ids%~~~~~ //"
  END

END

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

OUTER_SET darkhunter_ids = IDS_OF_SYMBOL (~kit~ ~C0DHUNT~)
  
COPY ~%MOD_FOLDER%/lua/m_c0ran2.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%darkhunter_ids%~~~~~ //"
  END

END

END
END
END