COPY ~%MOD_FOLDER%/Paladin\DivineChampion~ ~override~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/C0DC.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE
	REPLACE_TEXTUALLY ~GA_C0PAL02 ~ ~**** ~ // SMITE EVIL
	REPLACE_TEXTUALLY ~SPCL111 ~ ~**** ~ // CURE DISEASE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0DC01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_Increment = 2 STR_VAR f_Entry = GA_C0DC02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0DC03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_C0DC04 END

 	PRETTY_PRINT_2DA

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 6
	
    mixed         = RESOLVE_STR_REF(~神圣斗士~)
	
    lower         = RESOLVE_STR_REF(~神圣斗士~)
	
    help          = RESOLVE_STR_REF(~神圣斗士：神圣斗士是其神祇的坚实右臂。他们担任圣所守护者、朝圣者保护者与十字军领袖。在诸多善良阵营的教会中，这些职责多由圣武士承担，但神圣斗士可以举起任何神祇的战旗，无关阵营或信条。这些圣战者受其信奉者爱戴的程度，与被教会仇敌憎恨的程度不相上下。

神圣斗士无阵营限制，且无论阵营与声望如何，永远不会堕落。

职业优势：
–任意武器均可达到高阶精通（4个熟练位）。
–5级起所有豁免检定+1，之后每提升5级再+1。
–2级：每日可使用一次「惩戒异端」能力，每提升2级额外获得一次使用次数。

惩戒异端：接下来2回合内，神圣斗士的下一次攻击对任何道德阵营（善良、中立、邪恶）与自身不同的生物，造成每2等级1d4点魔法伤害。

–5级：每日可使用一次「神怒」能力。

神怒：神圣斗士引导其神祇的部分力量，获得命中、伤害与豁免检定+4，所有抗性+25%，且对抗所有道德阵营与自身不同的生物时，护甲等级与豁免检定额外+2。本能力持续1回合，每提升1级额外持续1回合。

职业限制：
–不获得基于魅力的额外豁免。
–不获得勇气光环。
–无法驱散不死生物。
–无法使用破邪斩。
–无法使用治病术。
–无法施展牧师法术。~)
	
    briefdesc     = RESOLVE_STR_REF(~神圣斗士：神圣斗士是其神祇的坚实右臂。他们担任圣所守护者、朝圣者保护者与十字军领袖。在诸多善良阵营的教会中，这些职责多由圣武士承担，但神圣斗士可以举起任何神祇的战旗，无关阵营或信条。~)
	
	fallen = 0
	
  STR_VAR
    kit_name      = ~C0DC~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 2 2 3~
	
    abclasrq      = ~12 9 0 0 13 17~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~1 1 1 1 1 1 1 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0DC~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0DC.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

APPEND ~fallen.2da~ ~C0DC 0~

ACTION_IF FILE_EXISTS_IN_GAME ~C0FIG01.SPL~ BEGIN
COPY_EXISTING ~C0DC.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // POWER ATTACK
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG02 END // EXPERTISE
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
  PRETTY_PRINT_2DA
BUT_ONLY

ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//divinechampion
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "C0DC" BEGIN
          READ_2DA_ENTRY index 4 col_count divinechampion_desc
          SPRINT old_divinechampion ~职业限制：~
          SPRINT new_divinechampion ~–5级：可使用「强力攻击」与「武器娴熟」攻击模式，同一时间仅可激活其中一种。
		  
强力攻击：神圣斗士牺牲精准度换取更重、更具杀伤力的打击，近战零级命中值降低3点，近战伤害提升3点。神圣斗士力量需达到17或以上才能激活此能力。

武器娴熟：神圣斗士专注于防御，以精准为代价，零级命中值降低3点，护甲等级提升3点。神圣斗士智力需达到15或以上才能激活此能力。

–6级：可使用「速射」攻击模式。

速射：神圣斗士每回合可额外进行一次远程攻击，命中受-4惩罚。

–12级：精通速射：速射激活时，神圣斗士的命中惩罚降低至-2。
–14级：可使用「精通强力攻击」与「精通武器娴熟」，将原能力的加成与惩罚提升至6点。

职业限制：~
          GET_STRREF %divinechampion_desc% divinechampion_text
          INNER_PATCH_SAVE divinechampion_text ~%divinechampion_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_divinechampion%~ ~%new_divinechampion%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%divinechampion_desc%~ ~%divinechampion_text%~
          END
		END
      END
      BUT_ONLY
    END
  END
  END
  
COPY ~%MOD_FOLDER%/Paladin/DivineChampion/c0dc01.spl~ ~override~
COPY ~%MOD_FOLDER%/Paladin/DivineChampion/c0dc02a.eff~ ~override~
COPY ~%MOD_FOLDER%/Paladin/DivineChampion/c0dc02a.spl~ ~override~
SAY NAME1 ~惩戒异端~
COPY ~%MOD_FOLDER%/Paladin/DivineChampion/c0dc02.spl~ ~override~
SAY NAME1 ~惩戒异端~
SAY UNIDENTIFIED_DESC ~惩戒异端
接下来2回合内，神圣斗士的下一次攻击对任何道德阵营（善良、中立、邪恶）与自身不同的生物，造成每2等级1d4点魔法伤害。~

COPY ~%MOD_FOLDER%/Paladin/DivineChampion/c0dc03.spl~ ~override~
SAY NAME1 ~神怒~
SAY UNIDENTIFIED_DESC ~神怒
神圣斗士引导其神祇的部分力量，获得命中、伤害与豁免检定+4，所有抗性+25%，且对抗所有道德阵营与自身不同的生物时，护甲等级与豁免检定额外+2。本能力持续1回合，每提升1级额外持续1回合。~

COPY ~%MOD_FOLDER%/Paladin/DivineChampion/c0dc04.spl~ ~override~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~numwslot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~C0DC~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 4
	  END
	END

OUTER_SET divine_champion_ids = IDS_OF_SYMBOL (~kit~ ~C0DC~)
  
COPY ~%MOD_FOLDER%/lua/m_c0dc1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%divine_champion_ids%~~~~~ //"
  END
END

COPY_EXISTING ~LUPA0.2da~ ~override/LUC0DC.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL923~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0DC1~ ability = ~GA_SPCL923~ excluded_by = ~GA_SPCL935~ alignment_restrict = ~ALL_EVIL~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0DC2~ ability = ~GA_SPCL935~ excluded_by = ~GA_SPCL923~ alignment_restrict = ~ALL_GOOD~ END	
