ACTION_IF dd = 1 THEN BEGIN
COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/spells~ ~override~

COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/2das/c0dd.2DA~ ~override/clabso01.2da~

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~DRAGON_DISCIPLE~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~龙脉术士：龙脉术士是血脉中潜藏龙之血脉的强大术士。他们天生的魔法天赋唤醒了自身的龙族传承，使其能够施展强力法术，并展现出类龙能力。

职业优势：
–1级：护甲等级+1。
–3级：每日可使用一次「龙息」。

龙息：龙脉术士喷出一道最远30尺的火焰，对140度锥形范围内的所有生物造成3d8点火焰伤害。

–4级：获得25%天生火焰抗性。
–5级：护甲等级与力量+1。
–6级：龙息伤害提升至4d8。
–8级：天生火焰抗性提升至50%。
–9级：龙息伤害提升至5d8。
–10级：护甲等级与智力+1。
–12级：龙息伤害提升至6d8。天生火焰抗性提升至75%。
–15级：护甲等级与体质+1。
–17级：力量+1。
–18级：移动速度提升2。
–20级：获得「龙化」。

龙化：龙脉术士完成蜕变，实质上成为半龙生物。获得力量+2、魅力+1、护甲等级+2，以及夜视术、免疫昏迷、定身与火焰伤害。此外，龙脉术士的视野范围略有提升，且可攻击半隐型的敌人。

–生命骰：d6

职业限制：
–每天可施展的每级法术减少一个~
END

ACTION_IF dd = 2 THEN BEGIN
COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/spells~ ~override~
COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/spells/C0DD05C.SPL~ ~override/C0DD05A.SPL~

COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/2das/c0dd2.2DA~ ~override/clabso01.2da~

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~DRAGON_DISCIPLE~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~龙脉术士：龙脉术士是血脉中潜藏龙之血脉的强大术士。他们天生的魔法天赋唤醒了自身的龙族传承，使其能够施展强力法术，并展现出类龙能力。

职业优势：
–1级：护甲等级+1。
–3级：每日可使用一次「龙息」。

龙息：龙脉术士喷出一道最远30尺的火焰，对140度锥形范围内的所有生物造成3d8点火焰伤害。

–4级：获得25%天生火焰抗性。
–5级：护甲等级与力量+1。
–6级：龙息伤害提升至4d8。
–8级：天生火焰抗性提升至50%。
–9级：龙息伤害提升至5d8。
–10级：护甲等级与智力+1。
–12级：龙息伤害提升至6d8。天生火焰抗性提升至75%。
–15级：护甲等级与体质+1。
–18级：移动速度提升2。
–20级：获得「龙化」。

龙化：龙脉术士完成蜕变，实质上成为半龙生物。获得力量+1、魅力+1、护甲等级+2，以及夜视术、免疫昏迷、定身与火焰伤害。此外，龙脉术士的视野范围略有提升，且可攻击半隐型的敌人。

–生命骰：d8

职业限制：
–每天可施展的每级法术减少一个~
END

COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/spells/spdd03.spl~ ~override~
SAY NAME1 ~龙息~
SAY UNIDENTIFIED_DESC ~龙息
角色喷出一道最远30尺的火焰，对140度锥形范围内的所有生物造成3d8点火焰伤害。3级之后，每提升3级，本技能额外造成1d8点火焰伤害（6级时4d8，9级时5d8，以此类推，12级时达到上限6d8）。~
COPY ~%MOD_FOLDER%/Sorcerer/DragonDisciple/spells/spdd04.spl~ ~override~