COPY ~%MOD_FOLDER%/Fighter/Dreadnought/2das~ ~override~
COPY ~%MOD_FOLDER%/Fighter/Dreadnought/bams~ ~override~
COPY ~%MOD_FOLDER%/Fighter/Dreadnought/spells~ ~override~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/C0DREADN.2DA~
	// REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0DREDA END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0DRED0 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0DRED1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0DRED3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = GA_C0DRED4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 15 f_Increment = 5 STR_VAR f_Entry = GA_C0DRED5 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_Increment = 8 STR_VAR f_Entry = GA_C0DRED4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = GA_C0DRED2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = GA_C0DRED2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = GA_C0DRED2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = GA_C0DRED2 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~无畏战士：无畏战士是令人闻风丧胆的战场杀器，他们摒弃精巧战技，崇尚力量与耐力，专攻全力挥击的战法，仅凭一击便可击倒最强悍的对手。然而尽管他们打法凶悍，若以为这只是单纯的蛮力就大错特错–如何将自身力量发挥到极致、打出最高伤害，是一门极少有人能掌握的高深技艺。

职业优势：
–力量属性获得+1加值。
–获得「力量打击」「重击强化」与「势不可挡」三项被动效果。

力量打击：除非使用特定技能，否则无畏战士每回合只能进行一次攻击。但他们的近战伤害可获得两倍力量调整值加值。

重击强化：无畏战士的近战重击会造成额外的钝击伤害，伤害随等级提升，额外加上常规力量调整值；目标需进行死亡豁免，豁免难度等于无畏战士常规力量伤害调整值的一半（向下取整），失败则震慑十秒。此外，无畏战士的重击可移除目标身上所有层数的石肤术及同类效果。
  1-4级：+1d6
  5-8级：+1d8
  9-12级：+1d10
  13-16级：+1d12
  17-20级：+2d8
  21-24级：+2d10
  25-28级：+2d12
  29-32级：+3d10
  33-36级：+3d12
  37级及以上：+4d10
  
势不可挡：无畏战士免疫大部分影响移动的效果，包括加速术、减速术、蛛网术、人类定身术、油腻术与纠缠术，但仍会受移动速率类效果影响。此外，当无畏战士遭到震慑时，会立刻解除该效果，并在下一回合获得+10近战伤害加值，同时在6回合内免疫后续震慑效果。

–可使用切换型技能「猛攻姿态」。

猛攻姿态：无畏战士将每回合基础攻击次数减半，但挥砍、穿刺与钝击伤害提升+50%，且每次攻击都会对目标触发重击强化效果。

–3级：每日可使用一次「全力进攻」技能。每提升8级获得额外一次使用次数。

全力进攻：接下来的三回合内，无畏战士将全身力量灌注于每一击，获得加速术效果，近战物理伤害提升+100%，期间每次攻击都造成最大伤害。但同一时间内，其护甲等级承受-6减值，钝击、穿刺与挥砍伤害抗性承受-50%减值，技能结束后还会承受严重的疲劳惩罚。此外，持续期间无畏战士无法施法、使用物品或游荡者技能。该技能无法与「坚韧」同时激活。

–5级：每日可使用一次「裂地一击」技能。10级与15级时各获得一次额外使用次数。

裂地一击：无畏战士挥出重击破地，连战场本身都会受其冲击。接下来三回合内的下一次攻击将自动判定为重击，并对自身前方10英尺直线上的次要目标触发重击强化效果，将除主目标外的所有生物略微击退。此外，重击的冲击会在原地留下一片半径10英尺的区域，持续五回合；除无畏战士自身外，站在区域内的所有生物敏捷属性与移动速率都会减半。

–7级：无畏战士额外获得+2近战伤害加值。
–9级：重击强化的额外伤害与震慑效果现在会作用于无畏战士周围5英尺半径内的所有敌人。
–12级：裂地一击现在可作用于接下来的两次攻击。
–13级：无畏战士额外获得+2近战伤害加值。
–15级：猛攻姿态的伤害加值提升至+75%。
–16级：裂地一击现在可作用于接下来的三次攻击。
–20级：猛攻姿态的伤害加值提升至+100%。

–生命骰：2d10

职业限制：
–护甲等级承受-2减值。
–不可兼职。
–不可使用远程武器；手持近战/远程武器切换为远程模式时，零级命中值承受-10减值。
–无法获得剑盾风格或双武器风格的熟练等级。KIT_DISADV_1~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–不可使用武器娴熟与快速射击。
–16级时不会获得全武器专精。
–不会获得精通先攻。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~无畏战士~)
	
    lower         = RESOLVE_STR_REF(~无畏战士~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~无畏战士：无畏战士是令人闻风丧胆的战场杀器，他们摒弃精巧战技，崇尚力量与耐力，专攻全力挥击的战法，仅凭一击便可击倒最强悍的对手。然而尽管他们打法凶悍，若以为这只是单纯的蛮力就大错特错–如何将自身力量发挥到极致、打出最高伤害，是一门极少有人能掌握的高深技艺。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0_DREADNOUGHT~
	
    unusable      = ~0x00000008~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~5 5 0 5 5 5 5 0 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 0 0 0 0 0 2 0 2 0~
	
    abclasrq      = ~17 0 16 0 0 0~
	
    abclsmod      = ~1 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    dualclas      = ~0 0 0 0 0 0~
	
    luabbr        = ~C0DRED~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0DREADN.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPC0DRED~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

APPEND ~splprot.2da~ ~C0HTAPR_NOTEQUAL 8 -1 5~ UNLESS ~C0HTAPR_NOTEQUAL~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTAPR_NOTEQUAL~ BEGIN
	    SET C0HTAPR_NOTEQUAL = %row%
	  END
	END

APPEND ~splprot.2da~ ~C0HTAPR_EQUAL 8 -1 1~ UNLESS ~C0HTAPR_EQUAL~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTAPR_EQUAL~ BEGIN
	    SET C0HTAPR_EQUAL = %row%
	  END
	END

APPEND ~splprot.2da~ ~C0HTSTR 36 -1 1~ UNLESS ~C0HTSTR~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTSTR~ BEGIN
	    SET C0HTSTR = %row%
	  END
	END

APPEND ~splprot.2da~ ~C0HTSTREXTRA_GTEQUAL 37 -1 4~ UNLESS ~C0HTSTREXTRA_GTEQUAL~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTSTREXTRA_GTEQUAL~ BEGIN
	    SET C0HTSTREXTRA_GTEQUAL = %row%
	  END
	END

APPEND ~splprot.2da~ ~C0HTSTREXTRA_EQUAL 37 -1 1~ UNLESS ~C0HTSTREXTRA_EQUAL~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTSTREXTRA_EQUAL~ BEGIN
	    SET C0HTSTREXTRA_EQUAL = %row%
	  END
	END

DEFINE_ACTION_FUNCTION	ADD_SPLPROT	INT_VAR	stat = 0	value = 0	relation = 0	RET	new_row		BEGIN
	ACTION_IF	(stat > 278)	BEGIN	WARN	~SPLPROT.2DA - Stat out of Bounds.~	END
	ACTION_IF	((stat != 259) AND (stat != 260) AND (relation > 11))	BEGIN	WARN	~SPLPROT.2DA - Relation out of Bounds.~	END
	COPY_EXISTING ~SPLPROT.2DA~	OVERRIDE
		COUNT_2DA_COLS	cols
		COUNT_2DA_ROWS cols rows
		TEXT_SPRINT check_row ~~
		TEXT_SPRINT check_stat ~~
		SET new_row = 0
		FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
			PATCH_IF (~%check_stat%~ STRING_EQUAL ~%stat%~)	BEGIN	READ_2DA_ENTRY current_row 2 cols check_value
				PATCH_IF (~%check_value%~ STRING_EQUAL ~%value%~)	BEGIN	READ_2DA_ENTRY current_row 3 cols check_relation
					PATCH_IF (~%check_relation%~ STRING_EQUAL ~%relation%~)	BEGIN	new_row = current_row	current_row = rows	END
				END
			END
		END
		PATCH_IF (new_row = 0)	BEGIN
			FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
				PATCH_IF (~%check_stat%~ STRING_EQUAL ~*~)	BEGIN	new_row = current_row	current_row = rows	END
			END
			PATCH_IF (new_row = 0)	BEGIN	new_row = rows	INSERT_2DA_ROW rows cols ~%new_row%		   %stat%		   %value%		   %relation%~
			END	ELSE	BEGIN	SET_2DA_ENTRY new_row 1 cols ~%stat%~	SET_2DA_ENTRY new_row 2 cols ~%value%~	SET_2DA_ENTRY new_row 3 cols ~%relation%~	END
		END
	BUT_ONLY
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	STR_EXTRA_1_75	BEGIN
	~STR_EXTRA_1_75~		=>	37
END
ACTION_PHP_EACH	STR_EXTRA_1_75 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 1	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 76	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	STR_EXTRA_76_90	BEGIN
	~STR_EXTRA_76_90~		=>	37
END
ACTION_PHP_EACH	STR_EXTRA_76_90 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 76	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 91	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	STR_EXTRA_91_99	BEGIN
	~STR_EXTRA_91_99~		=>	37
END
ACTION_PHP_EACH	STR_EXTRA_91_99 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 91	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 99	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

COPY_EXISTING ~C0DRED0C.SPL~ OVERRIDE
SAY NAME1 ~势不可挡~

ADD_PROJECTILE ~%MOD_FOLDER%/Fighter/Dreadnought/spells/c0dredp1.PRO~ ~无畏旋风~
ADD_PROJECTILE ~%MOD_FOLDER%/Fighter/Dreadnought/spells/c0dredp2.PRO~ ~无畏碎击~
ADD_PROJECTILE ~%MOD_FOLDER%/Fighter/Dreadnought/spells/c0dredp3.PRO~ ~无畏震地~

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~猛攻姿态~) STR_VAR bam_file = c0dred3i RET c0dred3i = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~裂地一击~) STR_VAR bam_file = c0dred5i RET c0dred5i = icon END

COPY_EXISTING ~C0DREDC.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 1 parameter2 = C0HTSTR END

COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE~
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = c0dredp1
END
  LPF ALTER_SPELL_HEADER
	INT_VAR
		header = 1
		projectile = 1
END
  LPF ALTER_SPELL_HEADER
	INT_VAR
		header = 2
		projectile = 1
END

COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC2.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDCA.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 2 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 1) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDCB.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 3 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 1) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDCC.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 4 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 2) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDCD.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 5 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 2) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDCE.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 6 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 3) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC4.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 7 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 3) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC5.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 8 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 4) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC6.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 9 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 4) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC7.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 5) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC8.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 11 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 5) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC9.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 12 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 6) END
COPY_EXISTING ~C0DREDC1.SPL~ ~OVERRIDE/C0DREDC0.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 14 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 7) END

COPY_EXISTING ~C0DREDC3.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0HTSTREXTRA_EQUAL STR_VAR match_resource = C0DREDCA END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = STR_EXTRA_1_75 STR_VAR match_resource = C0DREDCB END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = STR_EXTRA_76_90 STR_VAR match_resource = C0DREDCC END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = STR_EXTRA_91_99 STR_VAR match_resource = C0DREDCD END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0HTSTREXTRA_EQUAL STR_VAR match_resource = C0DREDCE END

COPY_EXISTING ~C0DRED3.SPL~ OVERRIDE
SAY NAME1 ~猛攻姿态~
SAY UNIDENTIFIED_DESC ~猛攻姿态
无畏战士将每回合基础攻击次数减半，但挥砍、穿刺与钝击伤害提升+120%。~

COPY_EXISTING ~C0DRED3A.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Heavy Assault Stance Active~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0dred3i END

COPY_EXISTING ~C0DRED3C.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Heavy Assault Stance Inactive~) END

COPY_EXISTING ~C0DRED4.SPL~ OVERRIDE
SAY NAME1 ~全力进攻~
SAY UNIDENTIFIED_DESC ~全力进攻
接下来的三回合内，无畏战士将全身力量灌注于每一击，获得加速术效果，近战物理伤害提升+100%，期间每次攻击都造成最大伤害。但同一时间内，其护甲等级承受-6减值，钝击、穿刺与挥砍伤害抗性承受-50%减值，技能结束后还会承受严重的疲劳惩罚。此外，持续期间无畏战士无法施法、使用物品或游荡者技能。该技能无法与「坚韧」同时激活。~

COPY_EXISTING ~C0DRED5.SPL~ OVERRIDE
SAY NAME1 ~裂地一击~
SAY UNIDENTIFIED_DESC ~裂地一击
无畏战士挥出重击破地，连战场本身都会受其冲击。接下来两回合内的下一次攻击将自动判定为重击，并对自身前方10英尺直线上的次要目标触发重击强化效果，将除主目标外的所有生物略微击退。此外，重击的冲击会在原地留下一片半径10英尺的区域，持续五回合；除无畏战士自身外，站在区域内的所有生物敏捷属性与移动速率都会减半。~

COPY_EXISTING ~C0DRED5B.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = c0dredp2
END
COPY_EXISTING ~C0DRED5C.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = c0dredp3
END
COPY_EXISTING ~C0DRED5D.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 1 parameter2 = C0HTSTR END

COPY_EXISTING ~C0DRED5X.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0dred5i END

COPY_EXISTING ~C0DRED5Y.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0dred5i END

COPY_EXISTING ~C0DRED5Z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0dred5i END

COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED52.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 1 END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED5F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 2 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 1) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED5G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 3 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 1) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED5H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 4 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 2) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED5I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 5 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 2) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED5J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 6 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 3) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED54.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 7 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 3) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED55.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 8 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 4) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED56.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 9 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 4) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED57.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 5) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED58.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 11 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 5) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED59.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 12 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 6) END
COPY_EXISTING ~C0DRED51.SPL~ ~OVERRIDE/C0DRED50.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 14 END
LPF ALTER_EFFECT INT_VAR match_savingthrow = 4 savebonus = (0 - 7) END

COPY_EXISTING ~C0DRED53.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0HTSTREXTRA_EQUAL STR_VAR match_resource = C0DRED5F END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = STR_EXTRA_1_75 STR_VAR match_resource = C0DRED5G END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = STR_EXTRA_76_90 STR_VAR match_resource = C0DRED5H END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = STR_EXTRA_91_99 STR_VAR match_resource = C0DRED5I END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0HTSTREXTRA_EQUAL STR_VAR match_resource = C0DRED5J END

COPY_EXISTING ~C0DREDH1.SPL~ OVERRIDE
SAY NAME1 ~专注攻击~
SAY UNIDENTIFIED_DESC ~全力进攻激活期间，无畏战士的近战重击调整值获得+5加值。~

COPY_EXISTING ~C0DREDH2.SPL~ OVERRIDE
SAY NAME1 ~主宰之势~
SAY UNIDENTIFIED_DESC ~使用全力进攻时，无畏战士将化为纯粹的毁灭机器，近战攻击可直接斩杀生命值低于60点的敌人。此外，全力进攻期间的惩罚减半：护甲等级减值降至-3，伤害抗性减值降至-25%。不仅如此，无畏战士将永久免疫疲劳。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ BEGIN

COPY_EXISTING ~C0DREADN.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // POWER ATTACK
  // LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
  // LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
  // LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = AP_C0FIG04 END // SPECIALIZATION
  // LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0FIG03 END // IMPROVED INITIATIVE
  PRETTY_PRINT_2DA

	END