COPY ~%MOD_FOLDER%/Fighter/DwarvenDefender/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/DwarvenDefender/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/CLABFI06.2DA~
	REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0DWD00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPDWD02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = GA_SPDWD02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 20 f_Increment = 5 STR_VAR f_Entry = AP_SPDWD01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0DWD01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0DWD02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0DWD04 END

 	PRETTY_PRINT_2DA

INCLUDE ~%MOD_FOLDER%/effects/fortitude.tpa~

OUTER_SPRINT kit_description ~矮人防御者：矮人防御者是令人敬畏的战士，相传其战力堪比两名其他种族的士兵。他们受过精深的矮人战技训练，寥寥数名这般强壮的战士便可构筑出几乎牢不可破的防线。

职业优势：
–免疫震慑与移位效果。
–每5级获得5%钝击、挥砍、穿刺与远程伤害抗性，20级时达到最高20%。
–坚毅：矮人防御者每次受到伤害时恢复1点生命值。
–每日可使用防御姿态。1级时获得1次使用次数，4级时再获得1次，之后每4级增加1次使用次数。

防御姿态：矮人防御者摆出防御架势，准备承受朝向自己的所有攻击，在1回合内根据自身等级获得多种增益。从1级开始，矮人防御者获得+2护甲等级与豁免检定，所有伤害抗性20%，有效个人空间翻倍，可在更大范围内阻挡敌人通行，但姿态持续期间移动速度减半，且无法造成重击。随等级提升的额外增益如下：
  5级：护甲等级与豁免检定加成提升至+3。
  8级：伤害抗性提升至35%。
  11级：护甲等级与豁免检定加成提升至+4。
  14级：对来袭的近战攻击者造成4d6+4点非致命反弹伤害。
  18级：护甲等级与豁免检定加成提升至+6，伤害抗性提升至50%。
  
–可使用盾击模式技能。

盾击：矮人防御者在对每个目标的首次近战攻击中用盾牌猛撞目标，使其失去平衡并陷入眩晕，额外造成1d10点钝击伤害，降低目标2点护甲等级；若目标未通过吐息豁免（每5级豁免检定减值-1），则暂时无法行动，持续1轮。矮人防御者每2轮只能对单个目标尝试一次盾击。

盾击激活期间，矮人防御者的每回合攻击次数减半，近战伤害降低2点。
  
–20级：不屈：矮人防御者永久获得10%几率抵消来袭伤害。

–生命骰：d12
  
职业限制：KIT_DISADV_1
–斧和战锤的熟练程度无法超过宗师水平（四星）。
–其他所有武器的熟练程度都无法超过精通（两星）。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

COPY_EXISTING ~C0FIG01.SPL~ ~OVERRIDE/C0DWD01.SPL~
LPF DELETE_SPELL_HEADER INT_VAR min_level = 14 END
SAY NAME1 ~猛力攻击~
SAY UNIDENTIFIED_DESC ~猛力攻击
战士放弃命中精度以换取更沉重、更具杀伤力的打击，牺牲3点近战THAC0来提升3点近战伤害。战士必须拥有17点及以上力量才能激活此技能。~

COPY_EXISTING ~C0FIG02.SPL~ ~OVERRIDE/C0DWD02.SPL~
LPF DELETE_SPELL_HEADER INT_VAR min_level = 14 END
SAY NAME1 ~寓守于攻~
SAY UNIDENTIFIED_DESC ~寓守于攻
战士以命中精度为代价专注于防御，牺牲3点THAC0来提升3点护甲等级。战士必须拥有15点及以上智力才能激活此技能。~

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用精通猛力攻击与精通寓守于攻。
–无法使用速射。
–16级时无法获得全武器专精。
–无法获得精通先攻。~

END

END ELSE BEGIN

COPY_EXISTING ~CLABFI06.2DA~ OVERRIDE
REPLACE_TEXTUALLY ~GA_C0DWD01~ ~****     ~
REPLACE_TEXTUALLY ~GA_C0DWD02~ ~****     ~
REPLACE_TEXTUALLY ~GA_C0FIG03~ ~****     ~

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~DWARVEN_DEFENDER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~盾击~) STR_VAR bam_file = c0dwd03i RET c0dwd03i = icon END

COPY_EXISTING ~SPDWD02.SPL~ OVERRIDE
SAY NAME1 ~防御姿态~
SAY UNIDENTIFIED_DESC ~防御姿态
使用者摆出防御架势，准备承受朝向自己的所有攻击，在1回合内根据自身等级获得多种增益。从1级开始，使用者获得+2护甲等级与豁免检定，所有伤害抗性20%，有效个人空间翻倍，可在更大范围内阻挡敌人通行，但姿态持续期间移动速度减半，且无法造成重击。随等级提升的额外增益如下：
  5级：护甲等级与豁免检定加成提升至+3。
  8级：伤害抗性提升至35%。
  11级：护甲等级与豁免检定加成提升至+4。
  14级：对来袭的近战攻击者造成4d6+4点非致命反弹伤害。
  18级：护甲等级与豁免检定加成提升至+6，伤害抗性提升至50%。~

COPY_EXISTING ~C0DWD03.SPL~ OVERRIDE
SAY NAME1 ~盾击~
SAY UNIDENTIFIED_DESC ~盾击
使用者在对每个目标的首次近战攻击中用盾牌猛撞目标，使其失去平衡并陷入眩晕，额外造成1d10点钝击伤害，降低目标2点护甲等级；若目标未通过吐息豁免（每5级豁免检定减值-1），则暂时无法行动，持续1轮。使用者每2轮只能对单个目标尝试一次盾击。

盾击激活期间，使用者的每回合攻击次数减半，近战伤害降低2点。~

COPY_EXISTING ~C0DWD03a.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0dwd03i END
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~盾击激活~) END

COPY_EXISTING ~C0DWD03b.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~盾击成功~) END

COPY_EXISTING ~C0DWD03c.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~眩晕~) END

COPY_EXISTING ~C0DWD03z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~盾击未激活~) END

COPY_EXISTING ~C0DWD04b.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~不屈效果抵消来袭伤害~)
END

OUTER_SPRINT kit_description ~先锋：先锋是受训于敌阵之中作战的前线战士。他们强壮坚韧，是可靠的防御者，足以守住阵线，承受足以击倒常人的打击。

职业优势：
–免疫震慑与移位效果。
–每5级获得5%钝击、挥砍、穿刺与远程伤害抗性，20级时达到最高20%。
–坚毅：先锋每次受到伤害时恢复1点生命值。
–每日可使用防御姿态。1级时获得1次使用次数，4级时再获得1次，之后每4级增加1次使用次数。

防御姿态：先锋摆出防御架势，准备承受朝向自己的所有攻击，在1回合内根据自身等级获得多种增益。从1级开始，先锋获得+2护甲等级与豁免检定，所有伤害抗性20%，有效个人空间翻倍，可在更大范围内阻挡敌人通行，但姿态持续期间移动速度减半，且无法造成重击。随等级提升的额外增益如下：
  5级：护甲等级与豁免检定加成提升至+3。
  8级：伤害抗性提升至35%。
  11级：护甲等级与豁免检定加成提升至+4。
  14级：对来袭的近战攻击者造成4d6+4点非致命反弹伤害。
  18级：护甲等级与豁免检定加成提升至+6，伤害抗性提升至50%。
  
–可使用盾击模式技能。

盾击：先锋在对每个目标的首次近战攻击中用盾牌猛撞目标，使其失去平衡并陷入眩晕，每2级额外造成1d4点钝击伤害，降低目标2点护甲等级；若目标未通过吐息豁免（每5级豁免检定减值-1），则暂时无法行动，持续1轮。先锋每2轮只能对单个目标尝试一次盾击。

盾击激活期间，先锋的每回合攻击次数减半，近战伤害降低2点。
  
–20级：不屈：先锋永久获得10%几率抵消来袭伤害。

–生命骰：d12

职业限制：KIT_DISADV_1
–单手近战武器的熟练度最高只能达到武器大师（4点）。
–其他武器的熟练度最高只能达到武器专精（2点）。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用精通猛力攻击与精通寓守于攻。
–无法使用速射。
–16级时无法获得全武器专精。
–无法获得精通先攻。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~先锋~)
	
    lower         = RESOLVE_STR_REF(~先锋~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~先锋：先锋是受训于敌阵之中作战的前线战士。他们强壮坚韧，是可靠的防御者，足以守住阵线，承受足以击倒常人的打击。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0VNGD~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~4 4 2 2 4 4 4 2 4 4 4 4 2 4 4 4 4 4 2 2 4 4 2 2 2 2 2 2 2 2 2 3~
	
    abclasrq      = ~12 9 16 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~FI4~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/CLABFI06.2da~
	
    kittable      = ~K_F_H K_F_E K_F_HE K_F_G K_F_HL K_F_HO~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END