COPY ~%MOD_FOLDER%/MultiKit/Eldritch_Knight/2das~ ~override~
COPY ~%MOD_FOLDER%/MultiKit/Eldritch_Knight/spells~ ~override~

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 7
	
    mixed         = RESOLVE_STR_REF(~奥法骑士~)
	
    lower         = RESOLVE_STR_REF(~奥法骑士~)
	
    help          = RESOLVE_STR_REF(~奥法骑士：兼修武道与奥术，造诣不相上下，是攻守兼备的多面战士。既能向敌人轰出火球术，也能拔剑冲锋。奥法骑士引以为傲的是，总能因敌制宜：对阵肉身强悍的敌人便用法术，对阵施法者便以兵刃相向。他们将时间平分在体能训练与奥术研习之间，前者让他们成为更优秀的战士，后者让他们学会更强的法术。奥法骑士往往都是坚毅执着之人——要同时精进施法与战技，需要付出海量的时间与心血。

职业优势：
–任意近战武器均可修习至宗师级（3点熟练槽）。
–护甲施法：奥法骑士身着至多钉皮甲时仍可施法。
–战斗施法：奥法骑士擅长在激战中施法。5尺范围内有敌人时，施法速度+2。
–3级：每日可使用一次「奥术打击」能力。6、9、12、15级各额外获得一次使用次数。

奥术打击：奥法骑士为<PRO_HISHER>下一次成功的攻击注入魔力，削弱目标对自身法术的抗性，使其豁免检定-2，魔法抗性降低25%，持续3回合。同一目标身上该效果不可叠加。

–6级：奥术打击的豁免惩罚提升至-3，魔法抗性降低50%。
–8级：每日可施展两次「任意门」。

任意门：本法术将施法者传送至视野范围内的任意地点。施法时，施法者面前会开启一道次元传送门，随即跨步而入。穿过传送门后，<PRO_HIMHER>便会出现在<PRO_HISHER>选定的目的地。

–10级：战地施法：奥法骑士身着任意护甲时均可施法。
–12级：奥术打击的豁免惩罚提升至-4，魔法抗性降低100%。
–14级：精通战斗施法：施法速度加成提升至4。

职业限制：
–所有远程武器仅能达到熟练级。
–超出战斗施法范围时，施法速度受-1惩罚。
–从2环起，每个法术等级的首个法术，学习进度比普通法师晚1级。~)
	
    briefdesc     = RESOLVE_STR_REF(~奥法骑士：兼修武道与奥术，造诣不相上下，是攻守兼备的多面战士。既能向敌人轰出火球术，也能拔剑冲锋。奥法骑士引以为傲的是，总能因敌制宜：对阵肉身强悍的敌人便用法术，对阵施法者便以兵刃相向。他们将时间平分在体能训练与奥术研习之间，前者让他们成为更优秀的战士，后者让他们学会更强的法术。奥法骑士往往都是坚毅执着之人——要同时精进施法与战技，需要付出海量的时间与心血。~)
	
	// fallen = 0
	
    suppress_warnings     = 1
	
  STR_VAR
    kit_name      = ~C0EK~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~3 3 3 3 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 2 2 2 3~
	
    abclasrq      = ~9 9 0 12 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 0 0 0~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    // clab_path     = ~override/C0EK.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = F
	
	clab_base_f = C0EK
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	clab_base_m = C0EK2
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    clascolr = ~96 50 47 1 3~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~奥术打击~) STR_VAR bam_file = c0ek2ic RET c0ek2ic = icon END

INCLUDE ~%MOD_FOLDER%/effects/combat_casting.tpa~

COPY_EXISTING ~C0EK.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0EKCC END // COMBAT CASTING
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 f_MaxLevel = 14 STR_VAR f_Entry = AP_C0EKCC2 END // IMPROVED COMBAT CASTING
  PRETTY_PRINT_2DA

COPY_EXISTING ~C0EKCC1A.SPL~ OVERRIDE
  LPF CLONE_EFFECT INT_VAR match_opcode = 189 opcode = 177 parameter2 = 9 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0EK~) STR_VAR resource = C0EKCC3 END

COPY_EXISTING ~C0EKCC1B.SPL~ OVERRIDE
  LPF CLONE_EFFECT INT_VAR match_opcode = 189 opcode = 177 parameter2 = 9 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0EK~) STR_VAR resource = C0EKCC3 END

COPY ~%MOD_FOLDER%/MultiKit/Eldritch_Knight/spells/c0eknam.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 290 parameter1 = RESOLVE_STR_REF (~奥法骑士~) END

COPY ~%MOD_FOLDER%/MultiKit/Eldritch_Knight/spells/c0ek2.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ek2ic END
SAY NAME1 ~奥术打击~
SAY UNIDENTIFIED_DESC ~奥术打击
奥法骑士为<PRO_HISHER>下一次成功的攻击注入魔力，削弱目标对自身法术的抗性，使其豁免检定-2，魔法抗性降低25%，持续3回合。~

COPY ~%MOD_FOLDER%/MultiKit/Eldritch_Knight/spells/c0ek2a.spl~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~豁免与魔法抗性已降低~) END

COPY ~%MOD_FOLDER%/MultiKit/Eldritch_Knight/spells/c0ek3.spl~ ~override~
SAY NAME1 ~任意门~
SAY UNIDENTIFIED_DESC ~任意门
（变化系）

等级：4
范围：自身
持续时间：即时
施法时间：1
影响区域：施法者
豁免检定：无

本法术将施法者传送至视野范围内的任意地点。施法时，施法者面前会开启一道次元传送门，随即跨步而入。穿过传送门后，<PRO_HIMHER>便会出现在<PRO_HISHER>选定的目的地。~

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x1F bard //reads the byte containing the fighter usability flag
    PATCH_IF ((bard BAND 0b01000000) = 0b00000000) BEGIN // if it is usable by bards
      READ_SHORT    0x1C type //reads the byte containing item type
	  READ_SHORT    0x22 appearance //reads the byte containing item appearance
      PATCH_IF (type = 2) AND (appearance = 16690) BEGIN // if it is leather armor
		LPF ALTER_EFFECT
			INT_VAR
				match_opcode = 145
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 0
				parameter2 = 2
				timing = 2
				insert_point = (0 - 1)
			STR_VAR
				resource = C0ARCAS1
		END
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0EK~)
				parameter2 = 9
				timing = 2
			STR_VAR
				resource = C0ARCAS3
		END
      END
      PATCH_IF (type = 2) AND (appearance = 16691) OR (appearance = 16692) BEGIN // if it is leather armor
		LPF ALTER_EFFECT
			INT_VAR
				match_opcode = 145
				silent = 1
				opcode = 177
				target = 1
				parameter1 = 0
				parameter2 = 2
				timing = 2
				insert_point = (0 - 1)
			STR_VAR
				resource = C0ARCAS2
		END
		LPF ADD_ITEM_EQEFFECT
			INT_VAR
				silent = 1
				opcode = 177
				target = 1
				parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0EK~)
				parameter2 = 9
				dicesize = 10
				timing = 2
			STR_VAR
				resource = C0ARCAS4
		END
      END
    END
  END
BUT_ONLY_IF_IT_CHANGES