COPY ~%MOD_FOLDER%/Druid/Elementalist/2da~ ~override~
COPY ~%MOD_FOLDER%/Druid/Elementalist/spells~ ~override~

COPY_EXISTING ~CLABDR01.2DA~ ~OVERRIDE/C0ELEM.2DA~
  REPLACE_TEXTUALLY ~GA_SPCL107~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL101~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL108~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL112~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL113~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL114~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL611~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL612~ ~**** ~
  REPLACE_TEXTUALLY ~GA_SPCL613~ ~**** ~
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0EL#02 END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0EL#01  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL103 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL115  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL117  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL204  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL211  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL217  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL320 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL327  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL304  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL308  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL319  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL404  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL418  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL432  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL512  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL503  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL523  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL517  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL614  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL615  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL628  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL702  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL724  END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0EL712  END

  PRETTY_PRINT_2DA

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 11
	
    mixed         = RESOLVE_STR_REF(~元素使~)
	
    lower         = RESOLVE_STR_REF(~元素使~)
	
    help          = RESOLVE_STR_REF(~元素使：元素使德鲁伊专精于自然的本源能量，得以凭借超凡的技艺驾驭四大元素。
	
职业优势：
–对强酸、寒冷、电击与火焰伤害获得+20%抗性。
–造成的强酸、寒冷、电击与火焰伤害提升+20%。
–施展奥术版的防护火焰、防护寒冷、防护电击、防护强酸与元素防护时，施法距离增加，且施法时间缩短为1。
–从1环到7环，每个法术环级都将有3个奥术法术加入<PRO_HISHER>的法术列表，具体如下：
  1环：燃烧之手、寒冷之触、电击掌
  2环：阿加纳扎的灼烧术、麦夫的酸箭、斯诺洛克的雪球群
  3环：火球术、冰枪术、闪电束
  4环：火焰护盾（红色）、冰风暴、强酸法球
  5环：寒冰锥、防护强酸、阳炎术
  6环：连锁闪电、死亡之雾、奥提路克的冷冻球
  7环：酸雨风暴、延迟爆焰火球、元素防护
  
职业限制：
–无法穿戴任何护甲。
–无法施展动物领域与非元素召唤领域的任何法术。
–无法变形为任何动物形态。~)
	
    briefdesc     = RESOLVE_STR_REF(~元素使：元素使德鲁伊专精于自然的本源能量，得以凭借超凡的技艺驾驭四大元素。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0ELEM~
	
    unusable      = ~0x10000000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1~
	
    // abclasrq      = ~0 15 0 14 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0ELEM.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~SPWI103.spl~ ~override/C0EL103.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI115.spl~ ~override/C0EL115.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI117.spl~ ~override/C0EL117.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI211.spl~ ~override/C0EL211.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI217.spl~ ~override/C0EL217.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI304.spl~ ~override/C0EL304.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI308.spl~ ~override/C0EL308.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI319.spl~ ~override/C0EL319.spl~
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 range = 30 END
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI320.spl~ ~override/C0EL320.spl~
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 range = 30 END
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI404.spl~ ~override/C0EL404.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI418.spl~ ~override/C0EL418.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI503.spl~ ~override/C0EL503.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI512.spl~ ~override/C0EL512.spl~
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 range = 30 END
WRITE_SHORT 0x1C 2 
WRITE_SHORT 0x34 4 
SAY UNIDENTIFIED_DESC ~防护电击
（防护系）

环级：4
射程：触碰
持续时间：每等级1回合
施法时间：5
影响区域：1个生物
豁免检定：无

施展本法术后，目标将完全免疫所有电击伤害，无论其来源是魔法还是非魔法，例如闪电束或是某些生物的喷吐武器。该效果持续至法术结束或被解除为止。~
COPY_EXISTING ~SPWI517.spl~ ~override/C0EL517.spl~
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 range = 30 END
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI523.spl~ ~override/C0EL523.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI614.spl~ ~override/C0EL614.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI615.spl~ ~override/C0EL615.spl~
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI702.spl~ ~override/C0EL702.spl~
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
WRITE_SHORT 0x1C 2 
COPY_EXISTING ~SPWI712.spl~ ~override/C0EL712.spl~
WRITE_SHORT 0x1C 2 

// SNILLOC'S SNOWBALL SWARM

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPWI204.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/snilloc~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/snilloc/IDPRO217.PRO~
COPY_EXISTING ~C0EL204.SPL~ ~override~
LPF ALTER_SPELL_HEADER INT_VAR projectile = IDPRO217 END
WRITE_SHORT 0x1C 2 
SAY NAME1 ~斯诺洛克的雪球群~
SAY UNIDENTIFIED_DESC ~斯诺洛克的雪球群
（塑能系）

环级：2
射程：施法者视野范围
持续时间：即时
施法时间：2
影响区域：半径15英尺
豁免检定：减半

本法术会在射程内的指定点引爆一阵漫天雪球。范围内的所有目标都会受到撞击，每施法者等级造成1d3点寒冷伤害，8级时达到上限8d3点。针对操纵火焰或栖身火焰的生物，每等级造成1d6点寒冷伤害，8级时达到上限8d6点。~
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI204.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI204.spl~ ~override/C0EL204.spl~
WRITE_SHORT 0x1C 2 
END

// ICELANCE

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPWI327.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/icelance~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/icelance/IDPRO251.PRO~
COPY_EXISTING ~C0EL327.SPL~ ~override~
LPF ALTER_SPELL_HEADER INT_VAR projectile = IDPRO251 END
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~Stunned~) END
WRITE_SHORT 0x1C 2 
SAY NAME1 ~冰枪术~
SAY UNIDENTIFIED_DESC ~冰枪术
（塑能系）

环级：3
射程：施法者视野范围
持续时间：即时
施法时间：3
影响区域：1个生物
豁免检定：特殊

本法术会向施法者选定的目标射出一支魔法冰枪。冰枪必定命中，造成5d6点寒冷伤害，并迫使目标进行法术豁免检定，失败则陷入震慑状态，持续3轮。~
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI327.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI327.spl~ ~override/C0EL327.spl~
WRITE_SHORT 0x1C 2 
END

// VITRIOLIC SPHERE

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPWI432.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/vitriolic~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/vitriolic/IDPRO316.PRO~
COPY_EXISTING ~C0EL432.SPL~ ~override~
LPF ALTER_SPELL_HEADER INT_VAR projectile = IDPRO316 END
WRITE_SHORT 0x1C 2 
SAY NAME1 ~强酸法球~
SAY UNIDENTIFIED_DESC ~强酸法球
（咒法系）

环级：4
射程：施法者视野范围
持续时间：特殊
施法时间：4
影响区域：半径5英尺
豁免检定：特殊

本法术会召唤出一颗散发翠绿光芒的酸球，施法者可操控它攻击射程内的任意目标。酸球命中目标后会炸裂，将强效酸液泼洒在目标身上。目标每受到1d4点强酸伤害，最高不超过12d4点。初次伤害过后，目标需进行法术豁免检定以避免持续伤害。若豁免失败，目标将在后续回合继续受到强酸伤害，每回合伤害骰数减少2颗。例如，一名8级法师在首回合造成8d4点伤害，第二回合6d4，第三回合4d4，第四回合2d4，法术在第五回合结束。首回合之后的每一轮，目标都可以进行一次法术豁免检定来终止该回合的伤害。

强酸法球还会在主目标周围半径5英尺范围内溅洒酸液。飞溅范围内的所有生物都需进行石化/变形豁免检定，失败则受到溅射伤害，每5个施法者等级造成1d4点伤害。溅射伤害不会产生持续效果。~
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI432.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI432.spl~ ~override/C0EL432.spl~
WRITE_SHORT 0x1C 2 
END

// OTILUKE'S FREEZING SPHERE

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPWI628.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/otiluke~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/otiluke/IDPRO269.PRO~
COPY_EXISTING ~C0EL628.SPL~ ~override~
LPF ALTER_SPELL_HEADER INT_VAR projectile = IDPRO269 END
WRITE_SHORT 0x1C 2 
SAY NAME1 ~奥提路克的冷冻球~
SAY UNIDENTIFIED_DESC ~奥提路克的冷冻球
（变化系、塑能系）

环级：6
射程：施法者视野范围
持续时间：即时
施法时间：6
影响区域：1个生物
豁免检定：无效

本法术向目标射出一颗寒冷能量球，每施法者等级造成1d4+2点寒冷伤害。但若目标成功通过法术豁免检定，则表示其躲开了法球，完全不受伤害。~
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI628.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI628.spl~ ~override/C0EL628.spl~
WRITE_SHORT 0x1C 2 
END

// ACID STORM

ACTION_IF NOT FILE_EXISTS_IN_GAME ~SPWI724.SPL~ THEN BEGIN
COPY ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/acidstorm~ ~override~
ADD_PROJECTILE ~%MOD_FOLDER%/Druid/Elementalist/iwdspells/acidstorm/IDPRO211.PRO~
COPY_EXISTING ~C0EL724.SPL~ ~override~
LPF ALTER_SPELL_HEADER INT_VAR projectile = IDPRO211 END
WRITE_SHORT 0x1C 2 
SAY NAME1 ~酸雨风暴~
SAY UNIDENTIFIED_DESC ~酸雨风暴
（塑能系）

环级：7
射程：施法者视野范围
持续时间：每等级1轮
施法时间：7
影响区域：半径12英尺
豁免检定：减半

本法术会在影响区域降下腐蚀性酸雨，前三轮每回合造成1d4点强酸伤害，接下来三轮每回合1d6点，之后每回合1d8点。离开影响区域并不能终止伤害——酸液会黏附在皮肤上，所有在法术施放时身处范围内的生物，在法术持续时间内都会持续受到强酸伤害。生物在被酸云笼罩后每回合可进行一次法术豁免检定，成功则该回合只受到半数伤害。~
END

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI724.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI724.spl~ ~override/C0EL724.spl~
WRITE_SHORT 0x1C 2 
END
