INCLUDE ~ArtisansKitpack/lib/thac0.tpa~

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 19
	
    mixed         = RESOLVE_STR_REF(~启迪之拳~)
	
    lower         = RESOLVE_STR_REF(~启迪之拳~)
	
    help          = RESOLVE_STR_REF(~启迪之拳：并非所有武僧都只追求心性圆满而摒弃其他学识。有些武僧将严谨的术业修行与武道、体魄修炼相结合，对他们而言，这份修行还包括研习魔法，并将诸多奥术技艺融入徒手格斗的招式之中。这些“启迪之拳”精通接触类法术，开创出全新的战斗方式——拳锋兼具迅疾之势、千钧之力与魔法威能。

职业优势：
–零级命中值（THAC0）成长等同于同等级牧师。
–移动速度比其他角色快2点，每提升5级，移动速度再额外增加1点。
–每轮可进行2次徒手攻击；9级与18级时，每轮额外增加半次攻击。
–启迪之拳的双拳蕴含威能，造成粉碎伤害，伤害随等级提升：
  1-4级：1d4
  5-8级：1d6
  9-12级：1d8
  13-16级：1d10
  17-20级：1d12
  21级及以上：2d8
  
–气：启迪之拳的徒手攻击灌注了“气”的力量。4级起视为+1附魔魔法武器，8级+2，12级+3，16级+4，20级+5；7级起，攻击同时视为银质武器。
–智慧属性每超出12点1点，基础护甲等级（AC）获得+1加值；7级起额外获得+1AC，之后每提升7级再增加1点。
–可使用查找陷阱、识破幻象、潜行技能。
–疾风连击：徒手或手持匕首时，每轮首次攻击可额外追加一次攻击，但所有攻击的THAC0承受-5惩罚。该额外攻击不受每轮攻击次数上限限制，可随时开启/关闭。13级时，THAC0惩罚降低至-2。
–获得被动效果「奥术之拳」。

奥术之拳：启迪之拳精通接触类法术，可将任何以接触为生效方式的奥术法术（例如寒冷之触、电击爪）的效果，附加在自身的常规近战攻击中。

–每日可使用「震慑拳」1次。1级时获得1次使用次数，之后每提升6级增加1次。

震慑拳：启迪之拳牺牲4点THAC0与伤害，在接下来10秒内的下一次成功命中时生效。目标受击后必须进行死亡豁免（智慧每高于14点，豁免获得-1调整值），失败则震慑3轮。

–5级：可使用「能量之拳」能力。

能量之拳：可选择消耗1次震慑拳的使用次数，改为在接下来10秒内，攻击附带1d8电击伤害与1d8魔法火焰伤害。10级时两种伤害均提升至2d8，18级时提升至3d8。

–10级：每日可使用「通体回春」1次。

通体回春：立即恢复相当于自身等级×3的生命值。

–14级：金刚魂：获得基础10%魔法抗性，每等级额外提升2%，20级时达到最高50%。
–18级：内视之眼：徒手状态下免疫重击。

职业限制：
–每日每等级可施展的法术数量减少1个。
–仅可选择守序阵营。
–仅可选人类、半精灵或半兽人种族。
–手持任何武器时，THAC0承受-6惩罚。~)
	
    briefdesc     = RESOLVE_STR_REF(~启迪之拳：并非所有武僧都只追求心性圆满而摒弃其他学识。有些武僧将严谨的术业修行与武道、体魄修炼相结合，将奥术技艺融入徒手格斗，以拳锋承载魔法威能。~)
  STR_VAR
    kit_name      = ~C0_ENLIGHTENED_FIST~
	
    // unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0~
	
    abclasrq      = ~0 9 0 9 12 9~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 0 0 0~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~1 1 1 0 0 0 0 0 0~
	
    dualclas      = ~0 0 0 0 0 0~
	
    luabbr        = ~C0EFM~
	
    // stweap        = ~CLCK13 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0EFN.2da~
	
    kittable      = ~K_S_H K_S_HE K_S_HO~
	
	// base_class = F
	
	// clab_base_f = ~C0AA~
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPROG~
	
    numwslot      = ~3~
	
	// METAL, MINOR, MAJOR, LEATHER, ARMOR
	clascolr = ~192 63 142 83 110~ 
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~0 0 100 100 100 100 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl
	
	// traplimt = ~6~
	
    // bdstweap      = ~CLCK12 * * * RING06 * * * * BRAC02 BELT04 * BULL02,40 * POTN08,5 POTN17,3 POTN24,1 SLNG02 DAGG05,40 STAF02~
  RET
    kit_id
END

COPY_EXISTING ~LUMA0.2da~ ~override/LUC0EFM.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL928~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL929~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL930~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0EFM1~ ability = ~GA_C0MN#H07~ num_allowed = 16 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0EFM2~ ability = ~GA_C0MN#H05~ num_allowed = 16 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0EFM3~ ability = ~AP_C0MN#H15~ num_allowed = 1 END	

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~奥术之拳~) STR_VAR bam_file = C0EFNSI RET C0EFNSI = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~能量之拳~) STR_VAR bam_file = C0EFN2I RET C0EFN2I = icon END

// WISDOM
APPEND ~splprot.2da~ ~C0HTWIS 39 -1 1~ UNLESS ~C0HTWIS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTWIS~ BEGIN
	    SET C0HTWIS = %row%
	  END
	PRETTY_PRINT_2DA
	END
	
COPY_EXISTING ~C0EFN1.SPL~ OVERRIDE
SAY NAME1 ~震慑拳~
SAY UNIDENTIFIED_DESC ~震慑拳
启迪之拳牺牲4点THAC0与伤害，在接下来10秒内的下一次成功命中时生效。目标受击后必须进行死亡豁免（智慧每高于14点，豁免获得-1调整值），失败则震慑3轮。~
	LPF ALTER_EFFECT
		INT_VAR
			match_opcode = 326
			match_special = 1000
			parameter2 = C0HTWIS
			silent = 1
	END

COPY_EXISTING ~C0EFN2.SPL~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0EFN2I END
SAY NAME1 ~能量之拳~
SAY UNIDENTIFIED_DESC ~能量之拳
启迪之拳可选择消耗1次震慑拳的使用次数，改为在接下来10秒内，攻击附带1d8电击伤害与1d8魔法火焰伤害。10级时两种伤害均提升至2d8，18级时提升至3d8。~

/// CHILL TOUCH

COPY_EXISTING ~SPWI117.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter2 = C0_KIT_CHECK parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_ENLIGHTENED_FIST~) STR_VAR resource = C0EFNS1 END

COPY_EXISTING ~C0EFNS1.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0EFNSI END

/// SHOCKING GRASP

COPY_EXISTING ~SPWI115.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter2 = C0_KIT_CHECK parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_ENLIGHTENED_FIST~) STR_VAR resource = C0EFNS2 END

COPY_EXISTING ~C0EFNS2.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0EFNSI END

/// GHOUL TOUCH

COPY_EXISTING ~SPWI218.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter2 = 109 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_ENLIGHTENED_FIST~) STR_VAR resource = C0EFNS3 END

COPY_EXISTING ~C0EFNS3.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0EFNSI END

/// LICH TOUCH

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI626.SPL~ THEN BEGIN
COPY_EXISTING ~SPWI626.SPL~ ~OVERRIDE~
LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter2 = 109 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_ENLIGHTENED_FIST~) STR_VAR resource = C0EFNS4 END
END

COPY_EXISTING ~C0EFNS4.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0EFNSI END

OUTER_SET enlightened_fist_ids = IDS_OF_SYMBOL (~kit~ ~C0_ENLIGHTENED_FIST~)
  
COPY ~%MOD_FOLDER%/lua/m_c0mnk2.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%enlightened_fist_ids%~~~~~ //"
  END