COPY ~%MOD_FOLDER%/Fighter/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/spells~ ~OVERRIDE~

ACTION_IF FILE_EXISTS_IN_GAME ~CLABFI01.2DA~ BEGIN
COPY_EXISTING ~CLABFI01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // POWER ATTACK
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG02 END // EXPERTISE
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = AP_C0FIG04 END // SPECIALIZATION
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0FIG03 END // IMPROVED INITIATIVE
  PRETTY_PRINT_2DA
BUT_ONLY
END

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 2) BEGIN
    // Set New Fighter Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Fighter kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "DWARVEN_DEFENDER")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // (IMPROVED) POWER ATTACK
        PRETTY_PRINT_2DA
      END
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "BERSERKER") OR
				("%kit_label%" STRING_EQUAL_CASE "DWARVEN_DEFENDER") OR
				("%kit_label%" STRING_EQUAL_CASE "BARBARIAN")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG02 END // (IMPROVED) EXPERTISE
        PRETTY_PRINT_2DA
      END
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "BERSERKER") OR
				("%kit_label%" STRING_EQUAL_CASE "KENSAI") OR
				("%kit_label%" STRING_EQUAL_CASE "DWARVEN_DEFENDER")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
		LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
        PRETTY_PRINT_2DA
      END
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "BERSERKER") OR
				("%kit_label%" STRING_EQUAL_CASE "WIZARDSLAYER") OR
				("%kit_label%" STRING_EQUAL_CASE "KENSAI") OR
				("%kit_label%" STRING_EQUAL_CASE "DWARVEN_DEFENDER") OR
				("%kit_label%" STRING_EQUAL_CASE "BARBARIAN")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 5 STR_VAR f_Entry = AP_C0FIG04 END // SPECIALIZATION
        PRETTY_PRINT_2DA
      END
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "BARBARIAN") OR
				("%kit_label%" STRING_EQUAL_CASE "DWARVEN_DEFENDER")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0FIG03 END // IMPROVED INITIATIVE
        PRETTY_PRINT_2DA
      END
	  
      BUT_ONLY
      END
    END
  END
  END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABFI01.2DA~ BEGIN
COPY_EXISTING ~CLABFI06.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DWD01 END // POWER ATTACK
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DWD02 END // EXPERTISE
  PRETTY_PRINT_2DA
BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//BERSERKER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "BERSERKER" BEGIN
          READ_2DA_ENTRY index 4 col_count berserker_desc
          SPRINT old_berserker ~－无法精通远程武器。~
          SPRINT new_berserker ~－无法使用寓守于攻与快速射击。
－16级时不会获得全武器专精。
－无法精通远程武器。~
          GET_STRREF %berserker_desc% berserker_text
          INNER_PATCH_SAVE berserker_text ~%berserker_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_berserker%~ ~%new_berserker%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%berserker_desc%~ ~%berserker_text%~
          END
		END
//WIZARDSLAYER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "WIZARD_SLAYER" BEGIN
          READ_2DA_ENTRY index 4 col_count wizardslayer_desc
          SPRINT old_wizardslayer ~职业限制：~
          SPRINT new_wizardslayer ~职业限制：
–16级时不会获得全武器专精。~
          GET_STRREF %wizardslayer_desc% wizardslayer_text
          INNER_PATCH_SAVE wizardslayer_text ~%wizardslayer_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_wizardslayer%~ ~%new_wizardslayer%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%wizardslayer_desc%~ ~%wizardslayer_text%~
          END
        END
//KENSAI
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "KENSAI" BEGIN
          READ_2DA_ENTRY index 4 col_count kensai_desc
          SPRINT old_kensai ~职业限制：~
          SPRINT new_kensai ~职业限制：
–无法使用快速射击。
–16级时不会获得全武器专精。~
          GET_STRREF %kensai_desc% kensai_text
          INNER_PATCH_SAVE kensai_text ~%kensai_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_kensai%~ ~%new_kensai%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%kensai_desc%~ ~%kensai_text%~
          END
        END
//DWARVEN_DEFENDER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "DWARVEN_DEFENDER" BEGIN
          READ_2DA_ENTRY index 4 col_count dwarvendefender_desc
          SPRINT old_dwarvendefender ~–种族必须是矮人~
          SPRINT new_dwarvendefender ~–种族必须是矮人
–无法使用精通猛力攻击与精通寓守于攻。
–无法使用快速射击。
–16级时不会获得全武器专精。
–不会获得精通先攻。~
          GET_STRREF %dwarvendefender_desc% dwarvendefender_text
          INNER_PATCH_SAVE dwarvendefender_text ~%dwarvendefender_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_dwarvendefender%~ ~%new_dwarvendefender%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%dwarvendefender_desc%~ ~%dwarvendefender_text%~
          END
        END

//BARBARIAN
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "BARBARIAN" BEGIN
          READ_2DA_ENTRY index 4 col_count barbarian_desc
          SPRINT old_barbarian ~－11级：获得10%的钝击、挥砍、穿刺和远程伤害抗性。在15级和19级时，各额外获得5%抗性。~
          SPRINT new_barbarian ~－5级：可使用猛力攻击模式能力。
		  
猛力攻击：野蛮人牺牲命中精度以换取更重的伤害，每轮近战命中降低3点，近战伤害提升3点。野蛮人力量需达到17点及以上才能激活此能力。

－6级：可使用快速射击模式能力。

快速射击：野蛮人每轮可额外进行一次远程攻击，但命中判定受到-4减值。

－11级：获得10%的钝击、挥砍、穿刺和远程伤害抗性。在15级和19级时，各额外获得5%抗性。
－12级：精通快速射击：快速射击激活时的命中减值降低至-2。
－14级：可使用精通猛力攻击，原能力的加成与减值均提升至6点。~

          GET_STRREF %barbarian_desc% barbarian_text
          INNER_PATCH_SAVE barbarian_text ~%barbarian_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_barbarian%~ ~%new_barbarian%~
            REPLACE_TEXTUALLY ~%old_barbarian_1%~ ~%new_barbarian_1%~
            REPLACE_TEXTUALLY ~%old_barbarian_2%~ ~%new_barbarian_2%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%barbarian_desc%~ ~%barbarian_text%~
          END
        END
		
      END
      BUT_ONLY
    END
  END
  
ACTION_FOR_EACH CLASSTEXT IN BGCLATXT CLASTEXT SODCLTXT BEGIN
ACTION_IF (FILE_EXISTS_IN_GAME ~%CLASSTEXT%.2da~) BEGIN
  COPY_EXISTING ~%CLASSTEXT%.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 0; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FIGHTER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (~战士：战士是战场的勇士、剑术<PRO_MANWOMAN>、军人与格斗者，凭借对武器与战术的掌握决定生死。无论何种战场，战士都身先士卒，与怪物和敌人正面交锋。通过严苛的训练与丰富的经验，战士可在一生中精通多种武器。优秀的战士必须强健壮硕，才能在战场上存活。

职业特性：

–可以穿戴头盔。
–可以穿戴任何种类的盔甲、使用全部类别的武器。
–可以对任何武器种类达到大宗师级别（5星）精通等级。
–可以精通（2星）任何战斗方式，双持武器可分配3点。
–5级：可使用猛力攻击与寓守于攻模式能力，同一时间仅可激活其中一种。

猛力攻击：战士牺牲命中精度以换取更重的伤害，每轮近战命中降低3点，近战伤害提升3点。战士力量需达到17点及以上才能激活此能力。

寓守于攻：战士专注于防御，牺牲命中精度来提升护甲等级，每轮命中降低3点，护甲等级提升3点。战士智力需达到15点及以上才能激活此能力。

–6级：可使用快速射击模式能力。

快速射击：战士每轮可额外进行一次远程攻击，但命中判定受到-4减值。

–12级：精通快速射击：快速射击激活时的命中减值降低至-2。
–14级：可使用精通猛力攻击与精通寓守于攻，原能力的加成与减值均提升至6点。
–16级：所有尚未达到专精及以上熟练度的武器，自动获得专精。
–20级：精通先攻：战士每轮额外获得半次攻击次数。

–生命骰：d10

主要兼职要求：力量~)
	  END
	END
  BUT_ONLY
	END
	END

///////////////////////////////////////////////////////////////////////////
// Append to SPLPROT.2DA                                                 //
///////////////////////////////////////////////////////////////////////////
// Weapon Profs
///////////////////////////////////////////////////////////////////////////
// Append to SPLPROT.2DA                                                 //
///////////////////////////////////////////////////////////////////////////
// Weapon Profs
ACTION_FOR_EACH weapon_prof IN
      89  // BASTARDSWORD
      90  // LONGSWORD
      91  // SHORTSWORD
      92  // AXE
      93  // TWOHANDEDSWORD
      94  // KATANA
      95  // SCIMITAR
      96  // DAGGER
      97  // WARHAMMER
      115 // CLUB
      98  // SPEAR
      99  // HALBERD
      100 // FLAILMORNINGSTAR
      101 // MACE
      102 // QUARTERSTAFF
      103 // CROSSBOW
      104 // LONGBOW
      105 // SHORTBOW
      106 // DART
      107 // SLING
      111 // SLING
      112 // SLING
      113 // SLING
      114 // SLING
    BEGIN
      APPEND ~splprot.2da~ ~prof_lt_%weapon_prof%%TAB%%weapon_prof%%TAB%-1%TAB%2~ UNLESS ~prof_lt_%weapon_prof%%TAB%%weapon_prof%%TAB%-1%TAB%2~
    END

// Update all imported files so they point in the correct direction.
COPY_EXISTING ~splprot.2da~ ~override~
    COUNT_2DA_COLS cols
    READ_2DA_ENTRIES_NOW rows cols
    FOR (row = 1; row < rows; ++row) BEGIN
      READ_2DA_ENTRY_FORMER rows row 0 ~stat~
      
      // WEAPON PROF ----------------------------------------------------------//
      // BASTARDSWORD
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_89~ BEGIN 
        SET prof_lt_89 = %row%
      // LONGSWORD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_90~ BEGIN
        SET prof_lt_90 = %row%
      // SHORTSWORD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_91~ BEGIN
        SET prof_lt_91 = %row%
      // AXE
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_92~ BEGIN
        SET prof_lt_92 = %row%
      // TWOHANDEDSWORD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_93~ BEGIN
        SET prof_lt_93 = %row%
      // KATANA
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_94~ BEGIN
        SET prof_lt_94 = %row%
      // SCIMITAR
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_95~ BEGIN
        SET prof_lt_95 = %row%
      // DAGGER
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_96~ BEGIN
        SET prof_lt_96 = %row%
      // WARHAMMER
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_97~ BEGIN
        SET prof_lt_97 = %row%
      // CLUB
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_115~ BEGIN
        SET prof_lt_115 = %row%
      // SPEAR
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_98~ BEGIN
        SET prof_lt_98 = %row%
      // HALBERD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_99~ BEGIN
        SET prof_lt_99 = %row%
      // FLAILMORNINGSTAR
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_100~ BEGIN
        SET prof_lt_100 = %row%
      // MACE
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_101~ BEGIN
        SET prof_lt_101 = %row%
      // QUARTERSTAFF
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_102~ BEGIN
        SET prof_lt_102 = %row%
      // CROSSBOW
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_103~ BEGIN
        SET prof_lt_103 = %row%
      // LONGBOW
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_104~ BEGIN
        SET prof_lt_104 = %row%
      // SHORTBOW
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_105~ BEGIN
        SET prof_lt_105 = %row%
      // DART
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_106~ BEGIN
        SET prof_lt_106 = %row%
    // SLING
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_107~ BEGIN
        SET prof_lt_107 = %row%

    // WEAPON STYLE ---------------------------------------------------------//
    // 2HANDED
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_111~ BEGIN
        SET prof_lt_111 = %row%
    // SWORDANDSHIELD
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_112~ BEGIN
        SET prof_lt_112 = %row%
    // SINGLEWEAPON
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_113~ BEGIN
        SET prof_lt_113 = %row%
    // 2WEAPON
      END ELSE PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~prof_lt_114~ BEGIN
        SET prof_lt_114 = %row%
    END
    END
    END

// Update Prof Checks
COPY_EXISTING ~c0fig04.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_89% STR_VAR match_resource = c0fig04a END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_90% STR_VAR match_resource = c0fig04b END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_91% STR_VAR match_resource = c0fig04c END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_92% STR_VAR match_resource = c0fig04d END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_93% STR_VAR match_resource = c0fig04e END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_94% STR_VAR match_resource = c0fig04f END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_95% STR_VAR match_resource = c0fig04g END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_96% STR_VAR match_resource = c0fig04h END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_97% STR_VAR match_resource = c0fig04i END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_98% STR_VAR match_resource = c0fig04j END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_99% STR_VAR match_resource = c0fig04k END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_100% STR_VAR match_resource = c0fig04l  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_101% STR_VAR match_resource = c0fig04m  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_102% STR_VAR match_resource = c0fig04n  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_103% STR_VAR match_resource = c0fig04o  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_104% STR_VAR match_resource = c0fig04p  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_105% STR_VAR match_resource = c0fig04q  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_106% STR_VAR match_resource = c0fig04r  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_107% STR_VAR match_resource = c0fig04s  END
    LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter1 = 2 parameter2 = %prof_lt_115% STR_VAR match_resource = c0fig04t  END
	
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04b.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 90 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04c.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 91 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04d.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 92 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04e.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 93 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04f.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 94 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04g.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 95 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04h.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 96 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04i.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 97 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04j.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 98 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04k.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 99 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04l.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 100 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04m.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 101 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04n.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 102 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04o.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 103 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04p.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 104 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04q.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 105 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04r.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 106 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04s.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 107 END
COPY_EXISTING ~c0fig04a.spl~ ~override/c0fig04t.spl~
    LPF ALTER_EFFECT INT_VAR match_opcode = 233 parameter2 = 115 END

// Continue doing the above for all profs

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~猛力攻击~) STR_VAR bam_file = C0FIG01I RET C0FIG01I = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~精通猛力攻击~) STR_VAR bam_file = C0FIG01J RET C0FIG01J = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~寓守于攻~) STR_VAR bam_file = C0FIG02I RET C0FIG02I = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~精通寓守于攻~) STR_VAR bam_file = C0FIG02J RET C0FIG02J = icon END

COPY_EXISTING ~C0FIG01X.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~猛力攻击—力量不足~) END
COPY_EXISTING ~C0FIG01.SPL~ OVERRIDE
SAY NAME1 ~猛力攻击~
SAY UNIDENTIFIED_DESC ~猛力攻击
战士牺牲命中精度以换取更重的伤害，每轮近战命中降低3点，近战伤害提升3点。战士力量需达到17点及以上才能激活此能力。~
	
COPY_EXISTING ~C0FIG01a.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~猛力攻击 激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 272 special = C0FIG01I END

COPY_EXISTING ~C0FIG01b.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~精通猛力攻击 激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 272 special = C0FIG01J END

COPY_EXISTING ~C0FIG01c.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~猛力攻击 未激活~) END

COPY_EXISTING ~C0FIG02X.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~寓守于攻—智力不足~) END
COPY_EXISTING ~C0FIG02.SPL~ OVERRIDE
SAY NAME1 ~寓守于攻~
SAY UNIDENTIFIED_DESC ~寓守于攻
战士专注于防御，牺牲命中精度来提升护甲等级，每轮命中降低3点，护甲等级提升3点。战士智力需达到15点及以上才能激活此能力。~

COPY_EXISTING ~C0FIG02a.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~寓守于攻 激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 272 special = C0FIG02I END

COPY_EXISTING ~C0FIG02b.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~精通寓守于攻 激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 272 special = C0FIG02J END

COPY_EXISTING ~C0FIG02c.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 opcode = 330 parameter1 = RESOLVE_STR_REF (~寓守于攻 未激活~) END

INCLUDE ~%MOD_FOLDER%/spells/rapidshot.tpa~

ACTION_IF FILE_EXISTS_IN_GAME ~KHALID7.CRE~ THEN BEGIN
COPY_EXISTING ~KHALID7.CRE~ ~override~
		    SET_BG2_PROFICIENCY 90 4
      	// do things here
END

ACTION_IF FILE_EXISTS_IN_GAME ~KORGAN8.CRE~ THEN BEGIN
COPY_EXISTING ~KORGAN8.CRE~ ~override~
		    SET_BG2_PROFICIENCY 97 3
      	// do things here
END

ACTION_IF FILE_EXISTS_IN_GAME ~MAZZY8.CRE~ THEN BEGIN
COPY_EXISTING ~MAZZY8.CRE~ ~override~
		    SET_BG2_PROFICIENCY 91 3
      	// do things here
END

ACTION_IF FILE_EXISTS_IN_GAME ~SAREV25A.DLG~ THEN BEGIN
COPY_EXISTING ~SAREVOK.CRE~ ~override~
		    SET_BG2_PROFICIENCY 103 3
		    SET_BG2_PROFICIENCY 99 3
      	// do things here
END

ACTION_IF FILE_EXISTS_IN_GAME ~SHARTE.CRE~ THEN BEGIN
COPY_EXISTING ~SHARTE.CRE~ ~override~
		    SET_BG2_PROFICIENCY 114 3
      	// do things here
END
