COPY ~%MOD_FOLDER%/Paladin/Inquisitor/2da~ ~override~
COPY ~%MOD_FOLDER%/Paladin/Inquisitor/bams~ ~override~
COPY ~%MOD_FOLDER%/Paladin/Inquisitor/spells~ ~override~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/CLABPA03.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE
	REPLACE_TEXTUALLY ~GA_SPCL211 ~ ~**** ~ // LAY ON HANDS
	REPLACE_TEXTUALLY ~GA_C0PAL02 ~ ~**** ~ // SMITE EVIL
	REPLACE_TEXTUALLY ~SPCL111 ~ ~**** ~ // CURE DISEASE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL234 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL235 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL233b END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0INQ02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0INQ03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0INQ03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = GA_C0INQ03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = GA_C0INQ03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 7 STR_VAR f_Entry = GA_C0INQ04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0INQ01 END

 	PRETTY_PRINT_2DA

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~否定光环~) STR_VAR bam_file = c0inqi02 RET c0inqi02 = icon END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~INQUISITOR~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~审判官：审判官毕生致力于搜寻并铲除邪术修习者、击溃黑暗势力，其神祇也为此赋予<PRO_HISHER>特殊的能力。

职业优势：
–免疫定身、魅惑与困惑效果。
–3级：获得「否定光环」被动能力。

否定光环：审判官拥有天生魔法抗性，并将一半抗性赋予20尺范围内的所有友军，同时减慢同范围内所有敌人的施法速度。效果强度如下：

  3级：10%魔法抗性，施法速度-1
  11级：16%魔法抗性，施法速度-1
  19级：32%魔法抗性，施法速度-2
  
–获得「真理之眼」被动能力。

真理之眼：每回合，审判官有20%+每等级2%的几率驱散20尺范围内的敌方幻象。每个目标单独掷骰判定。

–每日可使用两次「破魔术击」。

破魔术击：审判官的下一次成功攻击会使目标在接下来10秒内法术失败率为100%，并施加相当于自身等级两倍的驱散效果。此外，接下来2回合内目标的施法等级降低5，且施法持续时间减半。

–每日可使用一次「法术反转」。1级时获得1次，之后每提升7级额外获得1次。

–15级：额外获得两次「破魔术击」使用次数。

职业限制：
–不获得基于魅力的神恩加值。
–不获得勇气光环。
–无法驱散不死生物。
–无法使用圣疗术。
–无法使用破邪斩。
–无法施展治病术。
–无法施展牧师法术。~

COPY_EXISTING ~C0INQ01.SPL~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0inqi02 END

COPY_EXISTING ~C0INQ03.SPL~ OVERRIDE
  SAY NAME1 ~破魔术击~
  SAY UNIDENTIFIED_DESC ~破魔术击
审判官的下一次成功攻击会使目标在接下来10秒内法术失败率为100%，并施加相当于自身等级两倍的驱散效果。此外，接下来2回合内目标的施法等级降低5，且施法持续时间减半。

破魔术击的效果无视所有武器防护，即便攻击本身被招架也依然生效。~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~C0INQ03.spl~ ~override~
SAY UNIDENTIFIED_DESC ~破魔术击
审判官的下一次成功攻击会使目标在接下来10秒内法术失败率为100%，并施加相当于自身等级两倍的驱散效果。此外，接下来2回合内目标的施法等级降低5，且施法持续时间减半。

破魔术击的效果无视所有武器防护，即便攻击本身被招架也依然生效。~

COPY_EXISTING ~numwslot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~INQUISITOR~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 4
	  END
	END

COPY ~%MOD_FOLDER%/lua/m_c0pal2.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
END

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREE.PRO~ ~C0 Instant Area Enemies~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREL.PRO~ ~C0 Instant Area Enemies Large~

COPY_EXISTING ~C0INQ01A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

COPY_EXISTING ~C0INQ01B.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREE
END

COPY_EXISTING ~C0INQ02A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREL
END

COPY_EXISTING ~C0INQ03a.SPL~ OVERRIDE
 LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~驱散效果~) END

COPY_EXISTING ~C0INQ02a.SPL~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR header = 1  probability1 = 24 END
  LPF ALTER_EFFECT INT_VAR header = 2  probability1 = 26 END
  LPF ALTER_EFFECT INT_VAR header = 3  probability1 = 28 END
  LPF ALTER_EFFECT INT_VAR header = 4  probability1 = 30 END
  LPF ALTER_EFFECT INT_VAR header = 5  probability1 = 32 END
  LPF ALTER_EFFECT INT_VAR header = 6  probability1 = 34 END
  LPF ALTER_EFFECT INT_VAR header = 7  probability1 = 36 END
  LPF ALTER_EFFECT INT_VAR header = 8  probability1 = 38 END
  LPF ALTER_EFFECT INT_VAR header = 9  probability1 = 40 END
  LPF ALTER_EFFECT INT_VAR header = 10  probability1 = 42 END
  LPF ALTER_EFFECT INT_VAR header = 11  probability1 = 44 END
  LPF ALTER_EFFECT INT_VAR header = 12  probability1 = 46 END
  LPF ALTER_EFFECT INT_VAR header = 13  probability1 = 48 END
  LPF ALTER_EFFECT INT_VAR header = 14  probability1 = 50 END
  LPF ALTER_EFFECT INT_VAR header = 15  probability1 = 52 END
  LPF ALTER_EFFECT INT_VAR header = 16  probability1 = 54 END
  LPF ALTER_EFFECT INT_VAR header = 17  probability1 = 56 END
  LPF ALTER_EFFECT INT_VAR header = 18  probability1 = 58 END
  LPF ALTER_EFFECT INT_VAR header = 19  probability1 = 60 END
  LPF ALTER_EFFECT INT_VAR header = 20  probability1 = 62 END
  LPF ALTER_EFFECT INT_VAR header = 21  probability1 = 64 END
  LPF ALTER_EFFECT INT_VAR header = 22  probability1 = 66 END
  LPF ALTER_EFFECT INT_VAR header = 23  probability1 = 68 END
  LPF ALTER_EFFECT INT_VAR header = 24  probability1 = 70 END
  LPF ALTER_EFFECT INT_VAR header = 25  probability1 = 72 END
  LPF ALTER_EFFECT INT_VAR header = 26  probability1 = 74 END
  LPF ALTER_EFFECT INT_VAR header = 27  probability1 = 76 END
  LPF ALTER_EFFECT INT_VAR header = 28  probability1 = 78 END
  LPF ALTER_EFFECT INT_VAR header = 29  probability1 = 80 END
  LPF ALTER_EFFECT INT_VAR header = 30  probability1 = 82 END
  LPF ALTER_EFFECT INT_VAR header = 31  probability1 = 84 END
  LPF ALTER_EFFECT INT_VAR header = 32  probability1 = 86 END
  LPF ALTER_EFFECT INT_VAR header = 33  probability1 = 88 END
  LPF ALTER_EFFECT INT_VAR header = 34  probability1 = 90 END
  LPF ALTER_EFFECT INT_VAR header = 35  probability1 = 92 END
  LPF ALTER_EFFECT INT_VAR header = 36  probability1 = 94 END
  LPF ALTER_EFFECT INT_VAR header = 37  probability1 = 96 END
  LPF ALTER_EFFECT INT_VAR header = 38  probability1 = 98 END
  LPF ALTER_EFFECT INT_VAR header = 39  probability1 = 100 END

COPY_EXISTING ~SPWI701.spl~ ~override/C0INQ04.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
