COPY ~%MOD_FOLDER%/Thief/InvisibleBlade/2da~ ~override~
COPY ~%MOD_FOLDER%/Thief/InvisibleBlade/spells~ ~override~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/C0INVBL.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE
	REPLACE_TEXTUALLY ~AP_C0TH-A2~ ~**** ~ // EPIC PRECISION

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0IVBP1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0IVB02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0IVBP2 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~无踪短刃：无踪短刃是致命的战士，偏好使用匕首及同类武器作战。他们对这类武器的训练与技法，使其杀伤力丝毫不逊于任何全副武装的战士。无踪短刃乐于让他人低估自己的危险程度，也热衷于抓住一切机会证明：最不起眼的武器，往往最致命。

职业优势：
–匕首可达到宗师级精通（5个熟练位）。
–双武器战斗可达到精通级（3个熟练位）。
–持匕首时命中+1。每偶数等级额外+1，20级时达到上限+11。
–自由身法：智力每超过12点1点，无踪短刃的基础护甲等级就提升1点。
–流血不止：无踪短刃使用匕首的背刺会使目标流血不止，首次命中造成额外穿刺伤害，之后数回合造成无视护甲伤害。攻击必须造成伤害才能触发流血不止，同一目标可叠加该效果。
  1-4级：每回合2点伤害，持续2回合
  5-8级：每回合3点伤害，持续4回合
  9-12级：每回合4点伤害，持续8回合
  12-16级：每回合6点伤害，持续8回合
  17级及以上：每回合8点伤害，持续10回合
  无血液的目标免疫流血不止，但仍承受正常背刺伤害。
  
–可使用「虚招」攻击模式。

虚招：无踪短刃做出假动作诱使对手露出破绽，趁其不备发动攻击。虚招激活时，本回合无踪短刃每回合攻击次数减半，近战攻击会迫使目标进行强韧豁免（难度+4，每3级难度惩罚-1），失败则目标敏捷减半，持续1回合，并附加流血不止效果。每回合对单个目标仅可尝试一次虚招。虚招对无智生物（如魔像、史莱姆）无效。

–12级：虚招大师：虚招状态下，无踪短刃每回合的首次攻击必定视为背刺，并额外叠加一层流血不止。

职业限制：
–背刺倍率最高仅为2倍。KIT_DISADV_1
–无法穿戴任何护甲。
–每级仅可分配15点技能点数至游荡者技能。
–无法使用「设置陷阱」能力。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「致残打击」。
–不获得「史诗精准」。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

// INTELLIGENCE
APPEND ~splprot.2da~ ~C0HTINT%TAB%38%TAB%-1%TAB%1~ UNLESS ~C0HTINT~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTINT~ BEGIN
	    SET C0HTINT = %row%
	  END
	END
	
LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 4
	
    mixed         = RESOLVE_STR_REF(~无踪短刃~)
	
    lower         = RESOLVE_STR_REF(~无踪短刃~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~无踪短刃：无踪短刃是致命的战士，偏好使用匕首及同类武器作战。他们对这类武器的训练与技法，使其杀伤力丝毫不逊于任何全副武装的战士。无踪短刃乐于让他人低估自己的危险程度，也热衷于抓住一切机会证明：最不起眼的武器，往往最致命。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0_INVISIBLE_BLADE~
	
    unusable      = ~0x10000000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 5 1 0 1 0 0 1 0 1 1 0 0 1 1 5 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 3~
	
    // abclasrq      = ~0 9 0 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0INVB~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0INVBL.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    clascolr = ~199 186 182 83 190~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~100 100 100 100 100 100 0 0~
	
	backstab = ~1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
	
	sneakatt = ~1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	thiefskl = ~40 15~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~虚招~) STR_VAR bam_file = c0ivb02i RET c0ivb02i = icon END

COPY_EXISTING ~C0IVB00.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 1000 parameter2 = C0HTINT END

COPY_EXISTING ~C0IVB01a.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—每回合2点伤害，持续2回合~) END
COPY_EXISTING ~C0IVB01b.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—每回合3点伤害，持续4回合~) END
COPY_EXISTING ~C0IVB01c.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—每回合4点伤害，持续8回合~) END
COPY_EXISTING ~C0IVB01d.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—每回合6点伤害，持续8回合~) END
COPY_EXISTING ~C0IVB01e.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—每回合8点伤害，持续10回合~) END
COPY_EXISTING ~C0IVB01z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR header = 0 match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—承受伤害（2）~) END
LPF ALTER_EFFECT INT_VAR header = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—承受伤害（3）~) END
LPF ALTER_EFFECT INT_VAR header = 2 match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—承受伤害（4）~) END
LPF ALTER_EFFECT INT_VAR header = 3 match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—承受伤害（6）~) END
LPF ALTER_EFFECT INT_VAR header = 4 match_opcode = 139 parameter1 = RESOLVE_STR_REF (~流血不止—承受伤害（8）~) END

COPY_EXISTING ~C0IVB02.SPL~ OVERRIDE
SAY NAME1 ~虚招~
SAY UNIDENTIFIED_DESC ~虚招
无踪短刃做出假动作诱使对手露出破绽，趁其不备发动攻击。虚招激活时，本回合无踪短刃每回合攻击次数减半，近战攻击会迫使目标进行强韧豁免（难度+4，每3级难度惩罚-1），失败则目标敏捷减半，持续1回合，并附加流血不止效果。每回合对单个目标仅可尝试一次虚招。虚招对无智生物（如魔像、史莱姆）无效。~

COPY_EXISTING ~C0IVB02a.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = c0ivb02i END
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~虚招已激活~) END
COPY_EXISTING ~C0IVB02b.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~虚招成功~) END
COPY_EXISTING ~C0IVB02y.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~虚招已解除~) END

COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP203.EFF~
	WRITE_BYTE 0x1C 2
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP204.EFF~
	WRITE_BYTE 0x1C 3
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP205.EFF~
	WRITE_BYTE 0x1C 4
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP206.EFF~
	WRITE_BYTE 0x1C 5
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP207.EFF~
	WRITE_BYTE 0x1C 6
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP208.EFF~
	WRITE_BYTE 0x1C 7
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP209.EFF~
	WRITE_BYTE 0x1C 8
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP210.EFF~
	WRITE_BYTE 0x1C 9
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP211.EFF~
	WRITE_BYTE 0x1C 10
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP212.EFF~
	WRITE_BYTE 0x1C  11
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP213.EFF~
	WRITE_BYTE 0x1C  12
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP214.EFF~
	WRITE_BYTE 0x1C  13
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP215.EFF~
	WRITE_BYTE 0x1C  14
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP216.EFF~
	WRITE_BYTE 0x1C  15
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP217.EFF~
	WRITE_BYTE 0x1C  16
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP218.EFF~
	WRITE_BYTE 0x1C  17
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP219.EFF~
	WRITE_BYTE 0x1C  18
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP220.EFF~
	WRITE_BYTE 0x1C  19
COPY_EXISTING ~C0IVP202.EFF~ ~OVERRIDE/C0IVP221.EFF~
	WRITE_BYTE 0x1C  20
	
COPY_EXISTING ~LUTH0.2da~ ~override/LUC0INVB.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL910~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL911~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL912~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0INVB1~ ability = ~GA_SPCL900~ num_allowed = 16 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0INVB2~ ability = ~GA_SPCL901~ num_allowed = 16 prerequisite = ~GA_SPCL900~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0INVB3~ ability = ~GA_C0IVBH1~ num_allowed = 1 END	

COPY_EXISTING ~C0IVBH1.SPL~ OVERRIDE
SAY NAME1 ~匕首大师~
SAY UNIDENTIFIED_DESC ~无踪短刃对本命武器的精准掌控，使其一使用匕首进行近战攻击时，暴击几率获得+4加值修正。~

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x20 mage //reads the byte containing the fighter usability flag
      READ_SHORT    0x1C type //reads the byte containing item type
    PATCH_IF ((mage BAND 0b00000100) = 0b00000100) AND (type = 2) BEGIN 
		LPF DELETE_EFFECT STR_VAR match_resource = C0IVBP3 END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 177 target = 1 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_INVISIBLE_BLADE~) parameter2 = 9 timing = 2 STR_VAR resource = c0ivbp3 END
    END
  END
BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
      READ_SHORT    0x1C type //reads the byte containing item type
    PATCH_IF (type = 2) BEGIN 
		LPF DELETE_EFFECT STR_VAR match_resource = C0IVBP3 END
        LPF CLONE_EFFECT INT_VAR match_opcode = 319 opcode = 177 target = 1 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_INVISIBLE_BLADE~) parameter2 = 9 timing = 2 silent = 1 STR_VAR match_resource = C0EKARM_ resource = c0ivbp3 END
    END
  END
BUT_ONLY

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~C0INVBL.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
      LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0TH-E1 END // USE MAGIC DEVICE
  PRETTY_PRINT_2DA

END

END