COPY ~%MOD_FOLDER%/Fighter/Kensai/2da~ ~override~
COPY ~%MOD_FOLDER%/Fighter/Kensai/bam~ ~override~
COPY ~%MOD_FOLDER%/Fighter/Kensai/spells~ ~override~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/CLABFI04.2DA~
	// REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	// REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	// REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL143 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 4 STR_VAR f_Entry = AP_SPCL143 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 4 STR_VAR f_Entry = GA_SPCL144 END

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0KN#01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0KN#02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0KN#02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_Increment = 5 STR_VAR f_Entry = AP_C0KN#02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = GA_C0KN#03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0KN#04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0KN#06 END

 	PRETTY_PRINT_2DA

// FATIGUE
APPEND ~splprot.2da~ ~FATIGUEGTEQ%TAB%30%TAB%-1%TAB%4~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~FATIGUEGTEQ~ BEGIN
	    SET FATIGUEGTEQ = %row%
	  END
	END

  COPY_EXISTING ~abclasrq.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~KENSAI~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 12
		SET_2DA_ENTRY (%patch_row%) 2 cols 14
		SET_2DA_ENTRY (%patch_row%) 3 cols 9
		SET_2DA_ENTRY (%patch_row%) 5 cols 12
	  END
	END
  COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~KENSAI~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~C0KN~
	  END
	END
	
OUTER_SPRINT kit_description ~剑圣：该职业之名在通用语中意为「剑之圣者」，指受过专门训练、与武器融为一体的战士。剑圣致命而迅捷，惯于无甲作战。（注：虽名称带「剑」，但剑圣可使用任何自身熟练的近战武器。）

职业优势：
–基础护甲等级为8。
–每提升4级，速度因子-1。
–所有造成的物理伤害+10%。
–获得「气之暴击」先天能力。

气之暴击：暴击率+2。10级时额外+2，之后每提升5级再+1。

–每日可使用一次「气之专注」能力。1级时获得1次，之后每提升4级额外获得1次。

气之专注：接下来12秒内所有成功攻击必定命中，且物理伤害提升20%。

–3级起，可使用「防御架势」攻击模式。

防御架势：剑圣将基础护甲等级设为4 -（等级/2，向上取整）。本能力可持续至主动解除。但激活防御架势期间，剑圣失去气之暴击修正，无法造成暴击，也无法使用气之一击与气之专注。

–5级起，每回合可使用一次「气之一击」。

气之一击：使用本能力后一回合内，剑圣的下一次攻击气之暴击修正翻倍，且造成最大伤害。命中后剑圣会受到累积疲劳惩罚，惩罚数值随等级提升而降低。若疲劳过度，气之一击会失败。

–10级起，获得「完美防御」先天能力。

完美防御：防御架势激活时，剑圣免疫背刺，且每回合格挡首次受到的武器伤害。此外，15尺范围内每有一名敌人，剑圣的护甲等级累计+1。

–15级起，获得「完美攻势」先天能力。

完美攻势：剑圣攻击掷骰出1时不再失误。

职业限制：KIT_DISADV_1
–无法使用任何护甲、头盔、护手、护腕或盾牌。
–无法使用远程武器。
–无法获得「强健」「抵抗魔法」「战吼」等高阶能力。
–阵营限制为所有非混乱阵营。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「速射」。
–16级时不获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~KENSAI~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~

ACTION_IF NOT MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN
COPY_EXISTING ~CLABFI04.2DA~ OVERRIDE
REPLACE_TEXTUALLY ~GA_C0FIG01~ ~****     ~
REPLACE_TEXTUALLY ~GA_C0FIG02~ ~****     ~
REPLACE_TEXTUALLY ~GA_C0FIG03~ ~****     ~
END

COPY_EXISTING ~LUFI0.2da~ ~override/LUC0KN.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL904~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL905~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL907~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL908~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0KN1~ ability = ~AP_C0KN#07~ num_allowed = 1 prerequisite = ~GA_SPCL906~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0KN2~ ability = ~AP_C0KN#08~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0KN3~ ability = ~AP_C0KN#09~ num_allowed = 1 prerequisite = ~AP_C0KN#08~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0KN4~ ability = ~AP_C0KN#10~ num_allowed = 1 prerequisite = ~AP_C0KN#09~ END	
REPLACE_TEXTUALLY ~GA_SPCL905~ ~GA_C0KN#07~

COPY_EXISTING ~SPCL144.SPL~ ~OVERRIDE~
SAY NAME1 ~气之专注~
SAY UNIDENTIFIED_DESC ~气之专注
接下来12秒内所有成功攻击必定命中，且物理伤害提升20%。~

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#03.SPL~ ~OVERRIDE~
SAY NAME1 ~防御架势~
SAY UNIDENTIFIED_DESC ~防御架势
剑圣将<PRO_HISHER>基础护甲等级设为6 -（等级/2，向上取整）。本能力可持续至主动解除。但激活防御架势期间，剑圣失去气之暴击修正，无法造成暴击，也无法使用气之一击与气之专注。解除后，剑圣必须等待一回合才能重新激活防御架势。~

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#03x.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
	  match_opcode = 206
	  parameter1 = RESOLVE_STR_REF (~防御架势状态下无法使用气之专注。~)
	STR_VAR
	  match_resource = spcl144
END
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
	  match_opcode = 206
	  parameter1 = RESOLVE_STR_REF (~防御架势状态下无法使用气之一击。~)
	STR_VAR
	  match_resource = c0kn#04
END
COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#03z.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~防御架势已解除~) END

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#04.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
	  match_opcode = 326
	  parameter2 = %FATIGUEGTEQ%
END
SAY NAME1 ~气之一击~
SAY UNIDENTIFIED_DESC ~气之一击
使用本能力后一回合内，剑圣的下一次攻击气之暴击修正翻倍，且造成最大伤害。命中后剑圣会受到累积疲劳惩罚，惩罚数值随等级提升而降低。若疲劳过度，气之一击会失败。~
COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#04X.SPL~ ~OVERRIDE~
  LPF ALTER_EFFECT
    INT_VAR
      check_globals = 1
      check_headers = 1
	  match_opcode = 206
	  parameter1 = RESOLVE_STR_REF (~剑圣疲劳过度，无法施展气之一击。~)
END

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#05.SPL~ ~OVERRIDE~
SAY NAME1 ~解除防御架势~
SAY UNIDENTIFIED_DESC ~使用本能力解除防御架势。~

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#07.SPL~ ~OVERRIDE~
SAY NAME1 ~强化气之暴击~
SAY UNIDENTIFIED_DESC ~剑圣的近战暴击修正永久+4。

本技能在前置要求中等同于「暴击打击」能力。

需要：猛力攻击~

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#08.SPL~ ~OVERRIDE~
SAY NAME1 ~碾压暴击~
SAY UNIDENTIFIED_DESC ~剑圣的暴击会使目标的物理抗性累计降低5%，持续4回合。~

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#09.SPL~ ~OVERRIDE~
SAY NAME1 ~回气~
SAY UNIDENTIFIED_DESC ~剑圣造成暴击时，回复相当于最大生命值5%的生命，并减轻少量疲劳。

需要：碾压暴击~

COPY ~%MOD_FOLDER%/Fighter/Kensai/SPELLS/C0KN#10.SPL~ ~OVERRIDE~
SAY NAME1 ~毁灭暴击~
SAY UNIDENTIFIED_DESC ~剑圣的暴击若目标死亡豁免失败则直接秒杀。生命骰8及以下的生物无需豁免直接死亡。

需要：回气~
