COPY ~%MOD_FOLDER%/Thief/Magekiller/2da~ ~override~
COPY ~%MOD_FOLDER%/Thief/Magekiller/spells~ ~override~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/C0MKILL.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE
	REPLACE_TEXTUALLY ~AP_C0TH-A2~ ~**** ~ // EPIC PRECISION

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MK#000 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0MK#003 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = GA_C0MK#004 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_Increment = 10 STR_VAR f_Entry = AP_C0MK#001 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_C0MK#003 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_C0MK#005 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 STR_VAR f_Entry = GA_C0MK#006 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = GA_C0MK#003 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = GA_C0MK#007 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~法师杀手：在魔法遭到恐惧与迫害的地区，擅长追踪与铲除施法者的人才备受追捧。法师杀手是专精追踪、潜行与反魔法的游荡者，在辨识与对抗各类魔法上技艺高超。

职业优势：
–识破幻象+25%。
–对抗法术的豁免检定+2。每提升10级额外+1。
–法师杀手的背刺有几率移除目标身上的魔法效果，效果等同「解除魔法」法术。
–法师杀手的反魔法能力施法时间为1，且视为无法术等级、无学派的能力，因此不受基于法术等级或学派的防护效果影响。
–每日可天生施展一次「破法」。10级与15级时各额外获得1次使用次数。
–8级：每日可天生施展一次「法术免疫」。
–12级：每日可天生施展一次「无效结界」。
–16级：每日可天生施展一次「法术反转」。
–20级：每日可天生施展一次「破盾术」。

职业限制：
–背刺成长弱于普通游荡者：
  1-4级：1倍（无倍率）
  5-8级：2倍
  9-12级：3倍
  13级及以上：4倍KIT_DISADV_1
–每级仅可分配15点技能点数至游荡者技能。
–无法兼职成为法师。
–无法使用「设置陷阱」能力。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
–无法使用「致残打击」。
–不获得「史诗精准」。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 4
	
    mixed         = RESOLVE_STR_REF(~法师杀手~)
	
    lower         = RESOLVE_STR_REF(~法师杀手~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~法师杀手：在魔法遭到恐惧与迫害的地区，擅长追踪与铲除施法者的人才备受追捧。法师杀手是专精追踪、潜行与反魔法的游荡者，在辨识与对抗各类魔法上技艺高超。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0MKILL~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 1 1 1 1 1~
	
    abclasrq      = ~0 9 0 12 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    dualclas      = ~1 1 0 0 0 0~
	
    luabbr        = ~C0MKIL~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0MKILL.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	clasiskl = ~0 0 0 0 0 25 0~
	
	// clasthac = ~0~
	
	thiefscl = ~100 100 100 100 100 100 0 0~
	
	backstab = ~1 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	sneakatt = ~1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	thiefskl = ~40 15~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~LUTH0.2da~ ~override/LUC0MKIL.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL910~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL911~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL912~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0MKIL1~ ability = ~AP_C0MK#008~ num_allowed = 3 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MKIL2~ ability = ~GA_C0MK#010~ num_allowed = 1 prerequisite = ~GA_C0MK#008~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MKIL3~ ability = ~GA_SPCL904~ num_allowed = 16 END	

COPY_EXISTING ~C0MK#002.spl~ ~override~
	LPF ALTER_EFFECT
		INT_VAR
		match_opcode = 139
		parameter1 = RESOLVE_STR_REF (~驱散效果~)
	END

COPY_EXISTING ~SPWI513.spl~ ~override/C0MK#003.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
WRITE_BYTE 0x25 0
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
LPF ALTER_EFFECT INT_VAR power = 100 END

COPY_EXISTING ~SPWI510.spl~ ~override/C0MK#004.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
WRITE_BYTE 0x25 0
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
LPF ALTER_EFFECT INT_VAR power = 100 END

COPY_EXISTING ~SPWI602.spl~ ~override/C0MK#005.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
WRITE_BYTE 0x25 0
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
LPF ALTER_EFFECT INT_VAR power = 100 END

COPY_EXISTING ~SPWI701.spl~ ~override/C0MK#006.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
WRITE_BYTE 0x25 0
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
LPF ALTER_EFFECT INT_VAR power = 100 END

COPY_EXISTING ~SPWI805.spl~ ~override/C0MK#007.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
WRITE_BYTE 0x25 0
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
LPF ALTER_EFFECT INT_VAR power = 100 END

COPY_EXISTING ~C0MK#008.SPL~ ~OVERRIDE~
SAY NAME1 ~Spellstrike~
SAY UNIDENTIFIED_DESC ~The Magekiller gains the ability to cast Spellstrike as an innate ability once per day.

This ability may be chosen up to three times.~

COPY_EXISTING ~SPWI903.spl~ ~override/C0MK#009.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
WRITE_BYTE 0x25 0
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
LPF ALTER_SPELL_HEADER INT_VAR speed = 1 END
LPF ALTER_EFFECT INT_VAR power = 100 END

COPY_EXISTING ~C0MK#010.SPL~ ~OVERRIDE~
SAY NAME1 ~奥术封禁~
SAY UNIDENTIFIED_DESC ~奥术封禁
法师杀手触碰奥术施法者时，可将其永久囚禁于异次元反魔法监牢中，目标除非使用「自由术」否则无法逃脱。奥术封禁无视魔法抗性，且无豁免检定，但本能力仅对法师有效，对其他目标使用会失败。

本技能仅可选择1次。

需要：法击~
