ACTION_IF FILE_EXISTS_IN_GAME ~C0ILMCL.2DA~ THEN BEGIN
LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~C0ILM~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~殉道者：殉道者是苦难、坚韧与不屈之善神伊尔马特的信徒。伊尔马特教会的圣武士心怀慈悲，苦修自身以成为盟友的守护者，为他人减轻苦痛。

职业优势：
–每日可使用三次圣疗术。
–每提升5级，钝击、挥砍、穿刺与远程伤害抗性+5%，20级时达到上限20%。
–每日可使用一次「牺牲」能力。5级时额外获得1次，之后每提升5级再额外获得1次。

牺牲：殉道者将自身10点生命值+每等级2点转移给目标，20级时转移上限为50点。殉道者不会因此能力死亡——生命值若低于1，则改为陷入昏迷。

–5级起，每日可使用一次「殉道」能力。10级时额外获得1次，之后每提升10级再额外获得1次。

殉道：殉道者摆出防御姿态守护战友。持续1回合，临时最大生命值翻倍，护甲等级+4，所有伤害抗性+20%，免疫所有位移效果。姿态期间伤害与移动速度减半，但有效控制范围大幅提升，5尺半径内生物无法穿过。持续时间结束后，殉道者陷入重度疲劳。本能力不可与「强健」同时使用。

–3级：获得「庇护光环」。

庇护光环：殉道者散发出庇护光环守护同伴，15尺范围内所有友军获得护甲等级与钝击、穿刺、挥砍、远程伤害抗性加成。
  3级：护甲等级+1。
  11级：护甲等级+2，抗性+5%。
  19级：护甲等级+3，抗性+10%。
  
–8级：获得「终末之息」被动效果。

终末之息：殉道者无畏的英勇与坚韧，即便身死也能激励并守护盟友。若殉道者被击杀，所有盟友回复最大生命值的50%，且2回合内命中、伤害与豁免检定+4。

–10级：殉道者免疫疲劳。
–15级：每日可使用一次「伊尔马特的恩典」能力。

伊尔马特的恩典：殉道者可在战斗中唤起第二次生机，立即回复最大生命值的一半。接下来5回合内，逐步回复另外一半最大生命值。

–20级：苦难试炼：殉道者永久获得5%几率抵消受到的伤害。若伤害被抵消，殉道者与最近的友军每秒回复2点生命值，持续5秒。

–生命骰：d12

职业限制：
–不获得基于魅力的神恩加值。
–不获得勇气光环。
–伤害受-1惩罚。
–无法使用破邪斩。
–无法驱散不死生物。
–无法使用远程武器。~
END

COPY ~%MOD_FOLDER%/Paladin/Martyr/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Paladin/Martyr/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/C0ILMCL.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE
	REPLACE_TEXTUALLY ~GA_C0PAL02 ~ ~**** ~ // SMITE EVIL
	REPLACE_TEXTUALLY ~SPCL111 ~ ~**** ~ // CURE DISEASE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_SPCL154 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0ILMI1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPCL211 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPCL211 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL235 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0ILMS1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0ILMI2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_C0ILMS1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0ILMS2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = AP_C0ILMI3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = AP_C0ILMI4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_Increment = 10 STR_VAR f_Entry = GA_C0ILMS2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0ILMS6 END

 	PRETTY_PRINT_2DA

// Martyr

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 6
	
    mixed         = RESOLVE_STR_REF(~殉道者~)
	
    lower         = RESOLVE_STR_REF(~殉道者~)
	
    help          = RESOLVE_STR_REF(~殉道者：殉道者是苦难、坚韧与不屈之善神伊尔马特的信徒。伊尔马特教会的圣武士心怀慈悲，苦修自身以成为盟友的守护者，为他人减轻苦痛。

职业优势：
–每日可使用三次圣疗术。
–每提升5级，钝击、挥砍、穿刺与远程伤害抗性+5%，20级时达到上限20%。
–每日可使用一次「牺牲」能力。5级时额外获得1次，之后每提升5级再额外获得1次。

牺牲：殉道者将自身10点生命值+每等级2点转移给目标，20级时转移上限为50点。殉道者不会因此能力死亡——生命值若低于1，则改为陷入昏迷。

–5级起，每日可使用一次「殉道」能力。10级时额外获得1次，之后每提升10级再额外获得1次。

殉道：殉道者摆出防御姿态守护战友。持续1回合，临时最大生命值翻倍，护甲等级+4，所有伤害抗性+20%，免疫所有位移效果。姿态期间伤害与移动速度减半，但有效控制范围大幅提升，5尺半径内生物无法穿过。持续时间结束后，殉道者陷入重度疲劳。本能力不可与「强健」同时使用。

–3级：获得「庇护光环」。

庇护光环：殉道者散发出庇护光环守护同伴，15尺范围内所有友军获得护甲等级与钝击、穿刺、挥砍、远程伤害抗性加成。
  3级：护甲等级+1。
  11级：护甲等级+2，抗性+5%。
  19级：护甲等级+3，抗性+10%。
  
–8级：获得「终末之息」被动效果。

终末之息：殉道者无畏的英勇与坚韧，即便身死也能激励并守护盟友。若殉道者被击杀，所有盟友回复最大生命值的50%，且2回合内命中、伤害与豁免检定+4。

–10级：殉道者免疫疲劳。
–12级：殉道姿态激活时，殉道者的近战攻击命中时，会治疗10尺范围内最近的友军1d6+2点生命值。
–15级：每日可使用一次「伊尔马特的恩典」能力。

伊尔马特的恩典：殉道者可在战斗中唤起第二次生机，立即回复最大生命值的一半。接下来5回合内，逐步回复另外一半最大生命值。

–20级：苦难试炼：殉道者永久获得5%几率抵消受到的伤害。若伤害被抵消，殉道者与最近的友军每秒回复2点生命值，持续5秒。

–生命骰：d12

职业限制：
–不获得基于魅力的神恩加值。
–不获得勇气光环。
–伤害受-1惩罚。
–无法使用破邪斩。
–无法驱散不死生物。
–无法使用远程武器。~)
	
    briefdesc     = RESOLVE_STR_REF(~殉道者：殉道者是苦难、坚韧与不屈之善神伊尔马特的信徒。伊尔马特教会的圣武士心怀慈悲，苦修自身以成为盟友的守护者，为他人减轻苦痛。~)
	
	// fallen = 1
	
  STR_VAR
    kit_name      = ~C0ILM~
	
    unusable      = ~0x00000008~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 2 2 3~
	
    // abclasrq      = ~0 15 0 14 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0ILMCL.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~庇护光环~) STR_VAR bam_file = c0ilmi2i RET c0ilmi2i = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~殉道~) STR_VAR bam_file = c0ilms2i RET c0ilms2i = icon END

// CURRENT HP CHECK
APPEND ~splprot.2da~ ~C0CURHP%TAB%0%TAB%-1%TAB%0~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0CURHP~ BEGIN
	    SET C0CURHP = %row%
	  END
	END
	
	
COPY_EXISTING ~c0ilms1.spl~ ~override~
SAY NAME1 ~牺牲~
SAY NAME2 ~牺牲~
SAY UNIDENTIFIED_DESC ~牺牲
殉道者将自身10点生命值+每等级2点转移给目标，20级时转移上限为50点。殉道者不会因此能力死亡——生命值若低于1，则改为陷入昏迷。~

COPY_EXISTING ~c0ilms1a.spl~ ~override~
	
COPY_EXISTING ~c0ilmi2.spl~ ~override~
      LPF ADD_SPELL_EFFECT
      INT_VAR
	    opcode = 142
	    target = 2
		timing = 9
        parameter2 = c0ilmi2i
      END
	
COPY_EXISTING ~C0ilms2.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 142
	  parameter2 = c0ilms2i
END
SAY NAME1 ~殉道~
SAY NAME2 ~殉道~
SAY UNIDENTIFIED_DESC ~殉道
殉道者摆出防御姿态守护战友。持续1回合，护甲等级临时+6，所有伤害抗性+30%，免疫所有位移效果。姿态期间伤害与移动速度减半，但有效控制范围大幅提升，5尺半径内生物无法穿过。持续时间结束后，殉道者陷入重度疲劳。

12级起，殉道姿态激活时，殉道者的近战攻击命中时，会治疗10尺范围内最近的友军2d6+2点生命值。

本能力不可与「强健」同时使用。~

ADD_PROJECTILE ~%MOD_FOLDER%/Paladin/Martyr/spells/c0ilms2a.PRO~ ~C0 Martyrdom~

COPY_EXISTING ~C0ilms2a.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0ilms2a END

COPY_EXISTING ~C0ilms3.spl~ ~override~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~再生中~)
END
SAY NAME1 ~伊尔马特的恩典~
SAY NAME2 ~伊尔马特的恩典~
SAY UNIDENTIFIED_DESC ~伊尔马特的恩典
殉道者可在战斗中唤起第二次生机，立即回复最大生命值的一半。接下来5回合内，逐步回复另外一半最大生命值。~

COPY_EXISTING ~C0ilms5.spl~ ~override~
SAY NAME1 ~终末之息~

COPY_EXISTING ~C0ilms6b.spl~ ~override~
  LPF ALTER_SPELL_HEADER INT_VAR projectile = c0ilms2a END
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~苦难试炼抵消了伤害~)
END

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

OUTER_SET martyr_ids = IDS_OF_SYMBOL (~kit~ ~C0ILM~)
  
COPY ~%MOD_FOLDER%/lua/m_c0pal3.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%martyr_ids%~~~~~ //"
  END

END

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

COPY_EXISTING ~C0ILMI2A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END
