COPY ~%MOD_FOLDER%/MonkRevision/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/audio~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/bam~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/bmp~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/eff~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/MonkRevision/fists~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/spells/strength_exceptional~ ~OVERRIDE~

COPY_EXISTING ~CLABMO01.2DA~ ~OVERRIDE/CLABMO01.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL811~ ~**** ~ // STUNNING BLOW
	REPLACE_TEXTUALLY ~AP_SPCL812~ ~**** ~ // MOVEMENT RATE
	REPLACE_TEXTUALLY ~AP_SPCL813~ ~**** ~ // MOVEMENT RATE 2
	REPLACE_TEXTUALLY ~AP_SPCL814~ ~**** ~ // FREE ACTION
	REPLACE_TEXTUALLY ~GA_SPCL815~ ~**** ~ // LAY ON HANDS
	REPLACE_TEXTUALLY ~AP_SPCL816~ ~**** ~ // SPEED FACTOR
	REPLACE_TEXTUALLY ~AP_SPCL817~ ~**** ~ // IMMUNITY TO CHARM
	REPLACE_TEXTUALLY ~AP_SPCL818~ ~**** ~ // IMMUNITY TO POISON
	REPLACE_TEXTUALLY ~AP_SPCL819~ ~**** ~ // MAGIC RESISTANCE
	REPLACE_TEXTUALLY ~GA_SPCL820~ ~**** ~ // QUIVERING PALM
	REPLACE_TEXTUALLY ~AP_SPCL821~ ~**** ~ // WEAPON IMMUNITY
	REPLACE_TEXTUALLY ~AP_SPCL822~ ~**** ~ // AC BONUS

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 4 STR_VAR f_Entry = GA_SPCL811 END // STUNNING BLOW
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL812 END // MOVEMENT RATE
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL822 END // UNARMED APR
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0MN#04 END // FLURRY OF BLOWS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MN#04z END // FLURRY OF BLOWS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = AP_C0MN#04z END // FLURRY OF BLOWS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = AP_C0MN#04z END // FLURRY OF BLOWS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MN#00 END // INNATE BONUSES
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MN#13 END // INNATE BONUSES
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MN#03 END // SAVING THROWS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_Increment = 5 STR_VAR f_Entry = AP_C0MN#03 END // SAVING THROWS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0AK#EX END // EXCEPTIONAL STRENGTH
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_SPCL817 END // SAVE VS. ENCHANTMENT
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 f_Increment = 3 STR_VAR f_Entry = AP_SPCL816 END // SPEED FACTOR
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = AP_SPCL814 END // FREE ACTION
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_C0MN#06 END // AC BONUS
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_SPCL813 END // MOVEMENT RATE 2
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 7 STR_VAR f_Entry = GA_SPCL815 END // WHOLENESS OF BODY
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 11 STR_VAR f_Entry = AP_SPCL818 END // DIAMOND BODY
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_Increment = 1 f_MaxLevel = 30 STR_VAR f_Entry = AP_SPCL819 END // DIAMOND SOUL
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = AP_C0MN#14 END // QUIVERING PALM
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = GA_C0MN#05 END // EMPTY BODY
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = GA_C0MN#05 END // EMPTY BODY
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_SPCL821 END // PERFECT SELF

 	PRETTY_PRINT_2DA

COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 20) BEGIN
    // Set New Fighter Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Fighter kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0MN#04 END // FLURRY OF BLOWS
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0AK#EX END // FLURRY OF BLOWS
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 8 STR_VAR f_Entry = AP_C0MN#04Z END // FLURRY OF BLOWS
        PRETTY_PRINT_2DA

      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "C0_BRAWLER")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0MN#13 END
        PRETTY_PRINT_2DA
      END
	  
      BUT_ONLY
      END
    END
  END
  END

COPY_EXISTING ~CLABMO01.2DA~ ~OVERRIDE/CLABMO02.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL811~ ~**** ~ // STUNNING BLOW
	REPLACE_TEXTUALLY ~AP_C0MN#14~ ~**** ~ // QUIVERING PALM
	REPLACE_TEXTUALLY ~GA_SPCL815~ ~**** ~ // WHOLENESS OF BODY

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0DMM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0DMM02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 STR_VAR f_Entry = GA_C0DMM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = GA_C0DMM03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = GA_C0DMM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = GA_C0DMM04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 STR_VAR f_Entry = GA_C0DMM05 END

 	PRETTY_PRINT_2DA

COPY_EXISTING ~CLABMO01.2DA~ ~OVERRIDE/CLABMO03.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL811~ ~**** ~ // STUNNING BLOW
	REPLACE_TEXTUALLY ~AP_C0MN#14~ ~**** ~ // QUIVERING PALM
	REPLACE_TEXTUALLY ~GA_C0MN#05~ ~**** ~ // EMPTY BODY

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SSM00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0SSM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_C0SSM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0SSM02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 STR_VAR f_Entry = GA_C0SSM03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 STR_VAR f_Entry = GA_C0SSM04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 17 STR_VAR f_Entry = GA_C0SSM05 END

 	PRETTY_PRINT_2DA

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    BGCLATXT  
    clastext  
    sodcltxt 
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//BRAWLER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "C0_BRAWLER" BEGIN
          READ_2DA_ENTRY index 4 col_count brawler_desc
          SPRINT old_brawler_1 ~–无法使用圣疗术能力~
          SPRINT new_brawler_1 ~–无法使用混元体~
          SPRINT old_brawler_2 ~–不获得魔法抗性
–不免疫疾病、迟缓、加速、魅惑、毒素与非魔法武器~
          SPRINT new_brawler_2 ~–不获得感知带来的护甲等级加值
–不获得额外豁免检定
–不获得心如止水、肉身纯净、钻石身、金刚魂与超凡入圣~
          GET_STRREF %brawler_desc% brawler_text
          INNER_PATCH_SAVE brawler_text ~%brawler_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_brawler_1%~ ~%new_brawler_1%~
            REPLACE_TEXTUALLY ~%old_brawler_2%~ ~%new_brawler_2%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%brawler_desc%~ ~%brawler_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
//ENABLE MONK FOR HALFORCS___________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	COPY_EXISTING ~CLSRCREQ.2da~ ~override~
		SET_2DA_ENTRY 54 1 8 ~1~
		SET_2DA_ENTRY 54 3 8 ~1~
		SET_2DA_ENTRY 54 7 8 ~1~
		SET_2DA_ENTRY 56 1 8 ~1~
		SET_2DA_ENTRY 56 3 8 ~1~
		SET_2DA_ENTRY 56 7 8 ~1~
		SET_2DA_ENTRY 57 1 8 ~1~
		SET_2DA_ENTRY 57 3 8 ~1~
		SET_2DA_ENTRY 57 7 8 ~1~
	BUT_ONLY
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~K_MN_HO.2DA~ THEN BEGIN
COPY ~%MOD_FOLDER%/MonkRevision/K_MN_HO~ OVERRIDE
END

ACTION_IF FILE_EXISTS_IN_GAME ~K_MN_HO.2DA~ THEN BEGIN
APPEND ~K_MN_HO.2DA~ ~2    36
3    37~ UNLESS ~2    36~
END

ACTION_FOR_EACH monk_avatar IN 6500 6510 6505 6515 BEGIN
ACTION_IF FILE_EXISTS_IN_GAME ~%monk_avatar%.ini~ THEN BEGIN
COPY_EXISTING ~%monk_avatar%.ini~   ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~equip_helmet=1~~~~~
    string = EVAL ~~~~~equip_helmet=0~~~~~ //"
  END
  END
END

OUTER_SET opcode_342_eeex = 0
ACTION_IF MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~ AND FILE_EXISTS ~EEex_scripts/EEex_Opcode_Patch.lua~ THEN BEGIN
  
  PRINT ~EEex_Opcode_Patch exists.~

COPY_EXISTING ~EEex_scripts/EEex_Opcode_Patch.lua~ ~EEex_scripts~
PATCH_IF ~~ STRING_MATCHES_REGEXP ~Opcode #342~ BEGIN
  SET opcode_342_eeex = 1
  END

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN
  PRINT ~Opcode #342 has been patched.~
    END

END

ACTION_IF NOT (opcode_342_eeex = 1) THEN BEGIN

ACTION_DEFINE_ASSOCIATIVE_ARRAY monk_anims_6xxx BEGIN
    ~6500~ => ~MONK_MALE_HUMAN_1~
    ~6500a~ => ~MONK_MALE_HUMAN_2~
    ~6505~ => ~MONK_MALE_HALFORC_1~
    ~6505a~ => ~MONK_MALE_HALFORC_2~
    ~6510~ => ~MONK_FEMALE_HUMAN_1~
    ~6510a~ => ~MONK_FEMALE_HUMAN_2~
    ~6515~ => ~MONK_FEMALE_HALFORC_1~
    ~6515a~ => ~MONK_FEMALE_HALFORC_2~
  END
  ACTION_PHP_EACH monk_anims_6xxx AS animation => symbol BEGIN
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x6000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/MonkRevision\animations\%animation%.ini~ ~override/%hexNumber%.ini~
    OUTER_SET EVAL ~slot_%folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x%hexNumber% %symbol%~
END

END

ACTION_DEFINE_ASSOCIATIVE_ARRAY halforc_monk_anims_6xxx BEGIN
    ~female~ => ~MONK_FEMALE_HALFORC~
    ~male~ => ~MONK_MALE_HALFORC~
  END
  ACTION_PHP_EACH halforc_monk_anims_6xxx AS folder => symbol BEGIN
    ACTION_BASH_FOR ~%MOD_FOLDER%/MonkRevision\animations\halforc\%folder%~ ~.+\.bam~ ~%MOD_FOLDER%/MonkRevision\animations\halforc\%folder%~ ~.+\.bmp~ BEGIN
      COPY ~%BASH_FOR_FILESPEC%~ ~override~
    END
    LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0x6000 RET slot END
    LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
    COPY ~%MOD_FOLDER%/MonkRevision\animations\halforc\female/6515.ini~ ~override/6515.ini~
    COPY ~%MOD_FOLDER%/MonkRevision\animations\halforc\male/6505.ini~ ~override/6505.ini~
    COPY_EXISTING ~6500.ini~ ~override/6501.ini~
    COPY_EXISTING ~6510.ini~ ~override/6511.ini~
    OUTER_SET EVAL ~slot_%folder%~ = slot   // save animation slot number for later
    APPEND ~ANIMATE.IDS~ ~0x6501 MONK_MALE_ELF~
    APPEND ~ANIMATE.IDS~ ~0x6505 MONK_MALE_HALFORC~
    APPEND ~ANIMATE.IDS~ ~0x6511 MONK_MALE_ELF~
    APPEND ~ANIMATE.IDS~ ~0x6515 MONK_FEMALE_HALFORC~
END

// WISDOM
APPEND ~splprot.2da~ ~C0HTWIS 39 -1 1~ UNLESS ~C0HTWIS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTWIS~ BEGIN
	    SET C0HTWIS = %row%
	  END
	END
COPY ~%MOD_FOLDER%/MonkRevision/spells~ ~OVERRIDE~
	LPF ALTER_EFFECT
		INT_VAR
			match_opcode = 326
			match_special = 1000
			parameter2 = C0HTWIS
			silent = 1
	END

DEFINE_ACTION_FUNCTION mod_monk_profs BEGIN
	OUTER_SET count = 0

	ACTION_FOR_EACH class IN
                  monk

	BEGIN
		OUTER_SPRINT $monks("%count%") "%class%"
		OUTER_SET ++count
	END

	COPY_EXISTING kitlist.2da override
		READ_2DA_ENTRIES_NOW kitlist 3
		FOR (row = 2; row < kitlist; ++row) BEGIN // Skip past the vanilla kits
			READ_2DA_ENTRY_FORMER kitlist row 1 label
			READ_2DA_ENTRY_FORMER kitlist row 8 class
			PATCH_IF class = 20 BEGIN // monk
				SPRINT $monks("%count%") "%label%"
				++count
			END
		END
	BUT_ONLY

	COPY_EXISTING ~WEAPPROF.2DA~ override
		READ_2DA_ENTRIES_NOW weapprof 3
		COUNT_2DA_COLS cols
		PHP_EACH monks AS _ => name BEGIN
			FOR (col = 0; col < cols - 1; ++col) BEGIN
				READ_2DA_ENTRY_FORMER weapprof 0 col column_name
				PATCH_IF "%column_name%" STRING_EQUAL_CASE "%name%" BEGIN
					SET_2DA_ENTRY_LATER wweapprof 34 (col + 1) 1
					SET_2DA_ENTRY_LATER wweapprof 34 58 3
					SET_2DA_ENTRY_LATER wweapprof 18 58 3
				END
			END
		END
		SET_2DA_ENTRIES_NOW wweapprof 1
		PRETTY_PRINT_2DA
	BUT_ONLY
END

LAF mod_monk_profs END

INCLUDE ~%MOD_FOLDER%/lib/monk_staves.tpa~

ACTION_FOR_EACH CLASSTEXT IN CLASTEXT SODCLTXT BEGIN
ACTION_IF (FILE_EXISTS_IN_GAME ~%CLASSTEXT%.2da~) BEGIN
  COPY_EXISTING ~%CLASSTEXT%.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~MONK~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (~武僧：武僧是透过沉思和实际行动来追求完美境界的战士。他们是多才多艺的战士，尤其擅长于不穿戴护甲的徒手格斗。虽然武僧无法施法，但他们有专属的特殊法力。这种无形的能量称之为“气”，可透过它的运行展现出惊人的绝技。武僧最广为人知的绝招就是在空手格斗中击晕震慑住对手。

职业特性：

–武僧不能穿戴任何护甲。
–只能选用盗贼职业所使用的武器。
–手杖可达到宗师级精通（5星）。
–其他任意武器类最多仅能达到熟练级（1星）。
–双武器战斗、单武器战斗、双武器风格可达到熟练级（1星）。
–可使用「阴影躲藏」与「寻找陷阱」能力（但无法解除陷阱）。
–移动速度比其他角色快2点。每提升5级，移动速度再提升1点。
–徒手或持手杖时，每回合可攻击2次。
–每3级攻击速度-1。

–疾风连击：武僧徒手、持匕首或飞镖时，每回合首次攻击可额外追加一次攻击，零级命中值受-5惩罚。该额外攻击不受每回合攻击次数上限限制，且可自由切换开启。13级时，零级命中惩罚降低至-2。

–武僧的拳头造成钝击伤害，伤害随等级提升：
  1-2级：1d4
  3-4级：1d6
  5-6级：1d8
  7-9级：1d10
  10-14级：1d12
  15-19级：2d8
  20-24级：2d10
  25级及以上：2d12
  
–气：武僧的徒手攻击贯注气之力，4级时视为+1附魔魔法武器，8级+2，12级+3，16级+4，20级+5。7级起，视为银质武器。
–所有豁免检定+1。5级起每提升5级额外+1。
–智力每超过12点1点，武僧基础护甲等级+1。5级起每提升5级护甲等级额外+1。
–御箭：每3级，武僧对抗远程攻击的护甲等级+1。
–每日可使用一次「震眩拳」。1级时获得1次，之后每提升4级额外获得1次。

震眩拳：武僧在10秒内的下一次成功攻击，牺牲4点零级命中值与伤害。目标受击时必须进行死亡豁免（智力每超过14点1点，豁免难度-1），失败则震慑3回合。

–3级：心如止水：武僧对抗附魔系法术的豁免检定+2。
–5级：肉身纯净：武僧获得永久自由行动，且免疫所有疾病。
–7级：每日可使用一次「混元体」。

混元体：武僧立即回复自身每等级3点生命值。

–8级：疾风连打：疾风连击激活时，武僧每回合可额外进行第二次攻击。
–11级：钻石身：武僧永久免疫毒素。
–12级：金刚魂：武僧获得基础10%+每等级2%的魔法抗性，30级时达到上限70%。
–13级：每日可使用一次「渗透劲」。

渗透劲：武僧的最高深技法。使用后，10秒内的下一次成功攻击会在目标体内引发致命震颤，目标死亡豁免失败则立即死亡（智力每超过16点1点，豁免难度-1）。

–14级：每日可使用两次「空灵体」。

空灵体：武僧可隐入无形，获得每等级1回合的半隐形效果。攻击武僧的攻击掷骰受-4惩罚，武僧的豁免检定获得+4加值。除非能看破隐形，否则生物无法以法术锁定武僧。

–15级：内眼：武僧徒手时免疫暴击。
–20级：超凡入圣：武僧永久免疫魅惑、支配、命令、睡眠、迷宫、监禁、困惑、灵能，以及所有+1及以下附魔武器。
–阵营限制为守序。
–生命骰：d8~)
	  END
	END
  BUT_ONLY
	END
	END
  
LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~DARK_MOON~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~暗月武僧：暗月教团是信奉黑暗女神莎尔的隐秘僧侣教派。暗月武僧运用肉身技艺、黑暗魔法与种种欺瞒手段掩盖行踪，出手精准致命。

职业优势：
–侦测幻像+10%
–可为侦测幻像技能投入点数
–匕首可达到精通级（3个熟练位）。
–双武器战斗可投入3个熟练位。
–每日可使用一次「术士血脉」。6级与12级时各额外获得1次使用次数。

术士血脉：暗月教团的信徒入门时必须展现出某种法术天赋。因此所有暗月武僧都具备微弱的施法能力。本能力允许暗月武僧每日选择施展一个1环的塑能、幻术或死灵系法术。随着等级提升，可选择更强的法术：5级可选用2环，9级3环，13级4环，17级5环。

–5级：每日可使用一次「冰霜拳」。

冰霜拳：暗月武僧将幽寒能量贯注于徒手攻击中，接下来每5等级1回合内，拳头额外造成1d4魔法寒冷伤害（智力每超过14点1点，额外+1）。

–8级：每日可使用一次「毒蛇击」。

毒蛇击：暗月武僧打出狠厉一击，将腐化之气注入敌人体内。下一次徒手攻击会使目标中毒。毒素立即并在之后每回合造成伤害并降低目标体质，至少持续4回合。4回合后，目标必须进行死亡豁免，失败则再中毒4回合。因此只要目标未成功豁免，毒素就有可能无限持续。目标不会因毒素造成的体质流失而死亡。

1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。

–13级：每日可使用一次「黯影碾压」。

黯影碾压：暗月武僧释放气劲，形成心灵能量波席卷15尺范围内所有生物，施以压倒性绝望，造成10d6魔法伤害并吸取2个等级。每被本能力击杀一个目标，暗月武僧回复最大生命值的15%，并临时获得零级命中值与伤害+2，持续6回合。

–17级：每日可使用一次「月蚀」。

月蚀：暗月武僧周身环绕寒雾一回合，免疫寒冷伤害，力量、敏捷、体质+4。任何在范围内以武器或法术击中暗月武僧的对手，受到1d8+1点寒冷伤害，且必须进行法术豁免，失败则被吸取，额外受到1d6魔法伤害与1点零级命中值，该值临时转移给暗月武僧，持续2回合。

–20级：绝望使者：施放黯影碾压后，暗月武僧从受害者的痛苦中汲取力量，接下来3回合伤害额外+4。此外，在这3回合内击杀任何生物，都能获得与黯影碾压击杀相同的效果，并刷新强化持续时间。

职业限制：
–阵营限制为守序邪恶。
–无法习得日耀或雷霆架势。
–无法使用「震眩拳」能力。
–无法使用「渗透劲」能力。
–无法使用「混元体」能力。~

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~SUN_SOUL~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~日魂武僧：日魂武僧曾是耐瑟瑞尔时代阿曼纳塔的信徒，如今他们分奉洛山达、塞伦涅与苏伦。日魂武僧严守律法，以武道与魔法之力驱逐所见之处的黑暗与腐化。

职业优势：
–免疫目盲与等级吸取。
–每日可使用一次「日魂射线」。5级起每提升5级额外获得1次使用次数。

日魂射线：日魂武僧可凝聚能量形成耀眼光矢。光矢可作为远程投掷物，攻击掷骰+5。每发造成1d4+1点魔法伤害与3点额外魔法火焰伤害（对亡灵为10点），视为+4武器。日魂武僧可生成5发（每5级武僧等级额外+1发），每回合最多投掷5发。

–5级：每日可使用一次「燃烧之拳」。

燃烧之拳：日魂武僧将内在光芒贯注于徒手攻击中，将双拳化为烈焰武器，接下来每5等级1回合内，额外造成1d4魔法火焰伤害（智力每超过14点1点，额外+1）。

–8级：每日可使用一次「灼炎弧击」。

灼炎弧击：日魂武僧在拳中聚气，凝成白热焰浪。武僧下一次成功近战攻击释放出90度锥形火焰，造成5d6魔法火焰伤害并严重灼伤所有目标，使其护甲等级、零级命中值与伤害降低4点，且每回合额外受到1d6魔法火焰伤害，持续1回合，法术豁免成功则无效。此外，所有隐形目标破除隐形，无豁免。

–13级：每日可使用一次「日魂光束」。

日魂光束：日魂武僧以光之巨柱释放气劲，对所有敌人造成10d6魔法伤害，并致盲1回合。亡灵生物必须进行法术豁免，失败则直接被摧毁。

–17级：每日可使用一次「圣日术」。

圣日术：日魂武僧周身环绕光焰一回合，免疫火焰伤害，所有来源造成的火焰伤害提升30%。任何在范围内以武器或法术击中日魂武僧的对手，受到1d8+1点魔法火焰伤害，且必须进行法术豁免，失败则额外受到1d8魔法火焰伤害并致盲1回合。

–20级：阳炎化身：施放日魂光束后，日魂武僧持续散发光芒3回合，护甲等级+6，挥砍、穿刺、钝击与远程伤害抗性+30%。15尺范围内的所有敌人每回合受到1d6魔法伤害，且必须进行-2惩罚的法术豁免，失败则致盲1回合。

职业限制：
–阵营限制为守序善良。
–无法习得月辉或暗影架势。
–无法使用「震眩拳」能力。
–无法使用「渗透劲」能力。
–无法使用「空灵体」能力。~

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~疾风连击~) STR_VAR bam_file = C0MN#04I RET C0MN#04I = icon END

COPY_EXISTING ~clswpbon.2da~ ~override~
  COUNT_2DA_COLS numCols
  COUNT_2DA_ROWS numCols numRows
  FOR (row = 0; row < numRows; row += 1) BEGIN
    SET_2DA_ENTRY row 2 numCols ~0~
  END
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "DARK_MOON" = 0) BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count (val+10)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~MFIST1.ITM~ OVERRIDE
SAY NAME1 ~拳头~
SAY NAME2 ~拳头~
COPY_EXISTING ~MFIST2.ITM~ OVERRIDE
SAY NAME1 ~拳头~
SAY NAME2 ~拳头~
COPY_EXISTING ~MFIST3.ITM~ OVERRIDE
SAY NAME1 ~拳头+1~
SAY NAME2 ~拳头+1~
COPY_EXISTING ~MFIST4.ITM~ OVERRIDE
SAY NAME1 ~拳头+1~
SAY NAME2 ~拳头+1~
COPY_EXISTING ~MFIST5.ITM~ OVERRIDE
SAY NAME1 ~拳头+1~
SAY NAME2 ~拳头+1~
COPY_EXISTING ~MFIST6.ITM~ OVERRIDE
SAY NAME1 ~拳头+2~
SAY NAME2 ~拳头+2~
COPY_EXISTING ~MFIST7.ITM~ OVERRIDE
SAY NAME1 ~拳头+2~
SAY NAME2 ~拳头+2~
COPY_EXISTING ~MFIST8.ITM~ OVERRIDE
SAY NAME1 ~拳头+3~
SAY NAME2 ~拳头+3~
COPY_EXISTING ~MFIST9.ITM~ OVERRIDE
SAY NAME1 ~拳头+3~
SAY NAME2 ~拳头+3~
COPY_EXISTING ~MFIST10.ITM~ OVERRIDE
SAY NAME1 ~拳头+4~
SAY NAME2 ~拳头+4~
COPY_EXISTING ~MFIST11.ITM~ OVERRIDE
SAY NAME1 ~拳头+5~
SAY NAME2 ~拳头+5~
COPY_EXISTING ~MFIST12.ITM~ OVERRIDE
SAY NAME1 ~拳头+5~
SAY NAME2 ~拳头+5~

COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HUMAN_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_BYTE 0x90 1
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#042.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HUMAN_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#042~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#043.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HUMAN_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_ASCII 0x94 ~C0MN#043~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#044.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HUMAN_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#044~

COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#045.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HALFORC_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_ASCII 0x94 ~C0MN#045~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#046.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_MALE_HALFORC_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#046~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#047.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HALFORC_1~)
WRITE_BYTE 0x54 0
WRITE_BYTE 0x58 7
WRITE_ASCII 0x94 ~C0MN#047~
COPY_EXISTING ~C0MN#041.EFF~ ~OVERRIDE/C0MN#048.EFF~
WRITE_SHORT 0x1c IDS_OF_SYMBOL (~ANIMATE~ ~MONK_FEMALE_HALFORC_2~)
WRITE_BYTE 0x54 8
WRITE_BYTE 0x58 0
WRITE_ASCII 0x94 ~C0MN#048~

COPY_EXISTING ~C0MN#04.SPL~ OVERRIDE
SAY NAME1 ~疾风连击~
SAY UNIDENTIFIED_DESC ~疾风连击
武僧徒手、持匕首或飞镖时，每回合首次攻击可额外追加一次攻击，零级命中值受-5惩罚。该额外攻击不受每回合攻击次数上限限制，且可自由切换开启。13级时，零级命中惩罚降低至-2。~

COPY_EXISTING ~C0MN#04B.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~疾风连击已激活~) END
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0MN#04I END

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN
  COPY ~%MOD_FOLDER%/MonkRevision/eeex/C0MN#04B.SPL~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~疾风连击已激活~) END
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0MN#04I END
  COPY ~%MOD_FOLDER%/MonkRevision/eeex/C0MN#04X.SPL~ ~override~
END

COPY_EXISTING ~C0MN#04Y.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~疾风连击已解除~) END
COPY_EXISTING ~C0MN#04Y.SPL~ ~OVERRIDE/C0MN#04V.SPL~
COPY_EXISTING ~C0MN#04Z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~疾风连击已解除~) END

COPY_EXISTING ~C0MN#05.SPL~ OVERRIDE
SAY NAME1 ~空灵体~
SAY UNIDENTIFIED_DESC ~空灵体
武僧可隐入无形，获得每等级1回合的半隐形效果。攻击武僧的攻击掷骰受-4惩罚，武僧的豁免检定获得+4加值。除非能看破隐形，否则生物无法以法术锁定武僧。~

COPY_EXISTING ~SPCL811.SPL~ OVERRIDE
SAY NAME1 ~震眩拳~
SAY UNIDENTIFIED_DESC ~震眩拳
武僧在10秒内的下一次成功攻击，牺牲4点零级命中值与伤害。目标受击时必须进行死亡豁免（智力每超过14点1点，豁免难度-1），失败则震慑3回合。~

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 8 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00B END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 7 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00C END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 6 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00D END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 5 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00E END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 4 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00F END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 3 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00G END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 2 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00H END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 1 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00I END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 0 parameter1 = 0 END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00J END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00K.SPL~
LPF ALTER_EFFECT_EX INT_VAR match_opcode = 0 STR_VAR parameter1_ex = ~"-1"~ END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00K END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00L.SPL~
LPF ALTER_EFFECT_EX INT_VAR match_opcode = 0 STR_VAR parameter1_ex = ~"-2"~ END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00L END

COPY_EXISTING ~C0MN#00A.SPL~ ~OVERRIDE/C0MN#00M.SPL~
LPF ALTER_EFFECT_EX INT_VAR match_opcode = 0 STR_VAR parameter1_ex = ~"-3"~ END
LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = C0MN#00M END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01B END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01C END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01D END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01E END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01F END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01G END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01H END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01I END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01J END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01K.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01K END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01L.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01L END

COPY_EXISTING ~C0MN#01A.SPL~ ~OVERRIDE/C0MN#01M.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#01M END

COPY_EXISTING ~C0MN#01Z.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~震慑~) END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02B END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02C END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02D END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02E END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02F END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02G END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02H END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02I END

COPY_EXISTING ~C0MN#02A.SPL~ ~OVERRIDE/C0MN#02J.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 248 STR_VAR resource = C0MN#02J END

COPY_EXISTING ~SPCL815.SPL~ OVERRIDE
SAY NAME1 ~混元体~
SAY UNIDENTIFIED_DESC ~混元体
武僧立即回复自身每等级3点生命值。~

COPY_EXISTING ~SPCL820.SPL~ OVERRIDE
SAY NAME1 ~渗透劲~
SAY UNIDENTIFIED_DESC ~渗透劲
武僧的最高深技法。使用后，10秒内的下一次成功攻击会在目标体内引发致命震颤，目标死亡豁免失败则立即死亡（智力每超过16点1点，豁免难度-1）。~

COPY_EXISTING ~SPCL821.SPL~ OVERRIDE
SAY NAME1 ~超凡入圣~

COPY_EXISTING ~C0MN#H01.SPL~ OVERRIDE
SAY NAME1 ~日耀架势~
SAY UNIDENTIFIED_DESC ~日耀架势
武僧将气劲化为炽热烈焰，爆发出白炙火浪。15尺范围内的所有目标受到1d8钝击伤害与12d6火焰伤害（法术豁免减半），并被击飞短暂震晕。之后武僧身裹烈焰，接下来5回合徒手攻击额外造成2d6+1火焰伤害。5尺内攻击武僧的对手也会受到2d6+1火焰伤害。

同一时间仅可激活一种架势。使用其他架势会覆盖先前架势的效果。~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0mn#h1p.PRO~
COPY_EXISTING ~C0MN#H1A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0mn#h1p END

COPY_EXISTING ~C0MN#H02.SPL~ OVERRIDE
SAY NAME1 ~月辉架势~
SAY UNIDENTIFIED_DESC ~月辉架势
武僧释放气劲，化作月华光浪。武僧视野范围内的所有敌人必须进行-5惩罚的死亡豁免，失败则致盲5回合。豁免成功的目标也仍会致盲1回合。残光萦绕武僧周身，使其身形朦胧半透。接下来5回合，武僧对抗所有武器的护甲等级与所有豁免检定+10，获得半隐形，所有伤害抗性+50%。

同一时间仅可激活一种架势。使用其他架势会覆盖先前架势的效果。~

COPY_EXISTING ~C0MN#H03.SPL~ OVERRIDE
SAY NAME1 ~暗影架势~
SAY UNIDENTIFIED_DESC ~暗影架势
武僧将气劲遍布全身，进入完全隐形与空灵体状态，持续5回合。此状态下武僧不会受到伤害，也无法被锁定，即便能看破隐形的生物也不行。武僧的下一次攻击会解除空灵体状态，并瞄准弱点造成3倍背刺伤害。目标还会额外受到5d10魔法伤害，且护甲等级降低10，持续1回合。

同一时间仅可激活一种架势。使用其他架势会覆盖先前架势的效果。~

COPY_EXISTING ~C0MN#H04.SPL~ OVERRIDE
SAY NAME1 ~雷霆架势~
SAY UNIDENTIFIED_DESC ~雷霆架势
武僧将气劲化为神秘闪电，化作毁灭性雷暴席卷敌人。15尺范围内的所有敌人被闪电击中，受到4d6电击伤害。闪电随即跳向附近敌人，额外造成2d6电击伤害。接下来5回合，武僧的徒手攻击会迸出能量锥，造成2d6电击伤害，并以武僧等级驱散目标身上的效果。

同一时间仅可激活一种架势。使用其他架势会覆盖先前架势的效果。~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0mn#h4p.PRO~
COPY_EXISTING ~C0MN#H4A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0mn#h4p END

COPY_EXISTING ~C0MN#H05.SPL~ OVERRIDE
SAY NAME1 ~龙拳~
SAY UNIDENTIFIED_DESC ~龙拳
武僧将集中的气劲贯注双拳，短时间内攻击精准无匹。使用本能力后，下回合所有徒手攻击掷骰均视为自然20，必定暴击。~

COPY_EXISTING ~C0MN#H06.SPL~ OVERRIDE
SAY NAME1 ~猛虎击~
SAY UNIDENTIFIED_DESC ~猛虎击
武僧蓄气准备猛虎扑击般的强力跳击。一回合内的下一次徒手攻击必定暴击，并将目标击飞震慑3回合。攻击用尽前，武僧移动速度翻倍。

需要：龙拳~

COPY_EXISTING ~C0MN#H07.SPL~ OVERRIDE
SAY NAME1 ~千手~
SAY UNIDENTIFIED_DESC ~千手
本能力让武僧爆发出肉眼难辨的极速徒手连打。接下来2回合，武僧徒手状态下每回合攻击次数变为10次。~

COPY_EXISTING ~C0MN#H08.SPL~ OVERRIDE
SAY NAME1 ~瞬身步~
SAY UNIDENTIFIED_DESC ~瞬身步
本能力让武僧以气劲催动身形，快到近乎瞬移般移动到视野内指定位置。习得后每日可无限制使用。~

COPY_EXISTING ~C0MN#H15.SPL~ OVERRIDE
SAY NAME1 ~宗师之道~
SAY UNIDENTIFIED_DESC ~宗师之道
武僧已将基础技法修至化境，可习得一项由自身道德阵营决定的终极能力。善良阵营武僧习得「宁神掌」，中立阵营习得「衡平击」，邪恶阵营习得「杀戮之手」。

宁神掌
旨在制敌而非杀生的技法。武僧10秒内的下一次成功徒手攻击会短暂扰乱目标认知，使其2回合内无法行动，效果同「愚钝术」。持续时间结束后，目标接下来4回合造成的所有伤害降低66%。

衡平击
武僧引导气劲发动制衡一击，对自身与目标同时施加平衡状态。武僧10秒内的下一次成功徒手攻击，对自身与目标各造成相当于其剩余生命值一半的伤害。该伤害无法以任何方式减免。

杀戮之手
渗透劲技法的残暴进阶版，唯有冷酷无情者方能掌握。武僧10秒内的下一次成功徒手攻击，目标必须进行死亡豁免（智力每超过16点1点，豁免难度-1），失败则死亡。武僧获得临时生命值，数值等于目标死亡前剩余的生命值，持续1回合。~

COPY_EXISTING ~C0MN#H09.SPL~ OVERRIDE
SAY NAME1 ~宁神掌~
SAY UNIDENTIFIED_DESC ~宁神掌
旨在制敌而非杀生的技法。武僧10秒内的下一次成功徒手攻击会短暂扰乱目标认知，使其2回合内无法行动，效果同「愚钝术」。持续时间结束后，目标接下来4回合造成的所有伤害降低66%。~

COPY_EXISTING ~C0MN#H10.SPL~ OVERRIDE
SAY NAME1 ~衡平击~
SAY UNIDENTIFIED_DESC ~衡平击
武僧引导气劲发动制衡一击，对自身与目标同时施加平衡状态。武僧10秒内的下一次成功徒手攻击，对自身与目标各造成相当于其剩余生命值一半的伤害。该伤害无法以任何方式减免。~

COPY_EXISTING ~C0MN#H11.SPL~ OVERRIDE
SAY NAME1 ~杀戮之手~
SAY UNIDENTIFIED_DESC ~杀戮之手
渗透劲技法的残暴进阶版，唯有冷酷无情者方能掌握。武僧10秒内的下一次成功徒手攻击，目标必须进行死亡豁免（智力每超过16点1点，豁免难度-1），失败则死亡。武僧获得临时生命值，数值等于目标死亡前剩余的生命值，持续1回合。~

COPY_EXISTING ~C0MN#H12.SPL~ OVERRIDE
SAY NAME1 ~强化金刚魂~
SAY UNIDENTIFIED_DESC ~强化金刚魂
武僧对气劲的掌握足以抵挡更强的魔法效果。每选择一次本能力，武僧永久获得+5%魔法抗性与+1豁免检定。

强化金刚魂最多可选择2次。~

COPY_EXISTING ~C0MN#H13.SPL~ OVERRIDE
SAY NAME1 ~无垢之身~
SAY UNIDENTIFIED_DESC ~无垢之身
武僧的气劲已修至极高深境界，足以永久维持自身生机。习得本能力后，武僧实质上成为不灭之躯，无需进食也无需休息。因此武僧移动速度翻倍，获得永久灵气净化，且再也不会疲劳。~

COPY_EXISTING ~C0MN#H14.SPL~ OVERRIDE
SAY NAME1 ~额外渗透劲~
SAY UNIDENTIFIED_DESC ~额外渗透劲
武僧每日可额外使用一次渗透劲。本能力最多可选择3次。~

COPY_EXISTING ~C0DMM01.SPL~ OVERRIDE
SAY NAME1 ~术士血脉~
SAY UNIDENTIFIED_DESC ~术士血脉
暗月教团的信徒入门时必须展现出某种法术天赋。因此所有暗月武僧都具备微弱的施法能力。本能力允许暗月武僧每日选择施展一个1环的塑能、幻术或死灵系法术。随着等级提升，可选择更强的法术：5级可选用2环，9级3环，13级4环，17级5环。~

COPY_EXISTING ~C0DMM02.SPL~ OVERRIDE
SAY NAME1 ~冰霜拳~
SAY UNIDENTIFIED_DESC ~冰霜拳
暗月武僧将幽寒能量贯注于徒手攻击中，接下来每5等级1回合内，拳头额外造成1d4寒冷伤害（智力每超过14点1点，额外+1）。~

COPY_EXISTING ~C0DMM03.SPL~ OVERRIDE
SAY NAME1 ~毒蛇击~
SAY UNIDENTIFIED_DESC ~毒蛇击
暗月武僧打出狠厉一击，将腐化之气注入敌人体内。下一次徒手攻击会使目标中毒。毒素立即并在之后每回合造成伤害并降低目标体质，至少持续4回合。4回合后，目标必须进行死亡豁免，失败则再中毒4回合。因此只要目标未成功豁免，毒素就有可能无限持续。目标不会因毒素造成的体质流失而死亡。

1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。~

COPY_EXISTING ~C0DMM04.SPL~ OVERRIDE
SAY NAME1 ~黯影碾压~
SAY UNIDENTIFIED_DESC ~黯影碾压
暗月武僧释放气劲，形成心灵能量波席卷15尺范围内所有生物，施以压倒性绝望，造成10d6魔法伤害并吸取2个等级。每被本能力击杀一个目标，暗月武僧回复最大生命值的15%，并临时获得零级命中值与伤害+2，持续6回合。~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0dmm04p.PRO~
COPY_EXISTING ~C0DMM04D.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0dmm04p END

COPY_EXISTING ~C0DMM05.SPL~ OVERRIDE
SAY NAME1 ~月蚀~
SAY UNIDENTIFIED_DESC ~月蚀
暗月武僧周身环绕寒雾一回合，免疫寒冷伤害，力量、敏捷、体质+4。任何在范围内以武器或法术击中暗月武僧的对手，受到1d8+1点寒冷伤害，且必须进行法术豁免，失败则被吸取，额外受到1d6魔法伤害与1点零级命中值，该值临时转移给暗月武僧，持续2回合。~

COPY_EXISTING ~C0SSM01.SPL~ OVERRIDE
SAY NAME1 ~日魂射线~
SAY UNIDENTIFIED_DESC ~日魂射线
日魂武僧可凝聚能量形成耀眼光矢。光矢可作为远程投掷物，攻击掷骰+5。每发造成1d4+1点魔法伤害与3点额外魔法火焰伤害（对亡灵为10点），视为+4武器。日魂武僧可生成5发（每5级武僧等级额外+1发），每回合最多投掷5发。~

COPY_EXISTING ~C0SSMBO1.SPL~ OVERRIDE
SAY NAME1 ~日魂射线~
SAY NAME2 ~日魂射线~

COPY_EXISTING ~C0SSM02.SPL~ OVERRIDE
SAY NAME1 ~燃烧之拳~
SAY UNIDENTIFIED_DESC ~燃烧之拳
日魂武僧将内在光芒贯注于徒手攻击中，将双拳化为烈焰武器，接下来每5等级1回合内，额外造成1d4火焰伤害（智力每超过14点1点，额外+1）。~

COPY_EXISTING ~C0SSM03.SPL~ OVERRIDE
SAY NAME1 ~灼炎弧击~
SAY UNIDENTIFIED_DESC ~灼炎弧击
日魂武僧在拳中聚气，凝成白热焰浪。武僧下一次成功近战攻击释放出90度锥形火焰，造成5d6魔法火焰伤害并严重灼伤所有目标，使其护甲等级、零级命中值与伤害降低4点，且每回合额外受到1d6火焰伤害，持续1回合，法术豁免成功则无效。此外，所有隐形目标破除隐形，无豁免。~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/projectiles/c0ssm04p.PRO~
COPY_EXISTING ~C0SSM04.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER INT_VAR projectile = c0ssm04p END
SAY NAME1 ~日魂光束~
SAY UNIDENTIFIED_DESC ~日魂光束
日魂武僧以光之巨柱释放气劲，对所有敌人造成10d6魔法伤害，并致盲1回合。亡灵生物必须进行法术豁免，失败则直接被摧毁。~

COPY_EXISTING ~C0SSM05.SPL~ OVERRIDE
SAY NAME1 ~圣日术~
SAY UNIDENTIFIED_DESC ~圣日术
日魂武僧周身环绕光焰一回合，免疫火焰伤害，所有来源造成的火焰伤害提升30%。任何在范围内以武器或法术击中日魂武僧的对手，受到1d8+1点魔法火焰伤害，且必须进行法术豁免，失败则额外受到1d8魔法火焰伤害并致盲1回合。~

INCLUDE ~%MOD_FOLDER%/effects/poison_weapon.tpa~

//// DARK MOON MONK SPELLCASTING

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN
INCLUDE ~%MOD_FOLDER%/lib/replace_multiline.tpa~

COPY ~%MOD_FOLDER%/lua/m_c0dmm1.lua~      ~override~

COPY_EXISTING ~SPWI106.spl~ ~override/C0DM101.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI112.spl~ ~override/C0DM102.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI120.spl~ ~override/C0DM103.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI125.spl~ ~override/C0DM104.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI201.spl~ ~override/C0DM201.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI205.spl~ ~override/C0DM202.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI212.spl~ ~override/C0DM203.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI223.spl~ ~override/C0DM204.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI307.spl~ ~override/C0DM301.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI308.spl~ ~override/C0DM302.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI314.spl~ ~override/C0DM303.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI315.spl~ ~override/C0DM304.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI403.spl~ ~override/C0DM401.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI405.spl~ ~override/C0DM402.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI409.spl~ ~override/C0DM403.spl~
WRITE_SHORT 0x1C 3 
COPY_EXISTING ~SPWI414.spl~ ~override/C0DM404.spl~
WRITE_SHORT 0x1C 3 

COPY_EXISTING_REGEXP GLOB ~.+\.CRE~ ~override~
    READ_BYTE 0x234 level1
      READ_ASCII DEATHVAR "dv" (32) NULL
      PATCH_IF (~%dv%~ STR_EQ ~RASAAD~) BEGIN
      WRITE_BYTE 0x48 10
    END
    
///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//dark_moon
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "DARK_MOON" BEGIN
          READ_2DA_ENTRY index 4 col_count dark_moon_desc
          SPRINT old_dark_moon ~SORCEROUS LINEAGE: Disciples of the Order of the Dark Moon must display some sort of sorcerous power during their initiation. As such, All Dark Moon Monks have a minor level of magical ability. This ability allows the Dark Moon Monk to cast a level 1 Invocation, Illusion or Necromancy spell of choice once per day. As the Dark Moon Monk gains in levels, stronger spells may be chosen, gaining level 2 spells at 5th level, level 3 spells at 9th level, level 4 spells at 13th level and level 5 spells at 17th level.~
          SPRINT new_dark_moon ~术士血脉：暗月教团的信徒入门时必须展现出某种法术天赋。因此所有暗月武僧都具备微弱的施法能力，可像法师一样施展有限的塑能、幻术与死灵学派法术。暗月武僧随等级提升获得更强力的法术：5级可选用2环，9级3环，13级4环。习得法术如下：
  1环：目盲术、魔法飞弹、镜像术、惊恐术
  2环：模糊术、造影术、恐慌术、耳聋术
  3环：群体隐形、闪电箭、吸血之触、幽魂形态
  4环：火焰护盾（冰）、高级隐形、疫病术、灵魂护甲~
          GET_STRREF %dark_moon_desc% dark_moon_text
          INNER_PATCH_SAVE dark_moon_text ~%dark_moon_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_dark_moon%~ ~%new_dark_moon%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%dark_moon_desc%~ ~%dark_moon_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
  
ACTION_IF FILE_EXISTS_IN_GAME ~CLABMO02.2DA~ BEGIN
COPY_EXISTING ~CLABMO02.2DA~ ~OVERRIDE~
  REPLACE_TEXTUALLY ~GA_C0DMM01~ ~****      ~
COPY_EXISTING ~CLABMO02.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM101 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM102 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM103 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0DM104 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM201 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM202 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM203 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0DM204 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM301 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM302 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM303 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = GA_C0DM304 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM401 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM402 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM403 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13 f_MaxLevel = 13 STR_VAR f_Entry = GA_C0DM404 END
  PRETTY_PRINT_2DA
BUT_ONLY
END
END
