COPY ~%MOD_FOLDER%/Paladin/MysticFire/2da~ ~override~
COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells~ ~override~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/C0MF.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE
	REPLACE_TEXTUALLY ~GA_SPCL213 ~ ~**** ~ // PROTECTION FROM EVIL
	// REPLACE_TEXTUALLY ~GA_SPCL212 ~ ~**** ~ // DETECT EVIL
	REPLACE_TEXTUALLY ~GA_SPCL211 ~ ~**** ~ // LAY ON HANDS
	REPLACE_TEXTUALLY ~GA_C0PAL02 ~ ~**** ~ // SMITE EVIL
	// REPLACE_TEXTUALLY ~SPCL111 ~ ~**** ~ // CURE DISEASE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0MF#1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MF#2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = AP_C0MF#2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MF#3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0MF#4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL235 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0MF01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_Increment = 6 STR_VAR f_Entry = GA_C0MF01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0MF02 END

 	PRETTY_PRINT_2DA

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 6
	
    mixed         = RESOLVE_STR_REF(~秘火骑士~)
	
    lower         = RESOLVE_STR_REF(~秘火骑士~)
	
    help          = RESOLVE_STR_REF(~秘火骑士：秘火骑士是侍奉魔法女神蜜斯特拉的圣武士。他们既精通近战格斗，也擅长奥术魔法。除了恪守圣武士的传统美德外，秘火骑士还将毕生精力投入到古老魔法的发掘与研习之中。

职业优势：
–每等级学识+2。
–每等级可额外施展两个法术。
–对抗法术的豁免检定+1。5级起每提升5级额外+1。
–秘火骑士施法时，视为同等级的牧师。
–可记诵少量法师法术：
 1环：魔法飞弹、电击掌、护盾术、召唤魔宠
 2环：镜像术、蛛网术、阿加纳扎灼击术、隐形术
 3环：火球术、闪电箭、加速术、初级法术偏转
 4环：高等厄运诅咒、火焰护盾·赤、石肤术、秘语术
<MF_LEVEL5><MF_LEVEL6><MF_LEVEL7>
–每日可使用一次「破法术击」，之后每提升6级额外获得1次使用次数。
 
破法术击：秘火骑士可制裁施法者，扰乱其防御法术与施法能力。两回合内秘火骑士的下一次攻击会驱散目标的战斗防护效果。此外，若目标法术豁免失败（难度-2），则两回合内法术失败率为100%。

–5级起，每日可使用一次「法术之刃」。

法术之刃：秘火骑士为自身武器附魔一小时，武器获得+3附魔等级，额外造成1d4魔法伤害（每5级+1d4，20级上限），且每次命中降低目标5%魔法抗性，持续2回合。12级时附魔提升至+4，18级时提升至+5。

–12级：战斗施法：秘火骑士精于战斗中施法。若5尺内存在敌人，施法速度+2。

职业限制：
–生命骰：d8
–无法习得以下高阶能力：高等旋风攻击、高等致命一击、制裁、强健
–不获得勇气光环。
–无法使用破邪斩。
–无法使用防护邪恶。
–无法驱散不死生物。
–无法使用圣疗术。~)
	
    briefdesc     = RESOLVE_STR_REF(~秘火骑士：秘火骑士是侍奉魔法女神蜜斯特拉的圣武士。他们既精通近战格斗，也擅长奥术魔法，毕生致力于古老魔法的发掘与研习。~)
	
	// fallen = 1
	
  STR_VAR
    kit_name      = ~C0MF~
	
    unusable      = ~0x00000000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 2 2 2 3~
	
    abclasrq      = ~9 0 9 13 13 17~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0MF~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0MF.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~hpprs~
	
    // numwslot      = ~4~
	
    clascolr = ~64 127 18 96 27~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

INCLUDE ~%MOD_FOLDER%/effects/combat_casting.tpa~

COPY_EXISTING ~C0MF.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0EKCC END // COMBAT CASTING
  PRETTY_PRINT_2DA

COPY_EXISTING ~LUPA0.2da~ ~override/LUC0MF.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL901~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL903~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL907~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL909~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL923~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0MF1~ ability = ~AP_C0MFHL1~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MF2~ ability = ~AP_C0MFHL2~ num_allowed = 1 prerequisite = ~AP_C0MFHL1~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MF3~ ability = ~AP_C0MFHL3~ num_allowed = 1 prerequisite = ~AP_C0MFHL2~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MF4~ ability = ~AP_C0MFHL4~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MF5~ ability = ~AP_C0MFHL5~ num_allowed = 1 prerequisite = ~AP_C0MFHL4~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MF6~ ability = ~AP_C0MFHL6~ num_allowed = 1 prerequisite = ~AP_C0MFHL5~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0MF7~ ability = ~AP_C0MFHL7~ num_allowed = 1 prerequisite = ~AP_C0MFHL6~ END	

COPY_EXISTING ~SPWI112.SPL~ ~OVERRIDE/C0MF101.SPL~
WRITE_SHORT 0X1C 2
COPY ~%MOD_FOLDER%/Paladin/MysticFire/SPELLS/C0MF102.SPL~ ~OVERRIDE~
SAY NAME1 ~电击掌~
SAY UNIDENTIFIED_DESC ~电击掌
（变化系）

等级：1
射程：触碰
持续时间：特殊
施法时间：1
影响范围：1个生物
豁免检定：无

这一改良版电击掌可让秘火骑士将能量贯注于近战武器而非手掌。法术生效期间，秘火骑士触碰生物时，电流会对目标造成1d8+每等级1点伤害。此外，该攻击视为+6武器。秘火骑士仅有一次充能，命中目标后法术能量即消耗完毕。秘火骑士有每等级1回合的时间来触碰目标。~
COPY ~%MOD_FOLDER%/Paladin/MysticFire/SPELLS/C0MF102a.SPL~ ~OVERRIDE~
COPY_EXISTING ~SPWI114.SPL~ ~OVERRIDE/C0MF103.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI123.SPL~ ~OVERRIDE/C0MF104.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI206.SPL~ ~OVERRIDE/C0MF201.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI217.SPL~ ~OVERRIDE/C0MF202.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI212.SPL~ ~OVERRIDE/C0MF203.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI215.SPL~ ~OVERRIDE/C0MF204.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI304.SPL~ ~OVERRIDE/C0MF301.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI305.SPL~ ~OVERRIDE/C0MF302.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI308.SPL~ ~OVERRIDE/C0MF303.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI318.SPL~ ~OVERRIDE/C0MF304.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI408.SPL~ ~OVERRIDE/C0MF401.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI412.SPL~ ~OVERRIDE/C0MF402.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI418.SPL~ ~OVERRIDE/C0MF403.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI419.SPL~ ~OVERRIDE/C0MF404.SPL~
WRITE_SHORT 0X1C 2
COPY_EXISTING ~SPWI510.SPL~ ~OVERRIDE/C0MF501.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI515.SPL~ ~OVERRIDE/C0MF502.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI523.SPL~ ~OVERRIDE/C0MF503.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI503.SPL~ ~OVERRIDE/C0MF504.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI602.SPL~ ~OVERRIDE/C0MF601.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI611.SPL~ ~OVERRIDE/C0MF602.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI613.SPL~ ~OVERRIDE/C0MF603.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI618.SPL~ ~OVERRIDE/C0MF604.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI722.SPL~ ~OVERRIDE/C0MF701.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI705.SPL~ ~OVERRIDE/C0MF702.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI716.SPL~ ~OVERRIDE/C0MF703.SPL~
WRITE_SHORT 0x1C 3
COPY_EXISTING ~SPWI701.SPL~ ~OVERRIDE/C0MF704.SPL~
WRITE_SHORT 0x1C 3

COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mf01.spl~ ~override~
SAY NAME1 ~破法术击~
SAY NAME2 ~破法术击~
SAY UNIDENTIFIED_DESC ~破法术击
秘火骑士可制裁施法者，扰乱其防御法术与施法能力。两回合内秘火骑士的下一次攻击会驱散目标的战斗防护效果。此外，若目标法术豁免失败（难度-2），则两回合内法术失败率为100%。~
COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mf01a.spl~ ~override~
	LPF ALTER_EFFECT
		INT_VAR
			match_opcode = 139
			match_parameter2 = 1
			parameter1 = RESOLVE_STR_REF (~法术防护已移除~)
		END
	LPF ALTER_EFFECT
		INT_VAR
			match_opcode = 139
			match_parameter2 = 0
			parameter1 = RESOLVE_STR_REF (~法术失控~)
		END
 
ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~c0mf01.spl~ ~override~
SAY UNIDENTIFIED_DESC ~破法术击
秘火骑士可制裁施法者，扰乱其防御法术与施法能力。两回合内秘火骑士的下一次攻击会驱散目标的战斗防护效果。此外，若目标法术豁免失败（难度-2），则两回合内法术失败率为100%。

破法术击的效果无视所有武器防护，即便攻击本身被招架也依然生效。~
 
OUTER_SET mystic_fire_ids = IDS_OF_SYMBOL (~kit~ ~C0MF~)
  
COPY ~%MOD_FOLDER%/lua/m_c0pal1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%mystic_fire_ids%~~~~~ //"
  END

END

COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mf02.spl~ ~override~
SAY NAME1 ~法术之刃~
SAY NAME2 ~法术之刃~
SAY UNIDENTIFIED_DESC ~法术之刃
秘火骑士为自身武器附魔一小时，武器获得+3附魔等级，额外造成1d4魔法伤害（每5级+1d4，20级上限），且每次命中降低目标5%魔法抗性，持续2回合。12级时附魔提升至+4，18级时提升至+5。~

COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl1.spl~ ~override~
SAY NAME1 ~额外1环法术~
SAY NAME2 ~额外1环法术~
SAY UNIDENTIFIED_DESC ~额外1环法术
选择本能力可让秘火骑士额外施展一个1环法术。~
 
COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl2.spl~ ~override~
SAY NAME1 ~额外2环法术~
SAY NAME2 ~额外2环法术~
SAY UNIDENTIFIED_DESC ~额外2环法术
选择本能力可让秘火骑士额外施展一个2环法术。

需要：额外1环法术~
 
COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl3.spl~ ~override~
SAY NAME1 ~额外3环法术~
SAY NAME2 ~额外3环法术~
SAY UNIDENTIFIED_DESC ~额外3环法术
选择本能力可让秘火骑士额外施展一个3环法术。

需要：额外2环法术~
 
COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl4.spl~ ~override~
SAY NAME1 ~额外4环法术~
SAY NAME2 ~额外4环法术~
SAY UNIDENTIFIED_DESC ~额外4环法术
选择本能力可让秘火骑士额外施展一个4环法术。

需要：额外3环法术~

COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl5.spl~ ~override~
SAY NAME1 ~奥术学识 I~
SAY NAME2 ~奥术学识 I~
SAY UNIDENTIFIED_DESC ~奥术学识
资深秘火骑士对奥术的理解愈发接近真正的法师，获得所有豁免检定+1，并可每日施展一次寒冰锥、法术免疫、神谕术与阳炎术。~

COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl6.spl~ ~override~
SAY NAME1 ~奥术学识 II~
SAY NAME2 ~奥术学识 II~
SAY UNIDENTIFIED_DESC ~奥术学识 II
资深秘火骑士对奥术的掌控愈发接近真正的法师，施法时间-1，并可每日施展一次无效结界、高级加速术、魔法武器防护与法术反转。

需要：奥术学识 I~

COPY ~%MOD_FOLDER%/Paladin/MysticFire/spells/c0mfhl7.spl~ ~override~
SAY NAME1 ~奥术学识 III~
SAY NAME2 ~奥术学识 III~
SAY UNIDENTIFIED_DESC ~奥术学识 III
秘火骑士对奥术的造诣已堪比真正的法师，法术持续时间+20%，并可每日施展一次有限祈愿术、魔邓肯之剑、凯尔本金的守护鞭与法术反转。

需要：奥术学识 II~

INCLUDE ~%MOD_FOLDER%/lib/mystic_fire_spells.tpa~