COPY ~%MOD_FOLDER%/MonkRevision/Ninja/2da~ ~override~
COPY ~%MOD_FOLDER%/MonkRevision/Ninja/spl~ ~override~

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 20
	
    mixed         = RESOLVE_STR_REF(~忍者~)
	
    lower         = RESOLVE_STR_REF(~忍者~)
	
    help          = RESOLVE_STR_REF(~忍者：忍者是潜行矫健的战士，穿行于暗影之中，出其不意地击倒毫无防备的敌人。忍者精通武器、武道与窃术，来自东方国度，是氏族忠诚的执行者，身兼战士、刺客与密探。

职业特性：
–无法穿戴任何护甲。
–仅可使用盗贼职业可用的武器。
–任意战斗风格可达到专精级（2个熟练位），双武器战斗可分配3个熟练位。
–每等级可获得20点（1级时30点）盗贼技能点数，可分配于：开锁、扒窃、找寻并解除陷阱、无声行动、阴影躲藏、侦测幻象、设置陷阱。
–移动速度比其他角色快2点。每提升5级，移动速度再提升1点。
–每回合可进行2次徒手攻击。
–可以通过使用背刺能力提高伤害。
  1-8级：2倍
  9-16级：3倍
  17级及以上：4倍
–忍者的拳头造成钝击伤害，伤害随等级提升：
  1-2级：1d4
  3-4级：1d6
  5-6级：1d8
  7-9级：1d10
  10-14级：1d12
  15-19级：2d8
  20-24级：2d10
  25级及以上：2d12
–气：忍者的徒手攻击贯注气劲，4级时视为+1附魔魔法武器，8级+2，12级+3，16级+4，20级+5。7级起，视为银质武器。
–所有豁免检定+1。5级起每提升5级额外+1。
–感知每超过12点1点，忍者基础护甲等级+1。5级起每提升5级护甲等级额外+1。
–御箭：每3级，忍者对抗远程攻击的护甲等级+1。
–每日可使用一次「烟雾弹」「设置陷阱」与「淬毒武器」。1级时获得1次，之后每提升6级额外获得1次使用次数。

烟雾弹：在目标位置生成一片烟幕，范围内所有生物致盲且移动速度减半，只要留在烟幕中效果持续。忍者免疫自身烟幕的致盲效果，且只要留在烟幕中就处于隐形状态，可从任意方向发动背刺。烟幕持续2回合，每6级额外持续1回合。

设置陷阱：视野内无敌对生物时，在选定位置布置陷阱。陷阱威力随游荡者等级提升，且仅会被敌人触发。
  1级：造成2d8+5点远程伤害。
  11级：造成2d8+5点远程伤害，且接下来3回合每回合额外造成2d6点毒素伤害。
  16级：造成3d8+5点远程伤害与4d8+2点火焰伤害。
  21级：造成3d8+5点远程伤害与20点毒素伤害，无豁免；若目标死亡豁免（+4加值）失败则直接被斩杀。

淬毒武器：忍者可在武器上涂抹一种发作缓慢但剧毒的毒素，持续8小时。毒素立即并在之后每回合造成伤害并降低目标体质，至少持续4回合。4回合后，目标必须进行死亡豁免，失败则再中毒4回合。因此只要目标未成功豁免，毒素就有可能无限持续。目标不会因毒素造成的体质流失而死亡。
  1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
  6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
  11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
  16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
  21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。

–6级：每次使用烟雾弹可投掷2枚。
–11级：金刚体：忍者永久免疫毒素。
–12级：每次使用烟雾弹可投掷3枚。
–14级：每日可使用两次「空灵体」。、

空灵体：忍者可隐入无形，获得每等级1回合的半隐形效果。攻击忍者的攻击掷骰受-4惩罚，忍者的豁免检定获得+4加值。除非能看破隐形，否则生物无法以法术锁定忍者。

–15级：内眼：忍者徒手时免疫暴击。
–18级：忍者在自身烟幕中时移动速度翻倍。
–22级：忍者在自身烟幕中时，背刺倍率额外+1倍。

–生命骰：d6~)
	
    briefdesc     = RESOLVE_STR_REF(~忍者：忍者是潜行矫健的战士，穿行于暗影之中，出其不意地击倒敌人。忍者精通武器、武道与窃术，来自东方国度，身兼战士、刺客与密探。~)

  STR_VAR
  
    kit_name      = ~C0_NINJA~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                          T   S           F   Q             S S
	//                                          W   C           L   U             W I
	//                                  B L S   O   I   W       A   A             O N
	//                                  A O H   H   M   A       I   R C   S       R G
	//                  L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//                  _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
       weapprof      = ~2 2 2 0 2 0 0 2 0 2 2 0 0 2 2 2 0 0 0 0 0 0 0 0 0 2 2 2 0 0 2 3~
	
    abclasrq      = ~0 14 0 0 12 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~1 1 1 1 1 1 1 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0NINJ~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0NINJA.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    clswpbon      = ~1 0 2~
	
    hpclass       = ~HPROG~
	
    // numwslot      = ~4~
	
    clascolr = ~192 182 136 93 142~ // METAL MINOR MAJOR LEATHER ARMOR
	
	clasiskl = ~0 5 10 10 15 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~100 100 100 100 100 100 100 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	thiefskl = ~30 20~
	
	traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

OUTER_SET ninja_ids = IDS_OF_SYMBOL (~kit~ ~C0_NINJA~)
  
COPY ~%MOD_FOLDER%/lua/m_c0mon2.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%ninja_ids%~~~~~ //"
  END

// backstab
APPEND ~backstab.2da~ ~C0_NINJA 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
APPEND ~sneakatt.2da~ ~C0_NINJA 2 2 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7~
APPEND ~crippstr.2da~ ~C0_NINJA 2 2 2 2 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 5 5 5 5 5 5 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7~

ADD_PROJECTILE ~%MOD_FOLDER%/MonkRevision/Ninja/pro/C0NINJP1.PRO~
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP2.PRO~
WRITE_BYTE 0x216 18
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP3.PRO~
WRITE_BYTE 0x216 24
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP4.PRO~
WRITE_BYTE 0x216 30
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP5.PRO~
WRITE_BYTE 0x216 36
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP6.PRO~
WRITE_BYTE 0x216 42
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP7.PRO~
WRITE_BYTE 0x216 48
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP8.PRO~
WRITE_BYTE 0x216 54
COPY_EXISTING ~C0NINJP1.PRO~ ~OVERRIDE/C0NINJP9.PRO~
WRITE_BYTE 0x216 60

ADD_PROJECTILE ~override/C0NINJP2.PRO~
ADD_PROJECTILE ~override/C0NINJP3.PRO~
ADD_PROJECTILE ~override/C0NINJP4.PRO~
ADD_PROJECTILE ~override/C0NINJP5.PRO~
ADD_PROJECTILE ~override/C0NINJP6.PRO~
ADD_PROJECTILE ~override/C0NINJP7.PRO~
ADD_PROJECTILE ~override/C0NINJP8.PRO~
ADD_PROJECTILE ~override/C0NINJP9.PRO~

COPY_EXISTING ~C0NINJ1.SPL~ ~OVERRIDE~
LPF ALTER_SPELL_HEADER INT_VAR header = 1 projectile = C0NINJP1 END
LPF ALTER_SPELL_HEADER INT_VAR header = 2 projectile = C0NINJP2 END
LPF ALTER_SPELL_HEADER INT_VAR header = 3 projectile = C0NINJP3 END
LPF ALTER_SPELL_HEADER INT_VAR header = 4 projectile = C0NINJP4 END
LPF ALTER_SPELL_HEADER INT_VAR header = 5 projectile = C0NINJP5 END
LPF ALTER_SPELL_HEADER INT_VAR header = 6 projectile = C0NINJP6 END
LPF ALTER_SPELL_HEADER INT_VAR header = 7 projectile = C0NINJP7 END
LPF ALTER_SPELL_HEADER INT_VAR header = 8 projectile = C0NINJP8 END
LPF ALTER_SPELL_HEADER INT_VAR header = 9 projectile = C0NINJP9 END
SAY NAME1 ~烟雾弹~
SAY UNIDENTIFIED_DESC ~烟雾弹
在目标位置生成一片烟幕，范围内所有生物视野减半、移动速度减半，只要留在烟幕中效果持续。忍者免疫自身烟幕的负面效果，且只要留在烟幕中就处于隐形状态。烟幕持续2回合，每6级额外持续1回合。~

COPY_EXISTING ~C0NINJ2.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 290 parameter1 = RESOLVE_STR_REF (~精英忍者~) END

COPY_EXISTING ~C0NINJ3.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 290 parameter1 = RESOLVE_STR_REF (~大师忍者~) END


COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x20 thief //reads the byte containing the fighter usability flag
    PATCH_IF ((thief BAND 0b01000000) = 0b00000000) BEGIN // if it is usable by fighters
      READ_BYTE    0x21 monk //reads the byte containing monks usability flag
      READ_SHORT    0x1C type //reads the byte containing item type
      PATCH_IF (type = 15) OR (type = 5) BEGIN // if it is a staff
        WRITE_BYTE    0x21 (monk BAND 0b11011111)  // makes usable by monks
      END
    END
  END
BUT_ONLY_IF_IT_CHANGES

//__________________________________________________________________________________

ACTION_IF GAME_IS ~BG2EE EET~ BEGIN

COMPILE ~ArtisansKitpack/strongholds/ninja.d~

  END
  