COPY ~%MOD_FOLDER%/Paladin/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Paladin/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/CLABPA01.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL212 ~ ~**** ~ // DETECT EVIL

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0PAL00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0PAL00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0PAL05 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0PAL00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0PAL00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0PAL00 END

 	PRETTY_PRINT_2DA

// CHARISMA
APPEND ~splprot.2da~ ~C0HTCHR%TAB%42%TAB%-1%TAB%1~ UNLESS ~C0HTCHR~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTCHR~ BEGIN
	    SET C0HTCHR = %row%
	  END
	END
	
ACTION_FOR_EACH CLASSTEXT IN BGCLATXT CLASTEXT SODCLTXT BEGIN
ACTION_IF (FILE_EXISTS_IN_GAME ~%CLASSTEXT%.2da~) BEGIN
  COPY_EXISTING ~%CLASSTEXT%.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~PALADIN~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (~圣武士：圣武士是英勇高洁的战士，是一切良善与真诚的典范。与战士相同，圣武士长于行动与战斗。然而，圣武士毕生奉行正义、公正、诚实、虔诚与骑士精神的信条，并力求成为这些美德的鲜活榜样，让他人既能受其言传，也能蒙其行远益。

职业特性：

–可以穿戴头盔。
–可以穿戴任何种类的盔甲、使用全部类别的武器。
–不能对任何武器类别达到精通（2星）以上的水准。
–可以精通（2星）任何战斗方式，双持武器可分配3点。
–圣武士每天可以使用一次圣疗术，能为目标治疗2hp/级。
–可随意施展「侦测邪恶」。
–每日可使用一次「治愈疾病」。
–每日可使用一次「破邪斩」，下一次成功攻击对邪恶阵营生物额外造成1d6+每3等级1d6点伤害。
–每日可施展「防护邪恶」，次数等于职业等级（1级时1次）。
–可以驱散不死生物，效果等同于低2级的牧师，从3级开始。
–自等级9开始能够施放牧师神术。
–免疫疾病。
–神恩：圣武士豁免检定+2；魅力达到19后，每再提升2点魅力，额外+1。
–3级：获得「勇气灵光」。

勇气灵光：圣武士永久免疫恐惧效果，并被动将自身神恩加值的一半（向上取整）赋予视野范围内的所有友军。

–15级：破邪斩每日额外获得3次使用次数。
–阵营限制为守序善良。
–生命骰：d10。~)
	  END
	END
  BUT_ONLY
	END
	END
	
DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~勇气灵光~) STR_VAR bam_file = c0pal00i RET c0pal00i = icon END

COPY_EXISTING ~C0PAL00.SPL~ OVERRIDE
      LPF ADD_SPELL_EFFECT
      INT_VAR
	    opcode = 142
	    target = 2
		timing = 9
        parameter2 = c0pal00i
      END
COPY_EXISTING ~C0PAL01.SPL~ OVERRIDE
	LPF ALTER_EFFECT
		INT_VAR
			match_opcode = 326
			parameter2 = C0HTCHR
			silent = 1
	END
COPY_EXISTING ~C0PAL02.SPL~ OVERRIDE
SAY NAME1 ~破邪斩~
SAY UNIDENTIFIED_DESC ~破邪斩
圣武士下一次成功攻击对邪恶阵营生物额外造成1d6+每3等级1d6点伤害。~
	
ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

COPY_EXISTING ~C0PAL04A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

COPY_EXISTING ~C0PAL04B.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

COPY_EXISTING ~C0PAL04C.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~#PALDISE.SPL~ BEGIN
COPY ~%MOD_FOLDER%/Paladin/Spells/iwdee/#PALDISE.SPL~ OVERRIDE
END
	
ACTION_IF NOT FILE_EXISTS_IN_GAME ~#PALFEAR.SPL~ BEGIN
COPY ~%MOD_FOLDER%/Paladin/Spells/iwdee/#PALFEAR.SPL~ OVERRIDE
END
	
COPY ~%MOD_FOLDER%/Paladin/Spells/C0PAL05.SPL~ OVERRIDE
SAY NAME1 ~治愈疾病~
SAY UNIDENTIFIED_DESC ~治愈疾病
（防护系）

等级：3
射程：触碰
学派：死灵系
持续时间：即时
施法时间：9
影响范围：1个生物
豁免检定：无

对患病目标施放本法术后，可立即治愈其疾病并恢复5点生命值。治愈效果永久，但不会使目标免疫后续的同类病症。目盲与耳聋也可借此术治愈。本法对不死生物、构装生物或异界生物无效。~