COPY ~%MOD_FOLDER%/Sorcerer/PaleMaster/2das~ ~override~
COPY ~%MOD_FOLDER%/Sorcerer/PaleMaster/abilities~ ~override~

// -----------------------------
// PALE MASTER KIT (TOME NOT INSTALLED)
// -----------------------------
LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 19
	
    mixed         = RESOLVE_STR_REF(~苍白之主~)
	
    lower         = RESOLVE_STR_REF(~苍白之主~)
	
    help          = RESOLVE_STR_REF(~苍白之主：对奥术施法者而言，死灵学派通常并非佳选——真正想要精通亡者之道的人，大多会投身神术之道。但对于那些渴望掌控亡灵之力、又不愿彻底放弃奥术技艺的人，另一条道路依然存在。这就是苍白之主，他们从禁忌秘典中汲取力量，掌握着独属于自身的可怖死灵之力。

职业优势：
–1级：获得「骨肤术」。

骨肤术：苍白之主坚韧如尸的身躯提供+1护甲等级，以及穿刺、挥砍、钝击与远程伤害抗性+5%。7级时提升至+2/+10%，13级时提升至+3/+15%。

–2级：每日可作为特殊能力施展一次「操纵死尸」。

操纵死尸：效果同法师与牧师的同名法术，召唤一名同盟骷髅战士为施法者效力。

–3级：获得「不死活力」。

不死活力：苍白之主的躯体愈发趋近其亡灵仆从的不朽血肉。永久获得黑暗视觉，免疫所有睡眠效果，对抗麻痹/毒素/死亡的豁免检定+1。8级时豁免加值提升至+2，13级时提升至+3。

–6级：苍白之主屈从于可怖的死灵癖好，外科手术切除自己的右臂，替换为不死义肢——形态可能是枯骨，或是类似血肉魔偶般缝合的防腐血肉。义肢永久为苍白之主提供+2力量加值，并允许每日使用三次「不死义肢」能力。

不死义肢：苍白之主可对单一目标进行接触攻击，攻击检定+4，目标必须进行死亡豁免，失败则随机承受以下效果之一：
  麻痹之触：目标麻痹4回合。
  虚弱之触：目标力量-6，持续8回合。
  退化之触：目标永久流失1个等级。
  毁灭之触：目标体质-6，持续8回合。
  
–10级：不死义肢的豁免惩罚变为-1。
–12级：获得「坚如白骨」。

坚如白骨：苍白之主愈发接近那些不可撼动的亡灵，永久免疫定身、震慑与毒素。

–14级：不死义肢的豁免惩罚变为-2。
–16级：「统御亡灵」：苍白之主强化附近的同盟亡灵生物，使其力量与敏捷+4，最大生命值+30%。
–16级：苍白之主的不死义肢变为致命，可改用「不死君主之触」替代其他效果。

不死君主之触：苍白之主以攫命之手触碰目标，攻击检定+4，目标死亡豁免（难度-3）失败则立即死亡。被本能力击杀的目标会作为吸血鬼被唤起，受苍白之主操控8小时。吸血鬼的强度与被击杀目标的强度相关。

–18级：不死义肢的豁免惩罚变为-3。
–18级：获得「不死掌握」。

不死掌握：苍白之主除了名义之外，实质上已是亡灵生物，永久免疫暴击、死亡魔法与等级吸取。任何影响亡灵的法术或能力（无论有益有害）都对其生效，统御亡灵的加值效果除外。

–生命骰：d6

职业限制：
–永久失去右手戒指位的使用。
–每日每等级可施展的法术减少一个。
–阵营限制为非善良。
–魅力受-4惩罚。~)
	
    briefdesc     = RESOLVE_STR_REF(~苍白之主：对奥术施法者而言死灵术通常并非佳选，但对那些渴望掌控亡灵之力、又不愿放弃奥术技艺的人，苍白之主便是另一条道路，他们从禁忌秘典中汲取独属于自身的可怖死灵之力。~)
	
	biography	  = RESOLVE_STR_REF(~尽管养父多方劝阻，死灵术始终是你最沉迷的爱好。经年累月，你已学会以独到的方式引导体内的原始魔力，就连最睿智的欧格玛祭司也为之困惑。你常说，死者比活人更适合做伴，而如今它们对你低语，许诺在烛堡的高墙之外，还有更强大的力量等着你。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~PaleMaster~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    abclasrq      = ~0 0 9 9 0 0~
	
    abclsmod      = ~0 0 0 0 0 -4~
	
    // abdcdsrq      = ~0 0 0 0 0 0~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    stweap        = ~* * * BAG29 RING40 * * BOOT01 AMUL21 BRAC15 BELT10 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 SLNG05 DAGG05,20 STAF20~
	
    clab_path     = ~override/PMaster.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPDD~
	
    // numwslot      = ~4~
	
    clascolr = ~171 174 190 171 171~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~SPWI501.spl~ ~override/PMAbil1.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END

COPY_EXISTING ~C0PMHN1.ITM~ ~OVERRIDE~
SAY NAME2 ~右手~
SAY DESC ~苍白之主的右手预备在获得足够经验后，以外科手术替换为不死义肢，无法佩戴戒指。~

COPY_EXISTING ~C0PMHN2.ITM~ ~OVERRIDE~
SAY NAME2 ~不死义肢~
SAY DESC ~苍白之主的右手灌注了死灵魔法，已被外科替换为亡灵肢体，操控起来与生来的手掌无异。只要义肢仍连结，苍白之主永久获得+2力量，并可用于发动接触攻击。但它无法获得魔法戒指的属性加成。~

COPY_EXISTING ~C0PMHN3.ITM~ ~OVERRIDE~
SAY NAME2 ~不死义肢~
SAY DESC ~苍白之主的右手灌注了死灵魔法，已被外科替换为亡灵肢体，操控起来与生来的手掌无异。只要义肢仍连结，苍白之主永久获得+2力量，并可用于发动接触攻击。但它无法获得魔法戒指的属性加成。~

COPY_EXISTING ~C0PMSP1A.SPL~ ~OVERRIDE~
SAY NAME1 ~不死义肢~

COPY_EXISTING ~C0PMSP1B.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~麻痹~) END
SAY NAME1 ~不死义肢~

COPY_EXISTING ~C0PMSP1C.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~力量流失~) END
SAY NAME1 ~不死义肢~

COPY_EXISTING ~C0PMSP1D.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~等级流失~) END
SAY NAME1 ~不死义肢~

COPY_EXISTING ~C0PMSP1E.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~体质流失~) END
SAY NAME1 ~不死义肢~

COPY_EXISTING ~C0PMSP2.SPL~ ~OVERRIDE~
SAY NAME1 ~不死君主之触~

COPY_EXISTING ~C0PMSP2A.SPL~ ~OVERRIDE~
SAY NAME1 ~不死君主之触~

COPY_EXISTING ~C0PMVM1M.cre~ ~override~
SAY NAME1 ~初拥吸血鬼~
SAY NAME2 ~初拥吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM1F.cre~ ~override~
SAY NAME1 ~初拥吸血鬼~
SAY NAME2 ~初拥吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM2M.cre~ ~override~
SAY NAME1 ~吸血鬼~
SAY NAME2 ~吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM2F.cre~ ~override~
SAY NAME1 ~吸血鬼~
SAY NAME2 ~吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM3M.cre~ ~override~
SAY NAME1 ~年长吸血鬼~
SAY NAME2 ~年长吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM3F.cre~ ~override~
SAY NAME1 ~年长吸血鬼~
SAY NAME2 ~年长吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM4M.cre~ ~override~
SAY NAME1 ~远古吸血鬼~
SAY NAME2 ~远古吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable

COPY_EXISTING ~C0PMVM4F.cre~ ~override~
SAY NAME1 ~远古吸血鬼~
SAY NAME2 ~远古吸血鬼~
WRITE_ASCII 0x280 ~C0PMVM~ #32 // death variable


ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb00.qd~) THEN BEGIN //core revisions check and update
          COPY_EXISTING ~PMaster.2da~ ~override~
                        INSERT_2DA_ROW 3 0 ~FAMILIAR   GA_QDFAMLR    ****          ****          ****       ****          ****          ****          ****          ****       ****        ****       ****          ****          ****       ****          ****          ****       ****       ****       ****          ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
END

ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb01.qd~) THEN BEGIN //spell selection through dialog check and update
          COPY_EXISTING ~PMaster.2da~ ~override~
                        INSERT_2DA_ROW 3 0 ~MEMORIZE   GA_QDSORSM    ****          ****          ****       ****          ****          ****          ****          ****       ****        ****       ****          ****          ****       ****          ****          ****       ****       ****       ****          ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
END

ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb03.qd~) THEN BEGIN //armored casting check and update
          COPY_EXISTING ~PMaster.2da~ ~override~
                        INSERT_2DA_ROW 3 0 ~AMRCAST    AP_QDACNO     ****          ****          ****       ****          ****          ****          ****          ****       ****        ****       ****          ****          ****       ****          ****          ****       ****       ****       ****          ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
END

ACTION_IF (FILE_EXISTS_IN_GAME ~qdtnb05.qd~) THEN BEGIN //arcane crafting check and update
          COPY_EXISTING ~PMaster.2da~ ~override~
                        INSERT_2DA_ROW 3 0 ~ARCNCRFT   ****	     ****          ****          ****       GA_B_BREW1    ****          ****          ****          ****       GA_B_WAND1  ****       ****          ****          ****       GA_B_RECH1    ****          ****       ****       ****       ****          ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****       ****~
END
