COPY ~%MOD_FOLDER%/Ranger/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABRN01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 STR_VAR f_Entry = GA_C0CL922 END // Tracking
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG00 END // Camouflage
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG00 END // Camouflage
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 5 STR_VAR f_Entry = GA_SPCL412 END // Set Snare
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0RNG01 END // Set Traps
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1  STR_VAR f_Entry = AP_C0RNH1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2  STR_VAR f_Entry = AP_C0RNH2 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3  STR_VAR f_Entry = AP_C0RNH3 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4  STR_VAR f_Entry = AP_C0RNH4 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5  STR_VAR f_Entry = AP_C0RNH5 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6  STR_VAR f_Entry = AP_C0RNH6 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7  STR_VAR f_Entry = AP_C0RNH7 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8  STR_VAR f_Entry = AP_C0RNH8 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9  STR_VAR f_Entry = AP_C0RNH9 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10  STR_VAR f_Entry = AP_C0RNH10 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11  STR_VAR f_Entry = AP_C0RNH11 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12  STR_VAR f_Entry = AP_C0RNH12 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13  STR_VAR f_Entry = AP_C0RNH13 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 14  STR_VAR f_Entry = AP_C0RNH14 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15  STR_VAR f_Entry = AP_C0RNH15 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16  STR_VAR f_Entry = AP_C0RNH16 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 17  STR_VAR f_Entry = AP_C0RNH17 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 18  STR_VAR f_Entry = AP_C0RNH18 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19  STR_VAR f_Entry = AP_C0RNH19 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10  STR_VAR f_Entry = AP_C0RNH20 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 21  STR_VAR f_Entry = AP_C0RNH21 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 22  STR_VAR f_Entry = AP_C0RNH22 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 23  STR_VAR f_Entry = AP_C0RNH23 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 24  STR_VAR f_Entry = AP_C0RNH24 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 25  STR_VAR f_Entry = AP_C0RNH25 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 26  STR_VAR f_Entry = AP_C0RNH26 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 27  STR_VAR f_Entry = AP_C0RNH27 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 28  STR_VAR f_Entry = AP_C0RNH28 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 29  STR_VAR f_Entry = AP_C0RNH29 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20  STR_VAR f_Entry = AP_C0RNH30 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 31  STR_VAR f_Entry = AP_C0RNH31 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 32  STR_VAR f_Entry = AP_C0RNH32 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 33  STR_VAR f_Entry = AP_C0RNH33 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 34  STR_VAR f_Entry = AP_C0RNH34 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 35  STR_VAR f_Entry = AP_C0RNH35 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 36  STR_VAR f_Entry = AP_C0RNH36 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 37  STR_VAR f_Entry = AP_C0RNH37 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 38  STR_VAR f_Entry = AP_C0RNH38 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 39  STR_VAR f_Entry = AP_C0RNH39 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 40  STR_VAR f_Entry = AP_C0RNH40 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 41  STR_VAR f_Entry = AP_C0RNH41 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 42  STR_VAR f_Entry = AP_C0RNH42 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 43  STR_VAR f_Entry = AP_C0RNH43 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 44  STR_VAR f_Entry = AP_C0RNH44 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 45  STR_VAR f_Entry = AP_C0RNH45 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 46  STR_VAR f_Entry = AP_C0RNH46 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 47  STR_VAR f_Entry = AP_C0RNH47 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 48  STR_VAR f_Entry = AP_C0RNH48 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 49  STR_VAR f_Entry = AP_C0RNH49 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 50  STR_VAR f_Entry = AP_C0RNH50 END
  PRETTY_PRINT_2DA
BUT_ONLY

ACTION_FOR_EACH CLASSTEXT IN BGCLATXT CLASTEXT SODCLTXT BEGIN
ACTION_IF (FILE_EXISTS_IN_GAME ~%CLASSTEXT%.2da~) BEGIN
  COPY_EXISTING ~%CLASSTEXT%.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~RANGER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (~游侠：游侠是精通武器、熟知林野之道的林中战士。游侠常为迷途的旅人与淳朴的乡民提供守护与指引。要在自然中安身立命，游侠必须体魄强健、通晓自然之道。

职业特性：

–可以穿戴头盔。
–可以穿戴任何种类的护甲、使用全部类别的武器。
–不能对任何武器类别达到精通（2星）以上的水准。
–可以精通（2星）任何战斗方式。
–开始就精通（2星）双武器模式，并可投入至3星。
–可以选择一个宿敌，在对抗宿敌时享有+4的命中和伤害奖励。
–每提升2个等级，每天就可以多使用1次魅惑动物能力（等级为1时每天可使用1次）
–在不穿盔甲或穿皮甲、皮环甲的状态下可以隐藏在阴影之中。
–穿林：户外时游侠移动速度+2。5级起，游侠免疫纠缠术与蛛网术效果。
–伪装：户外时，游侠隐匿阴影与潜行的技能检定获得+25%加值。
–强健：1级时最大生命值+4，之后每等级+1。
–每日可使用一次「设置陷阱」。1级时获得1次，之后每提升5级额外获得1次使用次数。

设置陷阱：视野内无敌对生物时，在选定位置布置陷阱。陷阱威力随游侠等级提升，且仅会被敌人触发。每个区域游侠最多可布置3个陷阱。
  1级：造成2d8+5点远程伤害。
  11级：造成2d8+5点远程伤害，且接下来3回合每回合额外造成2d6点毒素伤害。
  16级：造成3d8+5点远程伤害与4d8+2点火焰伤害。
  21级：造成3d8+5点远程伤害与20点毒素伤害，无豁免；若目标死亡豁免（+4加值）失败则直接被斩杀。
  
–户外时可使用「追踪」模式能力。

追踪：游侠对周遭环境与栖居其中的生物了如指掌，可使用追踪能力大致获知区域内的生物种类与方位。游侠50尺范围内的所有敌人都会在战争迷雾中显形。9级与18级时，追踪范围半径额外增加25尺。

–自等级8开始能够施放德鲁伊法术。
–必须为善良阵营。
–生命骰：d10。

主要兼职要求：力量、敏捷、智慧~)
	  END
	END
  BUT_ONLY
	END
	END
	
DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~穿林~) STR_VAR bam_file = C0RNG00I RET C0RNG00I = icon END

APPEND ~TRAPLIMT.2DA~ ~RANGER 3
FERALAN 3
STALKER 3
BEASTMASTER 3~ UNLESS ~RANGER~

// RANGER - HLA
COPY_EXISTING ~LURA0.2DA~ ~OVERRIDE~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL922~ END
	
APPEND ~splprot.2da~ ~C0_OUTDOORS_CHECK%TAB%0x106%TAB%1%TAB%8~ UNLESS ~C0_OUTDOORS_CHECK~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_OUTDOORS_CHECK~ BEGIN
	    SET C0_OUTDOORS_CHECK = %row%
	  END
	END
	
APPEND ~splprot.2da~ ~C0_NOT_OUTDOORS_CHECK%TAB%0x106%TAB%1%TAB%9~ UNLESS ~C0_NOT_OUTDOORS_CHECK~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_NOT_OUTDOORS_CHECK~ BEGIN
	    SET C0_NOT_OUTDOORS_CHECK = %row%
	  END
	END
	
COPY_EXISTING ~c0rng00a.spl~ ~override~
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0_OUTDOORS_CHECK STR_VAR match_resource = c0rng00b END
	LPF ALTER_EFFECT INT_VAR match_opcode = 326 parameter2 = C0_NOT_OUTDOORS_CHECK STR_VAR match_resource = c0rng00c END

COPY_EXISTING ~c0rng00b.spl~ ~override~
	LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0RNG00I END

ACTION_FOR_EACH hit_points IN 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 BEGIN
  COPY_EXISTING ~c0rnh2.spl~ ~override/c0rnh%hit_points%.spl~
    LPF ALTER_EFFECT STR_VAR match_resource = C0RNH_2 resource = EVAL ~C0RNH_%hit_points%~ END
  COPY_EXISTING ~c0rnh_2.spl~ ~override/c0rnh_%hit_points%.spl~
    LPF ALTER_EFFECT STR_VAR match_resource = C0RNH_2 resource = EVAL ~C0RNH_%hit_points%~ END
END

COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 12) BEGIN
    // Set New Fighter Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Fighter kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "FERALAN")
        OR
				("%kit_label%" STRING_EQUAL_CASE "STALKER")
														 ) BEGIN
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1  STR_VAR f_Entry = AP_C0RNH1 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 2  STR_VAR f_Entry = AP_C0RNH2 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 3  STR_VAR f_Entry = AP_C0RNH3 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4  STR_VAR f_Entry = AP_C0RNH4 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 5  STR_VAR f_Entry = AP_C0RNH5 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 6  STR_VAR f_Entry = AP_C0RNH6 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 7  STR_VAR f_Entry = AP_C0RNH7 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8  STR_VAR f_Entry = AP_C0RNH8 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 9  STR_VAR f_Entry = AP_C0RNH9 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10  STR_VAR f_Entry = AP_C0RNH10 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 11  STR_VAR f_Entry = AP_C0RNH11 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 12  STR_VAR f_Entry = AP_C0RNH12 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 13  STR_VAR f_Entry = AP_C0RNH13 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 14  STR_VAR f_Entry = AP_C0RNH14 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 15  STR_VAR f_Entry = AP_C0RNH15 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16  STR_VAR f_Entry = AP_C0RNH16 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 17  STR_VAR f_Entry = AP_C0RNH17 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 18  STR_VAR f_Entry = AP_C0RNH18 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 19  STR_VAR f_Entry = AP_C0RNH19 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 10  STR_VAR f_Entry = AP_C0RNH20 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 21  STR_VAR f_Entry = AP_C0RNH21 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 22  STR_VAR f_Entry = AP_C0RNH22 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 23  STR_VAR f_Entry = AP_C0RNH23 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 24  STR_VAR f_Entry = AP_C0RNH24 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 25  STR_VAR f_Entry = AP_C0RNH25 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 26  STR_VAR f_Entry = AP_C0RNH26 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 27  STR_VAR f_Entry = AP_C0RNH27 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 28  STR_VAR f_Entry = AP_C0RNH28 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 29  STR_VAR f_Entry = AP_C0RNH29 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20  STR_VAR f_Entry = AP_C0RNH30 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 31  STR_VAR f_Entry = AP_C0RNH31 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 32  STR_VAR f_Entry = AP_C0RNH32 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 33  STR_VAR f_Entry = AP_C0RNH33 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 34  STR_VAR f_Entry = AP_C0RNH34 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 35  STR_VAR f_Entry = AP_C0RNH35 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 36  STR_VAR f_Entry = AP_C0RNH36 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 37  STR_VAR f_Entry = AP_C0RNH37 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 38  STR_VAR f_Entry = AP_C0RNH38 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 39  STR_VAR f_Entry = AP_C0RNH39 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 40  STR_VAR f_Entry = AP_C0RNH40 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 41  STR_VAR f_Entry = AP_C0RNH41 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 42  STR_VAR f_Entry = AP_C0RNH42 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 43  STR_VAR f_Entry = AP_C0RNH43 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 44  STR_VAR f_Entry = AP_C0RNH44 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 45  STR_VAR f_Entry = AP_C0RNH45 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 46  STR_VAR f_Entry = AP_C0RNH46 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 47  STR_VAR f_Entry = AP_C0RNH47 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 48  STR_VAR f_Entry = AP_C0RNH48 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 49  STR_VAR f_Entry = AP_C0RNH49 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 50  STR_VAR f_Entry = AP_C0RNH50 END
        PRETTY_PRINT_2DA
      END
      
      BUT_ONLY
      END
    END
  END
  END

ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
        READ_2DA_ENTRY index 1 col_count class_id
//inspiration
        PATCH_IF (
				("%row_name%" STRING_EQUAL_CASE "FERALAN")
        OR
				("%row_name%" STRING_EQUAL_CASE "ARCHER")
        OR
				("%row_name%" STRING_EQUAL_CASE "STALKER")
														 )
                              BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_inspiration ~职业限制：~
          SPRINT new_inspiration ~–无法获得强健。~
          SPRINT disadvantages_none ~
–无。~
          GET_STRREF %kit_desc% desc_text
          INNER_PATCH_SAVE desc_text ~%desc_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_inspiration%~ ~%old_inspiration%
%new_inspiration%~
            REPLACE_TEXTUALLY ~%disadvantages_none%~ ~~
          END
            SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%desc_text%~)
            PRETTY_PRINT_2DA
		END
		  END

      COPY_EXISTING ~KITLIST.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 1; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 1 col_count row_name
        READ_2DA_ENTRY index 8 col_count class_id
//inspiration
        PATCH_IF (
				("%row_name%" STRING_EQUAL_CASE "FERALAN")
        OR
				("%row_name%" STRING_EQUAL_CASE "ARCHER")
        OR
				("%row_name%" STRING_EQUAL_CASE "STALKER")
														 )
                              BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          GET_STRREF %kit_desc% desc_text
          INNER_PATCH_SAVE desc_text ~%desc_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_inspiration%~ ~%old_inspiration%
%new_inspiration%~
            REPLACE_TEXTUALLY ~%disadvantages_none%~ ~~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%desc_text%~)
            PRETTY_PRINT_2DA
		      END
		  END


      BUT_ONLY
    END
  END
COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "RANGER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "RANGER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count (val+20)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "CLERIC_RANGER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "CLERIC_RANGER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count (val+20)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  

COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~ranger_kitlist~ 10
  FOR (row = 3; row < ranger_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~ranger_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~ranger_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~ranger_kitlist~ row 8 kit_class

  PATCH_IF NOT ~%kit_class%~ STRING_EQUAL_CASE ~*~ BEGIN
    PATCH_IF (%kit_class% = 12 || %kit_class% = 18) BEGIN
    
      INNER_ACTION BEGIN
        // This gives Ranger kits the Thief snare at the same frequency Thieves get them.
        COPY_EXISTING ~%kit_clab%.2DA~ override
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 STR_VAR f_Entry = GA_C0CL922 END // Tracking
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0RNG00 END // Camouflage
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 5 STR_VAR f_Entry = GA_SPCL412 END // Set Snare
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0RNG01 END // Set Traps
          PRETTY_PRINT_2DA
        BUT_ONLY
      END

      // Set Max Skills Points in THIEFSCL.2DA
      INNER_ACTION BEGIN
      COPY_EXISTING ~THIEFSCL.2DA~ ~override~
        READ_2DA_ENTRIES_NOW thiefscl 3
        COUNT_2DA_COLS cols
        FOR (col = 0; col < cols - 1; ++col) BEGIN
        READ_2DA_ENTRY_FORMER thiefscl 0 col column_name
        PATCH_IF "%column_name%" STRING_EQUAL_CASE "%kit_label%" BEGIN
          SET_2DA_ENTRY 9 (col + 1) 1 ~100~   // SET_TRAPS
          PRETTY_PRINT_2DA
        END
        END
      BUT_ONLY
      END

      // Set Max Skills Points in THIEFSCL.2DA
      INNER_ACTION BEGIN
      COPY_EXISTING ~CLASISKL.2DA~ ~override~
        READ_2DA_ENTRIES_NOW CLASISKL 3
        COUNT_2DA_COLS cols
        FOR (col = 0; col < cols - 1; ++col) BEGIN
        READ_2DA_ENTRY_FORMER CLASISKL 0 col column_name
        PATCH_IF "%column_name%" STRING_EQUAL_CASE "%kit_label%" BEGIN
          SET_2DA_ENTRY 9 (col + 1) 1 ~20~   // SET_TRAPS
          PRETTY_PRINT_2DA
        END
        END
      BUT_ONLY
      END

    END
  END
  END
  
INCLUDE ~%MOD_FOLDER%/spells/tracking.tpa~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY ~%MOD_FOLDER%/lua/m_c0ran1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself

ACTION_IF FILE_EXISTS_IN_GAME ~CLABRN01.2DA~ BEGIN

COPY_EXISTING ~CLABRN01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
  PRETTY_PRINT_2DA
BUT_ONLY

END
///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "RANGER" = 0) BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "RANGER" = 0) BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count (val+20)
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count (val+20)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "CLERIC_RANGER" = 0) BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "CLERIC_RANGER" = 0) BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count (val+20)
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count (val+20)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~ranger_kitlist~ 10
  FOR (row = 3; row < ranger_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~ranger_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~ranger_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~ranger_kitlist~ row 8 kit_class

  PATCH_IF NOT ~%kit_class%~ STRING_EQUAL_CASE ~*~ BEGIN
    PATCH_IF (%kit_class% = 12 || %kit_class% = 18) BEGIN
    
      INNER_ACTION BEGIN
        // This gives Ranger kits the Thief snare at the same frequency Thieves get them.
        COPY_EXISTING ~%kit_clab%.2DA~ override
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "C0TBM")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 20 f_Increment = 1 STR_VAR f_Entry = AP_C0RNG02 END // FIND TRAP/ILLUSION POINTS
          PRETTY_PRINT_2DA
        END
        BUT_ONLY
      END

      // Set Max Skills Points in THIEFSCL.2DA
      INNER_ACTION BEGIN
      COPY_EXISTING ~THIEFSCL.2DA~ ~override~
        READ_2DA_ENTRIES_NOW thiefscl 3
        COUNT_2DA_COLS cols
        FOR (col = 0; col < cols - 1; ++col) BEGIN
        READ_2DA_ENTRY_FORMER thiefscl 0 col column_name
        PATCH_IF "%column_name%" STRING_EQUAL_CASE "%kit_label%" BEGIN
          SET_2DA_ENTRY 5 (col + 1) 1 ~100~   // SET_TRAPS
          SET_2DA_ENTRY 8 (col + 1) 1 ~100~   // SET_TRAPS
          PRETTY_PRINT_2DA
        END
        END
      BUT_ONLY
      END

      // Set Max Skills Points in THIEFSCL.2DA
      INNER_ACTION BEGIN
      COPY_EXISTING ~CLASISKL.2DA~ ~override~
        READ_2DA_ENTRIES_NOW CLASISKL 3
        COUNT_2DA_COLS cols
        FOR (col = 0; col < cols - 1; ++col) BEGIN
        READ_2DA_ENTRY_FORMER CLASISKL 0 col column_name
        PATCH_IF "%column_name%" STRING_EQUAL_CASE "%kit_label%" BEGIN
          SET_2DA_ENTRY 5 (col + 1) 1 ~20~   // SET_TRAPS
          SET_2DA_ENTRY 8 (col + 1) 1 ~20~   // SET_TRAPS
          PRETTY_PRINT_2DA
        END
        END
      BUT_ONLY
      END

    END
  END
  END
  
///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
//RANGER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "RANGER" BEGIN
          READ_2DA_ENTRY index 4 col_count ranger_desc
          SPRINT old_ranger ~–在不穿盔甲或穿皮甲、皮环甲的状态下可以隐藏在阴影之中。~
          SPRINT new_ranger ~–可侦测陷阱与幻象。
–在不穿盔甲或穿皮甲、皮环甲的状态下可以隐藏在阴影之中。~
          GET_STRREF %ranger_desc% ranger_text
          INNER_PATCH_SAVE ranger_text ~%ranger_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_ranger%~ ~%new_ranger%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%ranger_desc%~ ~%ranger_text%~
          END
		END
		
      END
      BUT_ONLY
    END
  END
  END
  