COPY ~ArtisansKitpack/Mage/RedWizard/2das~ ~override~
COPY ~ArtisansKitpack/Mage/RedWizard/spells~ ~override~

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 1
	
	visible = 0
	
    mixed         = RESOLVE_STR_REF(~红袍法师（咒术师）~)
	
    lower         = RESOLVE_STR_REF(~红袍法师~)
	
    help          = RESOLVE_STR_REF(~红袍法师：红袍法师是塞伊的主宰者，是当地拉希米人的征服者，也是费伦大陆潜在的魔法霸主。他们比任何专精法师都更专注于单一魔法学派，在极窄的领域中达到了惊人的魔法造诣。托瑞尔各地的民众视他们为残暴邪恶的暴君，少数红袍法师选择离开故土，隐瞒身份，在不必顾虑政治同盟与奴隶起义的地方研习魔法。

职业优势：
–专精强化：成为红袍法师后，角色会进一步投入自身的法师专精学派，获得对应学派的多种加成。
–红袍法师30尺范围内的所有敌人，对抗其专精学派法术的豁免检定受-4惩罚，取代原本专精的法术施法修正。
–每等级可额外施展一个法术，数量在专精加成之外。
–法术强效：红袍法师的奥术法术视为比自身实际等级高1级施展。3级、6级、9级与12级时，该加值各提升1级。
–专精学派防御：红袍法师对抗自身专精学派法术的豁免检定额外+1。4级、8级、12级与16级时，该加值各提升1级。

职业限制：
–必须为非善良阵营。
–作为专精强化的代价，红袍法师必须额外选择一个禁学学派。艾德温的额外禁学学派为幻术系。~)
	
    briefdesc     = RESOLVE_STR_REF(~红袍法师：红袍法师是塞伊的主宰者，专注单一魔法学派的造诣远超普通专精法师。他们被托瑞尔各地视为残暴的暴君，少数人选择离开故土、隐瞒身份在外修行。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0REDWIZ~
	
    unusable      = ~0x00001080~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    //weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 5 1 1 1 1 1 1~
	
    // abclasrq      = ~0 15 0 14 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0REDWIZ.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY ~ArtisansKitpack/Mage/RedWizard/items/misc89.itm~ ~override~
SAY NAME1 ~艾德温的护符~
SAY DESC ~这是艾德温的祖传之物，镶嵌着他的家族宝石。

属性：

重量：1~

 ACTION_FOR_EACH edwin IN edwin edwin2 edwin4 edwin6 edwin7 edwin9 edwin11 edwin12 edwin13 edwin15 BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%edwin%.cre~ THEN BEGIN
    COPY_EXISTING ~%edwin%.cre~ ~override~
		WRITE_SHORT 0x246 (IDS_OF_SYMBOL (~kit~ ~C0REDWIZ~))
		REMOVE_KNOWN_SPELL ~SPWI120~ ~SPWI106~ ~SPWI212~ ~SPWI201~ ~SPWI307~ ~SPWI405~ ~SPWI505~
		REMOVE_MEMORIZED_SPELL ~SPWI120~ ~SPWI106~ ~SPWI212~ ~SPWI201~ ~SPWI307~ ~SPWI405~ ~SPWI505~
		BUT_ONLY
END
END

ACTION_IF FILE_EXISTS_IN_GAME ~EDWIN.BCS~ THEN BEGIN
COPY_EXISTING_REGEXP GLOB ~EDWIN.BCS~ ~override~
  DECOMPILE_AND_PATCH BEGIN
    REPLACE_TEXTUALLY ~AddSpecialAbility("SPWI212")~ ~~
  END
  BUT_ONLY
  END

ADD_PROJECTILE ~ArtisansKitpack/spells/C0INAREL.PRO~ ~C0 Instant Area Enemies Large~

COPY_EXISTING ~C0REDW1.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREL
END
