LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 3
	
    mixed         = RESOLVE_STR_REF(~神拳使~)
	
    lower         = RESOLVE_STR_REF(~神拳使~)
	
    help          = RESOLVE_STR_REF(~神拳使：神拳使是诸多神殿中独立的修行组织。其苦行的修士将神圣魔法向内修炼，使身心与意志达成和谐。神拳使修士立誓弃绝武器与重甲，视自身的身心为神祇的恩赐，认为未能将这份天赋修至极致便是罪孽。施法并不会玷污他们或他们的神祇。神拳使修士在信仰、意志与体魄上都极为强大。

职业优势：
–移动速度比其他角色快2点。每提升5级，移动速度再提升1点。
–每回合可进行2次徒手攻击。9级与18级时，每回合额外获得半次攻击。
–神拳使修士的拳掌贯注神力，造成钝击伤害，伤害随等级提升：
  1-4级：1d4
  5-8级：1d6
  9-12级：1d8
  13-16级：1d10
  17-20级：1d12
  21级及以上：2d8
  
–气：神拳使修士的徒手攻击贯注气劲，4级时视为+1附魔魔法武器，8级+2，12级+3，16级+4，20级+5。7级起，视为银质武器。
–智慧每超过12点1点，神拳使修士基础护甲等级+1。7级起每提升7级，护甲等级额外+1。
–可使用寻找陷阱与侦测幻象能力。
–疾风连击：神拳使修士徒手或持匕首时，每回合首次攻击可额外追加一次攻击，零级命中值受-5惩罚。该额外攻击不受每回合攻击次数上限限制，且可自由切换开启。13级时，零级命中惩罚降低至-2。
–每日可使用一次「震慑拳」。1级时获得1次，之后每提升6级额外获得1次使用次数。

震慑拳：修士在10秒内的下一次成功攻击，牺牲4点零级命中值与伤害。目标受击时必须进行死亡豁免（智慧每超过14点1点，豁免难度-1），失败则震慑3回合。

–5级：每日可使用一次「神圣焰击」。10级、20级、30级与40级时额外获得使用次数。

神圣焰击：神拳使修士在手脚周围召起神圣火焰，接下来1回合内，近战攻击额外造成1d6魔法火焰伤害与1d6魔法伤害。

–14级：金刚魂：神拳使修士获得基础10%+每等级2%的魔法抗性，20级时达到上限50%。
–16级：每日可使用一次「渗透劲」。

渗透劲：修士的最高深技法。使用后，10秒内的下一次成功攻击会在目标体内引发致命震颤，目标死亡豁免失败则立即死亡（智慧每超过16点1点，豁免难度-1）。

–18级：内眼：神拳使修士徒手时免疫暴击。

职业限制：
–必须为任意守序阵营。
–3级、7级、11级与15级时，施法等级不提升。
–无法穿戴比钉甲更重的护甲。
–无法使用盾牌。
–仅可为人类、半精灵或半兽人。
–兼职仅可选择游荡者或法师。
–持用任何武器时，零级命中值受-6惩罚。~)
	
    briefdesc     = RESOLVE_STR_REF(~神拳使：神拳使是神殿中的苦行修行组织，修士将神圣魔法向内修炼，以求身心和谐。他们立誓弃绝武器与重甲，视身心为神祇恩赐，以将天赋修至极致为己任。~)
  STR_VAR
    kit_name      = ~C0_SACRED_FIST~
	
    unusable      = ~0x00014000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                         T   S           F   Q             S S
	//                                         W   C           L   U             W I
	//                                 B L S   O   I   W       A   A             O N
	//                                 A O H   H   M   A       I   R C   S       R G
	//                 L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//                 _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//                 S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//                 W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//                 O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//                 R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//                 D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0~
	
    abclasrq      = ~0 9 0 9 12 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 0 0 0~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~1 1 1 0 0 0 0 0 0~
	
    dualclas      = ~0 0 1 1 0 0~
	
    luabbr        = ~C0SFF~
	
    // stweap        = ~CLCK13 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0SFF.2da~
	
    kittable      = ~K_C_H K_C_HE K_C_HO~
	
	// base_class = F
	
	// clab_base_f = ~C0AA~
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPFM~
	
    numwslot      = ~3~
	
	// METAL, MINOR, MAJOR, LEATHER, ARMOR
	clascolr = ~79 183 141 165 27~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~0 0 100 0 0 100 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl
	
	// traplimt = ~6~
	
    // bdstweap      = ~CLCK12 * * * RING06 * * * * BRAC02 BELT04 * BULL02,40 * POTN08,5 POTN17,3 POTN24,1 SLNG02 DAGG05,40 STAF02~
  RET
    kit_id
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLABMA01.2DA~ BEGIN
COPY ~%MOD_FOLDER%/2das/blankclab.2DA~ ~OVERRIDE/CLABMA01.2DA~
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABMA01.2DA~ BEGIN
COPY_EXISTING ~CLABMA01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0MONDC END
  PRETTY_PRINT_2DA
BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~CLABTH01.2DA~ BEGIN
COPY_EXISTING ~CLABTH01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0MONDC END
  PRETTY_PRINT_2DA
BUT_ONLY
END

COPY_EXISTING ~C0MONDC.SPL~ OVERRIDE
 LPF ALTER_EFFECT INT_VAR match_opcode = 177 parameter1 = IDS_OF_SYMBOL (~KIT~ ~C0_SACRED_FIST~) END

COPY_EXISTING ~C0MOND1.SPL~ OVERRIDE
 LPF ADD_SPELL_EFFECT INT_VAR target = 2 timing = 9 opcode = 177 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~MAGE_ALL~) parameter2 = 5 STR_VAR resource = C0SFFMA END
 LPF ADD_SPELL_EFFECT INT_VAR target = 2 timing = 9 opcode = 177 parameter1 = IDS_OF_SYMBOL (~CLASS~ ~THIEF_ALL~) parameter2 = 5 STR_VAR resource = C0SFFTH END

COPY ~%MOD_FOLDER%/SPELLS/C0KTNAME.EFF~ ~OVERRIDE/C0SFFMA.EFF~
WRITE_LONG 0x1c RESOLVE_STR_REF (~神拳使/法师~)
WRITE_LONG 0x48 14

COPY ~%MOD_FOLDER%/SPELLS/C0KTNAME.EFF~ ~OVERRIDE/C0SFFTH.EFF~
WRITE_LONG 0x1c RESOLVE_STR_REF (~神拳使/盗贼~)
WRITE_LONG 0x48 15

COPY_EXISTING ~LUCL0.2da~ ~override/LUC0SFF.2DA~
LPF patch_add_hla STR_VAR 2da_row = ~C0EFM1~ ability = ~GA_C0MN#H07~ num_allowed = 16 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0EFM2~ ability = ~GA_C0MN#H05~ num_allowed = 16 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0EFM3~ ability = ~AP_C0MN#H15~ num_allowed = 1 END	

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~神圣焰击~) STR_VAR bam_file = C0SFF1I RET C0SFF1I = icon END

COPY_EXISTING ~C0SFF1.SPL~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0SFF1I END
SAY NAME1 ~神圣焰击~
SAY UNIDENTIFIED_DESC ~神圣焰击
神拳使修士在手脚周围召起神圣火焰，接下来1回合内，近战攻击额外造成1d6魔法火焰伤害与1d6魔法伤害。~

OUTER_SET sacred_fist_ids = IDS_OF_SYMBOL (~kit~ ~C0_SACRED_FIST~)
  
COPY ~%MOD_FOLDER%/lua/m_c0mnk1.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself
///////////////////////////////////////////////////////////////////////////
// Update lua file                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~0x4000~~~~~
    string = EVAL ~~~~~%sacred_fist_ids%~~~~~ //"
  END
