COPY ~%MOD_FOLDER%/Fighter/Samurai/BAMS~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Fighter/Samurai/spells~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/bmp~ ~OVERRIDE~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/C0SAMURA.2DA~
	REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	// REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SAM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SAM02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0CAV03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_Increment = 8 STR_VAR f_Entry = GA_C0CAV03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = GA_C0SAM04 END

 	PRETTY_PRINT_2DA

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/C0RONIN.2DA~
	REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	// REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SAM01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SAM05 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0AS#P1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_Increment = 6 STR_VAR f_Entry = GA_C0AS#P1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 14 STR_VAR f_Entry = GA_C0SAM04 END

 	PRETTY_PRINT_2DA

INCLUDE ~%MOD_FOLDER%/effects/poison_weapon.tpa~

OUTER_SPRINT kit_description_1 ~武士：武士首先是战士，以剑为生，也以剑赴死。武士道上赢得荣誉与历练，实力与地位与日俱增。然而武士之道严苛无情，武士必须时刻抱持赴死的觉悟。

职业优势：
-免疫背刺、恐惧与士气崩溃。
-获得「武士道」被动效果。

武士道：15尺范围内没有盟友时，武士的近战零级命中值、伤害、护甲等级与所有豁免检定持续获得+2加值；若15尺范围内存在等级相当或更高的敌人，还可额外获得对应加值：
  敌人12级及以上：+2加值
  敌人21级及以上：+3加值
  敌人30级及以上：+4加值
  敌人40级及以上：+5加值
该加值不叠加，仅取最高有效值。

-每日可使用一次「决死挑戦」。每提升8级，额外获得1次使用次数。

决死挑戦：武士标记一名目标生物，接下来三回合内，目标与武士自身的护甲等级各降低10点。武士对被挑战的目标造成额外的无法减免魔法伤害。此外，被挑战目标在战争迷雾中会显形，且效果持续期间无法进入隐身状态。
  1-11级：造成1d6点伤害
  12-19级：造成2d6点伤害
  20级及以上：造成4d6点伤害IAIJUTSU_DESCRIPTION

-14级：每日可使用一次「气合大喝」。

气合大喝：武士暴喝一声，下回合内的所有攻击均取最大伤害值。附近所有敌人士气大幅受挫，必须额外进行一次麻痹豁免检定（难度-4），失败则一回合内完全无法移动或采取任何行动，且护甲等级受-10惩罚。

职业限制：
-必须为守序阵营。
-若武士声望降至6以下，将沦为浪人：阵营永久转为混乱，失去武士道加值与决死挑戦的使用权，但会获得其他相应优势，并可兼职游荡者。KIT_DISADV_1
-未成为浪人时，不可兼职游荡者。
-不可穿戴比镶片甲更重的护甲。
-仅可精通武士刀、胁差与长弓三类武器。
-不可精通剑盾战斗风格。~

OUTER_SET opcode_342_eeex = 0
ACTION_IF MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~ AND FILE_EXISTS ~EEex_scripts/EEex_Opcode_Patch.lua~ THEN BEGIN
  
  PRINT ~EEex_Opcode_Patch exists.~

COPY_EXISTING ~EEex_scripts/EEex_Opcode_Patch.lua~ ~EEex_scripts~
PATCH_IF ~~ STRING_MATCHES_REGEXP ~Opcode #342~ BEGIN
  SET opcode_342_eeex = 1
  END

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN
  PRINT ~Opcode #342 has been patched.~
    END

END

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN

OUTER_PATCH_SAVE kit_description_1 ~%kit_description_1%~ BEGIN
  REPLACE_TEXTUALLY ~IAIJUTSU_DESCRIPTION~ ~

-9级：可使用「居合术」。

居合术：手持单手剑时，浪人每回合额外获得半次攻击；且每两回合的首次攻击速度因子为0，必定暴击，最小伤害掷骰+4。若手持双手武器、远程武器，或副手持有任何物品，则失去该加值。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description_1 ~%kit_description_1%~ BEGIN
  REPLACE_TEXTUALLY ~IAIJUTSU_DESCRIPTION~ ~~
END

END


ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description_1 ~%kit_description_1%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-16级时，不会获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description_1 ~%kit_description_1%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~武士~)
	
    lower         = RESOLVE_STR_REF(~武士~)
	
    help          = RESOLVE_STR_REF(~%kit_description_1%~)
	
    briefdesc     = RESOLVE_STR_REF(~武士：武士首先是战士，以剑为生，也以剑赴死。武士道严苛无情，武士必须时刻抱持赴死的觉悟。~)
	
	// fallen = 0

	fallen_notice = RESOLVE_STR_REF (~失格：职业已转为浪人~)
	
  STR_VAR
    kit_name      = ~C0_SAMURAI~
	
    unusable      = ~0x40000000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                         T   S           F   Q             S S
	//                                         W   C           L   U             W I
	//                                 B L S   O   I   W       A   A             O N
	//                                 A O H   H   M   A       I   R C   S       R G
	//                 L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//                 _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//                 S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//                 W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//                 O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//                 R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//                 D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~0 0 0 0 0 0 0 0 0 0 0 0 0 5 5 0 0 0 0 0 0 0 0 0 5 0 0 0 2 0 2 3~
	
    abclasrq      = ~13 0 13 14 13 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//                 L L L N N N C C C
	//                 G N E G N E G N E
    alignmnt      = ~1 1 1 0 0 0 0 0 0~
	
    dualclas      = ~0 1 1 0 1 0~
	
    //luabbr        = ~C0SAM~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0SAMURA.2da~
	
  //  kittable      = ~K_F_H K_F_E K_F_HE K_F_G K_F_HL K_F_HO~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
  //  hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
     clascolr = ~145 47 141 5 21~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

//////////////////////////////
/////       RONIN        /////
//////////////////////////////

OUTER_SPRINT kit_description_2 ~浪人：浪人是失格的武士，背弃了自身的荣誉准则。尽管抛弃了过往的道，也失去了部分原有技艺，但剑术依旧致命；而不再受原则束缚的他们，更愿意钻研并利用独属于自己的奇策诡术。

职业优势：
-免疫背刺、恐惧与士气崩溃。
-获得「务实之道」被动效果。

务实之道：当目标处于睡眠、恐慌、震慑、魅惑、中毒、缓慢、目盲、患病、愚钝或困惑状态时，或是浪人在隐身状态下发动攻击时，浪人的近战攻击会额外造成4点无法减免的穿刺伤害。

-1级起每日可使用一次「淬毒武器」，之后每提升6级额外获得1次使用次数。

淬毒武器：浪人可在武器上涂抹剧毒，药效持续八小时。毒素发作平缓但烈性极强，立即并在之后每回合造成伤害，同时降低目标体质，效果至少持续4回合。4回合后，目标必须进行死亡豁免检定，失败则毒素再持续4回合。因此只要目标未能成功豁免，毒素就可能无限持续。目标不会因毒素造成的体质流失而直接死亡。
  1级：目标受到2点毒素伤害，损失1点体质。无豁免惩罚。
  6级：目标受到4点毒素伤害，损失1点体质。豁免惩罚-1。
  11级：目标受到6点毒素伤害，损失2点体质。豁免惩罚-2。
  16级：目标受到8点毒素伤害，损失2点体质。豁免惩罚-3。
  21级：目标受到10点毒素伤害，损失3点体质。豁免惩罚-4。IAIJUTSU_DESCRIPTION

-14级：每日可使用一次「气合大喝」。

气合大喝：浪人暴喝一声，下回合内的所有攻击均取最大伤害值。附近所有敌人士气受挫一回合，且必须额外进行一次麻痹豁免检定（难度-4），失败则一回合内完全无法移动或采取任何行动，且护甲等级受-10惩罚。

职业限制：
-必须为混乱阵营。KIT_DISADV_1
-不可穿戴比镶片甲更重的护甲。
-仅可精通武士刀、胁差与长弓三类武器，无法达到武器大师级。
-不可精通剑盾战斗风格。~

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN

OUTER_PATCH_SAVE kit_description_2 ~%kit_description_2%~ BEGIN
  REPLACE_TEXTUALLY ~IAIJUTSU_DESCRIPTION~ ~

-9级：可使用「居合术」。

居合术：手持单手剑时，浪人每回合额外获得半次攻击；且每两回合的首次攻击速度因子为0，必定暴击，最小伤害掷骰+4。若手持双手武器、远程武器，或副手持有任何物品，则失去该加值。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description_2 ~%kit_description_2%~ BEGIN
  REPLACE_TEXTUALLY ~IAIJUTSU_DESCRIPTION~ ~~
END

END

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description_2 ~%kit_description_2%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-16级时，不会获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description_2 ~%kit_description_2%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~浪人~)
	
    lower         = RESOLVE_STR_REF(~浪人~)
	
    help          = RESOLVE_STR_REF(~%kit_description_2%~)
	
    briefdesc     = RESOLVE_STR_REF(~浪人：浪人是失格的武士，背弃了荣誉准则。虽失去了部分原有技艺，但不再受原则束缚，更擅长钻研独有的诡术。~)
	
	visible = 0
	
  STR_VAR
    kit_name      = ~C0_RONIN~
	
    unusable      = ~0x40000000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                         T   S           F   Q             S S
	//                                         W   C           L   U             W I
	//                                 B L S   O   I   W       A   A             O N
	//                                 A O H   H   M   A       I   R C   S       R G
	//                 L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//                 _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//                 S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//                 W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//                 O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//                 R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//                 D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~2 2 2 2 2 2 2 2 2 2 2 2 2 5 5 2 2 2 2 2 2 2 2 2 5 2 2 2 2 0 2 3~
	
    abclasrq      = ~13 0 13 14 13 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//                 L L L N N N C C C
	//                 G N E G N E G N E
    alignmnt      = ~0 0 0 0 0 0 1 1 1~
	
    dualclas      = ~0 1 1 1 1 0~
	
    //luabbr        = ~C0SAM~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0RONIN.2da~
	
    // kittable      = ~~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
  //  hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

ACTION_IF GAME_IS ~BG2EE EET~ THEN BEGIN
COMPILE ~%MOD_FOLDER%/Fighter/Samurai/dialogue/samurai_dialog.d~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur.bcs~ THEN BEGIN
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/Fighter/Samurai/scripts/samurai_reputation.baf~
EXTEND_TOP ~baldur.bcs~ ~%MOD_FOLDER%/Fighter/Samurai/scripts/samurai_regain.baf~
END

ACTION_IF GAME_IS ~BG2EE EET~ THEN BEGIN
EXTEND_TOP ~AR1304.bcs~ ~%MOD_FOLDER%/Fighter/Samurai/scripts/samurai_regain.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~bdbaldur.bcs~ THEN BEGIN
EXTEND_TOP ~bdbaldur.bcs~ ~%MOD_FOLDER%/Fighter/Samurai/scripts/samurai_reputation.baf~
END

ACTION_IF FILE_EXISTS_IN_GAME ~baldur25.bcs~ THEN BEGIN
EXTEND_TOP ~baldur25.bcs~ ~%MOD_FOLDER%/Fighter/Samurai/scripts/samurai_reputation.baf~
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~武士道~) STR_VAR bam_file = C0SAMI01 RET C0SAMI01 = icon END

ADD_PROJECTILE ~%MOD_FOLDER%/Fighter/Samurai/pro/C0SAM02P.PRO~ ~C0 Samurai Bushido~
ADD_PROJECTILE ~%MOD_FOLDER%/Fighter/Samurai/pro/C0SAM02X.PRO~ ~C0 Samurai Bushido2~
COPY_EXISTING ~C0SAM02A.spl~ ~override~
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0SAM02P
END
  LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 142
		parameter2 = C0SAMI01
END
COPY_EXISTING ~C0SAM02X.spl~ ~override~
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0SAM02X
END
COPY_EXISTING ~C0SAM02Y.spl~ ~override~
  LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 240
		parameter2 = C0SAMI01
END
  LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 169
		parameter2 = C0SAMI01
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~C0CAV03.SPL~ BEGIN

COPY ~%MOD_FOLDER%/spells/challenge~ ~override~

COPY_EXISTING ~C0CAV03.spl~ ~override~
SAY NAME1 ~决死挑戦！~
SAY UNIDENTIFIED_DESC ~决死挑戦
施法者标记一名目标生物，接下来三回合内，目标与施法者自身的护甲等级各降低10点。施法者对被挑战的目标造成额外的无法减免魔法伤害。此外，被挑战目标在战争迷雾中会显形，且效果持续期间无法进入隐身状态。
  1-11级：造成1d6点伤害
  12-19级：造成2d6点伤害
  20级及以上：造成4d6点伤害~
  LPF ALTER_EFFECT
    INT_VAR
      match_opcode = 139
	  parameter1 = RESOLVE_STR_REF (~挑战标记~)
END

END

ACTION_IF (opcode_342_eeex = 1) THEN BEGIN

INCLUDE ~%MOD_FOLDER%/eeex/profs_eeex.tpa~

LAF ADD_IDS_ENTRY INT_VAR minValue = 1 preferredValue = 200 STR_VAR idsFile = "stats.ids" identifier = "C0_DUAL_WIELDING" RET value END

OUTER_SET C0_DUAL_WIELDING = IDS_OF_SYMBOL (~STATS~ ~C0_DUAL_WIELDING~)

APPEND ~splprot.2da~ ~C0_DUAL_WIELDING%TAB%%C0_DUAL_WIELDING%%TAB%-1%TAB%1~ UNLESS ~C0_DUAL_WIELDING~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_DUAL_WIELDING~ BEGIN
	    SET C0_DUAL_WIELDING = %row%
	  END
	END

COPY_EXISTING ~C0SAM03A.spl~ ~override~
  LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 318
		parameter1 = 2
		parameter2 = C0_DUAL_WIELDING
END

COPY_EXISTING ~C0SAM03D.spl~ ~override~
  LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 139
		parameter1 = RESOLVE_STR_REF (~居合一击~)
END

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (SOURCE_SIZE > 0x71) THEN BEGIN // protects against invalid files
    READ_BYTE 0x1f "usa2"
    READ_BYTE 0x29 "kit1"
    PATCH_IF ((("%kit1%" BAND 0b01000000) = 0b01000000) AND // if unusable by fighters and barbarians
              (("%usa2%" BAND 0b00001000) = 0b00001000)) THEN BEGIN
      WRITE_BYTE 0x29 ("%kit1%" BAND 0b10111111) //remove redundant barb flag
      LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 timing = 2 power = 0 parameter1 = 0 parameter2 = 5 special = RESOLVE_STR_REF (~野蛮人~) END
    END
  END
  BUT_ONLY

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
      READ_BYTE    0x1E row1
      READ_BYTE    0x1F row2
      READ_BYTE    0x20 row3
      READ_BYTE    0x21 row4
      READ_BYTE    0x29 kit_row1
    READ_BYTE    0x18 twohanded
    PATCH_IF ((twohanded BAND 0b00000010) = 0b00000000) BEGIN 
      READ_SHORT    0x22 appearance 
      PATCH_IF (appearance = 22593) OR (appearance = 19523) OR (appearance = 17476) OR (appearance = 12358) OR (appearance = 12614) OR (appearance = 12870) OR (appearance = 13126) OR (appearance = 19526) OR (appearance = 21318) OR (appearance = 12627) OR (appearance = 13139) OR (appearance = 12877) OR (appearance = 17229) OR (appearance = 21325) OR (appearance = 12371) OR (appearance = 17235) OR (appearance = 21331) OR (appearance = 18519) BEGIN
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 326 target = 1 parameter1 = 2 parameter2 = C0_DUAL_WIELDING timing = 2 STR_VAR resource = C0SAM03X END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 401 target = 1 parameter1 = 1 parameter2 = 0 timing = 2 special = IDS_OF_SYMBOL (~STATS~ ~C0_DUAL_WIELDING~) END
    	END
  END
    READ_BYTE    0x18 twohanded
    PATCH_IF ((twohanded BAND 0b00000010) = 0b00000010) BEGIN 
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 318 target = 1 parameter1 = 0 parameter2 = 0 timing = 2 STR_VAR resource = C0SAM03A END
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = 0 timing = 2 STR_VAR resource = C0SAM03X END
      END
  END
BUT_ONLY

COPY_EXISTING ~C0SAMURA.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = AP_C0SAM03 END // IAIJUTSU
  PRETTY_PRINT_2DA

COPY_EXISTING ~C0RONIN.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 9 f_MaxLevel = 9 STR_VAR f_Entry = AP_C0SAM03 END // IAIJUTSU
  PRETTY_PRINT_2DA

	END

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ BEGIN

COPY_EXISTING ~C0SAMURA.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // POWER ATTACK
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG02 END // EXPERTISE
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
   // LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = AP_C0FIG04 END // SPECIALIZATION
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0FIG03 END // IMPROVED INITIATIVE
  PRETTY_PRINT_2DA

COPY_EXISTING ~C0RONIN.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG01 END // POWER ATTACK
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_MaxLevel = 5 STR_VAR f_Entry = GA_C0FIG02 END // EXPERTISE
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 6 f_MaxLevel = 6 STR_VAR f_Entry = GA_C0ARC03 END // RAPID SHOT
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 f_MaxLevel = 12 STR_VAR f_Entry = AP_C0ARC03Z END
   // LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = AP_C0FIG04 END // SPECIALIZATION
   LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0FIG03 END // IMPROVED INITIATIVE
  PRETTY_PRINT_2DA

	END

COPY_EXISTING ~C0SAM04.SPL~ ~OVERRIDE~
SAY NAME1 ~气合大喝~
SAY UNIDENTIFIED_DESC ~气合大喝
武士暴喝一声，下回合内的所有攻击均取最大伤害值。附近所有敌人士气大幅受挫一回合，且必须额外进行一次麻痹豁免检定（难度-4），失败则一回合内完全无法移动或采取任何行动，且护甲等级受-10惩罚。~
