
COPY ~%MOD_FOLDER%/Thief/Shadowdancer/2DAs~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Thief/Shadowdancer/SPELLS~ ~OVERRIDE~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/CLABTH05.2DA~
	REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE
	REPLACE_TEXTUALLY ~AP_C0TH-A2~ ~**** ~ // EPIC PRECISION

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_SPSD02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 STR_VAR f_Entry = GA_SPSD02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SD-1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 STR_VAR f_Entry = AP_C0SD-2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = GA_C0SD-A1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = GA_C0SD-A2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 f_Increment = 10 STR_VAR f_Entry = GA_C0SD-A2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = AP_C0SD-3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_C0SD-A3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_C0SD-A3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_C0SD-A3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 12 STR_VAR f_Entry = AP_C0SD-4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0SD-5 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0SD-6 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~影舞者：影舞者游走于光暗交界，是灵巧狡黠的欺诈大师。他们神秘莫测、行迹难寻，从不为人全然信任，却总能引得旁人惊叹。影舞者能驾驭魔法之力强化潜行本领。这些技艺独特的盗贼诡谲而致命，能以普通盗贼无法企及的方式融入暗影，出手毫无征兆——有时甚至带着超自然的速度。尽管与暗影和诡计相伴，影舞者的阵营可善可恶。

职业优势：
–+15%阴影躲藏与无声行动能力
-凭空消失：只要上一回合内未受到攻击，影舞者即便在被注视的情况下也能隐入阴影。
-每日可使用一次「暗影步」。1级时获得1次，之后每提升5级额外获得1次使用次数。

暗影步：踏入暗影位面，在时间停滞的7秒内自由移动。影舞者在暗影位面中无法攻击或施法。

-2级：永久获得黑暗视觉。
-3级：每日可使用一次「召唤幽影」。

召唤幽影：影舞者可从暗影位面召唤一只生物协助战斗，持续2回合。幽影具备影舞者的能力，威力随召唤者的影舞者等级提升。

-5级：每日可使用一次「暗影眩晕」。每提升10级额外获得1次使用次数。

暗影眩晕：目标法术豁免（难度-3）失败则陷入幻象眩晕5回合：护甲等级-10且无法行动，受到攻击后效果立即解除。

-10级：每日可使用三次「暗影闪避」。

暗影闪避：影舞者将自身隐入暗影。接下来3回合内，影舞者处于半隐形状态，除非生物能看破隐形，否则无法以法术锁定。处于半隐形状态时，物理抗性+5%，护甲等级+1。15级、20级与25级时，该加值会在原有基础上再提升一倍。

-10级：获得「防御翻滚」。

防御翻滚：当影舞者受到足以致命的伤害时，改为仅剩1点生命值存活，并立即进入隐形状态，下回合免疫所有伤害。本效果无法防护即死效果或非伤害类死亡效果。每8小时最多触发一次。

-12级：免疫背刺。
-15级：获得「心智灵活」。

心智灵活：影舞者受到影响心灵的法术或效果时，效果持续期间每回合都可进行一次法术豁免检定（难度-4），成功则立即摆脱该效果。

-20级：即便受到攻击后，影舞者也可使用凭空消失。

职业限制：KIT_DISADV_1
-背刺伤害倍率远低于普通盗贼：
  1-4级：1倍（无额外倍率）
  5-8级：2倍
  9-12级：3倍
–每等级只能在盗贼技能上投入15技能点数
–不能使用设置陷阱能力

兼职主属性要求：力量、敏捷、魅力~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-无法使用致残打击。
-不获得史诗精准。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~SHADOWDANCER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~
	
// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~防御翻滚~) STR_VAR bam_file = C0SD-3I RET C0SD-3I = icon END

// PROFICIENCIES

COPY_EXISTING ~BACKSTAB.2da~ ~override~
  REPLACE_EVALUATE ~SHADOWDANCER \([- %TAB%0-9]+\)~ BEGIN
    SPRINT data ~%MATCH1%~
  END ~SHADOWDANCER 1 1 1 1 1 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3~

  COPY_EXISTING ~thiefskl.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~SHADOWDANCER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols 40
		SET_2DA_ENTRY (%patch_row%) 2 cols 15
	  END
	END
  
COPY_EXISTING ~C0SD-3A.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0SD-3I
      END

COPY_EXISTING ~C0SD-3C.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~防御翻滚规避致命伤害~) END

COPY_EXISTING ~C0SD-5A.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~心智灵活挣脱附魔~) END

COPY_EXISTING ~C0SD-A1.SPL~ ~OVERRIDE~
SAY NAME1 ~召唤幽影~
SAY UNIDENTIFIED_DESC ~召唤幽影
影舞者可从暗影位面召唤一只生物协助战斗，持续2回合。幽影具备影舞者的能力，威力随召唤者的影舞者等级提升。~

COMPILE ~%MOD_FOLDER%/Thief/Shadowdancer/scripts/C0SD-A1A.BAF~

COPY_EXISTING ~C0SD-A1C.CRE~ ~OVERRIDE~
SAY NAME1 ~幽影~
SAY NAME2 ~幽影~
  WRITE_ASCII SCRIPT_OVERRIDE ~C0SD-A1A~ #8 // override
  WRITE_ASCII DEATHVAR ~C0SD-A1A~ #8 // death variable

COPY_EXISTING ~C0SD-A2.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~眩晕~) END
SAY NAME1 ~暗影眩晕~
SAY UNIDENTIFIED_DESC ~暗影眩晕
目标法术豁免（难度-3）失败则陷入幻象眩晕5回合：护甲等级-10且无法行动，受到攻击后效果立即解除。~

COPY_EXISTING ~C0SD-A3.SPL~ ~OVERRIDE~
SAY NAME1 ~暗影闪避~
SAY UNIDENTIFIED_DESC ~暗影闪避
影舞者将自身隐入暗影。接下来3回合内，影舞者处于半隐形状态，除非生物能看破隐形，否则无法以法术锁定。处于半隐形状态时，物理抗性+5%，护甲等级+1。15级、20级与25级时，该加值会在原有基础上再提升一倍。~
