COPY ~%MOD_FOLDER%/Fighter/Siegemaster/2das~ ~override~
COPY ~%MOD_FOLDER%/Fighter/Siegemaster/spells~ ~override~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/C0SIEGEM.2DA~
	REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
	REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
	REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
	REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
	REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
	REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SIEG0 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 2 f_Increment = 2 STR_VAR f_Entry = AP_C0SIEG1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = GA_C0SIEG4 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~攻城大师：攻城大师是身披重甲、武装精良的战士，专精于毁灭性的远程打击。他们能轻松驾驭尺寸最大、分量最重的远程武器，致命的射击足以击穿最坚固的护甲与设防最严密的城堡。对攻城大师而言，世上不存在「无法突破的防御」。

职业优势：
-每2级，远程武器的攻击检定与伤害掷骰获得+1加值。
-箭矢或弩矢造成的远程伤害+50%；若两回合内未成功命中过目标，该加成提升至+250%。
-获得「穿甲」与「重弩」被动效果。

穿甲：攻城大师擅长击破护甲与其他坚固防御，目标护甲等级每低于10点1点，就额外造成1点无法减免的穿刺伤害。此外，攻城大师的暴击可穿透目标50%的远程伤害抗性。

重弩：攻城大师的远程弹药冲击力极强，命中时震慑目标2秒并将其轻微击退。但每次攻击后，攻城大师的移动速度会短暂降低75%，该效果无法被「自由行动」抵消。

-10级：每日可使用一次「远射」。

远射：攻城大师化身成移动炮台。接下来两次攻击造成最大伤害，远程暴击修正+10，且攻击不会出现严重失误。此外视野范围大幅提升。但远射生效期间，移动速度降低90%。若两回合内未发动攻击，远射自动失效。

-15级：远射生效期间可攻击次数提升至3次。
-20级：远射生效期间可攻击次数提升至4次。

职业限制：KIT_DISADV_1
-非加速状态下，每回合攻击次数不得超过1次。
-除弓与弩外，无法装备任何其他远程武器。
-除弩与长弓外，其他武器的精通等级不得超过熟练级（1星）。
-任意战斗风格的精通等级不得超过熟练级（1星）。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-无法使用猛力攻击、武器专精或快速射击。
-16级时不会获得全武器专精。
-不获得精通先攻。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~攻城大师~)
	
    lower         = RESOLVE_STR_REF(~攻城大师~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~攻城大师：是武装精良、身披重甲的战士，专精于令人胆寒的远程打击。他们能游刃有余地操控尺寸最大、分量最重的远程武器，致命的射击足以击穿最坚固的护甲与设防森严的城堡。对攻城大师而言，世间不存在「坚不可摧的防御」。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0_SIEGEMASTER~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~1 1 5 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 5 1 0 0 1 1 1 1~
	
    abclasrq      = ~17 12 0 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0SIEG~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0SIEGEM.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

// Resistances
DEFINE_ACTION_FUNCTION	ADD_SPLPROT	INT_VAR	stat = 0	value = 0	relation = 0	RET	new_row		BEGIN
	ACTION_IF	(stat > 278)	BEGIN	WARN	~SPLPROT.2DA - Stat out of Bounds.~	END
	ACTION_IF	((stat != 259) AND (stat != 260) AND (relation > 11))	BEGIN	WARN	~SPLPROT.2DA - Relation out of Bounds.~	END
	COPY_EXISTING ~SPLPROT.2DA~	OVERRIDE
		COUNT_2DA_COLS	cols
		COUNT_2DA_ROWS cols rows
		TEXT_SPRINT check_row ~~
		TEXT_SPRINT check_stat ~~
		SET new_row = 0
		FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
			PATCH_IF (~%check_stat%~ STRING_EQUAL ~%stat%~)	BEGIN	READ_2DA_ENTRY current_row 2 cols check_value
				PATCH_IF (~%check_value%~ STRING_EQUAL ~%value%~)	BEGIN	READ_2DA_ENTRY current_row 3 cols check_relation
					PATCH_IF (~%check_relation%~ STRING_EQUAL ~%relation%~)	BEGIN	new_row = current_row	current_row = rows	END
				END
			END
		END
		PATCH_IF (new_row = 0)	BEGIN
			FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
				PATCH_IF (~%check_stat%~ STRING_EQUAL ~*~)	BEGIN	new_row = current_row	current_row = rows	END
			END
			PATCH_IF (new_row = 0)	BEGIN	new_row = rows	INSERT_2DA_ROW rows cols ~%new_row%		   %stat%		   %value%		   %relation%~
			END	ELSE	BEGIN	SET_2DA_ENTRY new_row 1 cols ~%stat%~	SET_2DA_ENTRY new_row 2 cols ~%value%~	SET_2DA_ENTRY new_row 3 cols ~%relation%~	END
		END
	BUT_ONLY
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

APPEND ~splprot.2da~ ~C0_SIEGEMASTER_AC 2 -1 1~ UNLESS ~C0_SIEGEMASTER_AC~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_SIEGEMASTER_AC~ BEGIN
	    SET C0_SIEGEMASTER_AC = %row%
	  END
	END
	
COPY_EXISTING ~C0SIEG2.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 0 parameter2 = C0_SIEGEMASTER_AC END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED02.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 2 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED03.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 3 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED04.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 4 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED05.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 5 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED06.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 6 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED07.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 7 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED08.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 8 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED09.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 9 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED10.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 10 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED11.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 11 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED12.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 12 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED13.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 13 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED14.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 14 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED15.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 15 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED16.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 16 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED17.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 17 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED18.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 18 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED19.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 19 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED20.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 20 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED21.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 21 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED22.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 22 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED23.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 23 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED24.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 24 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED25.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 25 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED26.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 26 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED27.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 27 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED28.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 28 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED29.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 29 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED30.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 30 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED31.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 31 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED32.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 32 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED33.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 33 END

COPY_EXISTING ~C0SIED01.SPL~ ~OVERRIDE/C0SIED34.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 12 parameter1 = 34 END

COPY_EXISTING ~C0SIEG0.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 181 special = RESOLVE_STR_REF (~无法使用该物品。~) END

COPY_EXISTING ~C0SIEG4.SPL~ ~OVERRIDE~
SAY NAME1 ~远射~
SAY UNIDENTIFIED_DESC ~远射
攻城大师化身成移动炮台。接下来两次攻击造成最大伤害，远程暴击修正+10，且攻击不会出现严重失误。此外视野范围大幅提升。但远射生效期间无法移动。若两回合内未发动攻击，远射自动失效。~

