COPY ~%MOD_FOLDER%/Ranger/Stalker/2DA~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Ranger/Stalker/spells~ ~OVERRIDE~

COPY_EXISTING ~CLABRN01.2DA~ ~OVERRIDE/CLABRN03.2DA~
	REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%] ~ ~**** ~ // TOUGHNESS
	REPLACE_TEXTUALLY ~AP_C0RNH[%0-9%][%0-9%] ~ ~**** ~ // TOUGHNESS
	// REPLACE_TEXTUALLY ~GA_SPCL311~ ~**** ~ // CHARM ANIMAL
	// REPLACE_TEXTUALLY ~GA_SPCL412~ ~**** ~ // SET SNARE
	REPLACE_TEXTUALLY ~C0RNG00A ~ ~**** ~ // CAMOUFLAGE
	REPLACE_TEXTUALLY ~C0CL922 ~ ~**** ~ // TRACKING

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0STK00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = AP_C0STK00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0STK00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0STK01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0STK02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0STK03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0STK04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0A_A01 END

 	PRETTY_PRINT_2DA

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~STALKER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~潜行者：潜行者是专职的隐秘情报搜集者，在荒野与都市环境中都能如鱼得水。他们身兼间谍、线人与审讯者多重身份。全面的技艺让他们足以胜任任何任务，无论是游说、暗杀还是正面作战。

职业优势：
-设置陷阱获得+10%加值。
-室内时，隐匿阴影与潜行获得迷彩加成（+25%）。
-室内可使用追踪能力。
-疾步：潜行者处于潜行或隐身状态时，移动速度提升30%。
-每个法术环级可记记一个法师法术：1环交友术、2环识破隐形、3环加速术。
-可使用背刺能力，但伤害倍率低于普通游荡者：
  1-8级：2倍
  9-16级：3倍
  17级及以上：4倍
-可随意使用「分析」能力。

分析：使用者可通过此能力仔细观察目标，识别其优缺点，显示目标的生命骰、零级命中值、豁免检定、魔法抗性、伤害抗性，以及对毒素与背刺的易伤性。此能力可无限制使用。

-15级：暗影披风：潜行者对潜行的掌控炉火纯青，处于隐匿或隐身状态时，无论魔法还是寻常手段都完全无法侦测、锁定<PRO_HIMHER>。即便通常能看破隐形的生物也无法察觉潜行者的存在。

职业限制：
-生命骰：d8，不获得强健加值
-不获得林地步伐。
–无法穿戴重于皮环甲的护甲。~

APPEND ~splprot.2da~ ~C0_OUTDOORS_CHECK%TAB%0x106%TAB%1%TAB%8~ UNLESS ~C0_OUTDOORS_CHECK~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_OUTDOORS_CHECK~ BEGIN
	    SET C0_OUTDOORS_CHECK = %row%
	  END
	END

INCLUDE ~%MOD_FOLDER%/spells/tracking.tpa~

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "STALKER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "STALKER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count (val+35)
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY

END
ACTION_IF NOT MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

COPY ~%MOD_FOLDER%/Ranger/Stalker/vanilla~ ~OVERRIDE~

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~STALKER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~潜行者：潜行者是专职的隐秘情报搜集者，在荒野与都市环境中都能如鱼得水。他们身兼间谍、线人与审讯者多重身份。全面的技艺让他们足以胜任任何任务，无论是游说、暗杀还是正面作战。

职业优势：
–无声行动和阴影躲藏+20%。
-潜行施法：潜行者在隐匿或隐身状态下施法时，若原施法时间长于1，则缩短为1。
-每个法术环级可记记一个法师法术：1环交友术、2环识破隐形、3环加速术。
–可以使用背刺能力，但是与盗贼相比伤害倍数较小：
  等级1–8：×2
  等级9–16：×3
  等级17+：×4
-可随意使用「分析」能力。

分析：使用者可通过此能力仔细观察目标，识别其优缺点，显示目标的生命骰、零级命中值、豁免检定、魔法抗性、伤害抗性，以及对毒素与背刺的易伤性。此能力可无限制使用。

-15级：暗影披风：潜行者对潜行的掌控炉火纯青，处于隐匿或隐身状态时，无论魔法还是寻常手段都完全无法侦测、锁定<PRO_HIMHER>。即便通常能看破隐形的生物也无法察觉潜行者的存在。

职业限制：
–无法穿戴重于皮环甲的护甲。~

END

// Friends
COPY_EXISTING ~SPWI107.SPL~ ~OVERRIDE/C0STK02.SPL~
WRITE_SHORT 0X34 1
WRITE_SHORT 0X1C 2
// Detect Invisibility
COPY_EXISTING ~SPWI203.SPL~ ~OVERRIDE/C0STK03.SPL~
WRITE_SHORT 0X34 2
WRITE_SHORT 0X1C 2
// Haste
COPY_EXISTING ~SPWI305.SPL~ ~OVERRIDE/C0STK04.SPL~
WRITE_SHORT 0X34 3
WRITE_SHORT 0X1C 2

// STALKER - HIT DIE
COPY_EXISTING ~hpclass.2da~ OVERRIDE
REPLACE_TEXTUALLY CASE_INSENSITIVE ~STALKER              HPWAR~ ~STALKER              HPARCH~

// STALKER - HLA
  COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~STALKER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~C0RA2~
	  END
	END

COPY_EXISTING ~LURA0.2da~ ~override/LUC0RA2.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPCL907~ END
LPF patch_add_hla STR_VAR 2da_row = ~C0RA2~ ability = ~GA_SPCL916~ num_allowed = 1 END
	
// VALYGAR

ACTION_IF FILE_EXISTS_IN_GAME ~valyg8.cre~ THEN BEGIN
    COPY_EXISTING ~valyg8.cre~ ~override~
	WRITE_SHORT 0x24 64
	WRITE_SHORT 0x26 64
END

ACTION_IF FILE_EXISTS_IN_GAME ~valyg9.cre~ THEN BEGIN
    COPY_EXISTING ~valyg8.cre~ ~override~
	WRITE_SHORT 0x24 72
	WRITE_SHORT 0x26 72
END

ACTION_IF FILE_EXISTS_IN_GAME ~valyg11.cre~ THEN BEGIN
    COPY_EXISTING ~valyg8.cre~ ~override~
	WRITE_SHORT 0x24 80
	WRITE_SHORT 0x26 80
END

ACTION_IF FILE_EXISTS_IN_GAME ~valyg12.cre~ THEN BEGIN
    COPY_EXISTING ~valyg8.cre~ ~override~
	WRITE_SHORT 0x24 92
	WRITE_SHORT 0x26 92
END

ACTION_IF FILE_EXISTS_IN_GAME ~valyg14.cre~ THEN BEGIN
    COPY_EXISTING ~valyg8.cre~ ~override~
	WRITE_SHORT 0x24 92
	WRITE_SHORT 0x26 92
END


ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~2000~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~M_C0RAN1.lua~ THEN BEGIN

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "STALKER") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 100
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 100
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~clasiskl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_EQUAL_CASE "STALKER") BEGIN
      READ_2DA_ENTRY 6 col col_count val
      SET_2DA_ENTRY  6 col col_count 20
      READ_2DA_ENTRY 3 col col_count val
      SET_2DA_ENTRY  3 col col_count 20
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
END
END