
COPY ~%MOD_FOLDER%/Thief/Swashbuckler/2DAs~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Thief/Swashbuckler/SPELLS~ ~OVERRIDE~

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/CLABTH04.2DA~
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE
	REPLACE_TEXTUALLY ~AP_C0TH-A2~ ~**** ~ // EPIC PRECISION

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SB-0 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0SB-1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0SB-2 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0SB-2A END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = AP_C0SB-1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 18 STR_VAR f_Entry = AP_C0SB-1 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0SB-3 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 f_Increment = 5 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0SB-4 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_C0THWAR END

 	PRETTY_PRINT_2DA

INCLUDE ~ArtisansKitpack/lib/thac0.tpa~

OUTER_SPRINT kit_description ~游荡剑客：这名盗贼身兼杂技艺人、剑客<PRO_MANWOMAN>与智者数重身份，是魅力与优雅的典范。游荡剑客集胆识与气度于一身，崇尚机敏与智慧胜过蛮力，无论战斗场合还是社交周旋都得心应手，是名副其实的多面手。

职业优势：
-英雄气运：所有豁免检定、攻击检定与技能检定获得+1加值。
–盗贼可用的任意近战武器技能都可以达到精通（二星）水平。
-可分别将剑盾式、单武器式、双武器式战斗风格修至专精级或大师级。
-零级命中值的成长与同等级战士相当。
-20级前，每偶数等级基础护甲等级+1。
-5级起获得护甲等级+1加值，效果持续至20级。
-获得「诡击」被动效果。

诡击：游荡剑客能施展精妙的攻击直击目标弱点，手持近战武器时，伤害与暴击率获得加值，加值随智力与等级提升。若装备任何会禁用盗贼技能的护甲，则失去该加值。

智力17：伤害+1
智力18：伤害+1
智力19：暴击率+1
5级且智力20：伤害+1
8级且智力21：暴击率+1
11级且智力22：伤害+1
14级且智力23：暴击率+1
17级且智力24：伤害+1
20级且智力25：暴击率+1

-10级：英雄气运加值提升至+2。
-18级：英雄气运加值提升至+3。
-20级：手持近战武器时，每回合额外获得半次攻击。

职业限制：KIT_DISADV_1
-每等级仅可分配15点技能点至盗贼技能。
–不能使用背刺能力。
-无法使用潜行能力。
-无法使用设置陷阱能力。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-无法使用魔法装置。
-无法使用致残打击。
-不获得史诗精准。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~SWASHBUCKLER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~
	
  COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~SWASHBUCKER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~C0-SB~
	  END
	END
	
// PROFICIENCIES
ACTION_CLEAR_ARRAY weapprof_cols_swashbuckler
        
COPY_EXISTING ~weapprof.2da~  ~override~
  COUNT_2DA_COLS col_count
  SET col_check = col_count - 1
  FOR (column = 0; column < col_check; ++column) BEGIN
    READ_2DA_ENTRY 0 column col_check name
    PATCH_IF (("SWASHBUCKLER" STRING_COMPARE_CASE "%name%" = 0)) BEGIN
      SET column += 1 // row with names has an empty entry for the first column
      DEFINE_ASSOCIATIVE_ARRAY weapprof_cols_swashbuckler BEGIN ~%column%~ => ~%column%~ END
    END
  END
  PATCH_PHP_EACH weapprof_cols_swashbuckler AS column => foo BEGIN
    FOR (row = 0; row < 32; ++row) BEGIN
      READ_2DA_ENTRY row column col_count stars
      PATCH_IF (stars < 5) BEGIN
        SET_2DA_ENTRY 29 column col_count 2
        SET_2DA_ENTRY 30 column col_count 2
      END
    END
  END
  PRETTY_PRINT_2DA
  BUT_ONLY
	
  COPY_EXISTING ~thiefskl.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~SWASHBUCKLER~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 2 cols 15
	  END
	END
	
// INTELLIGENCE
APPEND ~splprot.2da~ ~C0HTINT%TAB%38%TAB%-1%TAB%1~ UNLESS ~C0HTINT~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0HTINT~ BEGIN
	    SET C0HTINT = %row%
	  END
	END

COPY_EXISTING ~thiefscl.2da~ ~override~
  REPLACE_TEXTUALLY ~^\([ %TAB%]*MAGE\)~ ~CD_DELETE_ME \1~ // adding column to header column
  COUNT_2DA_COLS col_count
  FOR (col = 1 ; col < col_count ; ++col) BEGIN
    READ_2DA_ENTRY 0 col col_count kit
    PATCH_IF ("%kit%" STRING_COMPARE_CASE "SWASHBUCKLER" = 0) BEGIN
      READ_2DA_ENTRY 7 col col_count val
      SET_2DA_ENTRY  7 col col_count 0
      READ_2DA_ENTRY 4 col col_count val
      SET_2DA_ENTRY  4 col col_count 0
      READ_2DA_ENTRY 5 col col_count val
      SET_2DA_ENTRY  5 col col_count 0
      SET col = col_count // kill loop
    END
  END  
  REPLACE_TEXTUALLY ~CD_DELETE_ME ~ ~~ // removing it
  PRETTY_PRINT_2DA
  BUT_ONLY
  
COPY_EXISTING ~C0SB-I.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_parameter2 = 128 match_special = 1 parameter2 = C0HTINT END

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
      READ_SHORT    0x1C type //reads the byte containing item type
      PATCH_IF (type = 2)  BEGIN // if it is leather armor
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I16 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I17 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I18 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I19 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I20 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I21 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I22 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I23 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I24 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 321 target = 1 timing = 1 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I25 END
		LPF CLONE_EFFECT INT_VAR multi_match = 1 silent = 1 match_opcode = 144 match_parameter2 = 1 opcode = 206 target = 1 timing = 2 parameter1 = 0 parameter2 = 0 STR_VAR resource = C0SB-I END
		END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~C0SB-HL.SPL~ OVERRIDE
SAY NAME1 ~创伤打击~
SAY UNIDENTIFIED_DESC ~游荡剑客能以精准的打击削弱对手，使其更加脆弱。获得此能力后，游荡剑客的暴击会被动降低目标造成与承受伤害的幸运修正值2点，持续4回合。

在其他能力的前置条件判定中，本技能视同已学会猛力攻击。~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY ~%MOD_FOLDER%/lua/m_c0thf2.lua~      ~override~ // Lua file read by EEex, provided by Bubbs and further edited by myself

END

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~CLABTH04.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
      LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0TH-E2 END // USE MAGIC DEVICE
  PRETTY_PRINT_2DA

END

END