COPY ~%MOD_FOLDER%/Thief/spells~ ~OVERRIDE~

ACTION_IF FILE_EXISTS_IN_GAME ~CLABTH01.2DA~ BEGIN
COPY_EXISTING ~CLABTH01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = GA_C0TH-A1 END // CRIPPLING STRIKE
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TH-A2 END // EPIC PRECISION
  PRETTY_PRINT_2DA
BUT_ONLY

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 4) BEGIN
    // Set New Fighter Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Fighter kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
      PATCH_IF (
				("%kit_label%" STRING_EQUAL_CASE "ASSASIN") OR 
				("%kit_label%" STRING_EQUAL_CASE "ASSASSIN")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 f_MaxLevel = 16 STR_VAR f_Entry = GA_C0TH-A1 END // CRIPPLING STRIKE
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TH-A2 END // EPIC PRECISION
        PRETTY_PRINT_2DA
      END
      PATCH_IF (
				("%kit_label%" STRING_EQUAL_CASE "C0ADVENT")
														 ) BEGIN
        LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 f_MaxLevel = 20 STR_VAR f_Entry = AP_C0TH-A2 END // EPIC PRECISION
        PRETTY_PRINT_2DA
      END
      
      BUT_ONLY
      END
    END
  END
  END

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name
        READ_2DA_ENTRY index 1 col_count class_id
//bard

        PATCH_IF "%row_name%" STRING_EQUAL_CASE "THIEF" BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_desc ~–阵营不能是守序善良~
          SPRINT new_desc ~–16级：可将致残打击作为切换式能力使用。
          
致残打击：盗贼背刺时，可降低自身2级背刺伤害倍率，对目标施加致残打击。目标死亡豁免（难度-3）失败则伤害值受-4惩罚，且下回合无法造成暴击。
–20级：获得史诗精准。
          
史诗精准：进入潜行或隐身状态时，盗贼的下一次攻击造成最大伤害，且额外获得+4修正。直到下一次重新进入潜行前，该修正不会恢复。
~
          GET_STRREF %kit_desc% kit_text
          INNER_PATCH_SAVE kit_text ~%kit_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_desc%~ ~%new_desc%
%old_desc%~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%kit_text%~)
            PRETTY_PRINT_2DA
		  END

      PATCH_IF (%class_id% = 4) AND !((
				("%row_name%" STRING_EQUAL_CASE "ASSASIN") OR 
				("%row_name%" STRING_EQUAL_CASE "ASSASSIN") OR
				("%row_name%" STRING_EQUAL_CASE "C0ADVENT")
														 )) BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_kitdesc ~职业限制：~
          SPRINT new_kitdesc ~–无法获得史诗精准。~
          GET_STRREF %kit_desc% kit_text
          INNER_PATCH_SAVE kit_text ~%kit_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_kitdesc%~ ~%old_kitdesc%
%new_kitdesc%~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%kit_text%~)
            PRETTY_PRINT_2DA
          END

      PATCH_IF (%class_id% = 4) AND !((
				("%row_name%" STRING_EQUAL_CASE "ASSASIN") OR 
				("%row_name%" STRING_EQUAL_CASE "ASSASSIN") 
														 )) BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_kitdesc ~职业限制：~
          SPRINT new_kitdesc ~–无法使用致残打击。~
          GET_STRREF %kit_desc% kit_text
          INNER_PATCH_SAVE kit_text ~%kit_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_kitdesc%~ ~%old_kitdesc%
%new_kitdesc%~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%kit_text%~)
            PRETTY_PRINT_2DA
            END
		  END

      COPY_EXISTING ~KITLIST.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 1; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 1 col_count row_name
        READ_2DA_ENTRY index 8 col_count class_id
//inspiration
      PATCH_IF (%class_id% = 4) AND !((
				("%row_name%" STRING_EQUAL_CASE "ASSASIN") OR 
				("%row_name%" STRING_EQUAL_CASE "ASSASSIN") OR
				("%row_name%" STRING_EQUAL_CASE "C0ADVENT")
														 )) BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_kitdesc ~职业限制：~
          SPRINT new_kitdesc ~–无法获得史诗精准。~
          GET_STRREF %kit_desc% kit_text
          INNER_PATCH_SAVE kit_text ~%kit_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_kitdesc%~ ~%old_kitdesc%
%new_kitdesc%~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%kit_text%~)
            PRETTY_PRINT_2DA
		      END
      PATCH_IF (%class_id% = 4) AND !((
				("%row_name%" STRING_EQUAL_CASE "ASSASIN") OR 
				("%row_name%" STRING_EQUAL_CASE "ASSASSIN") 
														 )) BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_kitdesc ~职业限制：~
          SPRINT new_kitdesc ~–无法使用致残打击。~
          GET_STRREF %kit_desc% kit_text
          INNER_PATCH_SAVE kit_text ~%kit_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_kitdesc%~ ~%old_kitdesc%
%new_kitdesc%~
          END
          SET_2DA_ENTRY index 4 col_count RESOLVE_STR_REF (~%kit_text%~)
            PRETTY_PRINT_2DA
            END
		  END

      BUT_ONLY
    END
  END
END
  
// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~致残打击~) STR_VAR bam_file = C0TH-A1I RET C0TH-A1I = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~史诗精准~) STR_VAR bam_file = C0TH-A2I RET C0TH-A2I = icon END

COPY_EXISTING ~C0TH-A1.SPL~ ~OVERRIDE~
SAY NAME1 ~致残打击~
SAY UNIDENTIFIED_DESC ~致残打击
盗贼背刺时，可降低自身2级背刺伤害倍率，对目标施加致残打击。目标死亡豁免（难度-3）失败则伤害值受-4惩罚，且下回合无法造成暴击。~
COPY_EXISTING ~C0TH-A1A.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~致残打击已激活~) END
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0TH-A1I
      END
COPY_EXISTING ~C0TH-A1B.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 330 parameter1 = RESOLVE_STR_REF (~致残打击未激活~) END
COPY_EXISTING ~C0TH-A1C.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~致残打击已生效~) END
COPY_EXISTING ~C0TH-A2C.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0TH-A2I
      END


ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

///////////////////////////////////////////////////////////////////////////
// Update Kit Descriptions                                               //
///////////////////////////////////////////////////////////////////////////
ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRIES_NOW ~rog_clastext~ 10
        READ_2DA_ENTRY index 0 col_count row_name
        READ_2DA_ENTRY index 1 col_count class_id

      PATCH_IF (
				("%row_name%" STRING_EQUAL_CASE "THIEF")
														 ) BEGIN
          READ_2DA_ENTRY index 4 col_count kit_desc
          SPRINT old_kitdesc ~–可以通过使用背刺能力提高伤害。~
          SPRINT new_kitdesc_1 ~–魔法装置运用：智力达到17点及以上的盗贼，可使用法师专属的魔法法杖与卷轴。~

          GET_STRREF %kit_desc% kit_text
          INNER_PATCH_SAVE kit_text ~%kit_text%~ BEGIN
            REPLACE_TEXTUALLY ~
%new_kitdesc_1%~ ~~
            REPLACE_TEXTUALLY ~%old_kitdesc%~ ~%new_kitdesc_1%
%old_kitdesc%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%kit_desc%~ ~%kit_text%~
          END
        END

      END
  BUT_ONLY
    END
      
  END
LAF ADD_IDS_ENTRY INT_VAR minValue = 1 preferredValue = 200 STR_VAR idsFile = "stats.ids" identifier = "C0_THIEF_UMD" RET value END

OUTER_SET C0_THIEF_UMD = IDS_OF_SYMBOL (~STATS~ ~C0_THIEF_UMD~)

APPEND ~splprot.2da~ ~C0_THIEF_UMD %C0_THIEF_UMD% 1 1~ UNLESS ~C0_THIEF_UMD~
COPY_EXISTING ~splprot.2da~ ~override~ 
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~C0_THIEF_UMD~ BEGIN
	    SET C0_THIEF_UMD = %row%
	  END
	END

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ //copies all item files
  PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
    READ_BYTE    0x20 mage //reads the byte containing the fighter usability flag
    PATCH_IF ((mage BAND 0b00000100) = 0b00000000) AND ((mage BAND 0b01000000) = 0b01000000) BEGIN 
      READ_BYTE    0x20 row3
      READ_SHORT    0x1C itemtype 
      PATCH_IF (itemtype = 35) OR (itemtype = 11) BEGIN
        WRITE_BYTE    0x20 (row3 BAND 0b10111111)
        LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = 0 parameter2 = C0_THIEF_UMD timing = 2 power = 2 special = RESOLVE_STR_REF (~盗贼~) END
      END
    END
  END
BUT_ONLY

ACTION_IF FILE_EXISTS_IN_GAME ~CLABTH01.2DA~ BEGIN
COPY_EXISTING ~CLABTH01.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0TH-E1 END // USE MAGIC DEVICE
  PRETTY_PRINT_2DA
BUT_ONLY

COPY ~%MOD_FOLDER%/Thief/spells/EEex~ ~OVERRIDE~

COPY_EXISTING ~C0TH-E1B.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 STR_VAR resource = C0TH-E1B END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 STR_VAR resource = C0TH-E1C END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 401 target = 1 timing = 9 special = IDS_OF_SYMBOL (~STATS~ ~C0_THIEF_UMD~) parameter1 = 0 parameter2 = 1 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 1 timing = 9 STR_VAR resource = C0TH-E1B END

COPY_EXISTING ~C0TH-E1C.spl~ ~override~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 STR_VAR resource = C0TH-E1B END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 STR_VAR resource = C0TH-E1C END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 401 target = 1 timing = 9 special = IDS_OF_SYMBOL (~STATS~ ~C0_THIEF_UMD~) parameter1 = 1 parameter2 = 1 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 1 timing = 9 STR_VAR resource = C0TH-E1C END

COPY_EXISTING ~C0TH-E1C.spl~ ~override/C0TH-E2.SPL~
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 STR_VAR resource = C0TH-E2 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 401 target = 1 timing = 9 special = IDS_OF_SYMBOL (~STATS~ ~C0_THIEF_UMD~) parameter1 = 1 parameter2 = 1 END
    LPF ADD_SPELL_EFFECT INT_VAR opcode = 318 target = 1 timing = 9 STR_VAR resource = C0TH-E1 END

///////////////////////////////////////////////////////////////////////////
// Set Abilities for all Fighter Kits                                    //
// This allows all previously installed fighter kits to receive the      //
// benefits of your overhaul                                             //
///////////////////////////////////////////////////////////////////////////
COPY_EXISTING ~KITLIST.2DA~ ~override~
  READ_2DA_ENTRIES_NOW ~fig_kitlist~ 10
  FOR (row = 1; row < fig_kitlist; row += 1) BEGIN
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 5 kit_clab
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 1 kit_label
  READ_2DA_ENTRY_FORMER ~fig_kitlist~ row 8 kit_class
  
  PATCH_IF (%kit_class% = 4) BEGIN
    // Set New Fighter Abilities
    PATCH_IF FILE_EXISTS_IN_GAME ~%kit_clab%.2da~ BEGIN
      INNER_ACTION BEGIN
      // Add new abilities to all Fighter kits
      COPY_EXISTING ~%kit_clab%.2DA~ override
      PATCH_IF !(
				("%kit_label%" STRING_EQUAL_CASE "SWASHBUCKLER")
														 ) BEGIN
      LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0TH-E1 END // USE MAGIC DEVICE
        PRETTY_PRINT_2DA
      END

      PATCH_IF (
				("%kit_label%" STRING_EQUAL_CASE "SWASHBUCKLER")
														 ) BEGIN
      LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = AP_C0TH-E2 END // USE MAGIC DEVICE
        PRETTY_PRINT_2DA
      END
      
      END
      END
    END
  END
      BUT_ONLY
  END


END