
COPY ~%MOD_FOLDER%/Druid/TotemicDruid/2DAs~ ~OVERRIDE~
COPY ~%MOD_FOLDER%/Druid/TotemicDruid/SPELLS~ ~OVERRIDE~

ACTION_IF FILE_EXISTS_IN_GAME ~CLABDR02.2DA~ BEGIN
COPY_EXISTING ~CLABDR02.2DA~ ~OVERRIDE~
  REPLACE_TEXTUALLY ~GA_SPCL621~ ~****      ~
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_MaxLevel = 1 STR_VAR f_Entry = GA_C0D2_A0 END
  PRETTY_PRINT_2DA
END

OUTER_SPRINT kit_description ~图腾德鲁伊：这名德鲁伊与某一特定动物深度共鸣，<PRO_HESHE>认为这只动物正是<PRO_HISHER>灵魂的化身。这份羁绊赋予<PRO_HIMHER>与动物王国的特殊联结，<PRO_HESHE>能够呼唤动物之灵前来助<PRO_HIMHER>一臂之力。

职业优势：
-可使用特殊能力「图腾守护灵」。

图腾守护灵：图腾德鲁伊始终受一只动物灵的守护。进入战斗时灵体便会显现，战斗结束后方才散去。灵体可被操控，威力随召唤者的德鲁伊等级提升。图腾德鲁伊每日可选择一只守护灵，每种灵体都会为15尺范围内所有德鲁伊、萨满、游侠与野蛮人提供不同的加值。
  熊之坚韧：召唤者物理抗性+10%，死亡豁免+1。
  狼之骁勇：召唤者造成的所有伤害+10%，近战伤害额外+1。
  狮之勇气：召唤者零级命中值、士气与法术豁免+1。
  蛇之迅捷：召唤者护甲等级、移动速度与呼吸豁免+1。
  
-5级：守护灵在场时，可使用「灵护」能力。该能力由守护灵的特殊能力栏施放，而非召唤者自身。

灵护：图腾德鲁伊可命令守护灵将自身力量灌注给指定目标，持续1回合。期间守护灵暂时隐去，无论目标职业为何，均可获得守护灵的全部加值。效果结束后，守护灵会重新现身于召唤者身侧。

-8级：图腾守护灵的各项效果提升至+15%/+2。
-10级：灵护可为目标恢复相当于最大生命值50%的生命。
-12级：灵护可移除目标身上的负面心灵效果，并在持续期间为目标提供同类效果免疫。
-14级：图腾守护灵的各项效果提升至+20%/+3。
-14级：灵护可对已死亡的友军施放，将其复活后再提供常规加值。但守护灵会为此耗尽力量。此外，只要图腾德鲁伊正受守护灵庇护，即可获得「死亡护盾」法术的效果，免疫即死效果。若在此保护下将受到致命伤害，守护灵会耗尽力量挡下攻击，并对其施放灵护。
-15级：图腾守护灵的各项效果提升至+25%/+4。灵护可为目标恢复相当于最大生命值100%的生命。

职业限制：
-无法使用变形术。
-若图腾德鲁伊的守护灵在战斗中被击溃，或为复活友军、保护召唤者免于死亡而耗尽力量，则需经过一整回合且战斗仍在进行时才能重新显现。发生这种情况时，图腾德鲁伊施法速度受-2惩罚，且一回合内有25%几率法术失手。~

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~TOTEMIC_DRUID~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~灵：熊~) STR_VAR bam_file = C0D2_I1 RET C0D2_I1 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~灵：狼~) STR_VAR bam_file = C0D2_I2 RET C0D2_I2 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~灵：狮~) STR_VAR bam_file = C0D2_I3 RET C0D2_I3 = icon END
LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~灵：蛇~) STR_VAR bam_file = C0D2_I4 RET C0D2_I4 = icon END

ADD_PROJECTILE ~%MOD_FOLDER%/Druid/TotemicDruid/projectile/C0D2_P1.PRO~ ~C0 Totemic Projectile One Target~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

COPY_EXISTING ~C0D2_A1A.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0D2_P1
END

COPY_EXISTING ~C0D2_SA3.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END

COPY_EXISTING ~C0D2_A0.SPL~ ~OVERRIDE~
SAY NAME1 ~图腾守护灵~
SAY UNIDENTIFIED_DESC ~图腾德鲁伊始终受一只动物灵的守护，当范围内出现敌人时灵体便会显现，战斗结束后方才散去。灵体可被操控，威力随召唤者的德鲁伊等级提升；除非灵体在战斗中被摧毁，否则会持续为图腾德鲁伊提供常驻加值。图腾德鲁伊每日可选择一只守护灵，每种灵体提供的加值各不相同。
  熊之坚韧：召唤者物理抗性+10%，死亡豁免+1。
  狼之骁勇：召唤者造成的所有伤害+10%，近战伤害额外+1。
  狮之勇气：召唤者零级命中值、士气与法术豁免+1。
  蛇之迅捷：召唤者护甲等级、移动速度与呼吸豁免+1。~

COPY_EXISTING ~C0D2_A0A.SPL~ ~OVERRIDE/C0D2_A0B.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPIRITW END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A0A resource = C0D2_A0B END
COPY_EXISTING ~C0D2_A1A.SPL~ ~OVERRIDE/C0D2_A1B.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A2A resource = C0D2_A2B END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1 resource = C0D2_2 END
COPY_EXISTING ~C0D2_A2A.SPL~ ~OVERRIDE/C0D2_A2B.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_S1 resource = C0D2_S2 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A2A resource = C0D2_A2B END

COPY_EXISTING ~C0D2_A0A.SPL~ ~OVERRIDE/C0D2_A0C.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPIRITL END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A0A resource = C0D2_A0C END
COPY_EXISTING ~C0D2_A1A.SPL~ ~OVERRIDE/C0D2_A1C.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A2A resource = C0D2_A2C END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1 resource = C0D2_3 END
COPY_EXISTING ~C0D2_A2A.SPL~ ~OVERRIDE/C0D2_A2C.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_S1 resource = C0D2_S3 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A2A resource = C0D2_A2C END

COPY_EXISTING ~C0D2_A0A.SPL~ ~OVERRIDE/C0D2_A0D.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPIRITS END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A0A resource = C0D2_A0D END
COPY_EXISTING ~C0D2_A1A.SPL~ ~OVERRIDE/C0D2_A1D.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A2A resource = C0D2_A2D END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1 resource = C0D2_4 END
COPY_EXISTING ~C0D2_A2A.SPL~ ~OVERRIDE/C0D2_A2D.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_S1 resource = C0D2_S4 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_A2A resource = C0D2_A2D END

COPY_EXISTING ~C0D2_SA3.SPL~ ~OVERRIDE/C0D2_SB3.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SB4 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA5 resource = C0D2_SB5 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA6 resource = C0D2_SB6 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA7 resource = C0D2_SB7 END

COPY_EXISTING ~C0D2_SA3.SPL~ ~OVERRIDE/C0D2_SC3.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SC4 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA5 resource = C0D2_SC5 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA6 resource = C0D2_SC6 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA7 resource = C0D2_SC7 END

COPY_EXISTING ~C0D2_SA3.SPL~ ~OVERRIDE/C0D2_SD3.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SD4 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA5 resource = C0D2_SD5 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA6 resource = C0D2_SD6 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA7 resource = C0D2_SD7 END

COPY_EXISTING ~C0D2_SA4.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I1
      END
COPY_EXISTING ~C0D2_SB4.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I2
      END
COPY_EXISTING ~C0D2_SC4.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I3
      END
COPY_EXISTING ~C0D2_SD4.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I4
      END

COPY_EXISTING ~C0D2_1.SPL~ ~OVERRIDE~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I1
      END
      
COPY_EXISTING ~C0D2_1.SPL~ ~OVERRIDE/C0D2_2.SPL~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I2
      END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1 resource = C0D2_2 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1Z resource = C0D2_2Z END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1A resource = C0D2_2A END
COPY_EXISTING ~C0D2_1.SPL~ ~OVERRIDE/C0D2_3.SPL~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I3
      END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1 resource = C0D2_3 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1Z resource = C0D2_3Z END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1A resource = C0D2_3A END
COPY_EXISTING ~C0D2_1.SPL~ ~OVERRIDE/C0D2_4.SPL~
    LPF ALTER_EFFECT
      INT_VAR
	    match_opcode = 142
        parameter2 = C0D2_I4
      END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1 resource = C0D2_4 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1Z resource = C0D2_4Z END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_1A resource = C0D2_4A END

COPY_EXISTING ~C0D2_1A.EFF~ ~OVERRIDE/C0D2_1B.EFF~
WRITE_ASCII 0x30 ~C0D2_1B~
COPY_EXISTING ~C0D2_1A.EFF~ ~OVERRIDE/C0D2_1C.EFF~
WRITE_ASCII 0x30 ~C0D2_1C~
COPY_EXISTING ~C0D2_1A.EFF~ ~OVERRIDE/C0D2_1D.EFF~
WRITE_ASCII 0x30 ~C0D2_1D~
COPY_EXISTING ~C0D2_A0A.EFF~ ~OVERRIDE/C0D2_A0B.EFF~
WRITE_ASCII 0x30 ~C0D2_A1B~
COPY_EXISTING ~C0D2_A0A.EFF~ ~OVERRIDE/C0D2_A0C.EFF~
WRITE_ASCII 0x30 ~C0D2_A1C~
COPY_EXISTING ~C0D2_A0A.EFF~ ~OVERRIDE/C0D2_A0D.EFF~
WRITE_ASCII 0x30 ~C0D2_A1D~
COPY_EXISTING ~C0D2_S1.EFF~ ~OVERRIDE/C0D2_S2.EFF~
WRITE_ASCII 0x30 ~C0D2_S2~
COPY_EXISTING ~C0D2_S1.EFF~ ~OVERRIDE/C0D2_S3.EFF~
WRITE_ASCII 0x30 ~C0D2_S3~
COPY_EXISTING ~C0D2_S1.EFF~ ~OVERRIDE/C0D2_S4.EFF~
WRITE_ASCII 0x30 ~C0D2_S4~
COPY_EXISTING ~C0D2_SA3.EFF~ ~OVERRIDE/C0D2_SB3.EFF~
WRITE_ASCII 0x30 ~C0D2_SB3~
COPY_EXISTING ~C0D2_SA3.EFF~ ~OVERRIDE/C0D2_SC3.EFF~
WRITE_ASCII 0x30 ~C0D2_SC3~
COPY_EXISTING ~C0D2_SA3.EFF~ ~OVERRIDE/C0D2_SD3.EFF~
WRITE_ASCII 0x30 ~C0D2_SD3~
COPY_EXISTING ~C0D2_SA4.EFF~ ~OVERRIDE/C0D2_SB4.EFF~
WRITE_ASCII 0x30 ~C0D2_SB4~
COPY_EXISTING ~C0D2_SA5.EFF~ ~OVERRIDE/C0D2_SB5.EFF~
WRITE_ASCII 0x30 ~C0D2_SB4~
COPY_EXISTING ~C0D2_SA6.EFF~ ~OVERRIDE/C0D2_SB6.EFF~
WRITE_ASCII 0x30 ~C0D2_SB4~
COPY_EXISTING ~C0D2_SA7.EFF~ ~OVERRIDE/C0D2_SB7.EFF~
WRITE_ASCII 0x30 ~C0D2_SB4~
COPY_EXISTING ~C0D2_SA4.EFF~ ~OVERRIDE/C0D2_SC4.EFF~
WRITE_ASCII 0x30 ~C0D2_SC4~
COPY_EXISTING ~C0D2_SA5.EFF~ ~OVERRIDE/C0D2_SC5.EFF~
WRITE_ASCII 0x30 ~C0D2_SC4~
COPY_EXISTING ~C0D2_SA6.EFF~ ~OVERRIDE/C0D2_SC6.EFF~
WRITE_ASCII 0x30 ~C0D2_SC4~
COPY_EXISTING ~C0D2_SA7.EFF~ ~OVERRIDE/C0D2_SC7.EFF~
WRITE_ASCII 0x30 ~C0D2_SC4~
COPY_EXISTING ~C0D2_SA4.EFF~ ~OVERRIDE/C0D2_SD4.EFF~
WRITE_ASCII 0x30 ~C0D2_SD4~
COPY_EXISTING ~C0D2_SA5.EFF~ ~OVERRIDE/C0D2_SD5.EFF~
WRITE_ASCII 0x30 ~C0D2_SD4~
COPY_EXISTING ~C0D2_SA6.EFF~ ~OVERRIDE/C0D2_SD6.EFF~
WRITE_ASCII 0x30 ~C0D2_SD4~
COPY_EXISTING ~C0D2_SA7.EFF~ ~OVERRIDE/C0D2_SD7.EFF~
WRITE_ASCII 0x30 ~C0D2_SD4~

COPY_EXISTING ~C0D2_SP1.SPL~ ~OVERRIDE~
SAY NAME1 ~灵护~
SAY UNIDENTIFIED_DESC ~图腾德鲁伊可命令守护灵将自身力量灌注给指定目标，持续1回合。期间守护灵暂时隐去，无论目标职业为何，均可获得守护灵的全部加值。效果结束后，守护灵会重新现身于召唤者身侧。

10级：灵护可为友军恢复相当于最大生命值50%的生命。

12级：灵护可对已死亡的友军施放，将其复活后再提供常规加值。但守护灵在8小时内将无法再次显现。此外，只要图腾德鲁伊正受守护灵庇护，即可获得「死亡护盾」法术的效果，免疫即死效果。若在此保护下将受到致命伤害，守护灵会耗尽力量挡下攻击，并为其恢复30%最大生命值。

14级：灵护可对已死亡的友军施放，将其复活后再提供常规加值。但守护灵在8小时内将无法再次显现。此外，只要图腾德鲁伊正受守护灵庇护，即可获得「死亡护盾」法术的效果，免疫即死效果。若在此保护下将受到致命伤害，守护灵会耗尽力量挡下攻击，并为其恢复30%最大生命值。~

COPY_EXISTING ~C0D2_SP1.SPL~ ~OVERRIDE/C0D2_SP2.SPL~
LPF ALTER_EFFECT STR_VAR match_opcode = 318 match_resource = C0D2_SP1 resource = C0D2_SP2 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SB4 END
COPY_EXISTING ~C0D2_SP1.SPL~ ~OVERRIDE/C0D2_SP3.SPL~
LPF ALTER_EFFECT STR_VAR match_opcode = 318 match_resource = C0D2_SP1 resource = C0D2_SP3 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SC4 END
COPY_EXISTING ~C0D2_SP1.SPL~ ~OVERRIDE/C0D2_SP4.SPL~
LPF ALTER_EFFECT STR_VAR match_opcode = 318 match_resource = C0D2_SP1 resource = C0D2_SP4 END
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SD4 END

COPY_EXISTING ~C0D2_1Z.SPL~ ~OVERRIDE~
SAY NAME1 ~号令：灵护~
SAY UNIDENTIFIED_DESC ~此能力允许图腾德鲁伊直接将守护灵的祝福赐予指定友军。仅可在战斗外、守护灵尚未显现时使用。

图腾德鲁伊可命令守护灵将自身力量灌注给指定目标，持续1回合。期间守护灵暂时隐去，无论目标职业为何，均可获得守护灵的全部加值。效果结束后，守护灵会重新现身于召唤者身侧。

10级：灵护可为友军恢复相当于最大生命值50%的生命。

12级：灵护可对已死亡的友军施放，将其复活后再提供常规加值。但守护灵在8小时内将无法再次显现。此外，只要图腾德鲁伊正受守护灵庇护，即可获得「死亡护盾」法术的效果，免疫即死效果。若在此保护下将受到致命伤害，守护灵会耗尽力量挡下攻击，并为其恢复30%最大生命值。

14级：灵护可对已死亡的友军施放，将其复活后再提供常规加值。但守护灵在8小时内将无法再次显现。此外，只要图腾德鲁伊正受守护灵庇护，即可获得「死亡护盾」法术的效果，免疫即死效果。若在此保护下将受到致命伤害，守护灵会耗尽力量挡下攻击，并为其恢复30%最大生命值。~

COPY_EXISTING ~C0D2_1Z.SPL~ ~OVERRIDE/C0D2_2Z.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SB4 END
COPY_EXISTING ~C0D2_1Z.SPL~ ~OVERRIDE/C0D2_3Z.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SC4 END
COPY_EXISTING ~C0D2_1Z.SPL~ ~OVERRIDE/C0D2_4Z.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0D2_SA4 resource = C0D2_SD4 END

COPY_EXISTING ~C0D2_SPX.SPL~ OVERRIDE
  LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~图腾灵已殒——施法速度惩罚与法术失手~) END

ACTION_FOR_EACH baldur_script IN baldur bdbaldur baldur25 BEGIN
ACTION_IF FILE_EXISTS_IN_GAME ~%baldur_script%.bcs~ BEGIN
EXTEND_TOP ~%baldur_script%.bcs~ ~%MOD_FOLDER%/Druid/TotemicDruid/scripts/baldur.baf~
END
END

COMPILE ~%MOD_FOLDER%/Druid/TotemicDruid/scripts/C0D2_SM.BAF~

COPY ~%MOD_FOLDER%/Druid/TotemicDruid/creatures/C0D2_S1.cre~ ~OVERRIDE~
SAY NAME1 ~灵熊~
SAY NAME2 ~灵熊~
  WRITE_ASCII SCRIPT_OVERRIDE ~C0D2_SM~ #8 // override
  WRITE_ASCII DEATHVAR ~C0D2_SM~ #8 // death variable

COPY ~%MOD_FOLDER%/Druid/TotemicDruid/creatures/C0D2_S2.cre~ ~OVERRIDE~
SAY NAME1 ~灵狼~
SAY NAME2 ~灵狼~
  WRITE_ASCII SCRIPT_OVERRIDE ~C0D2_SM~ #8 // override
  WRITE_ASCII DEATHVAR ~C0D2_SM~ #8 // death variable

COPY ~%MOD_FOLDER%/Druid/TotemicDruid/creatures/C0D2_S3.cre~ ~OVERRIDE~
SAY NAME1 ~灵狮~
SAY NAME2 ~灵狮~
  WRITE_ASCII SCRIPT_OVERRIDE ~C0D2_SM~ #8 // override
  WRITE_ASCII DEATHVAR ~C0D2_SM~ #8 // death variable

COPY ~%MOD_FOLDER%/Druid/TotemicDruid/creatures/C0D2_S4.cre~ ~OVERRIDE~
SAY NAME1 ~灵蛇~
SAY NAME2 ~灵蛇~
  WRITE_ASCII SCRIPT_OVERRIDE ~C0D2_SM~ #8 // override
  WRITE_ASCII DEATHVAR ~C0D2_SM~ #8 // death variable

COPY_EXISTING ~luabbr.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~TOTEMIC_DRUID~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 1 cols ~C0D2_~
	  END
	END
COPY_EXISTING ~LUDR0.2da~ ~override/LUC0D2_.2DA~
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPPR731~ END
LPF patch_remove_hla STR_VAR remove_ability = ~GA_SPPR732~ END
LPF patch_add_hla STR_VAR 2da_row = ~LUC0D2_1~ ability = ~AP_C0D2_H1~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~LUC0D2_2~ ability = ~AP_C0D2_H2~ num_allowed = 1 END	

COPY_EXISTING ~C0D2_H1.SPL~ ~OVERRIDE~
SAY NAME1 ~赋能灵魄：勇武~
SAY UNIDENTIFIED_DESC ~选择此能力后，图腾德鲁伊的守护灵每次显现时，均可使用一次「旋风斩」、「猛力攻击」与「致命一击」能力。~

COPY_EXISTING ~C0D2_H2.SPL~ ~OVERRIDE~
SAY NAME1 ~赋能灵魄：坚韧~
SAY UNIDENTIFIED_DESC ~选择此能力后，图腾德鲁伊的守护灵每次显现时，均可使用一次「强健」、「魔法抗性」与「高级闪避」能力。~