
COPY ~%MOD_FOLDER%/Thief/Trickster/2da~ OVERRIDE
COPY ~%MOD_FOLDER%/Thief/Trickster/bam~ OVERRIDE
COPY ~%MOD_FOLDER%/Thief/Trickster/spells~ OVERRIDE

COPY_EXISTING ~CLABTH01.2DA~ ~OVERRIDE/C0TRICKS.2DA~
	REPLACE_TEXTUALLY ~GA_C0TH-A1~ ~**** ~ // CRIPPLING STRIKE
	REPLACE_TEXTUALLY ~AP_C0TH-A2~ ~**** ~ // EPIC PRECISION

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0TR#00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0TR#01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 3 STR_VAR f_Entry = GA_C0TR#02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0TR#03 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0TR#04 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 5 STR_VAR f_Entry = AP_C0TR#05 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = AP_C0TR#06 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 10 STR_VAR f_Entry = AP_C0TR#00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = AP_C0TR#07 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0TR#08 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 20 STR_VAR f_Entry = AP_C0TR#00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 25 STR_VAR f_Entry = AP_C0TR#09 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 30 STR_VAR f_Entry = AP_C0TR#10 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 35 STR_VAR f_Entry = AP_C0TR#11 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 40 STR_VAR f_Entry = AP_C0TR#12 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 40 STR_VAR f_Entry = AP_C0TR#00 END

 	PRETTY_PRINT_2DA

OUTER_SPRINT kit_description ~模仿士：或许是最难定义、最复杂的盗贼类型，模仿士几乎没有真正属于自己的能力。他们不靠正规训练打磨技艺，而是凭借过人的智谋与强记能力，以近乎瞬发的速度掌握其他职业的技能，运用起来如同浸淫多年——这份天赋常被人嘲讽为一分机智两分运气。因此，绝无两个完全相同的模仿士。作为万事通，他们与吟游诗人的区别在于，其技艺全凭临场领悟而非系统修习。虽说应变灵活、上手极快，但缺乏真正的专精也让他们的成长更为缓慢。

职业优势：
-幸运：所有豁免检定、攻击检定、最小伤害/治疗掷骰+1，所有盗贼技能+5%。
-投机者：模仿士的暴击会使目标的护甲等级、零级命中值与伤害降低1点，持续1回合。
-每日可使用一次「诡术」能力。每提升3级额外获得1次使用次数。

诡术：模仿士以精妙的手法与迅捷的身法，瞬间用一尊与自身等大的替身替换自己，持续1回合，同时进入隐身状态。模仿士的下一次攻击必定暴击。这份障眼法极为逼真，哪怕是破除幻象的魔法、或是能看破隐形的生物也会被蒙骗，在替身存在期间不会攻击模仿士。

-可使用「模仿」能力。

模仿：无论是细心观察、边用边学，还是天赋异禀，模仿士都能模仿几乎任何职业的技能，化为己用。使用后，可永久将该能力替换为另一职业套件的一项能力或被动效果。若为兼职职业，模仿士在该职业非激活状态下仍可使用已学会的能力。

-5级：获得1次模仿使用次数。
-8级：投机者减益效果提升至2点。
-10级：幸运被动加值翻倍。获得1次模仿使用次数。
-15级：投机者减益效果提升至3点。获得1次模仿使用次数。
-20级：幸运被动加值变为三倍。获得1次模仿使用次数。
-25级：获得1次模仿使用次数。
-30级：投机者减益效果提升至4点。获得1次模仿使用次数。
-35级：获得1次模仿使用次数。
-40级：幸运被动加值变为四倍。获得1次模仿使用次数。

职业限制：
-背刺伤害倍率远低于普通盗贼：
  1-8级：2倍
  9级及以上：3倍
-阵营不得为守序。KIT_DISADV_1
-自负：护甲等级受-1惩罚。
-每等级仅可分配20点技能点至盗贼技能。
-作为模仿士，仅能获得90%的经验值。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~7000~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-无法使用致残打击。
-不获得史诗精准。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 4
	
    mixed         = RESOLVE_STR_REF(~模仿士~)
	
    lower         = RESOLVE_STR_REF(~模仿士~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~模仿士：或许是最难定义、最复杂的盗贼类型，模仿士几乎没有真正属于自己的能力。他们不靠正规训练打磨技艺，而是凭借过人的智谋与强记能力，以近乎瞬发的速度掌握其他职业的技能，运用起来如同浸淫多年。因此绝无两个完全相同的模仿士，应变灵活但专精不足。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0TRICKS~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                          T   S           F   Q             S S
	//                                          W   C           L   U             W I
	//                                  B L S   O   I   W       A   A             O N
	//                                  A O H   H   M   A       I   R C   S       R G
	//                  L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//                  _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//                  S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//                  W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//                  O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//                  R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//                  D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    // weapprof      = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
	
    abclasrq      = ~0 9 0 16 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    alignmnt      = ~0 0 0 1 1 1 1 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~C0TRIC~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0TRICKS.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    // hpclass       = ~HPPRS~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	backstab = ~1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3~
	
	sneakatt = ~1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	thiefskl = ~40 20~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

COPY_EXISTING ~LUTH0.2da~ ~override/LUC0TRIC.2DA~
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC1~ ability = ~AP_C0TR#H1~ num_allowed = 1 excluded_by = ~AP_C0TR#H2~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC2~ ability = ~AP_C0TR#H2~ num_allowed = 1 excluded_by = ~AP_C0TR#H1~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC3~ ability = ~GA_SPCL900~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC4~ ability = ~GA_SPCL902~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC5~ ability = ~GA_SPCL904~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC6~ ability = ~GA_SPCL906~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC7~ ability = ~GA_SPCL905~ num_allowed = 1 prerequisite = ~GA_SPCL906~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC8~ ability = ~GA_SPCL908~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC9~ ability = ~GA_SPCL907~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC10~ ability = ~GA_SPCL921~ num_allowed = 1 prerequisite = ~GA_SPCL915~ END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC11~ ability = ~GA_SPCL922~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC12~ ability = ~GA_SPCL936~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC13~ ability = ~GA_SPCL937~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC14~ ability = ~GA_SPCL938~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC15~ ability = ~GA_SPCL940~ num_allowed = 1 END	
LPF patch_add_hla STR_VAR 2da_row = ~C0TRIC16~ ability = ~GA_SPCL941~ num_allowed = 1 prerequisite = ~GA_SPCL940~ END	

ACTION_IF GAME_IS ~IWDEE~ THEN BEGIN

ACTION_IF FILE_EXISTS_IN_GAME ~C0TRICKS.2DA~ BEGIN
COPY_EXISTING ~C0TRICKS.2DA~ OVERRIDE
  // Borrowed from Rogue Rebalancing
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 25 f_MaxLevel = 25 STR_VAR f_Entry = AP_SPCL915 END // USE ANY ITEMS
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 30 f_MaxLevel = 30 STR_VAR f_Entry = AP_C0TR#HL END // MASTERY
  PRETTY_PRINT_2DA
BUT_ONLY

ACTION_FOR_EACH description IN 
    clastext  
  BEGIN
    ACTION_IF FILE_EXISTS_IN_GAME ~%description%.2da~ BEGIN
      COPY_EXISTING ~%description%.2DA~ ~override~
      COUNT_2DA_COLS col_count
      COUNT_2DA_ROWS col_count rows
      FOR (index = 0; index < rows; ++index) BEGIN
        READ_2DA_ENTRY index 0 col_count row_name

//TRICKSTER
        PATCH_IF "%row_name%" STRING_EQUAL_CASE "C0TRICKS" BEGIN
          READ_2DA_ENTRY index 4 col_count trickster_desc
          SPRINT old_trickster1 ~-25级：获得1次模仿使用次数。~
          SPRINT new_trickster1 ~-25级：获得1次模仿使用次数，且可使用「万物皆用」。~
          SPRINT old_trickster2 ~-30级：投机者减益效果提升至4点。获得1次模仿使用次数。~
          SPRINT new_trickster2 ~-30级：投机者减益效果提升至4点。获得1次模仿使用次数。
-30级：获得1次「精通」使用次数，可用于永久习得「秘传剑术」或「易如呼吸」。

秘传剑术：模仿士观察模仿过无数战士，对诸多战斗风格形成了融会贯通的理解。习得此能力后，模仿士永久获得每回合额外1.5次攻击。

易如呼吸：模仿士对模仿技艺的精通，让他们能以惊人的速度与效率运用自身的技艺库。习得此能力后，模仿士永久获得「光环净化」效果。~
          GET_STRREF %trickster_desc% trickster_text
          INNER_PATCH_SAVE trickster_text ~%trickster_text%~ BEGIN
            REPLACE_TEXTUALLY ~%old_trickster%~ ~%new_trickster%~
          END
          INNER_ACTION BEGIN
            STRING_SET_EVALUATE ~%trickster_desc%~ ~%trickster_text%~
          END
		END
	END

      BUT_ONLY
    END
  END
  
END
END

// MIMICRY
COPY_EXISTING ~C0TR#02.SPL~ OVERRIDE
SAY NAME1 ~诡术~
SAY UNIDENTIFIED_DESC ~模仿士以精妙的手法与迅捷的身法，瞬间用一尊与自身等大的静止替身替换自己，持续1回合，同时进入隐身状态。替身仅有1点生命值。模仿士的下一次攻击会消除诱饵，但必定暴击。这份障眼法极为逼真，哪怕是破除幻象的魔法、或是能看破隐形的生物也会被蒙骗，在替身存在期间不会攻击模仿士。~

COPY_EXISTING ~C0TR#04Y.SPL~ OVERRIDE
SAY NAME1 ~模仿 I~
SAY UNIDENTIFIED_DESC ~无论是细心观察、边用边学，还是天赋异禀，模仿士都能模仿几乎任何职业的技能，化为己用。使用后，可永久将该能力替换为另一职业套件的一项能力或被动效果。若为兼职职业，模仿士在该职业非激活状态下仍可使用已学会的能力。~

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#05.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#05Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#05Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#05Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#002 END
SAY NAME1 ~模仿 II~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#05Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#05 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#06.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#06Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#06Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#06Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#003 END
SAY NAME1 ~模仿 III~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#06Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#06 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#07.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#07Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#07Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#07Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#004 END
SAY NAME1 ~模仿 IV~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#07Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#07 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#08.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#08Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#08Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#08Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#005 END
SAY NAME1 ~模仿 V~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#08Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#08 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#09.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#09Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#09Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#09Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#006 END
SAY NAME1 ~模仿 VI~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#09Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#09 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#10.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#10Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#10Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#10Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#007 END
SAY NAME1 ~模仿 VII~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#10Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#10 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#11.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#11Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#11Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#11Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#008 END
SAY NAME1 ~模仿 VIII~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#11Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#11 END

COPY_EXISTING ~C0TR#04.SPL~ ~OVERRIDE/C0TR#12.SPL~
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Y resource = C0TR#12Y END
LPF ALTER_EFFECT STR_VAR match_resource = C0TR#04Z resource = C0TR#12Z END
COPY_EXISTING ~C0TR#04Y.SPL~ ~OVERRIDE/C0TR#12Y.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#009 END
SAY NAME1 ~模仿 IX~
COPY_EXISTING ~C0TR#04Z.SPL~ ~OVERRIDE/C0TR#12Z.SPL~
LPF ALTER_EFFECT STR_VAR resource = C0TR#12 END

COPY_EXISTING ~C0TR#10A.SPL~ OVERRIDE
SAY NAME1 ~模仿：狂战士：狂怒~
COPY_EXISTING ~C0TR#11A.SPL~ OVERRIDE
SAY NAME1 ~模仿：巫师杀手：魔法抗性+5%~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#12A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL144 END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL144 END
SAY NAME1 ~模仿：剑圣：居合~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#13A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPDWD02B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPDWD02 END
SAY NAME1 ~模仿：矮人卫士：防御姿态~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#14A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL121B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL121 END
SAY NAME1 ~模仿：弓箭手：呼号射击~
COPY_EXISTING ~C0TR#15A.SPL~ OVERRIDE
SAY NAME1 ~模仿：潜行者：隐匿阴影与潜行+15%~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#16A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPPR402B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0TR#16Z END
SAY NAME1 ~模仿：兽主：召唤动物~
COPY_EXISTING ~C0TR#16Z.SPL~ OVERRIDE
SAY NAME1 ~召唤动物~
SAY UNIDENTIFIED_DESC ~模仿士施展兽主的召唤动物牧师法术。法术强度取决于模仿士等级：

1-9级：召唤动物 I
10-19级：召唤动物 II
20级及以上：召唤动物 III~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#17A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL222B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL222 END
SAY NAME1 ~模仿：骑士：移除恐惧~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#18A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPPR303B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL231 END
SAY NAME1 ~模仿：审判者：解除魔法~
COPY_EXISTING ~C0TR#19A.SPL~ OVERRIDE
SAY NAME1 ~模仿：亡灵猎手：亡灵祸祟~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#20A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPWI119B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL102 END
SAY NAME1 ~模仿：黑卫：吸取生命~

ACTION_IF FILE_EXISTS ~C0BG#00.spl~ THEN BEGIN
COPY_EXISTING ~C0TR#20A.SPL~ OVERRIDE
LPF ALTER_SPELL_HEADER STR_VAR icon = C0BG#02 END
SAY NAME1 ~模仿：黑卫：生命汲取~
END

COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#21A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL741B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL741 END
SAY NAME1 ~模仿：洛山达牧师：洛山达恩赐~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#22A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL731B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL731 END
SAY NAME1 ~模仿：亥姆牧师：寻觅之剑~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#23A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL721B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL721 END
SAY NAME1 ~模仿：塔洛斯牧师：风暴护盾~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#24A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = OHTYR1B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = OHTYR1 END
SAY NAME1 ~模仿：提尔牧师：升阶术~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#25A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = OHTMPS2B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = OHTMPS2 END
SAY NAME1 ~模仿：坦帕斯牧师：战场混乱~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#26A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL621B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL621 END
SAY NAME1 ~模仿：图腾德鲁伊：召唤灵兽~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#27A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPIN155B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL643 END
SAY NAME1 ~模仿：变形者：变形狼人~

ACTION_IF FILE_EXISTS_IN_GAME ~c0ss-fh.spl~ THEN BEGIN
COPY_EXISTING ~C0TR#27A.SPL~ ~override~
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0SS-FH END
END

COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#28A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = PLYBASSB END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL634 END
SAY NAME1 ~模仿：复仇者：变形火蜥蜴~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#29A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = C0TR#29B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0TR#29Z END
SAY NAME1 ~模仿：奥术施法~
COPY_EXISTING ~C0TR#29Z.SPL~ OVERRIDE
SAY NAME1 ~模仿：施法~
SAY UNIDENTIFIED_DESC ~模仿士施展一个选定的1环奥术法术。6级起可施展2环，11级起可施展3环，16级起可施展4环。~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#30A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL423B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL423 END
SAY NAME1 ~模仿：刺客：武器淬毒~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#31A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL414B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL414 END
SAY NAME1 ~模仿：赏金猎人：特制陷阱~
COPY_EXISTING ~C0TR#32A.SPL~ OVERRIDE
SAY NAME1 ~模仿：剑客：副手武器零级命中值+2~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#33A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPSD02B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPSD02 END
SAY NAME1 ~模仿：影舞者：影步~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#34A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL522B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL522 END
SAY NAME1 ~模仿：刀锋：防御旋斩~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#35A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = C0TR#35B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0TR#35Z END
SAY NAME1 ~模仿：弄臣：愚者赌局~
COPY_EXISTING ~C0TR#35Z.SPL~ OVERRIDE
SAY NAME1 ~愚者赌局~
SAY UNIDENTIFIED_DESC ~模仿士模仿弄臣的吟游诗曲，施加效果持续3回合。持续期间模仿士可自由行动，不会打破效果。~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#36A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = C0TR#36B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0TR#36Z END
SAY NAME1 ~模仿：吟游诗人：战歌~
COPY_EXISTING ~C0TR#36Z.SPL~ OVERRIDE
SAY NAME1 ~战歌~
SAY UNIDENTIFIED_DESC ~模仿士模仿吟游诗人的战歌，施加效果持续3回合。持续期间模仿士可自由行动，不会打破效果。~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#37A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPWI117B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0TR#37Z END
SAY NAME1 ~模仿：暗月僧侣：冰寒之拳~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#38A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL238B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0TR#38Z END
SAY NAME1 ~模仿：日魂僧侣：烈焰之拳~
COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#39A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPDD03B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPDD03 END
SAY NAME1 ~模仿：龙裔信徒：吐息武器~

COPY_EXISTING ~C0TR#40.SPL~ OVERRIDE
SAY NAME1 ~高等模仿 I~
SAY UNIDENTIFIED_DESC ~模仿士可永久将此能力替换为以下任一高阶能力：

-猛力攻击
-致命一击
-致死打击
-旋风攻击
-战吼
-强健
-魔法抗性
-追踪
-暗影形态
-暗影迷宫
-暗影双生
-刺杀
-魔法长笛~

COPY_EXISTING ~C0TR#40.SPL~ ~OVERRIDE/C0TR#41.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#H02 END
SAY NAME1 ~高等模仿 II~

COPY_EXISTING ~C0TR#40.SPL~ ~OVERRIDE/C0TR#42.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 214 STR_VAR resource = C0TR#H03 END
SAY NAME1 ~高等模仿 III~

COPY_EXISTING ~C0TR#10A.SPL~ ~OVERRIDE/C0TR#43A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL906B END
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#40 END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL906 END
SAY NAME1 ~模仿：猛力攻击~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#44A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL905B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL905 END
SAY NAME1 ~模仿：致命一击~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#45A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL902B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL902 END
SAY NAME1 ~模仿：致死打击~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#46A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL900B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL900 END
SAY NAME1 ~模仿：旋风攻击~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#47A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL908B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL908 END
SAY NAME1 ~模仿：战吼~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#48A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL907B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL907 END
SAY NAME1 ~模仿：强健~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#49A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL904B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL904 END
SAY NAME1 ~模仿：魔法抗性~

ACTION_IF FILE_EXISTS_IN_GAME ~C0CL922.SPL~ THEN BEGIN
COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#50A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL920B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL922 END
SAY NAME1 ~模仿：追踪~
END ELSE BEGIN

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#50A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL920B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = C0CL922 END
SAY NAME1 ~模仿：追踪~

	END

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#51A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL938B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL938 END
SAY NAME1 ~模仿：暗影形态~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#52A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL937B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL937 END
SAY NAME1 ~模仿：暗影迷宫~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#53A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL936B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL936 END
SAY NAME1 ~模仿：暗影双生~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#54A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL916B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL916 END
SAY NAME1 ~模仿：刺杀~

COPY_EXISTING ~C0TR#43A.SPL~ ~OVERRIDE/C0TR#55A.SPL~
LPF ALTER_SPELL_HEADER STR_VAR icon = SPCL921B END
LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = SPCL921 END
SAY NAME1 ~模仿：魔法长笛~

COPY_EXISTING ~C0TR#HL.SPL~ ~OVERRIDE~
SAY NAME1 ~精通~
SAY UNIDENTIFIED_DESC ~此能力可使用一次，用于习得「秘传剑术」或「易如呼吸」。

秘传剑术：模仿士观察模仿过无数战士，对诸多战斗风格形成了融会贯通的理解。习得此能力后，模仿士永久获得每回合额外1.5次攻击。

易如呼吸：模仿士对模仿技艺的精通，让他们能以惊人的速度与效率运用自身的技艺库。习得此能力后，模仿士永久获得「光环净化」效果。~

COPY_EXISTING ~C0TR#H1.SPL~ ~OVERRIDE~
SAY NAME1 ~秘传剑术~
SAY UNIDENTIFIED_DESC ~模仿士观察模仿过无数战士，对诸多战斗风格形成了融会贯通的理解。习得此能力后，模仿士永久获得每回合额外1.5次攻击。

本能力与「易如呼吸」互斥。~

COPY_EXISTING ~C0TR#H2.SPL~ ~OVERRIDE~
SAY NAME1 ~易如呼吸~
SAY UNIDENTIFIED_DESC ~模仿士对模仿技艺的精通，让他们能以惊人的速度与效率运用自身的技艺库。习得此能力后，模仿士永久获得「光环净化」效果。

本能力与「秘传剑术」互斥。~

 ACTION_FOR_EACH mimics IN 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 BEGIN
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#05Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#06Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%D.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#07Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%E.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#08Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%F.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#09Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%G.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#10Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%H.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#11Y END
	COPY_EXISTING ~C0TR#%mimics%A.SPL~ ~override/C0TR#%mimics%I.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#12Y END
END

 ACTION_FOR_EACH hlamimics IN 43 44 45 46 47 48 49 50 51 52 53 54 55 BEGIN
	COPY_EXISTING ~C0TR#%hlamimics%A.SPL~ ~override/C0TR#%hlamimics%B.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#41 END
	COPY_EXISTING ~C0TR#%hlamimics%A.SPL~ ~override/C0TR#%hlamimics%C.SPL~
LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = C0TR#42 END
END