COPY ~%MOD_FOLDER%/Paladin/UndeadHunter/2da~ ~override~
COPY ~%MOD_FOLDER%/Paladin/UndeadHunter/spells~ ~override~

COPY_EXISTING ~CLABPA01.2DA~ ~OVERRIDE/CLABPA04.2DA~
	REPLACE_TEXTUALLY ~AP_C0PAL00 ~ ~**** ~ // AURA OF COURAGE
	REPLACE_TEXTUALLY ~GA_SPCL211 ~ ~**** ~ // LAY ON HANDS
	REPLACE_TEXTUALLY ~GA_C0PAL02 ~ ~**** ~ // SMITE EVIL

	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_C0UHU01 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 3 STR_VAR f_Entry = AP_C0UHU00 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0UHU02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0UHU02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = GA_C0UHU02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = GA_C0UHU02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = GA_C0UHU02 END
	LPF set_clab_2da_entries INT_VAR f_MinLevel = 15 STR_VAR f_Entry = GA_C0UHU02 END

 	PRETTY_PRINT_2DA

// ICONS

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~圣洁灵光~) STR_VAR bam_file = c0uhu01i RET c0uhu01i = icon END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~UNDEAD_HUNTER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~亡灵猎手：这名神圣复仇者将<PRO_HISHER>的技艺磨砺至极致，专司毁灭亡灵与其他邪秽生物，且对亡灵许多最致命的能力免疫。

职业优势：
-对亡灵生物的攻击检定与伤害掷骰获得+3加值。
-免疫定身、等级吸取与即死魔法。
-超度亡灵的效果等同于同等级牧师。
-每日可使用三次「破亡斩」。

破亡斩：亡灵猎手下一次对亡灵生物的成功攻击，会迫使目标进行一次死亡豁免，失败则直接被摧毁。若豁免成功，目标也会受到1d6点伤害，且亡灵猎手每提升3级，额外增加1d6点伤害。

-3级：获得「圣洁灵光」。

圣洁灵光：亡灵猎手散发出一道光环，保护友军免受亡灵与死灵魔法的侵害。视野范围内的所有友军，护甲等级与对抗亡灵的豁免检定获得+2加值；此外，对亡灵的攻击与伤害加值、对抗死灵法术的豁免加值还会随等级提升。
  3级：对亡灵的攻击与伤害+3，对抗死灵法术豁免+3。
  11级：对亡灵的攻击与伤害+3，对抗死灵法术豁免+3。友军免疫定身。
  19级：对亡灵的攻击与伤害+3，对抗死灵法术豁免+3。友军免疫定身与等级吸取。
  
-5级：破亡斩的豁免惩罚降至-1。
-9级：破亡斩的豁免惩罚降至-2。
-13级：破亡斩的豁免惩罚降至-3。
-15级：额外获得三次破亡斩使用次数。
-17级：破亡斩的豁免惩罚降至-4。

职业限制：
-不获得基于魅力的神恩加值。
-不获得勇气灵光。
-无法使用圣疗术。
-无法使用破邪斩。~

COPY_EXISTING ~C0UHU01.spl~ ~override~
      LPF ADD_SPELL_EFFECT
      INT_VAR
	    opcode = 142
	    target = 2
		timing = 9
        parameter2 = c0uhu01i
      END

COPY_EXISTING ~C0UHU02.spl~ ~override~
SAY NAME1 ~破亡斩~
SAY UNIDENTIFIED_DESC ~破亡斩
亡灵猎手下一次对亡灵生物的成功攻击，会迫使目标进行一次死亡豁免，失败则直接被摧毁。若豁免成功，目标也会受到1d6点伤害，且亡灵猎手每提升3级，额外增加1d6点伤害。~

ADD_PROJECTILE ~%MOD_FOLDER%/spells/C0INAREP.PRO~ ~C0 Instant Area Allies~

COPY_EXISTING ~c0uhu01a.SPL~ OVERRIDE
  LPF ALTER_SPELL_HEADER
	INT_VAR
		projectile = C0INAREP
END
