COPY_EXISTING ~clabfi06.2da~ ~override~

OUTER_SPRINT kit_description ~先锋卫士：先锋卫士是受训于敌阵之中厮杀的前线战士。坚韧强健、耐打抗揍，是可靠的防御者，足以守住阵线，扛下常人难以承受的重击。

职业优势：
-每日可使用「防御姿态」。1级获得1次，4级再获得1次，之后每4级额外获得1次。

防御姿态：持续1回合，先锋卫士获得所有物理伤害抗性+50%，豁免检定+2，但移动速度降低50%。

-每5级获得钝击、挥砍、穿刺、远程伤害抗性+5%，20级时达到最高20%。
-生命骰：d12

职业限制：KIT_DISADV_1
-单手近战武器的精通等级不得超过高级精通（4个熟练位）。
-其他任意武器的精通等级不得超过专精级（2个熟练位）。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-无法使用强化猛力攻击与强化武器专精。
-无法使用快速射击。
-16级时不会获得全武器专精。
-不获得精通先攻。~

END

END ELSE BEGIN

COPY_EXISTING ~CLABFI06.2DA~ OVERRIDE
REPLACE_TEXTUALLY ~GA_C0DWD01~ ~****     ~
REPLACE_TEXTUALLY ~GA_C0DWD02~ ~****     ~
REPLACE_TEXTUALLY ~GA_C0FIG03~ ~****     ~

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 2
	
    mixed         = RESOLVE_STR_REF(~先锋卫士~)
	
    lower         = RESOLVE_STR_REF(~先锋卫士~)
	
    help          = RESOLVE_STR_REF(~%kit_description%~)
	
    briefdesc     = RESOLVE_STR_REF(~先锋卫士：受训于敌阵之中厮杀的前线战士，坚韧耐打，是可靠的防线砥柱，足以扛下常人无法承受的重击。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0VNGD~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~4 4 2 2 4 4 4 2 4 4 4 4 2 4 4 4 4 4 2 2 4 4 2 2 2 2 2 2 2 2 2 3~
	
    abclasrq      = ~12 9 16 0 0 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    luabbr        = ~FI4~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/CLABFI06.2da~
	
    kittable      = ~K_F_H K_F_E K_F_HE K_F_G K_F_HL K_F_HO~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPBARB~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	// thiefscl = ~0 0 0 0 0 0 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END