COPY ~%MOD_FOLDER%/Shaman/WarShaman/2da~ ~override~
COPY ~%MOD_FOLDER%/Shaman/WarShaman/bam~ ~override~
COPY ~%MOD_FOLDER%/Shaman/WarShaman/eff~ ~override~
COPY ~%MOD_FOLDER%/Shaman/WarShaman/itm~ ~override~
COPY ~%MOD_FOLDER%/Shaman/WarShaman/spl~ ~override~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~K_SH_E.2DA~ THEN BEGIN
COPY_EXISTING ~K_SH_H.2DA~ ~OVERRIDE/K_SH_E.2DA~
COPY_EXISTING ~K_SH_H.2DA~ ~OVERRIDE/K_SH_HL.2DA~
COPY_EXISTING ~K_SH_H.2DA~ ~OVERRIDE/K_SH_G.2DA~
COPY_EXISTING ~K_SH_H.2DA~ ~OVERRIDE/K_SH_D.2DA~
END

ACTION_IF MOD_IS_INSTALLED ~ArtisansKitpack.tp2~ ~1005~ THEN BEGIN
OUTER_SPRINT warhorn_rage_desc ~战号萨满：出身北方的萨满同时也是娴熟的战士，战号萨满能召唤来自英灵殿、战士安息所等位的战士之灵。他们中许多人信奉战争之主坦帕斯，战斗能力与萨满魔法造诣不相上下。

职业优势：
-生命骰：d10
-阵营可为任意非守序阵营。
-萨满可用的所有武器均可达到专精级。
-所有战斗风格均可达到满专精。
-直接掌握数种独特法术，可与其他法术一样正常施放：战焰、战嚎、风怒、风暴屏障、雷缚战斧、天怒、不灭狂热
-每日可使用一次「狂暴」能力。1级获得1次，之后每提升6级额外获得1次。

狂暴：狂暴状态持续5回合，力量与体质+4，法术豁免+2，但护甲等级受-2惩罚。此外，激活狂暴会恢复施法者被吸取的等级，且持续期间免疫后续的等级吸取效果。狂暴结束后，施法者陷入疲劳状态，力量、敏捷、护甲等级与移动速度受-2惩罚，持续5回合，期间无法再次使用狂暴。

-萨满之舞可召唤以下生物：
  1级：战士之灵（装备长剑、长弓），同时最多存在2只。
  6级：狂战士之灵（双持战斧、双手剑），同时最多存在3只。
  12级：先祖之灵（战士/牧师），同时最多存在4只。
  18级：女武神（弓箭手、盾卫），同时最多存在5只。
  
职业限制：
-识破幻术的技能分值仅为正常水平的一半。
-无法施放普通的萨满专属法术。
-每个法术环级的每日施法次数减少1次。~
END

ACTION_IF NOT MOD_IS_INSTALLED ~ArtisansKitpack.tp2~ ~1005~ THEN BEGIN
OUTER_SPRINT warhorn_rage_desc ~战号萨满：出身北方的萨满同时也是娴熟的战士，战号萨满能召唤来自英灵殿、战士安息所等位的战士之灵。他们中许多人信奉战争之主坦帕斯，战斗能力与萨满魔法造诣不相上下。

职业优势：
-生命骰：d10
-阵营可为任意非守序阵营。
-萨满可用的所有武器均可达到专精级。
-所有战斗风格均可达到满专精。
-直接掌握数种独特法术，可与其他法术一样正常施放：战焰、战嚎、风怒、风暴屏障、雷缚战斧、天怒、不灭狂热
-每日可使用一次「狂暴」能力。1级获得1次，之后每提升6级额外获得1次。

狂暴：狂暴状态持续5回合，<PRO_HIMHER>获得力量+4、体质+4、护甲等级-2、法术豁免+2，同时免疫所有魅惑、定身、恐惧、迷宫、震慑、睡眠、困惑与等级吸取法术。

-萨满之舞可召唤以下生物：
  1级：战士之灵（装备长剑、长弓），同时最多存在2只。
  6级：狂战士之灵（双持战斧、双手剑），同时最多存在3只。
  12级：先祖之灵（战士/牧师），同时最多存在4只。
  18级：女武神（弓箭手、盾卫），同时最多存在5只。
  
职业限制：
-识破幻术的技能分值仅为正常水平的一半。
-无法施放普通的萨满专属法术。
-每个法术环级的每日施法次数减少1次。~
END

LAF ADD_KIT_EX
  INT_VAR
    // Mage	= 1
	// Fighter = 2
	// Cleric = 3
	// Thief = 4
	// Bard = 5
	// Paladin = 6
	// Fighter/Mage = 7
	// Fighter/Cleric = 8
	// Fighter/Thief = 9
	// Fighter/Mage/Thief = 10
	// Druid = 11
	// Ranger = 12
	// Mage/Thief = 13
	// Cleric/Mage = 14
	// Cleric/Thief = 15
	// Fighter/Druid = 16
	// Fighter/Mage/Cleric = 17
	// Cleric/Ranger = 18
	// Sorcerer = 19
	// Monk = 20
	// Shaman = 21
    kit_class     = 21
	
    mixed         = RESOLVE_STR_REF(~战号萨满~)
	
    lower         = RESOLVE_STR_REF(~战号萨满~)
	
    help          = RESOLVE_STR_REF(~%warhorn_rage_desc%~)
	
    briefdesc     = RESOLVE_STR_REF(~战号萨满：出身北方的战士萨满，能召唤战士之灵助战，信奉战争之主坦帕斯，战斗与施法能力同样出众。~)
	
	// fallen = 0
	
  STR_VAR
    kit_name      = ~C0WSHAM~
	
    unusable      = ~0x00004000~
    // clasweap      = ~1 1 1 1 1 1 1 1~
	//                                       T   S           F   Q             S S
	//                                       W   C           L   U             W I
	//                               B L S   O   I   W       A   A             O N
	//                               A O H   H   M   A       I   R C   S       R G
	//               L S           M S N O   A   I   R     H L   T R L H     2 D L 2
	//               _ _       S   I T G R   N K T D H     A M   E O O O     H A E W
	//               S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E
	//               W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A
	//               O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P
	//               R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O
	//               D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N
    weapprof      = ~0 2 2 2 2 0 2 2 0 0 0 2 0 0 0 2 0 2 2 0 0 0 2 0 0 2 2 2 2 2 2 3~
	
    abclasrq      = ~0 0 12 0 12 0~
	
    // abclsmod      = ~0 0 0 0 0 0~
	
    // abdcdsrq      = ~0 0 0 = 0 =~
	
    // abdcscrq      = ~15 0 0 0 0 0~
	
	//               L L L N N N C C C
	//               G N E G N E G N E
    // alignmnt      = ~0 1 1 0 1 1 0 1 1~
	
    // dualclas      = ~0 1 1 1 1 0~
	
    // luabbr        = ~FI0~
	
    // stweap        = ~CHAN09 * HELM07 BAG20 RING06 RING31 * BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN4,2 POTN14,5 HAM07 SW1H27 STAF08~
	
    clab_path     = ~override/C0WSHAM.2da~
	
    // kittable      = ~K_F_H K_F_E K_F_HE~
	
	// base_class = 
	
	// clab_base_f = 
	
	// clab_base_p = 
	
	// clab_base_d = 
	
	// clab_base_r = 
	
	// clab_base_m = 
	
	// clab_base_t = 
	
    // clsrcreq      = ~1 1 1 1 1 1 1~
	
    // clswpbon      = ~1 0 2~
	
    hpclass       = ~HPWAR~
	
    // numwslot      = ~4~
	
    // clascolr = ~27 136 119 21 187~
	
	// clasiskl = ~0 0 0 0 0 0 0~
	
	// clasthac = ~0~
	
	thiefscl = ~0 0 0 0 0 50 0 0~
	
	// backstab = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// sneakatt = ~2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
	
	// crippstr = ~0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4~
	
	// thiefskl = ~0 0~
	
	// traplimt = ~6~
	
    // bdstweap      = ~CHAN04 SHLD04 HELM01 * RING06 * * * * BRAC09 BELT02 AROW02,40 BULL02,40 BOLT02,40 POTN08,5 POTN17,3 POTN12,1 * SW1H05 HAMM02~
  RET
    kit_id
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF RA_SPHERE_COMPAT STR_VAR kitname = ~C0WSHAM~ clabfile = ~C0WSHAM~ END

PRINT ~Deities of Faerun installed: adding spheres to kit!~
END

ACTION_IF NOT GAME_IS ~IWDEE~ THEN BEGIN
COMPILE ~%MOD_FOLDER%/Shaman/WarShaman/BAF/C0WSHPR.BAF~
END

ACTION_IF GAME_IS ~IWDEE~ THEN BEGIN
COMPILE ~%MOD_FOLDER%/Shaman/WarShaman/BAF/IWDEE/C0WSHPR.BAF~
END

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR1.cre~ ~override~
SAY NAME1 ~战士之灵~
SAY NAME2 ~战士之灵~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR1~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR2.cre~ ~override~
SAY NAME1 ~射手之灵~
SAY NAME2 ~射手之灵~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR2~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR3.cre~ ~override~
SAY NAME1 ~狂战士之灵~
SAY NAME2 ~狂战士之灵~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR3~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR4.cre~ ~override~
SAY NAME1 ~狂战士之灵~
SAY NAME2 ~狂战士之灵~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR4~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR5.cre~ ~override~
SAY NAME1 ~先祖之灵~
SAY NAME2 ~先祖之灵~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR5~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR6.cre~ ~override~
SAY NAME1 ~女武神射手~
SAY NAME2 ~女武神射手~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR6~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/CRE/C0WSPIR7.cre~ ~override~
SAY NAME1 ~女武神盾卫~
SAY NAME2 ~女武神盾卫~
WRITE_ASCII 0x248 ~BDSHUNSU~  #8  // override
WRITE_ASCII 0x268 ~C0WSHPR~  #8  // default
WRITE_ASCII 0x280 ~C0WSPIR7~ #32 // death variable

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSH04.SPL~ ~OVERRIDE~
LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 139
		match_parameter1 = 103121
		parameter1 = RESOLVE_STR_REF (~战士之灵回应了你的召唤。~)
END
LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 139
		match_parameter1 = 103122
		parameter1 = RESOLVE_STR_REF (~狂战士之灵回应了你的召唤。~)
END
LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 139
		match_parameter1 = 103123
		parameter1 = RESOLVE_STR_REF (~先祖之灵回应了你的召唤。~)
END
LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 139
		match_parameter1 = 103124
		parameter1 = RESOLVE_STR_REF (~女武神之灵回应了你的召唤。~)
END
LPF ALTER_EFFECT
	INT_VAR
		match_opcode = 139
		match_parameter1 = 103120
		parameter1 = RESOLVE_STR_REF (~没有灵体回应你的召唤。~)
END

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS1.SPL~ ~OVERRIDE~
SAY NAME1 ~战焰~
SAY UNIDENTIFIED_DESC ~战焰
(变化系)

等级：1
领域：战斗
射程：自身
持续时间：2回合
施法时间：1
影响范围：施法者自身
豁免：无

施法者借古代战士之灵的力量获得强化。法术持续期间，施法者零级命中值与伤害获得非叠加的+2加值，之后每10级额外+1。~

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS2.SPL~ ~OVERRIDE~
SAY NAME1 ~战嚎~
SAY UNIDENTIFIED_DESC ~战嚎
(防护系)

等级：2
领域：魅惑
射程：30尺
持续时间：1小时
施法时间：1
影响范围：15尺半径
豁免：无

施法者向<PRO_HISHER>同伴发出鼓舞人心的战吼，将士气提升至最高，护甲与零级命中值获得非叠加的+2加值。持续时间结束后，受术者士气会逐渐恢复正常。若受术者正受魔法恐惧影响，该效果会被抵消。~

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS3.SPL~ ~OVERRIDE~
SAY NAME1 ~风怒~
SAY UNIDENTIFIED_DESC ~风怒
(附魔系/魅惑系)

等级：3
领域：元素、战斗
射程：自身
持续时间：1回合
施法时间：1
影响范围：施法者自身
豁免：无

施法者将北方风雪的力量灌注到<PRO_HISHER>武器中。法术持续期间，武器额外造成寒冷与电击伤害，且在判定可击中目标时视为+3附魔武器。额外伤害数值如下：

   8级及以下：1d4寒冷，1d4电击
   9-11级：1d6寒冷，1d6电击
   12-14级：1d8寒冷，1d8电击
   15-17级：1d10寒冷，1d10电击
   18级及以上：2d6寒冷，2d6电击
   
此外，由于武器灌注了风之力，<PRO_HESHE>在持续期间获得加速效果。~

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS4.SPL~ ~OVERRIDE~
SAY NAME1 ~风暴屏障~
SAY UNIDENTIFIED_DESC ~风暴屏障
(塑能系)

等级：4
领域：元素
射程：自身
持续时间：3回合+每等级1回合
施法时间：4
影响范围：施法者自身
豁免：无

风暴屏障以闪电之盾环绕施法者，保护其免受电击伤害。该护盾不仅为使用者提供50%电击抗性，还能保护施法者免受5尺范围内的攻击。任何在该半径内用武器或法术攻击施法者的对手，都会受到1d8+2点电击伤害。~

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS5.SPL~ ~OVERRIDE~
SAY NAME1 ~雷缚战斧~
SAY UNIDENTIFIED_DESC ~雷缚战斧
(塑能系)

等级：5
领域：战斗
射程：自身
持续时间：特殊
施法时间：3
影响范围：施法者自身
豁免：无

此法术创造数道战斧形的闪电，每2个经验等级1道，由施法者持握以替代<PRO_HISHER>常规武器。战斧可投向50尺内的目标，视为远程武器，攻击检定获得+5加值。每道战斧造成2d6+10点电击伤害，外加10点魔法伤害；若目标法术豁免（难度-2）失败，还会被震慑3回合。施法者每回合可投掷1道战斧。~
COPY ~%MOD_FOLDER%/Shaman/WarShaman/ITM/C0WSHS5.ITM~ ~OVERRIDE~
SAY NAME1 ~雷缚战斧~
SAY NAME2 ~雷缚战斧~

ADD_PROJECTILE ~%MOD_FOLDER%/Shaman/WarShaman/PRO/C0WSHS6.PRO~ ~Wrath of the Skies~
COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS6.SPL~ ~OVERRIDE~
READ_LONG 0x64 "abil_off"
READ_SHORT 0x68 "abil_num"
SET "delta" = 0
FOR (index = 0; index < abil_num; index = index + 1) BEGIN
WRITE_SHORT (%abil_off% + (0x28 * %index%) + 0x26) ~%C0WSHS6%~
END
SAY NAME1 ~天怒~
SAY UNIDENTIFIED_DESC ~天怒
(塑能系)

等级：6
领域：元素、天气
射程：270尺
持续时间：5回合
施法时间：5
影响范围：15尺半径
豁免：无

这道强力法术召唤寒冰风暴降临施法者选定位置，每回合造成2d10点伤害（一半寒冷，一半魔法），并将所有留在风暴中的敌人的魔法抗性降低50%，护甲等级降低4点。此法术不受魔法抗性影响，且不会影响友军。~

COPY ~%MOD_FOLDER%/Shaman/WarShaman/SPL/C0WSHS7.SPL~ ~OVERRIDE~
SAY NAME1 ~不灭狂热~
SAY UNIDENTIFIED_DESC ~不灭狂热
(变化系)

等级：7
领域：战斗
射程：0
持续时间：3回合
施法时间：1
影响范围：施法者自身
豁免：无

此法术让施法者陷入狂怒，力量强到在持续期间无法被杀死。此外，<PRO_HESHE>造成的物理伤害提升50%。但法术效果消退后，施法者会陷入重度疲劳，护甲等级受-6惩罚，移动速度减半，持续3回合。在此期间，萨满无法再次获得不灭狂热的效果。~