COPY ~%MOD_FOLDER%/Fighter/WizardSlayer/2da~ ~override~
COPY ~%MOD_FOLDER%/Fighter/WizardSlayer/spells~ ~override~

COPY_EXISTING ~CLABFI01.2DA~ ~OVERRIDE/CLABFI03.2DA~
  // REPLACE_TEXTUALLY ~GA_C0FIG01~ ~**** ~ // POWER ATTACK
  // REPLACE_TEXTUALLY ~GA_C0FIG02~ ~**** ~ // EXPERTISE
  // REPLACE_TEXTUALLY ~GA_C0ARC03~ ~**** ~ // RAPID SHOT
  // REPLACE_TEXTUALLY ~AP_C0ARC03Z~ ~**** ~
  REPLACE_TEXTUALLY ~AP_C0FIG04~ ~**** ~ // SPECIALIZATION
  // REPLACE_TEXTUALLY ~AP_C0FIG03~ ~**** ~ // IMPROVED INITATIVE

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 f_Increment = 1 STR_VAR f_Entry = AP_SPCL131 END

  LPF set_clab_2da_entries INT_VAR f_MinLevel = 1 STR_VAR f_Entry = AP_SPCL133 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 STR_VAR f_Entry = GA_C0WSL01 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 4 f_Increment = 2 STR_VAR f_Entry = GA_C0WSL01 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 8 f_MaxLevel = 12 f_Increment = 2 STR_VAR f_Entry = GA_C0WSL02 END
  LPF set_clab_2da_entries INT_VAR f_MinLevel = 16 STR_VAR f_Entry = AP_C0WSL03 END

  PRETTY_PRINT_2DA

// Resistances
DEFINE_ACTION_FUNCTION	ADD_SPLPROT	INT_VAR	stat = 0	value = 0	relation = 0	RET	new_row		BEGIN
	ACTION_IF	(stat > 278)	BEGIN	WARN	~SPLPROT.2DA - Stat out of Bounds.~	END
	ACTION_IF	((stat != 259) AND (stat != 260) AND (relation > 11))	BEGIN	WARN	~SPLPROT.2DA - Relation out of Bounds.~	END
	COPY_EXISTING ~SPLPROT.2DA~	OVERRIDE
		COUNT_2DA_COLS	cols
		COUNT_2DA_ROWS cols rows
		TEXT_SPRINT check_row ~~
		TEXT_SPRINT check_stat ~~
		SET new_row = 0
		FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
			PATCH_IF (~%check_stat%~ STRING_EQUAL ~%stat%~)	BEGIN	READ_2DA_ENTRY current_row 2 cols check_value
				PATCH_IF (~%check_value%~ STRING_EQUAL ~%value%~)	BEGIN	READ_2DA_ENTRY current_row 3 cols check_relation
					PATCH_IF (~%check_relation%~ STRING_EQUAL ~%relation%~)	BEGIN	new_row = current_row	current_row = rows	END
				END
			END
		END
		PATCH_IF (new_row = 0)	BEGIN
			FOR(current_row = 0; current_row < rows; ++current_row)	BEGIN	READ_2DA_ENTRY current_row 1 cols check_stat
				PATCH_IF (~%check_stat%~ STRING_EQUAL ~*~)	BEGIN	new_row = current_row	current_row = rows	END
			END
			PATCH_IF (new_row = 0)	BEGIN	new_row = rows	INSERT_2DA_ROW rows cols ~%new_row%		   %stat%		   %value%		   %relation%~
			END	ELSE	BEGIN	SET_2DA_ENTRY new_row 1 cols ~%stat%~	SET_2DA_ENTRY new_row 2 cols ~%value%~	SET_2DA_ENTRY new_row 3 cols ~%relation%~	END
		END
	BUT_ONLY
END

DEFINE_ACTION_FUNCTION cd_new_portrait_icon
  INT_VAR string = 0
  STR_VAR bam_file = "****"
  RET     icon
  BEGIN

  COPY_EXISTING ~statdesc.2da~ ~override~
    COUNT_2DA_ROWS 3 count
    READ_2DA_ENTRY (count - 1) 0 3 icon
    SET icon += 1

  APPEND ~statdesc.2da~ ~%icon% %string% %bam_file%~ UNLESS ~%bam_file%~

END

LAF cd_new_portrait_icon INT_VAR string = RESOLVE_STR_REF(~破法斩~) STR_VAR bam_file = C0WSL11I RET C0WSL11I = icon END

//	Array of Restistance / Stat#
ACTION_DEFINE_ASSOCIATIVE_ARRAY	MRES_DMG_ARRAY_0_9	BEGIN
	~MRES_DMG_ARRAY_0_9~	=>	18
END
ACTION_PHP_EACH	MRES_DMG_ARRAY_0_9 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 1	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 10	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	MRES_DMG_ARRAY_10_19	BEGIN
	~MRES_DMG_ARRAY_10_19~	=>	18
END
ACTION_PHP_EACH	MRES_DMG_ARRAY_10_19 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 10	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 19	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	MRES_DMG_ARRAY_20_29	BEGIN
	~MRES_DMG_ARRAY_20_29~	=>	18
END
ACTION_PHP_EACH	MRES_DMG_ARRAY_20_29 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 20	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 29	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	MRES_DMG_ARRAY_30_39	BEGIN
	~MRES_DMG_ARRAY_30_39~	=>	18
END
ACTION_PHP_EACH	MRES_DMG_ARRAY_30_39 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 30	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 39	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	MRES_DMG_ARRAY_40_49	BEGIN
	~MRES_DMG_ARRAY_40_49~	=>	18
END
ACTION_PHP_EACH	MRES_DMG_ARRAY_40_49 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 40	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 49	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

ACTION_DEFINE_ASSOCIATIVE_ARRAY	MRES_DMG_ARRAY_50_128	BEGIN
	~MRES_DMG_ARRAY_50_128~	=>	18
END
ACTION_PHP_EACH	MRES_DMG_ARRAY_50_128 AS one => two	BEGIN
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 50	relation = 	2	RET	min = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = two	value = 128	relation = 	4	RET	max = new_row	END
	LAF	ADD_SPLPROT	INT_VAR	stat = 260	value = min	relation = 	max	RET	EVAL ~%one%~ = new_row	END
END

OUTER_SPRINT kit_description ~法师杀手：这名战士受其教派的专门训练，精于狩猎与对抗各类施法者，练就了消解、扰乱各类魔法能量的天赋。在特定情形下，法师杀手甚至能将这份力量用于进攻，对非魔法使用者释放强力一击。但这份能量也有弊端：它会抵消许多魔法物品的增益，让它们在<PRO_HISHER>手中形同虚设。

职业优势：
-法师杀手每次成功命中会使目标累积施法失败几率，数值为10%+每等级1%，持续15回合。
-获得魔法抗性，数值为10%+每等级1%。
-4级：每日可使用两次「破法斩」，之后每提升2级额外获得1次使用次数。

破法斩：法师杀手消耗部分反魔法能量发动一次蓄力攻击，临时牺牲指定数值的魔法抗性，以提升自身零级命中值，并造成等额的额外真实伤害，同时移除目标的战斗防护效果。两回合后，法师杀手恢复自身魔法抗性。

-8级：每日可使用一次「反魔法力场」。10级与12级各额外获得1次使用次数。

反魔法力场：法师杀手将自身的天赋魔法抗性延伸至15尺范围内的所有友军，为其提供自身基础魔法抗性的一半。效果持续5回合，期间法师杀手失去自身的天赋魔法抗性，且无法使用破法斩。

-16级：法术屏障：法师杀手可吸收首个以自身为目标的任意环级法术的效果。该效果无法抵挡不以法师杀手为目标的区域法术与云雾效果。一回合后法术屏障恢复。

职业限制：KIT_DISADV_1
-除武器与护甲外无法使用任何魔法物品。~

ACTION_IF MOD_IS_INSTALLED ~Setup-ArtisansKitpack.tp2~ ~1100~ THEN BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~
-16级时不会获得全武器专精。~

END

END ELSE BEGIN

OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
  REPLACE_TEXTUALLY ~KIT_DISADV_1~ ~~
END

END

LAF ~GET_KIT_STRREF~ STR_VAR kit_name = ~WIZARD_SLAYER~ RET kit_strref END
STRING_SET_EVALUATE kit_strref ~%kit_description%~

COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~                  //Kindly provided and explained by kjeron with a solid base that Grammarsalad gave me to start knowing what to ask and look for.
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
		READ_SHORT	0x6a	fx_off
		READ_SHORT	0x70	glob_fx
		FOR	(j = 0; j < glob_fx; ++j)	BEGIN
			READ_SHORT (fx_off + j * 0x30) opcode
			PATCH_IF (opcode = 31) OR (opcode = 166)  BEGIN
				WRITE_BYTE	0x002f	(THIS BAND 0b11111101)
				SET j = glob_fx
			END
		END
	END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~POTN33.itm~ ~override~                            //Potion of Magic Blocking
WRITE_BYTE 0x2f (THIS BAND 0b11111101)

COPY_EXISTING ~POTN34.itm~ ~override~                            //Potion of Magic Protection
WRITE_BYTE 0x2f (THIS BAND 0b11111101)

COPY_EXISTING ~POTN35.itm~ ~override~                            //Potion of Magic Shielding
WRITE_BYTE 0x2f (THIS BAND 0b11111101)

ACTION_IF FILE_EXISTS_IN_GAME ~SPWI513.SPL~ BEGIN
COPY_EXISTING ~SPWI513.spl~ ~override/C0WSL00.spl~
WRITE_SHORT 0x1C 4 
WRITE_LONG 0x34 1 
READ_LONG 0x64 "offset_abil"
READ_SHORT 0x68 "num_abil"
READ_ASCII ("%offset_abil%" + 0x04) "bam" 
WRITE_EVALUATED_ASCII 0x3A "%bam%" 
WHILE (0 < "%num_abil%")
BEGIN
WRITE_SHORT (("%offset_abil%" + 0x02) + (("%num_abil%" - 1) * 0x28)) 4 
SET "num_abil" = ("%num_abil%" - 1)
END
END

COPY_EXISTING ~C0WSL01.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 1 parameter2 = MRES_DMG_ARRAY_0_9 END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 2 parameter2 = MRES_DMG_ARRAY_10_19 END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 3 parameter2 = MRES_DMG_ARRAY_20_29 END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 4 parameter2 = MRES_DMG_ARRAY_30_39 END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 5 parameter2 = MRES_DMG_ARRAY_40_49 END
LPF ALTER_EFFECT INT_VAR match_opcode = 326 match_special = 6 parameter2 = MRES_DMG_ARRAY_50_128 END
SAY NAME1 ~破法斩~
SAY UNIDENTIFIED_DESC ~破法斩
法师杀手消耗部分反魔法能量发动一次蓄力攻击，临时牺牲指定数值的魔法抗性，以提升自身零级命中值，并造成等额的额外真实伤害，同时移除目标的战斗防护效果。两回合后，法师杀手恢复自身魔法抗性。

破法斩的效果无视所有武器防护，即便攻击本身被抵消也依然生效。~

ACTION_IF (MOD_IS_INSTALLED ~EEEX/EEEX.TP2~ ~0~) THEN BEGIN

COPY_EXISTING ~C0WSL01.spl~ ~override~
SAY UNIDENTIFIED_DESC ~破法斩
法师杀手消耗部分反魔法能量发动一次蓄力攻击，临时牺牲指定数值的魔法抗性，以提升自身零级命中值，并造成等额的额外真实伤害，同时移除目标的战斗防护效果。两回合后，法师杀手恢复自身魔法抗性。

破法斩的效果无视所有武器防护，即便攻击本身被抵消也依然生效。~
 
END

COPY_EXISTING ~C0WSL011.SPL~ OVERRIDE
SAY NAME1 ~破法斩 — 10%魔法抗性~
COPY_EXISTING ~C0WSL012.SPL~ OVERRIDE
SAY NAME1 ~破法斩 — 20%魔法抗性~
COPY_EXISTING ~C0WSL013.SPL~ OVERRIDE
SAY NAME1 ~破法斩 — 30%魔法抗性~
COPY_EXISTING ~C0WSL014.SPL~ OVERRIDE
SAY NAME1 ~破法斩 — 40%魔法抗性~
COPY_EXISTING ~C0WSL015.SPL~ OVERRIDE
SAY NAME1 ~破法斩 — 50%魔法抗性~

COPY_EXISTING ~C0WSL01v.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 139 parameter1 = RESOLVE_STR_REF (~魔法抗性不足~) END

COPY_EXISTING ~C0WSL011.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0WSL11I END

COPY_EXISTING ~C0WSL012.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0WSL11I END

COPY_EXISTING ~C0WSL013.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0WSL11I END

COPY_EXISTING ~C0WSL014.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0WSL11I END

COPY_EXISTING ~C0WSL015.SPL~ OVERRIDE
LPF ALTER_EFFECT INT_VAR match_opcode = 142 parameter2 = C0WSL11I END

COPY_EXISTING ~C0WSL02.SPL~ OVERRIDE
SAY NAME1 ~反魔法力场~
SAY UNIDENTIFIED_DESC ~反魔法力场
法师杀手将自身的天赋魔法抗性延伸至15尺范围内的所有友军，为其提供自身基础魔法抗性的一半。效果持续5回合，期间法师杀手失去自身的天赋魔法抗性，且无法使用破法斩。~